### ISSUE TITLE
Pods fail with "NodeAffinity failed" after kubelet restarts

### ISSUE THREAD

**Issue by ruiwen-zhao** [kubernetes/kubernetes#100467]
#### What happened:
The issue is basically same as https://github.com/kubernetes/kubernetes/issues/92067. 

With the fix https://github.com/kubernetes/kubernetes/pull/94087 in place, kubelet will node lister to sync in [GetNode()](https://github.com/derekwaynecarr/kubernetes/blob/752135242e49dc571159eb51328bcfc7734e6033/pkg/kubelet/kubelet_getters.go#L241).  

However, in the case of kubelet restart, the pods scheduled on the node before the restart might still fail with "NodeAffinity failed" after the restart. Looking at the code, this is probably because the admit pod check ([canAdmitPod()](https://github.com/kubernetes/kubernetes/blob/5ae856c36f2ea338a6f26301e368ef8331ef2e73/pkg/kubelet/kubelet.go#L2107)) might happen before [GetNode()](https://github.com/derekwaynecarr/kubernetes/blob/752135242e49dc571159eb51328bcfc7734e6033/pkg/kubelet/kubelet_getters.go#L241).  

#### What you expected to happen:
After kubelet restart, old pods (pods scheduled on the node before the restart) do not see "NodeAffinity failed". 

#### How to reproduce it (as minimally and precisely as possible):
This issue does not happen all the time. To reproduce it, you will need to keep restarting the kubelet, and you might see a previously running Pod started to fail with "Predicate NodeAffinity failed".

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
cc @neolit123 @ehashman
/sig node

**Comment by neolit123** [comment]
thank you for reporting this @ruiwen-zhao

**Comment by neolit123** [comment]
> However, in the case of kubelet restart, the pods scheduled on the node before the restart might still fail with "NodeAffinity failed" after the restart. Looking at the code, this is probably because the admit pod check (canAdmitPod()) might happen before GetNode().

this should be resolved with https://github.com/kubernetes/kubernetes/pull/99336 ideally?

**Comment by lwsanty** [comment]
issue is still reproduced in GKE `1.19.8-gke.1600`

**Comment by Keramblock** [comment]
> 
> 
> issue is still reproduced in GKE `1.19.8-gke.1600`

same

**Comment by neolit123** [comment]
GKE builds are proprietary.

for upstream Kubernetes once these cherry picks merge you should check the latest respective PATCH releases:
https://github.com/kubernetes/kubernetes/pull/99336#issuecomment-824441152

**Comment by Keramblock** [comment]
@neolit123 Still, they based on open source, or aren't they?

**Comment by neolit123** [comment]
my point is that i cannot give you a timeline of when the GKE builds will be available and you should consult with GKE support.

k8s patch releases should be up on 12th of May:
https://groups.google.com/g/kubernetes-dev/c/H06vjjSzX44/m/rZcBO0_rAAAJ

**Comment by Keramblock** [comment]
Oh, ok. Thank you =)

**Comment by primeroz** [comment]
FYI this is also present in gke `1.18.17-gke.700` , i did hope they would backport the patch since yesterday the .700 was released to stable channel but that is not the case.

Luckily, for us, this is only an issue with `preemptible` nodes since that is effectively a node restart

Will wait for 1.18.19 impatiently. :crossed_fingers:

**Comment by sbocinec** [comment]
We got first affected by this issue after upgrading our GKE cluster  from `v1.17.17-gke.2800` to `1.18.17-gke.700` for pods running on pre-emptible nodes. Is this k8s `1.18+` specific?

**Comment by primeroz** [comment]
Same here, as far as i know this is fixed in 1.18.19 

fix in https://github.com/kubernetes/kubernetes/pull/99336#issuecomment-824441152 cherrypicked to 1.18 in https://github.com/kubernetes/kubernetes/pull/101343

**Comment by pacoxu** [comment]
It should be fixed in [1.18.19](https://github.com/kubernetes/kubernetes/blob/d41249f780316841a0e13948e7af24d10b9c9c0d/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v11818), [v1.19.10](https://github.com/kubernetes/kubernetes/blob/b4dddbafa2fcff6d82c933c13fe7febf75f00d68/CHANGELOG/CHANGELOG-1.19.md), [v1.20.7](https://github.com/kubernetes/kubernetes/blob/0ccf53dd2003b39651cabe68d1bdd17feb9cd4ec/CHANGELOG/CHANGELOG-1.20.md) and [v1.21.1](https://github.com/kubernetes/kubernetes/blob/47171077bf387bf63e10a04a61d5c96d59983037/CHANGELOG/CHANGELOG-1.21.md). 


For GKE upgrade, I think it should be asked in GKE service?
/triage duplicate
/close

**Comment by username1366** [comment]
After upgrading GKE to v1.18.19-gke.1700 I experienced the same issue - some of the pods after node preemption moved to NodeAffinity status
```
kubectl get pods -o wide --all-namespaces | grep NodeAffinity
app              app-cd5d5595f-tkw9p                          0/5     NodeAffinity
```

**Comment by primeroz** [comment]
On GKE i also tested with `v1.19.10-gke.1600` and getting plenty of `nodeaffinity` pods

**Comment by sbocinec** [comment]
Tested with the latest `v1.18.20-gke.900` and the issue is still present. @phantooom is it possible to reopen the issue as the fix appear not to fix it properly?

**Comment by miguepintor** [comment]
on GKE `v1.19.11-gke.2101` is reproducible as well, please @phantooom consider the re-opening

**Comment by alculquicondor** [comment]
/reopen
@neolit123 any ideas?

**Comment by neolit123** [comment]
sounds like something that regressed after the node sync changes, but the second one (that i did) did not fix it.

the change that i did:
https://github.com/kubernetes/kubernetes/pull/99336

was technically a refactor on what was already established by the previous change:
https://github.com/kubernetes/kubernetes/pull/94087

> However, in the case of kubelet restart, the pods scheduled on the node before the restart might still fail with "NodeAffinity failed" after the restart. Looking at the code, this is probably because the admit pod check (canAdmitPod()) might happen before GetNode().

this seems racy and should be brought to discussion at the SIG Node meeting
https://github.com/kubernetes/community/tree/master/sig-node#meetings

kubelet maintainers that are more savvy must be able to reproduce it:

> This issue does not happen all the time. To reproduce it, you will need to keep restarting the kubelet, and you might see a previously running Pod started to fail with "Predicate NodeAffinity failed".

we have a lot of GKE reporters in this ticket. has anyone seen the problem on non-GKE clusters?

**Comment by Tfmenard** [comment]
For affected  GKE users, [graceful node termination feature](https://cloud.google.com/kubernetes-engine/docs/how-to/preemptible-vms#kubernetes_preemptible_nodes) fixes the issue and is enabled on clusters running node pools on 1.20+

Note that this issue has little to no impact on workloads. As long as the pod is backed by controller (deployment/statefulset, etc), when a pod runs into the NodeAffinity issue a new pod is immediately created and rescheduled. 
See  https://issuetracker.google.com/185362914 for details.

In case this issue comes back, to reproduce it simply create a cluster with a node pool that runs preemptible VMs and deploy this simple deployment [1] that uses nodeSelector.
Then to simulate a preemption run 
`gcloud compute instances simulate-maintenance-event <node-name> --zone <zone name>`
If you're lucky the issue will occur on the first preemption, but it may only occur on the 10th one.

I'm closing this issue as we've only seen this occur on GKE and a fix is out now for GKE.
Please reopen if you experience the issue on GKE node pools running 1.20+ or on non-GKE clusters.

[1]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: na-test
spec:
  replicas: 5
  selector:
    matchLabels:
      role: na-test
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1000
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: na-test
    spec:
      containers:
      - image: busybox
        command:
          - sh
          - -c
          - 'echo "NodeAffinity test"; sleep 300;'
        imagePullPolicy: IfNotPresent
        name: busybox
      nodeSelector:
        cloud.google.com/gke-nodepool: <node pool name>
 ```

/close
