### ISSUE TITLE
Improve e2e test coverage of services

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#10268]
What's currently included in the services e2e test:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/service.go

1. Services should serve a basic endpoint from pods
1. Services should serve multiport endpoints from pods
1. Services should be able to create a functioning external load balancer
1. Services should be able to create a functioning NodePort service
1. Services should be able to change the type and nodeport settings of a service
1. Services should release the load balancer when Type goes from LoadBalancer -> NodePort
1. Services should prevent NodePort collisions
1. Services should check NodePort out-of-range
1. Services should release NodePorts on delete
1. Services should correctly serve identically named services in different namespaces on different external IP addresses

What's not yet covered (and there are surely more than what's in the following list):

- [x] Multiport TCP services (this seems false given item 2 above - update the comments).  https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/service.go#L67
- [ ] Spreading of traffic across backends appropriately (round robin etc).  @satnam6502 had an indirect test somewhere for this AFAIK, but we should perhaps factor it into a narrow service-specific test.
- [ ] LiveNessProbes (perhaps belongs in Kubelet e2e tests, but it would be good to make sure that they are usable and work properly in the use case of providing a highly available service).
- [ ] ReadinessProbes (comments as above)
- [ ] General high availability of services in the presence of pod or network failure. Inject pod, node and network failures, and verify that the service remains available, within the published specs.
- [ ] More... ??

**Comment by quinton-hoole** [comment]
@cjcullen @dchen1107 @justinsb @a-robinson  purely FYI

**Comment by alex-mohr** [comment]
@quinton-hoole Great to see tracking issues like this.  Presumably we have other gaps in our e2e testing -- are there similar ones for ensuring other cluster invariants hold?  What do we need to do to have 100% coverage as part of API compliance testing?

**Comment by quinton-hoole** [comment]
I have not yet managed to figure out a good answer to your last question yet.  It turns out to be challenging to accurately measure e2e test coverage.  I have some code to analyse API server logs to determine what percentage of the (objects x operations x response_codes) landscape has been exercised by a given test run, but given the number of optional aspects of many API object types (Does this service have an external load balancer?  Does it have liveness probes?  Does it have an underlying replication controller? etc, etc to name just a few), it seems inevitable that a human will need to make some subjective judgement of how much of this landscape can and should be reasonably tested.  And of course that landscape is constantly changing as we evolve the system.

It's near the top of my post-v1.0 priority list though ;-)

**Comment by mikedanese** [comment]
I will work on a couple of these if no one else is.

**Comment by quinton-hoole** [comment]
Thanks @mikedanese, that would be great!

**Comment by wojtek-t** [comment]
>
Spreading of traffic across backends appropriately (round robin etc). @satnam6502 had an indirect test somewhere for this AFAIK, but we should perhaps factor it into a narrow service-specific test.

This is covered in shell tests - see https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/e2e-suite/services.sh

We should also migrate the shell test to Go - I've created #10980, but this should be post 1.0 work.

**Comment by satnam6502** [comment]
Indeed, my test sprays lots of requests via service to pods and then checks that there is a response from each pod and reports the distribution of responses.

**Comment by quinton-hoole** [comment]
As discussed over lunch, lets move this to an e2e test @satnam6502, to improve CI test coverage as well as prevent bit rot of the test code.

**Comment by wojtek-t** [comment]
I don't understand this comment - this shall script is also running as e2e test. I've just fixed this today and will be moving it out of flaky suite.

**Comment by quinton-hoole** [comment]
Oh, apologies for the confusion.  I'm referring to Satnam's test referred
to above.

On Thu, Jul 9, 2015 at 1:17 PM, Wojciech Tyczynski <notifications@github.com

**Comment by davidopp** [comment]
This is marked 1.1 and P2 and hasn't been touched in over three months. Writing more e2e tests sounds like a great idea but not really a 1.1 blocker. @quinton-hoole can we punt this to 1.2?

**Comment by quinton-hoole** [comment]
Not strictly true that this has not been touched in over three months.  Both @mikedanese and @ArtfulCoder have been working on improving service test coverage, as discussed in the linked #11067 and associated PR's.  We're still missing some e2e coverage of services, IMO.  I'll assign this to @artfulcoder and team/cluster to decide what they want to do with it.

**Comment by quinton-hoole** [comment]
@kubernetes/goog-cluster @thockin FYI

**Comment by thockin** [comment]
Several of these points are covered in the kube-proxy test.  There's a very grey area between services and kube-proxy where the tests overlap

**Comment by thockin** [comment]
I moved this to 1.2 - there's always more we can do.

**Comment by davidopp** [comment]
Oops, very sorry, somehow I didn't realize that the date on a reference to an issue/PR that Github inserts is the date the issue/PR was initially mentioned, not the date it was last updated. Kinda makes sense, but for some reason I was assuming Github did the "cooler" thing (last update) and I didn't click through to the thread, hence my confusion about when #11067 was last touched.

**Comment by bprashanth** [comment]
I'm closing this for now because Services E2Es have made a lot of progress in the past few months. 

> Spreading of traffic across backends appropriately (round robin etc). @satnam6502 had an indirect test somewhere for this AFAIK, but we should perhaps factor it into a narrow service-specific test.

The services test checks that we reach all backends, which sort-of validates rr. I don't think we have anything for client affinity, filed: https://github.com/kubernetes/kubernetes/issues/21329

> LiveNessProbes (perhaps belongs in Kubelet e2e tests, but it would be good to make sure that they are usable and work properly in the use case of providing a highly available service).
 ReadinessProbes (comments as above)

We have both these in various kubelet tests. 

> General high availability of services in the presence of pod or network failure. Inject pod, node and network failures, and verify that the service remains available, within the published specs.

https://github.com/kubernetes/kubernetes/pull/19731 was one step toward this.


> More... ??

I think these should take the form of individual issues.
