### ISSUE TITLE
Multiple concurrent docker image pulls may lead to layer corruption

### ISSUE THREAD

**Issue by antoineco** [kubernetes/kubernetes#10623]
When adding a new node to an existing cluster (k8s 0.19.3), all containers scheduled on this node fail to start with the following pod event log:

```
Events:
  FirstSeen				LastSeen			Count	From							SubobjectPath				Reason		Message
  Wed, 01 Jul 2015 14:45:51 +0000	Wed, 01 Jul 2015 14:45:51 +0000	1	{scheduler }											scheduled	Successfully assigned api-ab8b8 to ip-10-0-21-24.eu-west-1.compute.internal
  Wed, 01 Jul 2015 14:45:51 +0000	Wed, 01 Jul 2015 14:45:51 +0000	1	{kubelet ip-10-0-21-24.eu-west-1.compute.internal}	implicitly required container POD	pulled		Successfully pulled image "gcr.io/google_containers/pause:0.8.0"
  Wed, 01 Jul 2015 14:45:51 +0000	Wed, 01 Jul 2015 14:45:51 +0000	1	{kubelet ip-10-0-21-24.eu-west-1.compute.internal}	implicitly required container POD	created		Created with docker id 8706f19a371e0f37a783161c93b202879cd9888bd8396184f6a2888a9e1267bb
  Wed, 01 Jul 2015 14:45:51 +0000	Wed, 01 Jul 2015 14:45:51 +0000	1	{kubelet ip-10-0-21-24.eu-west-1.compute.internal}	implicitly required container POD	started		Started with docker id 8706f19a371e0f37a783161c93b202879cd9888bd8396184f6a2888a9e1267bb
  Wed, 01 Jul 2015 14:46:05 +0000	Wed, 01 Jul 2015 14:46:25 +0000	2	{kubelet ip-10-0-21-24.eu-west-1.compute.internal}	spec.containers{api}			pulled		Successfully pulled image "myprivaterepo/rails:release-201507010826"
  Wed, 01 Jul 2015 14:46:05 +0000	Wed, 01 Jul 2015 14:46:34 +0000	4	{kubelet ip-10-0-21-24.eu-west-1.compute.internal}	spec.containers{api}			failed		Failed to create docker container with error: no such image
```

All subsequent container restart fail with the following error (also mentioned in #7332)

```
  Wed, 01 Jul 2015 14:48:20 +0000	Wed, 01 Jul 2015 14:48:20 +0000	1	{kubelet ip-10-0-21-24.eu-west-1.compute.internal}	spec.containers{api}			created		Created with docker id ea00cf3d55318b3dde9ed455c18945d3fca468610ea93f2e16e08c11bdc09845
  Wed, 01 Jul 2015 14:48:24 +0000	Wed, 01 Jul 2015 14:48:24 +0000	1	{kubelet ip-10-0-21-24.eu-west-1.compute.internal}	spec.containers{api}			failed		Failed to start with docker id ea00cf3d55318b3dde9ed455c18945d3fca468610ea93f2e16e08c11bdc09845 with error: API error (404): Cannot start container ea00cf3d55318b3dde9ed455c18945d3fca468610ea93f2e16e08c11bdc09845: [8] System error: no such file or directory
```

When this starts happening Docker fills the local disk indefinitely at a rate of about 4GB/minute with only 4 scheduled containers.

**Comment by antoineco** [comment]
Here is the procedure I have to follow in order to make the node operational:
* stop kubelet
* unmount kubelet's tmpfs volumes
* wipe /var/lib/kubelet/pods
* pull the images manually
* restart kubelet

**Comment by thockin** [comment]
Is this a matter of a wrong image (typo or something) or is there an actual bug in finding that image?

**Comment by thockin** [comment]
A quick try on near-HEAD does not repro this, but it's not clear how to do so.

**Comment by thockin** [comment]
@dchen1107 or @yujuhong for triage

**Comment by antoineco** [comment]
No there is no typo, as the log mentions the image is actually pulled and only after that everything falls apart.

I can reproduce it at 100%. It **seems** to happen because several pods try to pull the same image simultaneously.

**Comment by thockin** [comment]
ah, I mis-parsed the logs before.  So it could still be a GC issue, but
that should not be so reproducible.  There are 2 issues in play.  First,
why the pull succeeds and the run fails.  Second, why something (kubelet?)
goes into a loop trying the same thing over and over

**Comment by dchen1107** [comment]
Yeah, my first impression is I resolved this kind of issues before and caused by GC. :-) But you are right, GC shouldn't be so easy to reproduce, especially we changed the logic not using untagged filter to list images, and decide which ones are not useful. 

@antoineco You mentioned that you can reproduce it 100%. Could you please give more detail on the steps how to reproduce it? When you reproducing it, is it possible to enable kubelet -v=4, and share with us somewhere kubelet.log and docker.log (both are at /var/log)?

You hinted that it might be caused by simultaneously `docker pull` the same image. I did try it:

Terminal one:
```
# docker run -d ubuntu sleep 10000
Unable to find image 'ubuntu:latest' locally
latest: Pulling from ubuntu
428b411c28f0: Pull complete 
435050075b3f: Pull complete 
9fd3c8c9af32: Pull complete 
6d4946999d4f: Already exists 
ubuntu:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:45e42b43f2ff4850dcf52960ee89c21cda79ec657302d36faaaa07d880215dd9
Status: Downloaded newer image for ubuntu:latest
916d18e0d2078782c5c325d121eda7eba17c96bb2dfe204b02554be01d42636b
```

Terminal two:

```
# docker run -d ubuntu sleep 10000
Unable to find image 'ubuntu:latest' locally
Repository ubuntu already being pulled by another client. Waiting.
73b7c9cd11d01ea7e229524e960a822d813d939c68f58add3ebb3d5c1d2581e2
```

From above, you can see docker actually block the second pull, and successfully start 2 containers with the same image later. The difference between what happened in Kubelet and the test I performed above is in kubelet, we are using remote API and here CLI.

**Comment by antoineco** [comment]
It seems to happen if at some point nodes are in a `NotReady` state:

---
State before adding the node

```
# kubectl get nodes
NAME                                        LABELS                                                             STATUS
ip-10-0-21-176.eu-west-1.compute.internal   kubernetes.io/hostname=ip-10-0-21-176.eu-west-1.compute.internal   NotReady
ip-10-0-21-31.eu-west-1.compute.internal    kubernetes.io/hostname=ip-10-0-21-31.eu-west-1.compute.internal    NotReady
```
```
# kubectl get pods               
NAME            READY     REASON    RESTARTS   AGE
api-45ntp       0/1       Pending   0          7s
api-mxgxo       0/1       Pending   0          7s
api-p4ele       0/1       Pending   0          7s
api-xxdjx       0/1       Pending   0          7s
api-yvf58       0/1       Pending   0          7s
api-zhp5x       0/1       Pending   0          7s
cron-h74e5      0/1       Pending   0          13s
sidekiq-zgpui   0/1       Pending   0          7s
web-cfcvt       0/1       Pending   0          13s
web-pz8r7       0/1       Pending   0          6s
web-sclfg       0/1       Pending   0          13s
web-t52fa       0/1       Pending   0          7s
```

---
We add a new node

```
NAME                                        LABELS                                                             STATUS
ip-10-0-21-176.eu-west-1.compute.internal   kubernetes.io/hostname=ip-10-0-21-176.eu-west-1.compute.internal   NotReady
ip-10-0-21-31.eu-west-1.compute.internal    kubernetes.io/hostname=ip-10-0-21-31.eu-west-1.compute.internal    NotReady
ip-10-0-21-204.eu-west-1.compute.internal   kubernetes.io/hostname=ip-10-0-21-204.eu-west-1.compute.internal   Ready
```
```
# kubectl get pods               
NAME            READY     REASON    RESTARTS   AGE
api-45ntp       0/1       Pending   0          4m
api-mxgxo       0/1       Pending   0          4m
api-p4ele       0/1       Pending   0          4m
api-xxdjx       0/1       Pending   0          4m
api-yvf58       0/1       Pending   0          4m
api-zhp5x       0/1       Pending   0          4m
cron-h74e5      0/1       Pending   0          4m
sidekiq-zgpui   0/1       Pending   0          4m
web-cfcvt       0/1       Pending   0          4m
web-pz8r7       0/1       Pending   0          4m
web-sclfg       0/1       Pending   0          4m
web-t52fa       0/1       Pending   0          4m
```

---
After a short period of time

```
# kubectl get pods
NAME            READY     REASON                                              RESTARTS   AGE
api-45ntp       0/1       no such image                                       0          4m
api-mxgxo       0/1       no such image                                       0          4m
api-p4ele       0/1       no such image                                       0          4m
api-xxdjx       0/1       no such image                                       0          4m
api-yvf58       0/1       no such image                                       0          4m
api-zhp5x       0/1       no such image                                       0          4m
cron-h74e5      0/1       Error: image rails:release-201507010826 not found   0          5m
sidekiq-zgpui   0/1       no such image                                       0          4m
web-cfcvt       0/1       no such image                                       0          5m
web-pz8r7       0/1       no such image                                       0          4m
web-sclfg       0/1       no such image                                       0          5m
web-t52fa       0/1       no such image                                       0          4m
```

---

I'll create a gist with my logs.

**Comment by antoineco** [comment]
Logs available here: https://gist.github.com/antoineco/f03b389a23ffe22fddfe

**Comment by dchen1107** [comment]
Could you please run kubectl describe nodes <node-name> when it is notReady, and share with us the output? NotReady could be caused by docker is not running, kubelet is not responding to API server, or node network configuration issue, etc. 

Also from what you posted above, you have two nodes in NotReady state, and looks like they are stuck at that state, but newly joined node is in Ready very quickly. Is that expected to you? Are you marking those node NotSchedulable?

**Comment by antoineco** [comment]
The `NotReady` nodes have been stopped unintentionally to simulate a failure (I simple stopped kubelet)

Not sure if this is relevant but kubelet seems to mount multiple times the same secret:
```
$ sudo df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        2.0G     0  2.0G   0% /dev
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           2.0G  820K  2.0G   1% /run
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/xvda9      5.5G  5.3G     0 100% /
/dev/xvda3      985M  347M  588M  38% /usr
tmpfs           2.0G     0  2.0G   0% /media
tmpfs           2.0G     0  2.0G   0% /tmp
/dev/xvda6      108M   60K   99M   1% /usr/share/oem
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0b8e1b8d-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/database
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0b8e1b8d-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/secrets
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0ef06b6c-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/database
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0ef06b6c-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/secrets
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0ef5c8cb-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/database
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0efae530-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/database
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0f018ff2-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/database
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0efbff76-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/database
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0efaf961-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/database
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0ef5c8cb-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/secrets
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0efae530-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/secrets
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0f34c1ff-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/database
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0f018ff2-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/secrets
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0efbff76-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/secrets
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0efaf961-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/secrets
tmpfs           2.0G  4.0K  2.0G   1% /var/lib/kubelet/pods/0f34c1ff-2011-11e5-aad9-0a8f896ec459/volumes/kubernetes.io~secret/secrets
```

**Comment by dchen1107** [comment]
Ok, I ruled out GC in kubelet completely, but there is a bug introduced by GC which generates a wrong event related to image pulling. I will explain that later. 

From both docker and kubelet log, I saw pulling image does failed:

```
Jul 01 16:53:18 ip-10-0-21-204.eu-west-1.compute.internal kubelet[979]: W0701 16:53:18.004144     979 manager.go:1496] Failed to pull image "docker.freeletics.com/rails:release-201507010826" from pod "cron-h74e5_default" and container "cron": Error: image rails:release-201507010826 not found
```

```
Jul 01 16:52:54 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:52:54Z" level=info msg="GET /images/docker.freeletics.com/rails:release-201507010826/json"
Jul 01 16:52:54 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:52:54Z" level=info msg="+job image_inspect(docker.freeletics.com/rails:release-201507010826)"
Jul 01 16:52:54 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: No such image: docker.freeletics.com/web:release-201507010832
Jul 01 16:52:54 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:52:54Z" level=info msg="-job image_inspect(docker.freeletics.com/web:release-201507010832) = ERR (1)"
Jul 01 16:52:54 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:52:54Z" level=error msg="Handler for GET /images/{name:.*}/json returned error: No such image: docker.freeletics.com/web:release-201507010832"
Jul 01 16:52:54 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:52:54Z" level=error msg="HTTP Error: statusCode=404 No such image: docker.freeletics.com/web:release-201507010832"
Jul 01 16:52:54 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: No such image: docker.freeletics.com/rails:release-201507010826
Jul 01 16:52:54 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:52:54Z" level=info msg="-job image_inspect(docker.freeletics.com/rails:release-201507010826) = ERR (1)"
Jul 01 16:52:54 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:52:54Z" level=error msg="Handler for GET /images/{name:.*}/json returned error: No such image: docker.freeletics.com/rails:release-201507010826"
Jul 01 16:52:54 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:52:54Z" level=error msg="HTTP Error: statusCode=404 No such image: docker.freeletics.com/rails:release-201507010826"
```

Since you are pulling an image from a private registry, have you followed the steps here:https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/images.md#configuring-nodes-to-authenticate-to-a-private-registry, especially on how to configure an ImagePullSecrets on a pod?

**Comment by antoineco** [comment]
No I'm still using the old-fashioned way of dropping a .dockercfg in /var/lib/kubelet, but I can give `ImagePullSecrets` a try.

I also noticed these errors, and when I observe what's happening on the local machine it seems that images are deleted and pulled at the same time, resulting in a conflict. A watch on `docker images` alternatively shows me my tagged images and dangling images.

**Comment by dchen1107** [comment]
I filed #10629 for misreporting issue. 

When you said the image is deleted later, do you mean the same image you manually pulled from docker outside kubernetes? That is possible since you might pull image, but not used it for some window of time, and kubelet GC kicks in. I think if you run docker run with your image manually instead of docker pull, that image shouldn't be removed at all. 

But still the problem is pulling this one failed.

Also I swear I saw you post another node related to same tmpfs mount for same pod earlier (secret?), but couldn't find it now. Is that a real issue?

**Comment by yujuhong** [comment]
> From both docker and kubelet log, I saw pulling image does failed:

I saw the image pulling failed until around 16:55, where docker seemed to report that the image existed.
```
Jul 01 16:55:36 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:55:36Z" level=info msg="+job log(pull, docker.freeletics.com/rails:release-201507010826, )"
Jul 01 16:55:36 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:55:36Z" level=info msg="-job log(pull, docker.freeletics.com/rails:release-201507010826, ) = OK (0)"
Jul 01 16:55:36 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:55:36Z" level=info msg="-job pull(docker.freeletics.com/rails, release-201507010826) = OK (0)"
Jul 01 16:55:36 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:55:36Z" level=info msg="-job pull(docker.freeletics.com/rails, release-201507010826) = OK (0)"
Jul 01 16:55:36 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:55:36Z" level=info msg="-job pull(docker.freeletics.com/rails, release-201507010826) = OK (0)"
Jul 01 16:55:36 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:55:36Z" level=info msg="-job pull(docker.freeletics.com/rails, release-201507010826) = OK (0)"
Jul 01 16:55:36 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:55:36Z" level=info msg="-job pull(docker.freeletics.com/rails, release-201507010826) = OK (0)"
Jul 01 16:55:36 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:55:36Z" level=info msg="-job pull(docker.freeletics.com/rails, release-201507010826) = OK (0)"
Jul 01 16:55:36 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:55:36Z" level=info msg="-job pull(docker.freeletics.com/rails, release-201507010826) = OK (0)"
Jul 01 16:55:49 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:55:49Z" level=info msg="GET /images/docker.freeletics.com/rails:release-201507010826/json"
Jul 01 16:55:49 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:55:49Z" level=info msg="+job image_inspect(docker.freeletics.com/rails:release-201507010826)"
Jul 01 16:55:49 ip-10-0-21-204.eu-west-1.compute.internal dockerd[789]: time="2015-07-01T16:55:49Z" level=info msg="-job image_inspect(docker.freeletics.com/rails:release-201507010826) = OK (0)"
```
After that, there was no "No such image" error messages anymore. In the meantime, kubelet was still unable to start the containers.

Unless docker was wrong, the image was pulled successfully. @dchen1107, did I interpret the logs wrong?

**Comment by antoineco** [comment]
Thanks a lot for taking care of it.

My images are not deleted if I pull them manually, only if several pods are scheduled simultaneously on the same node and all of them attempt to pull the same image.

I was mistaken regarding the tmpfs mounts, this is why I cleaned up my original post :)

**Comment by antoineco** [comment]
The quickest way to reproduce the issue is simply to provision a fresh node without pre-pulled images and to run:

```
kubectl stop pod `kubectl get pods -o template -t "{{range.items}}{{.metadata.name}} {{end}}"`
```

If at least one Replication Controller in the cluster is scheduled with a sufficient amount of replicas (n.nodes * 3 for example) the problem will occur.

**Comment by dchen1107** [comment]
@yujuhong you interpret the log right. That is also what @antoineco said above, he can pull image manually through docker. I bet around 16:55, he did manual pull.

**Comment by dchen1107** [comment]
@yujuhong is going to carry on with the issue. The first step is reproducing the issue based on https://github.com/GoogleCloudPlatform/kubernetes/issues/10623#issuecomment-117779553

**Comment by yujuhong** [comment]
@antoineco, does the kubelet/docker log include the [kubelet restart and manual image pull you mentioned](https://github.com/GoogleCloudPlatform/kubernetes/issues/10623#issuecomment-117714220)? I didn't see any restart messages in kubelet.log you provided.

**Comment by antoineco** [comment]
Not at all, the logs are from a freshly provisioned node. Do you need the logs after a manual cleanup+pull?

**Comment by yujuhong** [comment]
> Not at all, the logs are from a freshly provisioned node. Do you need the logs after a manual cleanup+pull?

Nope. I just wanted to make sure that the image pull success wasn't caused by your manual pull. Then kubelet did report the pull success correctly, unlike what @dchen1107 stated above in  https://github.com/GoogleCloudPlatform/kubernetes/issues/10623#issuecomment-117789108

**Comment by dchen1107** [comment]
Yes, in this case, it looks like there is indeed a serious bug in kubelet.

**Comment by yujuhong** [comment]
> The quickest way to reproduce the issue is simply to provision a fresh node without pre-pulled images and to run:
> 
> kubectl stop pod `kubectl get pods -o template -t "{{range.items}}{{.metadata.name}} {{end}}"`
> If at least one Replication Controller in the cluster is scheduled with a sufficient amount of replicas (n.nodes * 3 for example) the problem will occur.

If I understand correctly, your reproduction steps cause the replication controller to create new pods, and some of the pods will be assigned to the freshly provisioned node. I should be able to reproduce it by just creating a replication controller with sufficient #replicas using a image that is not already on the nodes. I tried that but did not run into any bugs.

If the image GC actually kicked in and deleted the image, it would have logged something, but I didn't find such messages. Also, image GC would only be active if the disk space is low. @antoineco, was your node low on disk space?

Could you also verify that the image exists on the node after the (non-manual) pull succeeded, even though kubelet continue failing to start the containers?

**Comment by yujuhong** [comment]
@antoineco, I would like to rule out the possibility that the image doesn't exist on the node. It is possible that the container couldn't start for other reasons. Could you try manually starting a docker container using the image?

**Comment by antoineco** [comment]
I just gave it a quick try. I added a new node an scaled my RC: everything went fine.
Seems like I can reproduce it only if I **stop the current nodes** before adding new ones.

I'll try to reproduce the situation described above and do what you asked me to try. Stay tuned.

**Comment by antoineco** [comment]
Allright, interesting finding: it doesn't happen when pulling one image, but when pulling 2 images from the same repo (optionally from 2 different RCs).

I did a test with one RC which pulls the `nginx` image from the Docker Hub, and one RC which pulls the `postgres` image, both from the public repo. Both RC are set to 20 replicas.

```
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 20
  selector:
    image: nginx
  template:
    metadata:
      labels:
        image: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
```
```
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 20
  selector:
    image: postgres
  template:
    metadata:
      labels:
        image: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        imagePullPolicy: IfNotPresent
```

I had one node in `NotReady` state when I scheduled my RCs. Then I started kubelet on this node and saw the same errors after about 30sec.

I tried to start a container manually on the node from one of the images marked as "successfully pulled" (nginx for instance), but the Docker daemon was so overwhelmed that I got no feedback at all.

**Comment by antoineco** [comment]
@yujuhong I edited my previous comment.
The combination of events does not seem to be so easy to reproduce with public repos, however it happens every single time with our private repo, so I posted something much closer to our actual setup instead.

Our private repo is using the v2 API.

**Comment by yujuhong** [comment]
> I had one node in NotReady state when I scheduled my RCs. Then I started kubelet on this node and saw the same errors after about 30sec.

@antoineco, why was the node in `NotReady` state and how did you start kubelet? If you used our cluster setup scripts, `monit` would be monitoring kubelet and would restart it if it's not running.


> I tried to start a container manually on the node from one of the images marked as "successfully pulled" (web for instance), but the Docker daemon was so overwhelmed that I got no feedback at all.

Hmm...it'd be really nice to see if you could start the container manually. I wouldn't expect docker to be so overwhelmed that it didn't respond at all. Were you able to find any information of your request in the docker log file?


> The combination of events does not seem to be so easy to reproduce with public repos, however it happens every single time with our private repo, so I posted something much closer to our actual setup instead.

Could you try to reproduce this on a different private repo?

**Comment by antoineco** [comment]
We run our cluster on CoreOS and provision everything via fleet, so I simply stopped the systemd unit on the node, and started it again manually.

I haven't checked the Docker logs after my attempt, I'll try another time.

I will try with a private repo hosted on the Docker Hub.

**Comment by antoineco** [comment]
Ok, just made another attempt with two images an the RCs posted [earlier](https://github.com/GoogleCloudPlatform/kubernetes/issues/10623#issuecomment-117997161)
* toni0/redis (private)
* toni0/postgres (public)

Surprisingly the **public** images failed this time. This is driving me crazy.
Again the logs show `Successfully pulled image` but all the pods in the RC stay in a `Waiting, no such image` state.

---
master

```
$ kubectl get rc  
CONTROLLER   CONTAINER(S)   IMAGE(S)         SELECTOR                                                           REPLICAS
api          api            toni0/redis      example.com/app=api-backend,example.com/repo=fl-backend-rails      20
web          web            toni0/postgres   example.com/app=web-frontend,example.com/repo=fl-application-web   20

$ kubectl get pods
NAME        READY     REASON                                                                                                                                                                                                                                                                                       RESTARTS   AGE
api-1fknt   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-49epg   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-6itwa   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-7b9f9   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-8eclk   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-8f7ar   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-e3gvf   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-eabj3   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-fggm5   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-flnsj   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-g00n0   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-g4hfn   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-l83wv   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-ouihx   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-ppyc1   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-q4vte   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-qtige   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-vie6y   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-x48fw   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
api-y1ezw   1/1       Running                                                                                                                                                                                                                                                                                      0          9m
web-0xsog   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-3n019   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-4ire1   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-5c6mb   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-80lgw   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-8hj1a   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-90hoo   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-aofln   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-bmj1m   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-hzp8t   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-k4vat   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-o555g   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-okota   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-po3vy   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-sn8je   0/1       Error pulling image (latest) from toni0/postgres, Driver overlay failed to create image rootfs b79ac6ba829c1d2658ca4b48f4d5f285651c0dcbb0b96126e0d07a7089f7207b: lstat /var/lib/docker/overlay/b3d362b23ec1a7ba1694e6607b44c5e3fb63d68e5ae01f339c6abe8b0c995601: no such file or directory   0          9m
web-szrdy   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-uvj56   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-v0i7w   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-wmzsv   0/1       no such image                                                                                                                                                                                                                                                                                0          9m
web-z7ux2   0/1       no such image                                                                                                                                                                                                                                                                                0          9m

$ kubectl describe pod web-0xsog
Name:				web-0xsog
Image(s):			toni0/postgres
Node:				i-161510bc/10.0.23.7
Labels:				example.com/app=web-frontend,example.com/repo=fl-application-web
Status:				Pending
Reason:				
Message:			
IP:				172.17.93.27
Replication Controllers:	web (20/20 replicas created)
Containers:
  web:
    Image:		toni0/postgres
    State:		Waiting
      Reason:		no such image
    Ready:		False
    Restart Count:	0
Conditions:
  Type		Status
  Ready 	False 
Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath				Reason			Message
  Mon, 06 Jul 2015 21:33:37 +0000	Mon, 06 Jul 2015 21:34:41 +0000	7	{scheduler }							failedScheduling	Error scheduling: no nodes available to schedule pods
  Mon, 06 Jul 2015 21:35:41 +0000	Mon, 06 Jul 2015 21:35:41 +0000	1	{scheduler }							scheduled		Successfully assigned web-0xsog to i-161510bc
  Mon, 06 Jul 2015 21:35:43 +0000	Mon, 06 Jul 2015 21:35:43 +0000	1	{kubelet i-161510bc}	implicitly required container POD	pulled			Successfully pulled Pod container image "gcr.io/google_containers/pause:0.8.0"
  Mon, 06 Jul 2015 21:35:44 +0000	Mon, 06 Jul 2015 21:35:44 +0000	1	{kubelet i-161510bc}	implicitly required container POD	created			Created with docker id 8cd47d18a732
  Mon, 06 Jul 2015 21:35:45 +0000	Mon, 06 Jul 2015 21:35:45 +0000	1	{kubelet i-161510bc}	implicitly required container POD	started			Started with docker id 8cd47d18a732
  Mon, 06 Jul 2015 21:41:58 +0000	Mon, 06 Jul 2015 21:41:58 +0000	1	{kubelet i-161510bc}	spec.containers{web}			failed			Failed to pull image "toni0/postgres": Error pulling image (latest) from toni0/postgres, Server error: 404 trying to fetch remote history for b733b00eb1aeaf6eb3a6ac9db8293faa0efe130008b785ccf2112f2a01f1daef
  Mon, 06 Jul 2015 21:43:50 +0000	Mon, 06 Jul 2015 21:43:50 +0000	1	{kubelet i-161510bc}	spec.containers{web}			failed			Failed to pull image "toni0/postgres": Error pulling image (latest) from toni0/postgres, Driver overlay failed to create image rootfs b79ac6ba829c1d2658ca4b48f4d5f285651c0dcbb0b96126e0d07a7089f7207b: lstat /var/lib/docker/overlay/b3d362b23ec1a7ba1694e6607b44c5e3fb63d68e5ae01f339c6abe8b0c995601: no such file or directory
  Mon, 06 Jul 2015 21:44:32 +0000	Mon, 06 Jul 2015 21:44:32 +0000	1	{kubelet i-161510bc}	spec.containers{web}			failed			Failed to pull image "toni0/postgres": Error pulling image (latest) from toni0/postgres, Server error: 503 trying to fetch remote history for b733b00eb1aeaf6eb3a6ac9db8293faa0efe130008b785ccf2112f2a01f1daef
  Mon, 06 Jul 2015 21:37:24 +0000	Mon, 06 Jul 2015 21:45:41 +0000	47	{kubelet i-161510bc}	spec.containers{web}			failed			Failed to create docker container with error: no such image
  Mon, 06 Jul 2015 21:37:24 +0000	Mon, 06 Jul 2015 21:45:41 +0000	47	{kubelet i-161510bc}	spec.containers{web}			pulled			Successfully pulled image "toni0/postgres"
```

---
node

```
node $ docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
anigeo/awscli                    latest              c0be52a7d31d        2 hours ago         77.2 MB
toni0/redis                      latest              06a1f75304ba        10 weeks ago        111 MB
gcr.io/google_containers/pause   0.8.0               2c40b0526b63        3 months ago        241.7 kB

node $ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda9       13G  638M   12G   6% /
```

---

While kubelet is running, a manual pull/run is always interrupted:

```
$ docker run -it toni0/postgres bash
Unable to find image 'toni0/postgres:latest' locally
latest: Pulling from toni0/postgres
b79ac6ba829c: Download complete 
b79ac6ba829c: Error downloading dependent layers 
a434655952f5: Download complete 
9bcda8d0a286: Layer already being pulled by another client. Waiting. 
43456c1252a8: Download complete 
69701d84be3d: Download complete 
21205e2bc015: Pulling fs layer 
21205e2bc015: Download complete 
98e5d12b8156: Download complete 
fafa5e2bf319: Download complete 
8aabf1e9f5ec: Download complete 
bb01935ca883: Downloading [=>                                                 ] 1.084 MB/34.74 MB
283dadd11371: Download complete 
b45205d9bb4a: Download complete 
d7894be26ffe: Download complete 
84ffeab42052: Download complete 
122b9e94ad75: Download complete 
bcaf007f9d72: Download complete 
1c378a875d41: Download complete 
b733b00eb1ae: Error pulling image (latest) from toni0/postgres, Driver overlay failed to create image rootfs b79ac6ba829c1d2658ca4b48f4d5f285651c0dcbb0b96126e0d07a7089f7207b: lstat /var/lib/docker/overlay/b3d362b23ec1a7ba1694e6607b44c5e3fb63d68e5ae01f339c6abe8b0c995601: no such file or directory 9c6abe8b0c995601: no such file or directory 
b3d362b23ec1: Download complete 
FATA[0005] Error pulling image (latest) from toni0/postgres, Driver overlay failed to create image rootfs b79ac6ba829c1d2658ca4b48f4d5f285651c0dcbb0b96126e0d07a7089f7207b: lstat /var/lib/docker/overlay/b3d362b23ec1a7ba1694e6607b44c5e3fb63d68e5ae01f339c6abe8b0c995601: no such file or directory
```

Log upload in progress.

**Comment by antoineco** [comment]
Just updated the Gist @ https://gist.github.com/antoineco/f03b389a23ffe22fddfe

**Comment by antoineco** [comment]
Another attempt with a fresh node: this time posgres succeeded and redis failed.

```
$ kubectl get pods
NAME        READY     REASON                                                                                                                                                                                                                                                                                    RESTARTS   AGE
api-04k2y   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
api-1tde8   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
api-2zhvg   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
api-364nl   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
api-6jkfa   0/1       Error pulling image (latest) from toni0/redis, Driver overlay failed to create image rootfs 29809ed33dfd5174ead85945ef7757862cb2ef53396ee5bbd390fa1893e9f033: lstat /var/lib/docker/overlay/b3d362b23ec1a7ba1694e6607b44c5e3fb63d68e5ae01f339c6abe8b0c995601: no such file or directory   0          2m
api-86ihz   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
api-98su1   0/1       no such image                                                                                                                                                                                                                                                                             0          1m
api-9927k   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
api-bypsu   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
api-d43dc   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
api-d71og   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
api-eja4d   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
api-ge12j   0/1       no such image                                                                                                                                                                                                                                                                             0          1m
api-jdomo   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
api-rl9vq   0/1       no such image                                                                                                                                                                                                                                                                             0          1m
api-sieub   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
api-t2gkg   0/1       no such image                                                                                                                                                                                                                                                                             0          1m
api-xm3xl   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
api-xs231   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
api-y30h6   0/1       no such image                                                                                                                                                                                                                                                                             0          2m
web-05fh9   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-1zyv2   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-3709e   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-7uhua   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-8fpt2   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-cyxwb   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-ekjkg   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-ffyw7   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-gqj86   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-hgqkb   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-kd22k   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-kt619   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-mxzce   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-n5r5r   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-nrsl8   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-orrk6   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-pqox0   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-s3ky1   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-ug4q8   1/1       Running                                                                                                                                                                                                                                                                                   0          1m
web-yq38h   1/1       Running                                                                                                                                                                                                                                                                                   0          1m

```

This time most errors seem to be related to overlayfs, still the issue always seem to occur when multiple pods pull at the same time.

I'm committing a new revision of the Gist with a kubelet log level of 4.

**Comment by yujuhong** [comment]
@antoineco, what version of docker are you using? I found a docker issue https://github.com/docker/docker/issues/9718 (pre 1.7.1) that seemed to show similar symptoms as yours at concurrent image pulls. The issue has been fixed in docker 1.7.1

**Comment by antoineco** [comment]
Right now Docker 1.6.2.
I can try with Docker 1.7.1, but it will take a while before everybody updates to this version. It's surprising that I'm the only one to observe this behavior, especially with both the latest CoreOS and Kubernetes.

**Comment by yujuhong** [comment]
There seems to be quite a few people hitting this issue by looking at the docker issues (https://github.com/docker/docker/issues/9718, https://github.com/docker/docker/issues/13971). The fundamental problem seems to be layer corruption due to multiple concurrent pulls ("Multiple simultaneous docker pulls that depend on the same underlying layers will corrupt them.").

Thank you very much for bringing this issue to our attention :)  We'd like to implement a workaround to serialize image pulls, but given that our v1.0 release is imminent, we might not be able to make it in time. At the very least, we will document this known docker issue so that users can be aware.

**Comment by antoineco** [comment]
Short update from my side, using Docker 1.7.1 doesn't solve the issue. Images still seem to get corrupted if I schedule multiple pods on a fresh node. I'll see if I can reproduce it outside of Kubernetes and report it upstream.

**Comment by yujuhong** [comment]
@antoineco, thanks for the update! Please keep us posted on the reproduction attempt.

**Comment by antoineco** [comment]
So far I haven't tried to forcibly make it happen. I'll give it another shot in a cluster running Docker 1.8.1 with Artifactory 4.0.2 powering our repository.

**Comment by yujuhong** [comment]
That'd be great. Thanks! Just FYI, we are trying to upgrade to docker 1.8.2 for our next release.

**Comment by antoineco** [comment]
This is still happening with the environment described above: k8s 1.0.5, docker 1.8.1, artifactory 4.1.0

Output of `kubectl describe pod <name>`:
```
  Tue, 15 Sep 2015 14:17:40 +0200	Tue, 15 Sep 2015 14:17:40 +0200	1	{kubelet ip-10-0-1-106.eu-west-1.compute.internal}	implicitly required container POD	pulled		Successfully pulled Pod container image "gcr.io/google_containers/pause:0.8.0"
  Tue, 15 Sep 2015 14:17:40 +0200	Tue, 15 Sep 2015 14:17:40 +0200	1	{kubelet ip-10-0-1-106.eu-west-1.compute.internal}	implicitly required container POD	created		Created with docker id 7beaa8e1d55e
  Tue, 15 Sep 2015 14:17:40 +0200	Tue, 15 Sep 2015 14:17:40 +0200	1	{kubelet ip-10-0-1-106.eu-west-1.compute.internal}	implicitly required container POD	started		Started with docker id 7beaa8e1d55e
  Tue, 15 Sep 2015 14:18:28 +0200	Tue, 15 Sep 2015 14:18:28 +0200	1	{kubelet ip-10-0-1-106.eu-west-1.compute.internal}	spec.containers{sidekiq}		failed		Failed to pull image "docker.freeletics.com/rails:2015-09-15_0557": Error: image rails:2015-09-15_0557 not found
```

```
  Tue, 15 Sep 2015 14:17:40 +0200	Tue, 15 Sep 2015 14:17:40 +0200	1	{kubelet ip-10-0-1-106.eu-west-1.compute.internal}	implicitly required container POD	pulled		Successfully pulled Pod container image "gcr.io/google_containers/pause:0.8.0"
  Tue, 15 Sep 2015 14:17:40 +0200	Tue, 15 Sep 2015 14:17:40 +0200	1	{kubelet ip-10-0-1-106.eu-west-1.compute.internal}	implicitly required container POD	created		Created with docker id 561b3a48d1b9
  Tue, 15 Sep 2015 14:17:40 +0200	Tue, 15 Sep 2015 14:17:40 +0200	1	{kubelet ip-10-0-1-106.eu-west-1.compute.internal}	implicitly required container POD	started		Started with docker id 561b3a48d1b9
  Tue, 15 Sep 2015 14:19:32 +0200	Tue, 15 Sep 2015 14:21:16 +0200	13	{kubelet ip-10-0-1-106.eu-west-1.compute.internal}	spec.containers{web}			failed		Failed to pull image "docker.freeletics.com/web:2015-09-15_11-48": Error: image web:2015-09-15_11-48 not found
```

It doesn't happen if I manually pull the same images concurrently, for example by starting several `docker pull` in the background, so far only `kubelet` seems to cause this issue.

My partition is 58% full and the gc is configured as follows: `--image-gc-high-threshold=70 --image-gc-low-threshold=50` but the problem also happened before with `--image-gc-high-threshold=90 --image-gc-low-threshold=80` (the default) so it's definitely not a garbage collection issue.

I end up with the following error when I try to manually pull the image, until I stop the `kubelet` process and manually remove the faulty layers: `Error: image rails:2015-09-15_0557 not found`.

**Comment by yujuhong** [comment]
Agreed that this is not a GC issue. I don't think Docker has fixed this issue completely. From https://github.com/docker/docker/issues/9718#issuecomment-137250466, it seems like https://github.com/docker/docker/pull/15728 and https://github.com/docker/docker/pull/15955 would solve/mitigate the issue, and none of them have made it to the releases yet...

@dchen1107, v1.8.2 doesn't solve this problem. If this is targeted for v1.1, we would need to patch kubelet to serialize image pulls. On the other hand, I couldn't reliably reproduce this issue for testing :(

**Comment by antoineco** [comment]
@yujuhong you have to schedule 2+ pods with containers using images which share multiple layers.

The more layers the more chance you have to hit it, for example mysql:5.6 and postgres:9.4 both use debian:jessie as the baseimage, **but** debian:jessie has only 2 layers so chances are that you never corrupt them.

Our base image has 5 layers, 3 on top of debian:jessie, one of them being 154MB. We add about 4 more layers to each image you see in my previous log, one of them being some 150-200 extra MB. Pulling takes some time, and 5 layers are always shared.

Make sure everything is pulled at the same time, and make sure shared layers will be pulled on a single node, i.e. start kubelet on a node which had an empty /var/lib/docker in a single-node cluster. For example, our pods are scheduled before the first node even shows up, and as soon as it does... boom.

**Comment by dchen1107** [comment]
Serializing docker image pull might affect overall performance. I have some ideas on fixing this, will send out pr shortly.

**Comment by jhspaybar** [comment]
FYI, the AWS ECS agent does serialize pulls exactly for this reason.

**Comment by worldsense-tms** [comment]
using docker-1.9.0-dev I managed to get one such pull finished, while it failed consistently with 1.8.2. I downloaded it from https://master.dockerproject.org/, stopped the service and ran manually with sudo docker -d -D.

**Comment by yujuhong** [comment]
@worldsense-tms, that's good news! Thanks for letting us know.

@dchen1107, do you still want to get the short-term fix in for v1.1?

**Comment by dchen1107** [comment]
dup of #12670
