### ISSUE TITLE
client wait forever if kube-apiserver restart in slb environment

### ISSUE THREAD

**Issue by smileusd** [kubernetes/kubernetes#107266]
### What happened?

We found if use slb between kube-apiserver and client, when kube-apiserver restart, client watcher connection not close and wait an event forever. In this case has two connections:  kube-apiserver <-> slb, slb <-> client. After close the first connection could not ensure the second connection also closed if slb hard to handle this long connection situation.

### What did you expect to happen?

rebuild the client watcher and watch the new events

### How can we reproduce it (as minimally and precisely as possible)?

restart apiserver and patch a new resource and watch the log from client, will find nothing.

### Kubernetes version

v1.18.8

### Cloud provider

no

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
This has been fixed in recent versions that use HTTP2, by default there is an idle timeout of 30s in the connection that will detect that this is stale and restart it, solving this problem.

**Comment by aojea** [comment]
I think it went in in 1.19 https://github.com/kubernetes/kubernetes/issues/87615

**Comment by smileusd** [comment]
@aojea Thank you for reply. But i can not find the log from client "use of closed network connection", In my case client didn't recieved any events include EOF or `IsProbableEOF`. The connection is still available from slb to client. But as you said, go 1.16.5 add HTTP2 health check can check idle timeout may be can also solve this problem. I will try it. Thanks.

**Comment by smileusd** [comment]
@aojea I try to update golang from 1.14 to 1.16.12 and build a version. But issues still exist. The update can not fix this problem.

**Comment by aojea** [comment]
> @aojea I try to update golang from 1.14 to 1.16.12 and build a version. But issues still exist. The update can not fix this problem.

is not a golang version update, you need kubernetes 1.19 or greater. 
Bear in mind that latest release supported is 1.20, https://kubernetes.io/releases/ , this bug has to be present in one of the supported versions in order to be accepted

**Comment by smileusd** [comment]
This is my own controller and use client-go. I update golang to 1.16.12, client-go to newest and using newest "golang.org/x/net/http2" pkg. But also not work. Looks like http2 and healthcheck has been enabled

**Comment by aojea** [comment]
> @aojea This is my own controller and use client-go. I update golang to 1.16.12, client-go to newest and using newest "golang.org/x/net/http2" pkg. But also not work. Looks like http2 and healthcheck has been enabled

how can I reproduce it?

**Comment by smileusd** [comment]
After add client idle timeout from slb can resolved this. Client can receive EOF and rebuild a watcher:
```
I0106 10:16:51.074244       1 streamwatcher.go:103] Unexpected EOF during watch stream event decoding: unexpected EOF
I0106 10:16:51.074279       1 reflector.go:357] tess.io/ebay/vm-volume/pkg/controller/attach/attach_controller.go:282: Watch close - *v1.VmVolumeAttachment total 0 items received
```

**Comment by aojea** [comment]
> After add client idle timeout from slb can resolved this. Client can receive EOF and rebuild a watcher:

yeah, that should be added by default

https://github.com/kubernetes/kubernetes/blob/2af53e9f64eee81a09fd0fd1f0fc96ce0859eb0f/staging/src/k8s.io/apimachinery/pkg/util/net/http.go#L180-L189
