### ISSUE TITLE
Pods with failed status IP address reused on new pods, but traffic still going to old pods across namespaces. 

### ISSUE THREAD

**Issue by declangallagher** [kubernetes/kubernetes#109414]
### What happened?

Since upgrading to v1.22.7-gke.1500 in GKE cluster, we have noticed that pods marked as OutOfmemory
Terminated, ContainerStatusUnknown, OOMKilled, OutOfcpu are still showing as "ready" in the endpoints list, causing traffic to route to them.

### What did you expect to happen?

For the pods to be deleted, and if there IP address is reused, for the IP address not to be routed to the old pod anymore. 

### How can we reproduce it (as minimally and precisely as possible)?

Start a GKE cluster using OS: Container-Optimized OS, on version: v1.22.7-gke.1500

Achieve one of the following status's on a pod: 
OutOfmemory
Terminated
ContainerStatusUnknown
OOMKilled
OutOfcpu

Observe that a new pod in cluster is assigned the same IP address as the pod with one of the above failed status's, and that old pod is still serving requests on the now reused IP address. 

### Kubernetes version

<details>

```console
$ kubectl version
v1.22.7-gke.1500
```

</details>

### Cloud provider

GKE

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
KERNEL_COMMIT_ID=ccbab0481cec29d7f07947bcb6255f325b88513f
GOOGLE_CRASH_ID=Lakitu
GOOGLE_METRICS_PRODUCT_ID=26
VERSION=93
VERSION_ID=93
BUILD_ID=16623.102.23
$ uname -a
Linux gke-cf-europe-west2-cluster-ego-c2-pm-08b6d578-8kz5 5.10.90+ #1 SMP Sat Mar 5 10:09:49 UTC 2022 x86_64 Intel(R) Xeon(R) CPU @ 3.10GHz GenuineIntel GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by khenidak** [comment]
Hi @declangallagher few questions to get a better picture of the issue:

1. is client-pod accessing the server-pod (of which the IP has been given to a different pod) via a service or directly?
2. What was the health of the controller manager specifically endpoint and endpointSlice controllers?

**Comment by thockin** [comment]
Are you saying you have two running pods with the same IP?  Can you show us something like `kubectl get pods -o json | jq '.items[] | .metadata.name, .status.podIP, .status.phase'`

Is this on containerd or dockershim?

**Comment by aojea** [comment]
I've seen something similar with a CNI whose IPAM was recycling IPs, per example, podA was assigned 10.1.1.11, it was deleted and podB was created at the same time, reusing the previously assigned IP 10.1.1.11 ... just sharing

**Comment by thockin** [comment]
@declangallagher ICYMI we are waiting on you for more info.

**Comment by breunigs** [comment]
We're experiencing similar symptoms after upgrading from v1.21.5 to v1.22.8. Bisecting leads to 3eadd1a9ead7a009a9abfbd603a5efd0560473cc (https://github.com/kubernetes/kubernetes/pull/102344) as the first broken commit. The issue is still present on `HEAD` at the time (= 076168b84d0af4ad65cb5664fc1cef40f837e9dc). I'll attach the reproducer at the bottom.

We observe this when kubelet evicts a Pod, which then either goes into `ContainerStatusUnknown` or `Error`, depending on which exact version is checked out. While bisecting, I also observed some of the already fixed issues like https://github.com/kubernetes/kubernetes/pull/105462 . The issue does not appear when I manually evict through the Eviction API.

Prior to 3eadd1a9ead7a009a9abfbd603a5efd0560473cc, the Pod would not retain its PodIP after eviction and/or container termination/cleanup. After this PR it does, so that the IPs still show up in the `Endpoint` under `notReadyAddresses`. Since the IP eventually gets reused by unrelated pods, we run into issues similar to the ones described in this Prometheus ticket https://github.com/prometheus/prometheus/issues/10257#issuecomment-1046783113 .

The containers on the node are cleaned up properly.

I am not sure in which component the fault is. I.e. should the Pod lose its PodIP upon/after eviction; should it just not be present in the Endpoint/EndpointSlice at all; or should the IP not be reused until the Pod has been (manually) cleaned up?

My reproducer is similar to the ones in other tickets; essentially spawn a Pod that gets evicted due to ephemeral storage/disk pressure. I used `resources.limits.ephemeral-storage` here because that was easiest to change (and I did not want to exhaust my actual disk). On our non-kind cluster it works the same through normal node disk pressure eviction, though.

```bash
# setup
kubetest2 kind -v 2 --kube-root . --build --up
kubectl apply -f evictme.yaml
# observe through either; need to wait for the eviction to happen of course
kubectl get pods -owide
kubectl get endpoints -ojson evictme | jq '.subsets[0].notReadyAddresses'
# teardown
kubetest2 kind -v 2 --kube-root . --down
```

```yaml
# evictme.yaml
kind: Pod
apiVersion: v1
metadata:
  name: evictme
  labels:
    pod: evictme
spec:
  terminationGracePeriodSeconds: 10
  containers:
  - name: busybox
    image: k8s.gcr.io/e2e-test-images/nginx:1.14-2
    # the first sleep is meant to curb races, as that's not the main issue.
    # I didn't check if it's actually necessary.
    command: ["sh", "-c", "sleep 10; fallocate -l 10M file; sleep 100000"]
    ports:
    - containerPort: 80
    resources:
      limits:
        ephemeral-storage: 5Mia
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: evictme
spec:
  ports:
  - name: http
    port: 80
  selector:
    pod: "evictme"
  type: ClusterIP
```

**Comment by aojea** [comment]
/triage accepted

This is legit, thanks for the reproducer, and there more issues related like this https://github.com/kubernetes/kubernetes/issues/109718

In 1.22 there was a change in the kubelet https://github.com/kubernetes/kubernetes/issues/106884#issuecomment-1005074672 , most of the issues were solved but seems the surface was bigger than expected and is not deleting the pod.Status.PodIPs field cc: @smarterclayton

**Comment by smarterclayton** [comment]
Are CNI plug-ins depending on pod status ips as the authoritative record of allocation?  Also, do we formally define CNI destroy as happening before that release?

The answer to those two questions is required to correctly determine where in pod shutdown logic needs to be added (and this is another kubelet e2e test we need to add).  Ie if the second is no, we can clear the status podIPs once the pod containers are confirmed shutdown.  If the second is yes, we have to defer the final pod status update and the clear until after cni destroy is guaranteed to succeed (that has other safety implications).

**Comment by navidnadali** [comment]
Hi All

Apologies for the delay, just to confirm we are still experiencing this in production - I have asked @declangallagher to come back to all the questions today
