### ISSUE TITLE
kubectl exec -it get messed up terminal 

### ISSUE THREAD

**Issue by pallasathena92** [kubernetes/kubernetes#112109]
### What happened?

I want to get a pod shell to check the file inside the pod, but I can't get a normal terminal to run any command line. I tried in UI tool Lens and my local terminal, and I got the same error. I compared it to my colleague's terminal setting (bashrc), we have the same setting, but I get the wrong pod shell. I am not sure how I can fix it, so ask here.
![image](https://user-images.githubusercontent.com/31553858/187302457-34afda43-02d0-42eb-8c4f-62bd7db3b755.png)
![image](https://user-images.githubusercontent.com/31553858/187302531-14421267-b88c-44f9-9325-61c05bd8397f.png)

### What did you expect to happen?

I need a normal terminal to run commands I want

### How can we reproduce it (as minimally and precisely as possible)?

I am not sure, because my colleague can't reproduce it either.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
14:19 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"c999fea1e6dbf111d64000dfaaff45edaa4c34d2", GitTreeState:"clean", BuildDate:"2022-01-11T12:16:14Z", GoVersion:"go1.16.12 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

<details>
Oracle Cloud infrastructure - OCI
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
Catalina 10.15.7

### Install tools

<details>

</details>
14:31 $ docker version
Client:
 Cloud integration: v1.0.20
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:43:15 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:30 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dgl** [comment]
You've likely got an environment variable set like `DEBUG=1` and you're seeing [SpdyStream](https://pkg.go.dev/github.com/moby/spdystream#pkg-variables) debugging output.

Minimal reproducer is simply:
```
DEBUG=1 kubectl run --attach --stdin --tty --image=busybox busybox-test
If you don't see a command prompt, try pressing enter.
I0830 15:55:58.129372   95317 log.go:184] (0x140005c6370) (0x140004ad0e0) Create stream
                                                                                       I0830 15:55:58.129511   95317 log.go:184] (0x140005c6370) (0x140004ad0e0) Stream added, broadcasting: 1
````
[cut lots of command output]

I think this is best fixed in SpdyStream, there's already an issue here: https://github.com/moby/spdystream/issues/87

**Comment by pallasathena92** [comment]
> You've likely got an environment variable set like `DEBUG=1` and you're seeing [SpdyStream](https://pkg.go.dev/github.com/moby/spdystream#pkg-variables) debugging output.
> 
> Minimal reproducer is simply:
> 
> ```
> DEBUG=1 kubectl run --attach --stdin --tty --image=busybox busybox-test
> If you don't see a command prompt, try pressing enter.
> I0830 15:55:58.129372   95317 log.go:184] (0x140005c6370) (0x140004ad0e0) Create stream
>                                                                                        I0830 15:55:58.129511   95317 log.go:184] (0x140005c6370) (0x140004ad0e0) Stream added, broadcasting: 1
> ```
> 
> [cut lots of command output]
> 
> I think this is best fixed in SpdyStream, there's already an issue here: [moby/spdystream#87](https://github.com/moby/spdystream/issues/87)

I tried to change the `DEBUG=True` in my bash_profile, and I forced to make it False in my environment. But I still get messed up terminal 
```
kubectl exec -it pre-trained-document-ocr-685cb6b5b-bzvfv -c pre-trained-document-ocr -n pre-trained-triton-ocr bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
I0830 14:16:28.709438   75247 log.go:184] (0xc00013e2c0) (0xc0007a0000) Create stream
                                                                                     I0830 14:16:28.709797   75247 log.go:184] (0xc00013e2c0) (0xc0007a0000) Stream added, broadcasting: 1
                                                                                                                                                                                          I0830 14:16:28.804914   75247 log.go:184] (0xc00013e2c0) Reply frame received for 1
                                                                                                                                                                                                                                                                             I0830 14:16:28.804950   75247 log.go:184] (0xc00013e2c0) (0xc00068dae0) Create stream
                                                                                                                                                                                                                                                                                                                                                                  I0830 14:16:28.804958   75247 log.go:184] (0xc00013e2c0) (0xc00068dae0) Stream added, broadcasting: 3
                                                                                           I0830 14:16:28.908274   75247 log.go:184] (0xc00013e2c0) Reply frame received for 3
                                                                                                                                                                              I0830 14:16:28.908340   75247 log.go:184] (0xc00013e2c0) (0xc0007a0140) Create stream
                                                                                                                                                                                                                                                                   I0830 14:16:28.908367   75247 log.go:184] (0xc00013e2c0) (0xc0007a0140) Stream added, broadcasting: 5
                                                                                                                                                                                                                                                                                                                                                                        I0830 14:16:28.991571   75247 log.go:184] (0xc00013e2c0) Reply frame received for 5
```
Also, I tried to add bebug=0 in my command, it works
```
$ debug=0 kubectl exec -it pre-trained-document-ocr-685cb6b5b-bzvfv -c pre-trained-document-ocr -n pre-trained-triton-ocr bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@pre-trained-document-ocr-685cb6b5b-bzvfv:/opt/tritonserver# cd
root@pre-trained-document-ocr-685cb6b5b-bzvfv:~# ls
```
So now, the problem is how could make debug=0 as default during run kubectl?

**Comment by pallasathena92** [comment]
I tried in the Lens, change my env works now. thanks for the help @dgl
