### ISSUE TITLE
Pod is stuck in terminating with "MountVolume.SetUp failed for volume ... not registered" error

### ISSUE THREAD

**Issue by tossmilestone** [kubernetes/kubernetes#113289]
### What happened?

Pod is stuck in terminating state when rapidly create and delete the pod, the kubelet log reported the volume setup error:
```
Oct 21 12:09:20 slave2 kubelet[4089]: E1021 12:09:20.197090    4089 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/secret/dc79f107-6576-4d98-a120-23336154393e-tls-cert-vol podName:dc79f107-6576-4d98-a120-23336154393e nodeName:}" failed. No retries permitted until 2022-10-21 12:11:22.19703932 +0800 CST m=+323223.503182418 (durationBeforeRetry 2m2s). Error: MountVolume.SetUp failed for volume "tls-cert-vol" (UniqueName: "kubernetes.io/secret/dc79f107-6576-4d98-a120-23336154393e-tls-cert-vol") pod "vela-core-8494697c8c-xgrwt" (UID: "dc79f107-6576-4d98-a120-23336154393e") : object "cpaas-system"/"vela-core-admission" not registered
```

It has the same error with #105204, but the k8s 1.23.13 we used have fixed the issue with the PR #108756.

So the PR haven't totally fixed the issue. The cause may be if the pod is deleted when the volume manager is setting up the volume of the pod, the `syncPod` loop in kubelet won't add the reference count because it's in terminating state.

So the volume manager will still try to setup the volume of the pod but failed with the "not registed" error.

### What did you expect to happen?

The pod should be deleted without the volume setup error.

### How can we reproduce it (as minimally and precisely as possible)?

It's the possibel reproduce steps:
1. Create a pod with a configmap volume
2. After the pod is created, delete the pod immediately

Maybe the steps should be runned several times. 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
</details>
v1.23.13

### Cloud provider

<details>

</details>
None

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
CentOS 7.3

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/assign @rphillips 

sounds pretty close to other bug we looked at earlier when clean up was failing causing many pod GC loops keep running. @rphillips to take a look if it's the same issue

**Comment by ugur99** [comment]
We have the same problem from time to time with two different k8s version: `v1.24.10` and `v1.23.7`, but usually during the rollout process; old instances/pods get stuck in the termination phase with the following errors. Are there any updates on this issue?


kubelet logs:
```
E0828 00:58:36.944965 3293071 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/projected/3fdf6bd3-78d8-4ce6-a0ed-e97005a8d06b-kube-api-access-qlshz podName:3fdf6bd3-78d8-4ce6-a0ed-e97005a8d06b nodeName:}" failed. No retries permitted until 2023-08-28 01:00:38.94493703 +0000 UTC m=+218616.925334872 (durationBeforeRetry 2m2s). Error: MountVolume.SetUp failed for volume "kube-api-access-qlshz" (UniqueName: "kubernetes.io/projected/3fdf6bd3-78d8-4ce6-a0ed-e97005a8d06b-kube-api-access-qlshz") pod "pod-name-79687c7975-hrfmv" (UID: "3fdf6bd3-78d8-4ce6-a0ed-e97005a8d06b") : object "test-namespace"/"kube-root-ca.crt" not registered
2023-08-28 03:00:39.014	
I0828 01:00:39.014791 3293071 reconciler.go:258] "operationExecutor.MountVolume started for volume \"kube-api-access-qlshz\" (UniqueName: \"kubernetes.io/projected/3fdf6bd3-78d8-4ce6-a0ed-e97005a8d06b-kube-api-access-qlshz\") pod \"pod-name-79687c7975-hrfmv\" (UID: \"3fdf6bd3-78d8-4ce6-a0ed-e97005a8d06b\") " pod="test-namespace/pod-name-79687c7975-hrfmv"
2023-08-28 03:00:39.015	
E0828 01:00:39.014988 3293071 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/projected/3fdf6bd3-78d8-4ce6-a0ed-e97005a8d06b-kube-api-access-qlshz podName:3fdf6bd3-78d8-4ce6-a0ed-e97005a8d06b nodeName:}" failed. No retries permitted until 2023-08-28 01:02:41.014973186 +0000 UTC m=+218738.995371018 (durationBeforeRetry 2m2s). Error: MountVolume.SetUp failed for volume "kube-api-access-qlshz" (UniqueName: "kubernetes.io/projected/3fdf6bd3-78d8-4ce6-a0ed-e97005a8d06b-kube-api-access-qlshz") pod "pod-name-79687c7975-hrfmv" (UID: "3fdf6bd3-78d8-4ce6-a0ed-e97005a8d06b") : object "test-namespace"/"kube-root-ca.crt" not registered
2023-08-28 03:02:41.035	
I0828 01:02:41.034974 3293071 reconciler.go:258] "operationExecutor.MountVolume started for volume \"kube-api-access-qlshz\" (UniqueName: \"kubernetes.io/projected/3fdf6bd3-78d8-4ce6-a0ed-e97005a8d06b-kube-api-access-qlshz\") pod \"pod-name-79687c7975-hrfmv\" (UID: \"3fdf6bd3-78d8-4ce6-a0ed-e97005a8d06b\") " pod="test-namespace/pod-name-79687c7975-hrfmv"
```

`kubectl describe pod pod-name-79687c7975-hrfmv`:

```
Name:                      pod-name-79687c7975-hrfmv
Namespace:                 test-namespace
Node:                      worker02/ip
Status:                    Terminating (lasts 132m)
Termination Grace Period:  30s
Containers:
  pod-name:
    State:          Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 25 Aug 2023 13:17:59 +0200
      Finished:     Fri, 25 Aug 2023 14:19:12 +0200
    Ready:          False
    Restart Count:  0
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-qlshz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
Events:
  Type     Reason       Age                  From     Message
  ----     ------       ----                 ----     -------
  Warning  FailedMount  86s (x70 over 131m)  kubelet  MountVolume.SetUp failed for volume "kube-api-access-qlshz" : object "test-namespace"/"kube-root-ca.crt" not registered
```

**Comment by sharad740** [comment]
I fixed my this error 
```
20m (x16 over 36m)       Warning   FailedMount                    Pod/frappe-bench-mariadb-0                                 MountVolume.SetUp failed for volume "pvc-88b8fbdf-42e4-4a2e-9290-
0b823bf677fa" : mount failed: exit status 32                                                                                                                                                  
Mounting command: mount                                                                                                                                                                       
Mounting arguments: -t nfs 10.0.2.10:/home/sharad/nfs/default/erpnext-data-frappe-bench-mariadb-0-pvc-88b8fbdf-42e4-4a2e-9290-0b823bf677fa /var/lib/kubelet/pods/61cf3bbe-21cc-4b98-b698-9f9ed
c83900f/volumes/kubernetes.io~nfs/pvc-88b8fbdf-42e4-4a2e-9290-0b823bf677fa                                                                                                                    
Output: mount: /var/lib/kubelet/pods/61cf3bbe-21cc-4b98-b698-9f9edc83900f/volumes/kubernetes.io~nfs/pvc-88b8fbdf-42e4-4a2e-9290-0b823bf677fa: bad option; for several filesystems (e.g. nfs, c
ifs) you might need a /sbin/mount.<type> helper program.
```

by installing nfs-common in my worker node
```
sudo apt install -y nfs-common
```

Hope you don't have such silly mistake

**Comment by smileusd** [comment]
I also met this issue too, the secret and configmap block the pod terminating when delete namespace

**Comment by PaulFurtado** [comment]
@sharad740 that is a different mount error from the "not registered" issue.

@SergeyKanzhelev we're hitting this issue somewhat frequently in large clusters and it seems to be one of the few sorts of issue like this where restarting kubelet does not resolve the problem and we have to force delete the pod.

```
E0503 11:35:58.744234 4036992 projected.go:292] Couldn't get configMap browsers-dashboard/kube-root-ca.crt: object "browsers-dashboard"/"kube-root-ca.crt" not registered
E0503 11:35:58.744244 4036992 projected.go:198] Error preparing data for projected volume kube-api-access-dssjd for pod browsers-dashboard/session-agent-bc77c896-scv2f: object "browsers-dashboard"/"kube-root-ca.crt" not registered
```
This is on kubernetes v1.27.13

It seems to often happen for pods in the Terminating state for us and impacts all of the secret and configmap volumes, but no others.

**Comment by olyazavr** [comment]
^ For that case in particular, we see pods that have been running a while, and successfully mounting volumes start to fail to mount volumes while terminating. Something peculiar, but perhaps not related, is that the logs show that kubelet thinks this is a new pod just starting up as it is terminating.

successful mounts:
```
I0503 06:00:44.260458 3490635 volume_manager.go:433] "All volumes are attached and mounted for pod" pod="browsers-dashboard/session-agent-bc77c896-scv2f"
I0503 06:00:44.260272 3490635 volume_manager.go:399] "Waiting for volumes to attach and mount for pod" pod="browsers-dashboard/session-agent-bc77c896-scv2f"
I0503 06:00:44.261148 3490635 desired_state_of_world_populator.go:309] "Added volume to desired state" pod="browsers-dashboard/session-agent-bc77c896-scv2f" volumeName="tmp" volumeSpecName="tmp"
I0503 06:00:44.263140 3490635 reconciler_common.go:220] "Starting operationExecutor.MountVolume for volume \"kube-api-access-dssjd\" (UniqueName: \"kubernetes.io/projected/f4597db6-4c03-4bee-9e0a-15cbced247bf-kube-api-access-dssjd\") pod \"session-agent-bc77c896-scv2f\" (UID: \"f4597db6-4c03-4bee-9e0a-15cbced247bf\") Volume is already mounted to pod, but remount was requested." pod="browsers-dashboard/session-agent-bc77c896-scv2f"
I0503 06:00:44.263470 3490635 operation_generator.go:722] "MountVolume.SetUp succeeded for volume \"deploy-config\" (UniqueName: \"kubernetes.io/configmap/f4597db6-4c03-4bee-9e0a-15cbced247bf-deploy-config\") pod \"session-agent-bc77c896-scv2f\" (UID: \"f4597db6-4c03-4bee-9e0a-15cbced247bf\") " pod="browsers-dashboard/session-agent-bc77c896-scv2f"

...
I0503 06:59:14.490355 4036992 operation_generator.go:722] "MountVolume.SetUp succeeded for volume \"logs\" (UniqueName: \"kubernetes.io/empty-dir/f4597db6-4c03-4bee-9e0a-15cbced247bf-logs\") pod \"session-agent-bc77c896-scv2f\" (UID: \"f4597db6-4c03-4bee-9e0a-15cbced247bf\") " pod="browsers-dashboard/session-agent-bc77c896-scv2f"
```
then, as termination starts:
```
I0503 06:59:08.259941 3490635 status_manager.go:895] "Delaying pod deletion as the phase is non-terminal" phase=Running localPhase=Running pod="browsers-dashboard/session-agent-bc77c896-scv2f" podUID=f4597db6-4c03-4bee-9e0a-15cbced247bf
I0503 06:59:10.489083 4036992 kuberuntime_manager.go:1370] "getSandboxIDByPodUID got sandbox IDs for pod" podSandboxID=[927c000a6fc6843dd7a39dc8b3428e0f7f7d3bdfef1da5b6c50abd13c4b867ca] pod="browsers-dashboard/session-agent-bc77c896-scv2f"
I0503 06:59:10.492329 4036992 generic.go:459] "PLEG: Write status" pod="browsers-dashboard/session-agent-bc77c896-scv2f"
I0503 06:59:11.468951 4036992 topology_manager.go:212] "Topology Admit Handler" podUID=f4597db6-4c03-4bee-9e0a-15cbced247bf podNamespace="browsers-dashboard" podName="session-agent-bc77c896-scv2f"
I0503 06:59:11.468931 4036992 kubelet.go:2346] "SyncLoop ADD" source="api" pods=[browsers-dashboard/session-agent-bc77c896-scv2f]
I0503 06:59:11.468859 4036992 config.go:398] "Receiving a new pod" pod="browsers-dashboard/session-agent-bc77c896-scv2f"
I0503 06:59:11.469450 4036992 event.go:307] "Event occurred" object="browsers-dashboard/session-agent-bc77c896-scv2f" fieldPath="spec.containers{app}" kind="Pod" apiVersion="v1" type="Normal" reason="Killing" message="Stopping container app"
I0503 06:59:11.469174 4036992 pod_workers.go:1226] "Processing pod event" pod="browsers-dashboard/session-agent-bc77c896-scv2f" podUID=f4597db6-4c03-4bee-9e0a-15cbced247bf updateType="terminating"
I0503 06:59:11.469128 4036992 pod_workers.go:770] "Pod is being synced for the first time" pod="browsers-dashboard/session-agent-bc77c896-scv2f" podUID=f4597db6-4c03-4bee-9e0a-15cbced247bf updateType="create"
I0503 06:59:11.469274 4036992 kubelet.go:1956] "Pod terminating with grace period" pod="browsers-dashboard/session-agent-bc77c896-scv2f" podUID=f4597db6-4c03-4bee-9e0a-15cbced247bf gracePeriod=86400
I0503 06:59:11.469202 4036992 kubelet.go:1946] "SyncTerminatingPod enter" pod="browsers-dashboard/session-agent-bc77c896-scv2f" podUID=f4597db6-4c03-4bee-9e0a-15cbced247bf
I0503 06:59:11.469310 4036992 kuberuntime_container.go:730] "Killing container with a grace period override" pod="browsers-dashboard/session-agent-bc77c896-scv2f" podUID=f4597db6-4c03-4bee-9e0a-15cbced247bf containerName="app" containerID="containerd://9667033a35e9f90fe98351a266793c2b08250c4a7a09864e8b2de2c89a0c10a0" gracePeriod=86400
I0503 06:59:11.469141 4036992 pod_workers.go:856] "Pod is marked for graceful deletion, begin teardown" pod="browsers-dashboard/session-agent-bc77c896-scv2f" podUID=f4597db6-4c03-4bee-9e0a-15cbced247bf updateType="create"
I0503 06:59:14.287363 4036992 desired_state_of_world_populator.go:309] "Added volume to desired state" pod="browsers-dashboard/session-agent-bc77c896-scv2f" volumeName="logs" volumeSpecName="logs"
I0503 06:59:14.287237 4036992 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"tmp\" (UniqueName: \"kubernetes.io/empty-dir/f4597db6-4c03-4bee-9e0a-15cbced247bf-tmp\") pod \"session-agent-bc77c896-scv2f\" (UID: \"f4597db6-4c03-4bee-9e0a-15cbced247bf\") " pod="browsers-dashboard/session-agent-bc77c896-scv2f"
I0503 06:59:14.490456 4036992 event.go:307] "Event occurred" object="browsers-dashboard/session-agent-bc77c896-scv2f" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-public-cert\" : object \"browsers-dashboard\"/\"kube-public-cert\" not registered"
```

Since termination can take some time, why is registering the pod something reserved only for non-terminating pods? https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1842-L1849

**Comment by olyazavr** [comment]
I got to the bottom of what was happening in our case, and it's possible it's the same thing that was happening in the original report:

 In this [pod worker loop](https://github.com/kubernetes/kubernetes/blob/d8ed461ba19fce6fc64991a8e0e7e47167596fba/pkg/kubelet/pod_workers.go#L1211), [running pods get the SyncPod function](https://github.com/kubernetes/kubernetes/blob/d8ed461ba19fce6fc64991a8e0e7e47167596fba/pkg/kubelet/pod_workers.go#L1283), but terminating pods get the [SyncTerminatingPod function](https://github.com/kubernetes/kubernetes/blob/d8ed461ba19fce6fc64991a8e0e7e47167596fba/pkg/kubelet/pod_workers.go#L1279). [SyncPod](https://github.com/kubernetes/kubernetes/blob/d8ed461ba19fce6fc64991a8e0e7e47167596fba/pkg/kubelet/kubelet.go#L1843-L1848) has the pod registration flow, but [SyncTerminatingPod](https://github.com/kubernetes/kubernetes/blob/d8ed461ba19fce6fc64991a8e0e7e47167596fba/pkg/kubelet/kubelet.go#L2012) does not, but this is needed for kubelet to know what secrets/configmaps back mounted volumes. I added in:

```
if kl.podWorkers.CouldHaveRunningContainers(pod.UID) {
		if kl.secretManager != nil {
			kl.secretManager.RegisterPod(pod)
		}
		if kl.configMapManager != nil {
			kl.configMapManager.RegisterPod(pod)
		}
	}
```
in `SyncTerminatingPod` and that resolved my issue- when kubelet restarted, terminating pods were still able to mount volumes and shut down correctly without getting stuck. I can see how if you create and delete a pod quickly, you could end up in a similar situation where the first sync would go through `SyncTerminatingPod` and the same volume issue would arise

**Comment by HirazawaUi** [comment]
@PaulFurtado @olyazavr  
I cannot reproduce the problem you raised in the master branch. I used the following script to simulate your scenario and ran it for two hours without any problem of being unable to delete the pod. If there is any error in my test, please correct me.

**Pod usage secrets:** 
``` 
apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .secret-file: dmFsdWUtMg0KDQo=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
  labels:
    app: test
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
  containers:
    - name: dotfile-test-container
      image: nginx
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh","-c","sleep 60"]
      command:
        - "sleep"
        - "3600"
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
```
**Script**
```
#!/bin/bash

sudo /home/bing/go/src/k8s.io/kubernetes/_output/local/bin/linux/arm64/kubelet --v=3 --vmodule= --hostname-override=127.0.0.1 --cloud-provider= --cloud-config= --bootstrap-kubeconfig=/var/run/kubernetes/kubelet.kubeconfig --kubeconfig=/var/run/kubernetes/kubelet-rotated.kubeconfig --config='/tmp/local-up-cluster.sh.xi4rWh/kubelet.yaml' > kubelet.log 2>&1 &
kubelet_pid=$!
sleep 20
echo "Kubelet is running with pid ${kubelet_pid}"

while true
do
    echo "creating pods"
    kubectl create -f pod-secret.yml
    kubectl wait --for=condition=ready pod -l app=test
    # wait for 5s
    sleep 5
    kubectl delete -f pod-secret.yml --wait=true --timeout=2s
    # stop kubelet
    echo "Killing kubelet with pid ${kubelet_pid}"
    sudo kill -9 "${kubelet_pid}"
    echo "Starting Kubelet"
    sudo /home/bing/go/src/k8s.io/kubernetes/_output/local/bin/linux/arm64/kubelet --v=3 --vmodule= --hostname-override=127.0.0.1 --cloud-provider= --cloud-config= --bootstrap-kubeconfig=/var/run/kubernetes/kubelet.kubeconfig --kubeconfig=/var/run/kubernetes/kubelet-rotated.kubeconfig --config='/tmp/local-up-cluster.sh.xi4rWh/kubelet.yaml' > kubelet.log 2>&1 &
    kubelet_pid=$!
    echo "Kubelet is running with pid ${kubelet_pid}"
    kubectl delete pod secret-dotfiles-pod --wait=true --timeout=50s
    if [ $? -eq 0 ]
    then
       echo "Pod deleted successfully"
    else
        echo "Failed to delete pod"
        exit -1
    fi
done
```

**Comment by haircommander** [comment]
@frittentheke have you hit this issue? this bug does indeed seem stale to me, and we're waiting on additional information to be able to make forward progress. I am inclined to close, but don't want to if you're hitting it.
