### ISSUE TITLE
Server-side apply fails with duplicate container ports and env-vars allowed in created/updated pods by validation

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#113482]
https://github.com/kubernetes/kubernetes/pull/113245#discussion_r1009911070

Validation allows:

```
        ports:
        - containerPort: 93
          hostPort: 9376
        - containerPort: 93
          hostPort: 9377
```

but server-side apply does not:

```
Error from server: failed to create manager for existing fields: failed to convert new object (default/hostnames; apps/v1, Kind=Deployment) to smd typed: .spec.template.spec.containers[name="serve-hostname-zp2lc"].ports: duplicate entries for key [containerPort=93,protocol="TCP"]
```

**Comment by thockin** [comment]
@apelisse to advise if this can be fixed by adding hostPort to the keys

**Comment by apelisse** [comment]
Thanks, we don't have the ability to do that just yet, but we can try to see how this would work.

**Comment by thockin** [comment]
Do we know what bad things would happen if I just added a new field to the
key?

**Comment by apelisse** [comment]
There are many different cases and none of them seems particularly palatable. SSA Could fail, other types of updates could erase the managed fields, or conflicts/ownership is going to be all messed-up. We have plenty of time before the next release to make sure we do it right, did you want to back-port this into a previous release?

**Comment by thockin** [comment]
No, no.  I'm not in a hurry - no shortcuts needed.  I filed this bug so we
would not forget about it and so that if we had a clear way to explore it,
someone could undertake the effort if they wanted.

**Comment by alculquicondor** [comment]
FYI https://github.com/kubernetes/kubernetes/issues/118261#issuecomment-1572482716

**Comment by pacoxu** [comment]
#113245 add warnings for patching pod/podtemplate/service with dup ports.
- Should we add a validation error for the dup ports case? 
- - for upgradation, the dup ports case can be accepted by the apiserver, but the client will get a warning for patching. For new creations, the client will get a validation error.

**Comment by thockin** [comment]
When I filed this, I did not realize it would break all of SSA, even for unrelated fields.
 
Copying from https://github.com/kubernetes/kubernetes/issues/118261#issuecomment-1574155048

1) It's valid to have `containerPorts[]` with same `port`+`protocol` and different `hostPort` or `hostIP`.  In fact, it is (unfortunately) allowed to have the same `hostPort` and `hostIP` as long as they are unspecified (the Go zero values).  The SSA keys are wrong.  The current validation is overly loose, which practically means this field can not be treated as a map (or we break users who do this weird-but-valid thing).

2) An env var value can ref other env vars (including a previous instance of its own name!!).  Ergo, it's really not a map at all.

If I change both of these to `+listType=atomic` then SSA works for things which have PodSpec embedded (Pods, Deployments, etc).  @apelisse points out that this is an unfortunate tradeoff - if any client actually wants to co-own container ports (unlikely) or env vars (somewhat more likely), they have to know that this field is atomic, and do a read-modify-write.

I have a branch which implements this.  @apelisse is thinking about how to convince ourselves it is OK.

Also:  https://github.com/kubernetes/kubernetes/issues/118418  and  https://github.com/kubernetes/kubernetes/issues/118417 are some followup.

My branch: https://github.com/kubernetes/kubernetes/compare/master...thockin:kubernetes:ssa_hack_env_ports?expand=1

**Comment by alculquicondor** [comment]
Please prioritize an identifiable status code that we can use to fallback from SSA in controllers.
We can also include it as part of the hotfix of kcm in #118261
But I think the decision on what's the best status code falls on API machinery.

**Comment by alculquicondor** [comment]
/retitle Pod container ports and env-vars listMapKeys != validation

**Comment by mimowo** [comment]
Just for the record. This is currently a real issue with SSA which forced us to withdraw from its use in internal k8s controllers. To xreference: https://github.com/kubernetes/kubernetes/issues/118261 and https://github.com/kubernetes/kubernetes/pull/121103.

**Comment by alculquicondor** [comment]
@apelisse can we use SSA now?

I would probably do it in 1.30+, but I'm asking in advance.

**Comment by apelisse** [comment]
Yes, I would make sure everything works fine for you but I'm pretty confident your source of problem has been addressed. I'm going to fix the test situation now.

**Comment by thockin** [comment]
So glad to hear we worked this out.  Thank you Antoine.

**Comment by thockin** [comment]
Re-opening this.  As of 1.29 we can SSA unrelated fields (huge win) and even SSA "repairs" to objects in this state.  What we can't do is SSA them with this state in the apply, which means the original issue is only partially fixed. :(

I'm not sure what the "right" fix is (or are - there may be several).

For `containerPort`, the defined SSA key is not sufficiently unique (`+listType=map; +listMapKey=containerPort; +listMapKey=protocol` -- needs to include `hostPort`).  To evolve the key is tricky, but the only real alternative is atomic, which has it's own issues.  Is it worth trying to find a safe way to expand an SSA key?

For `env`, there IS NO UNIQUE KEY, because fundamentally it is a list, not a map.  We currently warn on duplicate keys, but it is actually semantically valid to have them.  It's even valid (if weird) to have the exact same key and value.  E.g.

```
       env:
        - name: FOO
          value: "foo"
        - name: FOO
          value: "foo-$(FOO)"
        - name: FOO
          value: "foo-$(FOO)"
        - name: FOO
          value: "foo-$(FOO)"
        - name: FOO
          value: "foo-$(FOO)"
```

Is it worth trying to teach SSA about this one weird case?  Is it OK to just leave SSA broken?

**Comment by liggitt** [comment]
I think making SSA work on objects which were created / updated to have duplicates is as far as I'd want to go generically.

I don't think we should teach SSA to inject duplicates.

For these two cases:
* There's no env list using duplicate names that *requires* that, it can always be expressed with unique names. I'd recommend that instead.
* I'd look to evolve the list key for ports

**Comment by liggitt** [comment]
I do think the problem originally tracked in this issue (SSA cannot deal with objects create / update allowed to be persisted) *is* fixed.

A separate issue to look at expanding the key for ports would be fine.

**Comment by thockin** [comment]
> I don't think we should teach SSA to inject duplicates, and I don't really think I'd call it broken :-D

The "duplicates" are semantically valid and allowed - supporting it is part of the system and not in other parts seems like the definition of "broken".  For env we already warn on it, and I am OK with that bit of broken (until some use-case emerges).  

> I'd look to evolve the list key for ports

I feel like this SHOULD be possible, but will be hard and we ultimately need to make a call about the ROI.  I do suspect that it's likely to come up again, somewhere else, eventually.

> A separate issue to look at expanding the key for ports would be fine.

This bug was originally specific to ports and SSA, then grew, and now shrinks :)

**Comment by liggitt** [comment]
Hrmm... I thought this was about how you could fix the duplicate error

https://github.com/kubernetes/kubernetes/pull/113245#discussion_r1003369999

>> Error from server: failed to create manager for existing fields: failed to convert new object
(default/nginx; apps/v1, Kind=Deployment) to smd typed:
.spec.template.spec.containers[name="nginx-1"].ports: duplicate entries for key [containerPort=443,protocol="UDP"]
>
> @apelisse this is fun... what's the expected/recommended recovery path for a user trying to fix an error like that using server-side apply? Do they have to use update or client-side apply to fix the error before they can use server-side apply?

You can now use SSA to fix the duplicate error.

If we don't want those ports to be considered duplicates surely the right way is to fix the key definition?

**Comment by thockin** [comment]
I think fixing the key is the right way, but it doesn't "just work" :)

**Comment by caozhuozi** [comment]
hit the same error...

**Comment by caozhuozi** [comment]
Hi， @liggitt  what do you mean by "You can now use SSA to fix the duplicate error." ?
We have existing objects with duplicate container ports.
ssa towards other fields (like annotations) would crash like this issue..

How to fix this given that I cannot "repair" the existing objects?

**Comment by thockin** [comment]
Update, since people are still hitting it.  As of kube 1.31:

I can create an object with dup ports with `create` and `apply` but not `apply --server-side`:

```
$ cat /tmp/ssadup.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dup-ports-ssa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssatest
  template:
    metadata:
      labels:
        app: ssatest
    spec:
      containers:
      - image: k8s.gcr.io/serve_hostname:v1.4
        name: serve
        ports:
        - containerPort: 93
          name: p
        - containerPort: 93
          name: q

$ k --context=diy create -f /tmp/ssadup.yaml 
Warning: spec.template.spec.containers[0].ports[1]: duplicate port definition with spec.template.spec.containers[0].ports[0]
deployment.apps/dup-ports-ssa created

$ k --context=diy get deploy dup-ports-ssa -o json | jq '.spec.template.spec.containers[].ports[].containerPort'
93
93

$ k --context=diy apply --server-side -f /tmp/ssadup.yaml 
Error from server: failed to create typed patch object (default/dup-ports-ssa; apps/v1, Kind=Deployment): .spec.template.spec.containers[name="serve"].ports: duplicate entries for key [containerPort=93,protocol="TCP"]

$ k --context=diy get deploy dup-ports-ssa -o json | jq '.spec.template.spec.containers[].ports[].containerPort'
93
93
```

I can "fix" it by making the port not duplicates any more:

```
$ cat /tmp/ssadup-fixed.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dup-ports-ssa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssatest
  template:
    metadata:
      labels:
        app: ssatest
    spec:
      containers:
      - image: k8s.gcr.io/serve_hostname:v1.4
        name: serve
        ports:
        - containerPort: 93
          name: p
        - containerPort: 94
          name: q

$ k --context=diy apply --server-side -f /tmp/ssadup-fixed.yaml --force-conflicts
deployment.apps/dup-ports-ssa serverside-applied

$ k --context=diy get deploy dup-ports-ssa -o json | jq '.spec.template.spec.containers[].ports[].containerPort'
93
94
```

I can SSA other fields as long as I do not mention the ports:

```
$ k --context=diy replace -f /tmp/ssadup.yaml # revert to broken state
Warning: spec.template.spec.containers[0].ports[1]: duplicate port definition with spec.template.spec.containers[0].ports[0]
deployment.apps/dup-ports-ssa replaced

$ cat /tmp/ssadup-others.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dup-ports-ssa
spec:
  template:
    metadata:
      labels:
        app: ssatest
        foo: bar

$ k --context=diy apply --server-side -f /tmp/ssadup-others.yaml 
Warning: spec.template.spec.containers[0].ports[1]: duplicate port definition with spec.template.spec.containers[0].ports[0]
deployment.apps/dup-ports-ssa serverside-applied

$ k --context=diy get deploy dup-ports-ssa -o json | jq '.spec.template.spec.containers[].ports[].containerPort'
93
93
```

The only complete fix at this moment is to not have ports within a container which have duplicate protocol+port.

If you are using SSA for a controller, you can avoid mentioning ports.

I have paged out some context, but IIRC @jpbetz convinced me that just expanding the SSA key was not "safe", but I'll have to go looking for exactly why.  It's super subtle.

**Comment by mimowo** [comment]
@thockin @jpbetz this is also an issue for Kueue which stores the original Pod Template in the Workload object: https://github.com/kubernetes-sigs/kueue/issues/3540. From the message above I assume there is not much hope for getting this fixed in the foreseeable future?

**Comment by mwysokin** [comment]
@thockin In order to help our users with this issue we implemented an alpha feature in Kueue to use PATCH instead of SSA. Do you have guidance or advice where PATCH over SSA might be problematic or something that we should watch out for in the Kueue controller when PATCH is enabled? I think our high level recommendation is going to be to enable it only if someone is running into issues with SSA and we'd like to keep SSA for the majority of users.

**Comment by mimowo** [comment]
Indeed in Kueue due to two issues with SSA (see [here](https://github.com/kubernetes-sigs/kueue/issues/6158) for summary) we decided to introduce the [feature-gate](https://github.com/kubernetes-sigs/kueue/blob/7b9f971745eb463c5940acca2d131d7114b2cfda/pkg/features/kube_features.go#L200) switch between the two modes (SSA vs Patch).

While we maintain two modes as feature-gate for the time being, there is no decision to maintain both long term. Supporting both options properly and multiplying all testing effort seems overkill long term.  Also, it does not seem like a knob users would be normally interested in.

So, we are considering fully transitioning to Patch and supporting only that mode in the long term. 

cc @tenzen-y

**Comment by thockin** [comment]
This is one of those problems that has no "obvious" fix but trickles into an degrades our ecosystem. Projects like kueue choosing not to use `apply` is unfortunate, but until/unless we has a solution here, what esle can they do?

We could tighten validation to disallow key-dups.  This is a breaking change for anyone who uses it and (anecdotally) some people DO use it on purpose (e.g. multiple hostPorts -> same containerPort).

We could change the SSA keys to include hostPort and name.  I don't know the SSA code well, so I do not know what breaks if we do that (and it doesn't fix CSA, but that may be a lost cause).

We could change it to atomic, but like above I do not know what breaks if we do that (and I suspect it is more than would break with the SSA key change).

We could add a new field with reasonable semantics and deprecate the old.  This doesn't help anyone who already has workloads deployed and it doesn't help controllers to rely on SSA instead of patch.

Expanding the SS key feels like it should be possible - if the list was unique by key X, it is also unique by X+Y, right?  And it if was not unique by X, but is unique by X+Y that's a win, right?  I just don't know what's going on in the machinery that would break.  @jpbetz do you know who could give a categorical answer?

**Comment by liggitt** [comment]
> ... (anecdotally) some people DO use it on purpose (e.g. multiple hostPorts -> same containerPort).

What behavior does this configuration drive? Is there a less broken-looking way to drive the same behavior?

> We could change the SSA keys to include hostPort and name. I don't know the SSA code well, so I do not know what breaks if we do that (and it doesn't fix CSA, but that may be a lost cause).

Adjusting the SSA key to pull in an existing field with existing persisted data is likely to be pretty weird / problematic. We've expanded an SSA key to add in *new* fields before they had any data in them, and that's ok because no keys change for any existing persisted data.

**Comment by thockin** [comment]
Copying from slack, after discussing this for a few days, I have distilled my understanding a bit.

Patch logic was not well considered when some of these older APIs were created, so I think the answer of "what do we want" needs to be considered case by case.

In this case, we originally thought that port number was sufficient (in CSA), and that worked for a long time. Then we added protocol (in SSA) but handwritten code wasn't sufficiently stringent and people made use of it in ways that work in create/replace but not apply.

So what do we want NOW?  IMO the better answer would be `port`+`protocol` and if you need multiple `hostPort`s we could pluralize that field.  Or that `name` would be required and serve as the key. 

So what can be done now?  If we extend the key to include `hostPort`, some patches might break (if someone tried to patch `[ { containerPort 93, hostPort: 9376 } ]` to `[ { containerPort: 93, hostPort: 7693 } ]`, then instead of replacing the existing port, they'd end up with duplicate ports).  If we tighten manual validation we will break some use-cases (unintended ones, but that's Hyrum's law).

If we do nothing we make SSA too high risk for any controller to use when Pod is involved.
