### ISSUE TITLE
ttlSecondsAfterFinished Ignored for jobs

### ISSUE THREAD

**Issue by yonahd** [kubernetes/kubernetes#116008]
### What happened?

When running a Job in Kubernetes 1.23 the job gets terminated immediately and not respecting ttlSecondsAfterFinished.

### What did you expect to happen?

Expected the job to stay alive for the timeframe defined in ttlSecondsAfterFinished

### How can we reproduce it (as minimally and precisely as possible)?

Create a job using 

```
apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
```

### Kubernetes version

<details>

```console
$ kubectl version
# Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T15:54:23Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by HirazawaUi** [comment]
this works fine on my local v1.26.1 cluster, before v1.24 it was determined by the TTLAfterFinished feature gate, to verify whether it's enabled, check the beginning of both apiserver log and controller-manager log and look for TTLAfterFinished to see if the feature gate is enabled
/kind support

**Comment by yonahd** [comment]
This looks to be a regression in 1.23 https://github.com/kubernetes/kubernetes/pull/109491
And fixed in 1.25 https://github.com/kubernetes/kubernetes/pull/110948

**Comment by yonahd** [comment]
@HirazawaUi

**Comment by HirazawaUi** [comment]
> feature gate

I'm sure it's not related to this problem, and everything works fine in the v1.23.16 cluster test, have you checked the TTLAfterFinished feature gate?

**Comment by HirazawaUi** [comment]
> This looks to be a regression in 1.23 #109491 And fixed in 1.25 #110948

It's not related to this issue, and everything works fine in v1.23.16 cluster test, did you check the TTLAfterFinished feature gate, maybe you need to provide more information

**Comment by neolit123** [comment]
/sig apps
/close

please reopen if still a problem.
contact the mainteners at #sig-apps on k8s slack.
