### ISSUE TITLE
kubelet fails with `UnmountVolume.NewUnmounter failed for volume` and `vol_data.json: no such file or directory` for CSI volumes and floods the logs 

### ISSUE THREAD

**Issue by vadasambar** [kubernetes/kubernetes#116847]
### What happened?

I think kubelet sometimes is not able to properly identify unmounted volume and clean up its `actualstateofworld` cache. It thinks the volume is not unmounted and keeps on trying unmounting it. This outputs a lot of logs which flood journalctl -> fluentd/bit -> third party logging solution. The flooding causes 2 problems:
1. Consumes node disk which reduces the amount of disk available for pods
2. Increases ingestion rate for paid third party logging solution thereby costing extra money1 and 2 can be worked around by rotating the logs more frequently, dropping the logs or filtering them out from ingestion into the third party logging solution but it is not a permanent fix to the problem. Also, note that re-starting kubelet fixes the issue. Here's what the error log looks like:
```
"Feb 13 22:05:35 ip-10-57-71-57 kubelet: E0213 22:05:35.753487   28558 reconciler.go:193] \"operationExecutor.UnmountVolume failed (controllerAttachDetachEnabled true) for volume \\\"drupal-code\\\" (UniqueName: \\\"kubernetes.io/csi/48033fa8-05f1-4c32-b109-4e25f23107ef-drupal-code\\\") pod \\\"48033fa8-05f1-4c32-b109-4e25f23107ef\\\" (UID: \\\"48033fa8-05f1-4c32-b109-4e25f23107ef\\\") : UnmountVolume.NewUnmounter failed for volume \\\"drupal-code\\\" (UniqueName: \\\"kubernetes.io/csi/48033fa8-05f1-4c32-b109-4e25f23107ef-drupal-code\\\") pod \\\"48033fa8-05f1-4c32-b109-4e25f23107ef\\\" (UID: \\\"48033fa8-05f1-4c32-b109-4e25f23107ef\\\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/48033fa8-05f1-4c32-b109-4e25f23107ef/volumes/kubernetes.io~csi/drupal-code/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/48033fa8-05f1-4c32-b109-4e25f23107ef/volumes/kubernetes.io~csi/drupal-code/vol_data.json]: open /var/lib/kubelet/pods/48033fa8-05f1-4c32-b109-4e25f23107ef/volumes/kubernetes.io~csi/drupal-code/vol_data.json: no such file or directory\" err=\"UnmountVolume.NewUnmounter failed for volume \\\"drupal-code\\\" (UniqueName: \\\"kubernetes.io/csi/48033fa8-05f1-4c32-b109-4e25f23107ef-drupal-code\\\") pod \\\"48033fa8-05f1-4c32-b109-4e25f23107ef\\\" (UID: \\\"48033fa8-05f1-4c32-b109-4e25f23107ef\\\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/48033fa8-05f1-4c32-b109-4e25f23107ef/volumes/kubernetes.io~csi/drupal-code/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/48033fa8-05f1-4c32-b109-4e25f23107ef/volumes/kubernetes.io~csi/drupal-code/vol_data.json]: open /var/lib/kubelet/pods/48033fa8-05f1-4c32-b109-4e25f23107ef/volumes/kubernetes.io~csi/drupal-code/vol_data.json: no such file or directory\"
```
If you look at the code for 1.22, you can see the the log is output [here](https://github.com/kubernetes/kubernetes/blob/bc4763cbf8b9e6adfbc07bb3194509b187b0b901/pkg/kubelet/volumemanager/reconciler/reconciler.go#L191).

Couple of things to note here: 
1. We have seen this happen a lot for short-lived pods. 
2. We have already looked at the following issues/PRs but they don't solve the problem
   1. https://github.com/kubernetes/kubernetes/issues/101378
   2. https://github.com/kubernetes/kubernetes/issues/101911
   3. https://github.com/kubernetes/kubernetes/issues/85280
   4. https://github.com/kubernetes/kubernetes/pull/102576 is ported back to 1.21 and 1.22 but it doesn't fix the problem
3. We have seen this problem happen in 1.21 and 1.22 version of kubelet
5. The volume is mounted using https://github.com/warm-metal/csi-driver-image
6. Because kubelet thinks the volume is still mounted, it doesn't cleanly take out the pod. The Pod gets stuck in `Terminating` state because all the volumes attached the pod are not unmounted yet. 
7. Note that the directory structure of CSI volume is present. Only `vol_data.json` is absent
![image](https://user-images.githubusercontent.com/34534103/226664453-426379c0-1d1c-46cf-8d73-2ba369b91b01.png)

### What did you expect to happen?

kubelet to not get stuck trying to unmount a volume

### How can we reproduce it (as minimally and precisely as possible)?

We have tried reproducing this issue but it is quite difficult to reproduce manually. So far we have only been able to observe it in our logs after it has happened. 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.16-eks-ffeb93d", GitCommit:"52e500d139bdef42fbc4540c357f0565c7867a81", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:42Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Docker
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CSI plugin: https://github.com/warm-metal/csi-driver-image
</details>

**Comment by vadasambar** [comment]
Please let me know if you need more details 🙏

**Comment by vadasambar** [comment]
Note that when I say it's hard to reproduce manually, I mean it's hard to get into a state where `vol_data.json` is deleted automatically. You can easily reproduce the error message above using the following steps:
1. Create a pod with CSI volume
2. Log into the node and go to the pod directory e.g., `cd /var/lib/kubelet/pods/<pod-uid>/volumes/kubernetes.io~csi/<vol-name>`
3. Remove vol_data.json using `rm vol_data.json`
4. You should start seeing the above error in kubelet logs

**Comment by HirazawaUi** [comment]
/assign 
i'll have a look

**Comment by HirazawaUi** [comment]
this issue has been reproduced in my local cluster with version 1.26.3.

**Comment by HirazawaUi** [comment]
> Note that when I say it's hard to reproduce manually, I mean it's hard to get into a state where `vol_data.json` is deleted automatically. You can easily reproduce the error message above using the following steps:
> 
> 1. Create a pod with CSI volume
> 2. Log into the node and go to the pod directory e.g., `cd /var/lib/kubelet/pods/<pod-uid>/volumes/kubernetes.io~csi/<vol-name>`
> 3. Remove vol_data.json using `rm vol_data.json`
> 4. You should start seeing the above error in kubelet logs

I have reproduced this error in a local cluster running version 1.26.3 following the steps mentioned above. However, I am uncertain if this error will be triggered when kubelet is functioning normally. I will continue to monitor it. Starting from a particular issue may help to better understand the source code of kubelet :)

**Comment by vadasambar** [comment]
Thank you for looking into this @HirazawaUi!

**Comment by HirazawaUi** [comment]
@vadasambar It seems to have disappeared on v1.26.3. I used the CSI-Drive like you and implemented short code to create PV, PVC, and POD every two minutes, and then delete them after one minute when they are created (simulating a short-lived pod). Everything was fine after running continuously for two days. Could you test if this issue occurs on the new version? (if possible)

**Comment by vadasambar** [comment]
@HirazawaUi thank you for looking deeper into this!

>  I used the CSI-Drive like you and implemented short code to create PV, PVC, and POD every two minutes, and then delete them after one minute when they are created (simulating a short-lived pod). Everything was fine after running continuously for two days.

I have tried something similar on older Kubernetes version (1.21/1.22) but I wasn't able to reproduce this issue. It makes me think, something else might be involved here (perhaps a race condition?).

**Comment by HirazawaUi** [comment]
> @HirazawaUi thank you for looking deeper into this!
> 
> > I used the CSI-Drive like you and implemented short code to create PV, PVC, and POD every two minutes, and then delete them after one minute when they are created (simulating a short-lived pod). Everything was fine after running continuously for two days.
> 
> I have tried something similar (CronJob which is set to run every minute with PV/PVC) on older Kubernetes version (1.21/1.22) but I wasn't able to reproduce this issue. It makes me think, something else might be involved here (perhaps a race condition?).

I'm sorry, I wasn't able to solve your issue. Perhaps need to wait for someone who is more familiar with storage
/unassign
/sig storage

**Comment by vadasambar** [comment]
@HirazawaUi not at all. Really appreciate you looking into this!

**Comment by qiliRedHat** [comment]
@HirazawaUi @vadasambar I saw the same issue too on Openshift OCP cluster
Version
```
Server Version: 4.13.0-rc.2
Kubernetes Version: v1.26.2+dc93b13

and

Server Version: 4.12.0
Kubernetes Version: v1.25.4+77bec7a
```
AWS with ebs.csi.aws.com csidriver
```
 % oc get csidriver
NAME              ATTACHREQUIRED   PODINFOONMOUNT   STORAGECAPACITY   TOKENREQUESTS   REQUIRESREPUBLISH   MODES        AGE
ebs.csi.aws.com   true             false            false             <unset>         false               Persistent   5d3h
```
How can we reproduce it (as minimally and precisely as possible)?
I encountered this in a long run test. The test have 15 concurrent users who create namespace, create pod and pvc under the namespace and then delete the namespace, continuously. The issue happened on about 4-5 days after I started the long run test. It happened very rarely, once or twice in a 5 days long run, which had totally 10k+ namespaces creation/deletion.

This bug is similar to a previous bug:
https://bugzilla.redhat.com/show_bug.cgi?id=2038780
https://github.com/kubernetes/kubernetes/pull/110670

**Comment by Chaunceyctx** [comment]
> @cvvz, @Chaunceyctx, does it look like a duplicate of #114207 ? Or something very similar, now in SetUp / TearDown instead of MountDevice / UnmountDevice?

These two problems look like similar. TearDown Operation may be performed multiple times. I will take a look if I have time LOL.

**Comment by vadasambar** [comment]
We checked some pods with unmount errors and Interestingly we are seeing `Orphaned pod found, but volumes are not cleaned up" podUID=XXXX` log such pods.

**Comment by dims** [comment]
cc @ConnorJC3 @torredil see references to `ebs.csi.aws.com csidriver` above

**Comment by cvvz** [comment]
I think these two issues are the same, there is a TOCTOU problem and `vol.data` maybe removed multiple times which trigger this issue.
We have fixed this issue by skipping `UnmountDevice` when `vol_data.json` file does not exist,  since in this situation, `UnmountDevice` must has been executed successfully before, no need to do `UnmountDevice` multiple times.

**Comment by jingxu97** [comment]
https://github.com/kubernetes/kubernetes/issues/114207#issuecomment-1535623925

if it is the correct fix

**Comment by vadasambar** [comment]
@jingxu97 thank you for the link. Looking [at the PR](https://github.com/kubernetes/kubernetes/pull/116138/files#diff-227f84916ffb93ece42ccaec840af8ea265714440c15c45f42b08d6a427a57bfR598-R600), I think the PR code might resolve our issue. Thanks a bunch!

**Comment by vadasambar** [comment]
>  FYI. this issue is fixed in 1.24.14, 1.25.10, 1.26.5, and has been fixed in v1.27.0

https://github.com/kubernetes/kubernetes/issues/114207#issuecomment-1535623925

**Comment by Venkat639** [comment]
Still getting same issue with k8s version 1.24.15. 
Scenario I tried --
Create prometheus Statefulset pod but VPA updated resources for that pod and pod got immediately deleted within one minute of creation time.
Pod got stuck with in terminating state forever.

Following are the logs --
Jul 25 23:07:56 ip-x-x-x-x kubelet[6181]: E0725 23:07:56.957366    6181 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/ebs.csi.aws.com^vol-xxxxx podName:884bc944-bba7-4b18-838c-6a9e777899c9 nodeName:}" failed. No retries permitted until 2023-07-25 23:07:57.457346569 +0000 UTC m=+153351.396529157 (durationBeforeRetry 500ms). Error: UnmountVolume.TearDown failed for volume "storage-volume" (UniqueName: "kubernetes.io/csi/ebs.csi.aws.com^vol-xxxx”) pod "884bc944-bba7-4b18-838c-6a9e777899c9" (UID: "884bc944-bba7-4b18-838c-6a9e777899c9") : kubernetes.io/csi: Unmounter.TearDownAt failed: rpc error: code = Internal desc = Could not unmount "/var/lib/kubelet/pods/884bc944-bba7-4b18-838c-6a9e777899c9/volumes/kubernetes.io~csi/pvc-2b7f37ef-6561-4601-bf91-f6caa8e984e8/mount": unmount failed: exit status 32
Jul 25 23:07:56 ip-x-x-x-x kubelet[6181]: Unmounting arguments: /var/lib/kubelet/pods/884bc944-bba7-4b18-838c-6a9e777899c9/volumes/kubernetes.io~csi/pvc-2b7f37ef-6561-4601-bf91-f6caa8e984e8/mount
Jul 25 23:07:56 ip-x-x-x-x kubelet[6181]: Output: umount: /var/lib/kubelet/pods/884bc944-bba7-4b18-838c-6a9e777899c9/volumes/kubernetes.io~csi/pvc-2b7f37ef-6561-4601-bf91-f6caa8e984e8/mount: no mount point specified. 
Jul 25 23:07:57 ip-x-x-x-x kubelet[6181]: E0725 23:07:57.055425    6181 reconciler.go:208] "operationExecutor.UnmountVolume failed (controllerAttachDetachEnabled true) for volume \"storage-volume\" (UniqueName: \"[kubernetes.io/csi/ebs.csi.aws.com^vol-xxxxx\](http://kubernetes.io/csi/ebs.csi.aws.com%5Evol-xxxxx%5C)”) pod \"884bc944-bba7-4b18-838c-6a9e777899c9\" (UID: \"884bc944-bba7-4b18-838c-6a9e777899c9\") : UnmountVolume.NewUnmounter failed for volume \"storage-volume\" (UniqueName: \"kubernetes.io/csi/ebs.csi.aws.com^vol-xxxxxx\”) pod \"884bc944-bba7-4b18-838c-6a9e777899c9\" (UID: \"884bc944-bba7-4b18-838c-6a9e777899c9\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/884bc944-bba7-4b18-838c-6a9e777899c9/volumes/kubernetes.io~csi/pvc-2b7f37ef-6561-4601-bf91-f6caa8e984e8/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/884bc944-bba7-4b18-838c-6a9e777899c9/volumes/kubernetes.io~csi/pvc-2b7f37ef-6561-4601-bf91-f6caa8e984e8/vol_data.json]: open /var/lib/kubelet/pods/884bc944-bba7-4b18-838c-6a9e777899c9/volumes/kubernetes.io~csi/pvc-2b7f37ef-6561-4601-bf91-f6caa8e984e8/vol_data.json: no such file or directory" err="UnmountVolume.NewUnmounter failed for volume \"storage-volume\" (UniqueName: \"kubernetes.io/csi/ebs.csi.aws.com^vol-0eeab778de635903d\") pod \"884bc944-bba7-4b18-838c-6a9e777899c9\" (UID: \"884bc944-bba7-4b18-838c-6a9e777899c9\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/884bc944-bba7-4b18-838c-6a9e777899c9/volumes/kubernetes.io~csi/pvc-2b7f37ef-6561-4601-bf91-f6caa8e984e8/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/884bc944-bba7-4b18-838c-6a9e777899c9/volumes/kubernetes.io~csi/pvc-2b7f37ef-6561-4601-bf91-f6caa8e984e8/vol_data.json]: open /var/lib/kubelet/pods/884bc944-bba7-4b18-838c-6a9e777899c9/volumes/kubernetes.io~csi/pvc-2b7f37ef-6561-4601-bf91-f6caa8e984e8/vol_data.json: no such file or directory"

**Comment by cvvz** [comment]
I filed a PR to resolve the race condition in reconciler, could you please take a look? @jingxu97 @jsafrane 

I think this is the real solution to this kind of problem. https://github.com/kubernetes/kubernetes/pull/116138 is just like some kind of workaround and not really solved the race condition problem.

**Comment by Dunge** [comment]
Got the same issue today randomly out of nowhere on a microk8s 1.27 cluster and lonhorn 1.5.1, so it's not fixed yet. The journalctl keep flooding this error every ms:

> Sep 06 20:56:56 jldocker-3.jamlogic.com microk8s.daemon-kubelite[4155471]: E0906 20:56:56.044356 4155471 reconciler_common.go:169] "operationExecutor.UnmountVolume failed (controllerAttachDetachEnabled true) for volume \"pvc-ce65fb13-5ebf-4bd3-a202-b698de05c261\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-ce65fb13-5ebf-4bd3-a202-b698de05c261\") pod \"5fcddea2-77a4-475f-9a4c-a62f5243b353\" (UID: \"5fcddea2-77a4-475f-9a4c-a62f5243b353\") : UnmountVolume.NewUnmounter failed for volume \"pvc-ce65fb13-5ebf-4bd3-a202-b698de05c261\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-ce65fb13-5ebf-4bd3-a202-b698de05c261\") pod \"5fcddea2-77a4-475f-9a4c-a62f5243b353\" (UID: \"5fcddea2-77a4-475f-9a4c-a62f5243b353\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/snap/microk8s/common/var/lib/kubelet/pods/5fcddea2-77a4-475f-9a4c-a62f5243b353/volumes/kubernetes.io~csi/pvc-ce65fb13-5ebf-4bd3-a202-b698de05c261/mount]: kubernetes.io/csi: failed to open volume data file [/var/snap/microk8s/common/var/lib/kubelet/pods/5fcddea2-77a4-475f-9a4c-a62f5243b353/volumes/kubernetes.io~csi/pvc-ce65fb13-5ebf-4bd3-a202-b698de05c261/vol_data.json]: open /var/snap/microk8s/common/var/lib/kubelet/pods/5fcddea2-77a4-475f-9a4c-a62f5243b353/volumes/kubernetes.io~csi/pvc-ce65fb13-5ebf-4bd3-a202-b698de05c261/vol_data.json: no such file or directory" err="UnmountVolume.NewUnmounter failed for volume \"pvc-ce65fb13-5ebf-4bd3-a202-b698de05c261\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-ce65fb13-5ebf-4bd3-a202-b698de05c261\") pod \"5fcddea2-77a4-475f-9a4c-a62f5243b353\" (UID: \"5fcddea2-77a4-475f-9a4c-a62f5243b353\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/snap/microk8s/common/var/lib/kubelet/pods/5fcddea2-77a4-475f-9a4c-a62f5243b353/volumes/kubernetes.io~csi/pvc-ce65fb13-5ebf-4bd3-a202-b698de05c261/mount]: kubernetes.io/csi: failed to open volume data file [/var/snap/microk8s/common/var/lib/kubelet/pods/5fcddea2-77a4-475f-9a4c-a62f5243b353/volumes/kubernetes.io~csi/pvc-ce65fb13-5ebf-4bd3-a202-b698de05c261/vol_data.json]: open /var/snap/microk8s/common/var/lib/kubelet/pods/5fcddea2-77a4-475f-9a4c-a62f5243b353/volumes/kubernetes.io~csi/pvc-ce65fb13-5ebf-4bd3-a202-b698de05c261/vol_data.json: no such file or directory"

I had a promotheus pod stuck in "terminating". I managed to force delete it but the errors continue. How to stop it?

**Comment by Dunge** [comment]
Last week I deleted the pod folder manually and rebooted the node and it seemed to have stopped.
This morning it started again.

Please advise.

**Comment by gnufied** [comment]
@Dunge thank you for reporting. Does the pod is stuck forever in `Terminating` state or did it clear soon?

**Comment by Dunge** [comment]
It was stuck terminating (over 12h during the night) with the errors about `vol_data.json` spamming the journalctl logs and with the new replacement pod who couldn't mount the volume so the service was down.
After issuing `microk8s stop` to shut down the node and the errors stopped in the console. I waited 5minutes for k8s to transfer the workload on the other pods. then it did clear up. I then restarted the node.

My interrogation is finding out what caused this in the first place, because two occurrences in less than a week is less than desirable. People are using the services on this cluster and their work was impacted.

**Comment by gnufied** [comment]
What is the kubelet version and can you capture kubelet log when this happens? I have found a way to reproduce this error - https://github.com/kubernetes/kubernetes/pull/120086#issuecomment-1718276990 but it does not prevent pod from being deleted and event spam eventually stops on its own.

**Comment by gnufied** [comment]
I think we should still fix the race, but the race being fixed in https://github.com/kubernetes/kubernetes/pull/120086#issuecomment-1718276990 might not prevent pod deletion issue, if that is what is happening here. So that is why, it is important to have kubelet logs when this event occured.

**Comment by Dunge** [comment]
Thank you @gnufied 
I'm attaching my kubetlet log. A 10 minute window, where the first 5 were calm and next 5 minutes seems liked the issue occurred, I'm not knowledgeable enough to interpret it, some network timeout? The kubelet process seemed to have rebooted, and then the error mentioned above started to log in repetition.

Version seems to be `"Kubelet version" kubeletVersion="v1.27.5"`, but since it matches microk8s version (it runs inside a process called kubelite) I'm not sure if it's the real one.

If you are kind enough to diagnose what caused the crash too, it would be appreciated ;)

[snap.microk8s.daemon-kubelite.tar.gz](https://github.com/kubernetes/kubernetes/files/12601852/snap.microk8s.daemon-kubelite.tar.gz)

**Comment by gnufied** [comment]
Your kubelet log has following message:

```
Sep 12 23:43:22 jldocker-2.jamlogic.com microk8s.daemon-kubelite[2636757]: E0912 23:43:22.198702 2636757 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/driver.longhorn.io^pvc-b74e3544-6c0a-4c12-9c88-fb2c8a74433b podName: nodeName:}" failed. No retries permitted until 2023-09-12 23:44:26.198630782 +0000 UTC m=+153.750913774 (durationBeforeRetry 1m4s). Error: MountVolume.SetUp failed for volume "pvc-b74e3544-6c0a-4c12-9c88-fb2c8a74433b" (UniqueName: "kubernetes.io/csi/drive
r.longhorn.io^pvc-b74e3544-6c0a-4c12-9c88-fb2c8a74433b") pod "redis-node-2" (UID: "bd9f056c-5532-4881-b424-0b1153fce25c") : rpc error: code = Internal desc = Failed to prepare mount point for volume pvc-b74e3544-6c0a-4c12-9c88-fb2c8a74433b error unmounted existing corrupt mount point /var/snap/microk8s/common/var/lib/kubelet/pods/bd9f056c-5532-4881-b424-0b1153fce25c/volumes/kubernetes.io~csi/pvc-b74e3544-6c0a-4c12-9c88-fb2c8a74433b/mount
```

Which appears that longhorn driver is doing something very suspicious when `NodePublish` fails. it looks like the driver has decided to unmount the volume in `NodePublish` call, which seems wrong... :/  @Dunge your proble might be specific behaviour of the CSI driver.

**Comment by gnufied** [comment]
Alright one last update.  If anyone is running into problems like these, make sure your CSI driver implements `NodeUnpublish` correctly at very minimum and idempotent.  This issue imo is almost entirely caused by problematic CSI driver implementations.

**Comment by chandratop** [comment]
Seeing the issue again: `operationExecutor.UnmountVolume failed`/`vol_data.json: no such file or directory`

Kubelet logs
```
Jun 17 08:43:44 worker-node-yyyy kubelet[5361]: E0617 08:43:44.920639    5361 reconciler_common.go:169] "operationExecutor.UnmountVolume failed (controllerAttachDetachEnabled true) for volume \"xxx\" (UniqueName: \"kubernetes.io/csi/ebs.csi.aws.com^vol-0e5ebc815961121bf\") pod \"6c8a91b8-1a49-4056-8f35-ff14e793584f\" (UID: \"6c8a91b8-1a49-4056-8f35-ff14e793584f\") : UnmountVolume.NewUnmounter failed for volume \"xxx\" (UniqueName: \"kubernetes.io/csi/ebs.csi.aws.com^vol-0e5ebc815961121bf\") pod \"6c8a91b8-1a49-4056-8f35-ff14e793584f\" (UID: \"6c8a91b8-1a49-4056-8f35-ff14e793584f\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/6c8a91b8-1a49-4056-8f35-ff14e793584f/volumes/kubernetes.io~csi/pvc-59d7c5b3-e94c-489e-aeaa-cdef1d0edac3/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/6c8a91b8-1a49-4056-8f35-ff14e793584f/volumes/kubernetes.io~csi/pvc-59d7c5b3-e94c-489e-aeaa-cdef1d0edac3/vol_data.json]: open /var/lib/kubelet/pods/6c8a91b8-1a49-4056-8f35-ff14e793584f/volumes/kubernetes.io~csi/pvc-59d7c5b3-e94c-489e-aeaa-cdef1d0edac3/vol_data.json: no such file or directory" err="UnmountVolume.NewUnmounter failed for volume \"xxx\" (UniqueName: \"kubernetes.io/csi/ebs.csi.aws.com^vol-0e5ebc815961121bf\") pod \"6c8a91b8-1a49-4056-8f35-ff14e793584f\" (UID: \"6c8a91b8-1a49-4056-8f35-ff14e793584f\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/6c8a91b8-1a49-4056-8f35-ff14e793584f/volumes/kubernetes.io~csi/pvc-59d7c5b3-e94c-489e-aeaa-cdef1d0edac3/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/6c8a91b8-1a49-4056-8f35-ff14e793584f/volumes/kubernetes.io~csi/pvc-59d7c5b3-e94c-489e-aeaa-cdef1d0edac3/vol_data.json]: open /var/lib/kubelet/pods/6c8a91b8-1a49-4056-8f35-ff14e793584f/volumes/kubernetes.io~csi/pvc-59d7c5b3-e94c-489e-aeaa-cdef1d0edac3/vol_data.json: no such file or directory"
```
Kubelet version: `v1.28.5`


Has this fix not been applied in the mainline releases?

**Comment by olyazavr** [comment]
We're still seeing this in 1.29.10:
```
reconciler_common.go:172] "operationExecutor.UnmountVolume failed (controllerAttachDetachEnabled true) for volume \"hadoop-mnt-volume\" (UniqueName: \"kubernetes.io/csi/ebs.csi.aws.com^vol-02dc2353016a61b7d\") pod \"0c02c37e-6742-4473-9984-34a2827d42f6\" (UID: \"0c02c37e-6742-4473-9984-34a2827d42f6\") : UnmountVolume.NewUnmounter failed for volume \"hadoop-mnt-volume\" (UniqueName: \"kubernetes.io/csi/ebs.csi.aws.com^vol-02dc2353016a61b7d\") pod \"0c02c37e-6742-4473-9984-34a2827d42f6\" (UID: \"0c02c37e-6742-4473-9984-34a2827d42f6\") : kubernetes.io/csi: unmounter failed to load volume data file [/mnt/kubelet/pods/0c02c37e-6742-4473-9984-34a2827d42f6/volumes/kubernetes.io~csi/pvc-74dfc15c-38e6-4764-989c-11dfeb68ece6/mount]: kubernetes.io/csi: failed to open volume data file [/mnt/kubelet/pods/0c02c37e-6742-4473-9984-34a2827d42f6/volumes/kubernetes.io~csi/pvc-74dfc15c-38e6-4764-989c-11dfeb68ece6/vol_data.json]: open /mnt/kubelet/pods/0c02c37e-6742-4473-9984-34a2827d42f6/volumes/kubernetes.io~csi/pvc-74dfc15c-38e6-4764-989c-11dfeb68ece6/vol_data.json: no such file or directory"
```

We created automation to restart kubelet when this log line appears, as that appears to fix it

**Comment by LLLLLBJ** [comment]
This problem may be caused by this scene: 
The CSI driver should not return error when the mnt dir is not found, because UnmountVolume may occur multiple rounds

![Image](https://github.com/user-attachments/assets/dc8fc5e1-1c30-4676-9885-defd39def08f)

**Comment by Mr-ZhuXingYi** [comment]
@vadasambar hi,I encountered this problem in 1.19, have you found the specific reason?
