### ISSUE TITLE
Kubernetes api returns incorrect conflicting fields during server-side apply in some cases

### ISSUE THREAD

**Issue by cheeseandcereal** [kubernetes/kubernetes#119141]
### What happened?

When performing a server-side apply PATCH request, if there are conflicts in what's being applied with differing field owners, kubernetes responds with a 409 conflict error with an array of causes in the error detail, enumerating the conflicting fields that were discovered.

In some cases, we see that the fields returned in this 409 error response are incorrect, containing both duplicate fields, and entirely missing other conflicts.

### What did you expect to happen?

The http 409 error response when receiving a conflict while using server-side apply should contain all of the correct fields (and also ideally no duplicates).

### How can we reproduce it (as minimally and precisely as possible)?

Save this file as `original.yaml`

<details>

```yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: simple-probe
spec:
  selector:
    matchLabels:
      k8s-app: simple-probe
  template:
    metadata:
      labels:
        k8s-app: simple-probe
    spec:
      containers:
      - name: probe
        image: registry.k8s.io/busybox
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 9999999
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          periodSeconds: 5
```

</details>

Save this file as `modified.yaml`

<details>

```yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: simple-probe
spec:
  template:
    spec:
      containers:
      - name: probe
        livenessProbe:
          exec:
            command:
            - ls
            - /tmp/healthy
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - ls
            - /tmp/healthy
          periodSeconds: 10
```

</details>

Now apply the first yaml with server-side apply:

`kubectl apply -f original.yaml --server-side --field-manager=original`

Apply the second yaml with server-side apply, using a different field manager:

`kubectl apply -f modified.yaml --server-side --field-manager=modified --validate=false --force-conflicts`

If we get the applied daemonset at this point (`kubectl get ds simple-probe -o yaml --show-managed-fields`), everything appears to be applied correctly with expected behavior and expected field owners

Now try to re-apply with the original command/field manager, forcing a conflict error to be returned (increased verbosity to see returned http body):

`kubectl apply -f original.yaml --server-side --field-manager=original -v=9`

When re-applying this original yaml (without force-conflicts), we expect to observe conflicts on all of the fields that were changed by modified.yaml and now owned by the `modified` field manager. These _should_ be:
```
.spec.template.spec.containers[name="probe"].livenessProbe.exec.command
.spec.template.spec.containers[name="probe"].livenessProbe.periodSeconds
.spec.template.spec.containers[name="probe"].readinessProbe.exec.command
.spec.template.spec.containers[name="probe"].readinessProbe.periodSeconds
```

However, this is the response we get when trying to apply using the increased verbosity command:

```
I0706 12:56:34.394111   74086 request.go:1188] Request Body: {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"name":"simple-probe","namespace":"default"},"spec":{"selector":{"matchLabels":{"k8s-app":"simple-probe"}},"template":{"metadata":{"labels":{"k8s-app":"simple-probe"}},"spec":{"containers":[{"args":["/bin/sh","-c","touch /tmp/healthy; sleep 9999999"],"image":"registry.k8s.io/busybox","livenessProbe":{"exec":{"command":["cat","/tmp/healthy"]},"periodSeconds":5},"name":"probe","readinessProbe":{"exec":{"command":["cat","/tmp/healthy"]},"periodSeconds":5}}]}}}}
I0706 12:56:34.394215   74086 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/json" -H "Content-Type: application/apply-patch+yaml" -H "User-Agent: kubectl/v1.27.3 (darwin/amd64) kubernetes/25b4e43" 'https://<REDACTED>/apis/apps/v1/namespaces/default/daemonsets/simple-probe?fieldManager=original&fieldValidation=Strict&force=false'
I0706 12:56:34.408095   74086 round_trippers.go:553] PATCH https://<REDACTED>/apis/apps/v1/namespaces/default/daemonsets/simple-probe?fieldManager=original&fieldValidation=Strict&force=false 409 Conflict in 13 milliseconds
I0706 12:56:34.408123   74086 round_trippers.go:570] HTTP Statistics: GetConnection 0 ms ServerProcessing 13 ms Duration 13 ms
I0706 12:56:34.408133   74086 round_trippers.go:577] Response Headers:
I0706 12:56:34.408142   74086 round_trippers.go:580]     Date: Thu, 06 Jul 2023 19:56:34 GMT
I0706 12:56:34.408147   74086 round_trippers.go:580]     Audit-Id: 4d2e7d6c-109c-4fb5-93eb-e81d5a4c9ead
I0706 12:56:34.408152   74086 round_trippers.go:580]     Cache-Control: no-cache, private
I0706 12:56:34.408157   74086 round_trippers.go:580]     Content-Type: application/json
I0706 12:56:34.408162   74086 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: 4fe5247d-d953-4884-81cc-c1abf9bd2989
I0706 12:56:34.408167   74086 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: 35c473fc-8e57-4244-9c7f-788f96aa29fd
I0706 12:56:34.408305   74086 round_trippers.go:580]     Content-Length: 1107
I0706 12:56:34.408342   74086 request.go:1188] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Apply failed with 4 conflicts: conflicts with \"modified\":\n- .spec.template.spec.containers[name=\"probe\"].readinessProbe.exec\n- .spec.template.spec.containers[name=\"probe\"].readinessProbe.exec.command\n- .spec.template.spec.containers[name=\"probe\"].readinessProbe.exec\n- .spec.template.spec.containers[name=\"probe\"].readinessProbe.exec.command","reason":"Conflict","details":{"causes":[{"reason":"FieldManagerConflict","message":"conflict with \"modified\"","field":".spec.template.spec.containers[name=\"probe\"].readinessProbe.exec"},{"reason":"FieldManagerConflict","message":"conflict with \"modified\"","field":".spec.template.spec.containers[name=\"probe\"].readinessProbe.exec.command"},{"reason":"FieldManagerConflict","message":"conflict with \"modified\"","field":".spec.template.spec.containers[name=\"probe\"].readinessProbe.exec"},{"reason":"FieldManagerConflict","message":"conflict with \"modified\"","field":".spec.template.spec.containers[name=\"probe\"].readinessProbe.exec.command"}]},"code":409}
error: Apply failed with 4 conflicts: conflicts with "modified":
- .spec.template.spec.containers[name="probe"].readinessProbe.exec
- .spec.template.spec.containers[name="probe"].readinessProbe.exec.command
- .spec.template.spec.containers[name="probe"].readinessProbe.exec
- .spec.template.spec.containers[name="probe"].readinessProbe.exec.command
```

Note that the conflicts returned by the 409 error have duplicate fields, and completely omit at least 3 of the fields we are actually conflicting with.

### Anything else we need to know?

If we re-apply the original with `--force-conflicts`, then the correct data is applied, and the correct field managers are set, however if we do not want to force conflicts, the conflicting fields returned in the 409 error returned from the API server are incorrect.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.3-eks-a5565ad", GitCommit:"78c8293d1c65e8a153bf3c03802ab9358c0e1a14", GitTreeState:"clean", BuildDate:"2023-06-16T17:32:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
aws eks
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
Tested on fresh/new EKS kubernetes cluster created with eksctl with defaults
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kmala** [comment]
this should be fixed with https://github.com/kubernetes-sigs/structured-merge-diff/pull/242

**Comment by cheeseandcereal** [comment]
The upstream PR that fixes this issue needs to be released and pulled into kubernetes/kubernetes release branches before this issue is resolved.

**Comment by jiahuif** [comment]
/assign @kmala 
Would you want to do the dependency bump too? Thank you.

**Comment by kmala** [comment]
> Would you want to do the dependency bump too?
Yes, i am working on getting a new tag released for updating the dependency.

**Comment by apelisse** [comment]
I mean, we've been able to release without the tag a few times, I still don't see what the problem is?

**Comment by apelisse** [comment]
Actually, maybe I'm wrong ... in that case, let me add a tag 😅
