### ISSUE TITLE
[Failing Test]  ci-kubernetes-e2e-kind-beta-features/pull-kubernetes-e2e-kind-beta-features failed for enabling some beta features(by default disabled)

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#121349]
### Which jobs are failing?

scheduler/controller-manager pod not ready

### Which tests are failing?

cluster initialization 

### Since when has it been failing?

 test-infra about this CI is https://github.com/kubernetes/test-infra/pull/30960/files.

### Testgrid link

- original: https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-kind-alpha-features&width=90
- later: https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-kind-beta-features&width=90

### Reason for failure (if possible)

The scheduler pod is not ready.
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/121105/pull-kubernetes-e2e-kind-alpha-features/1714601745411215360/artifacts/kind-control-plane/pods/kube-system_kube-scheduler-kind-control-plane_e08196ed28fb93698c413aa98de6b2bb/kube-scheduler/13.log

> 2023-10-18T11:43:36.163143598Z stderr F E1018 11:43:36.162981       1 run.go:74] "command failed" err="failed to create listener: failed to listen on 127.0.0.1:10257: listen tcp 127.0.0.1:10257: bind: address already in use" 
> 2023-10-18T11:32:28.647254667Z stderr F I1018 11:32:28.647171       1 secure_serving.go:213] Serving securely on 127.0.0.1:10257

### Anything else we need to know?

I did some test in https://github.com/kubernetes/kubernetes/pull/121345

### Relevant SIG(s)

/sig node testing

**Comment by aojea** [comment]
Some details, since we don't have periodics we can not really know , but last execution of the job in Oct 5th worked  https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-kind-alpha-features&width=90

It can be reproduced locally with kind building the node image from the current HEAD
```sh
cd kubernetes
git checkout master
kind build node-image
wget https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/121105/pull-kubernetes-e2e-kind-alpha-features/1714601745411215360/artifacts/kind-config.yaml 
kind create cluster --image kindest/node:latest --config kind-config-alpha.yaml --name alpha --retain
```

not all the pods fail always, it seems impacts more static pods, and the weird thing is that the process may be running but kubelet report it as failing, also it may try to restart and fails because there is already another process binding the port

**Comment by sairameshv** [comment]
> Some details, since we don't have periodics we can not really know , but last execution of the job in Oct 5th worked https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-kind-alpha-features&width=90
> 
> It can be reproduced locally with kind building the node image from the current HEAD
> 
> ```shell
> cd kubernetes
> git checkout master
> kind build node-image
> wget https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/121105/pull-kubernetes-e2e-kind-alpha-features/1714601745411215360/artifacts/kind-config.yaml 
> kind create cluster --image kindest/node:latest --config kind-config-alpha.yaml --name alpha --retain
> ```
> 
> not all the pods fail always, it seems impacts more static pods, and the weird thing is that the process may be running but kubelet report it as failing, also it may try to restart and fails because there is already another process binding the port

Yes, this seems to be observed more with static pods as they start prior to the other pods and it depends on how many times the SyncLoop ADD/UPDATE calls are made within the window of two consecutive GenericPLEG relistings i.e 1s.
Anyway, this would have been fixed by the recently merged [PR](https://github.com/kubernetes/kubernetes/pull/120942)

**Comment by pacoxu** [comment]
@sairameshv  thanks for the explanation. 

@aojea would you close it after https://github.com/kubernetes/kubernetes/pull/116516 presubmit CI passes?

**Comment by BenTheElder** [comment]
periodic here: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kind-alpha-beta-features ref https://github.com/kubernetes/test-infra/pull/31070

**Comment by BenTheElder** [comment]
Triggered rerun with latest, looking promising https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kind-alpha-beta-features/1715056907909074944

**Comment by BenTheElder** [comment]
kube-scheduler failed to run: 
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kind-alpha-beta-features/1715056907909074944/artifacts/kind-control-plane/pods/kube-system_kube-scheduler-kind-control-plane_11a0ca06444f9658f02731db37b3b32a/kube-scheduler/11.log

> 2023-10-19T17:52:27.015678767Z stderr F E1019 17:52:27.015525       1 run.go:74] "command failed" err="failed to create listener: failed to listen on 127.0.0.1:10259: listen tcp 127.0.0.1:10259: bind: address already in use"

**Comment by BenTheElder** [comment]
I don't think the evented pleg issue is fixed.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/31078 we will now have coverage of alpha only, beta only, alpha+beta for clarity.

https://prow.k8s.io/?job=*kind*features

**Comment by pacoxu** [comment]
> https://github.com/kubernetes/test-infra/pull/31078 we will now have coverage of alpha only, beta only, alpha+beta for clarity.

https://github.com/kubernetes/test-infra/pull/31078 enabled Evented PLEG(which is beta but disabled by default.)
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116516/pull-kubernetes-e2e-kind-alpha-features/1714944921665802240 And https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119362/pull-kubernetes-e2e-kind-alpha-features/1714950739324833792 still failed for static pod preparation. (The recent evented PLEG pull request https://github.com/kubernetes/kubernetes/pull/120942 did not fix this CI).
- https://github.com/kubernetes/kubernetes/pull/121345 Passed the initialization with Evented PLEG feature disabled.

**Comment by aojea** [comment]
The problem is with something in beta, https://testgrid.k8s.io/sig-testing-kind#kind-master-beta

alpha only works fine https://testgrid.k8s.io/sig-testing-kind#kind-master-alpha

**Comment by SergeyKanzhelev** [comment]
@pacoxu are you still working on this?

**Comment by pacoxu** [comment]
> @pacoxu are you still working on this?

The title may need a change.

I tested it today and it still failed for the  `pull-kubernetes-e2e-kind-beta-features`

- a test failed to start node(node not ready): https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121749/pull-kubernetes-e2e-kind-beta-features/1721476752632451072 The PR is a changelog change.
- In https://github.com/kubernetes/kubernetes/pull/121345 PR run, https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121345/pull-kubernetes-e2e-kind-beta-features/1721466557978120192 passed the node ready part. The PR only deprecated the EventedPLEG FG.

**Comment by pacoxu** [comment]
It indicates that the EventedPLEG FG has a critical bug.  IMO.

**Comment by sairameshv** [comment]
> It indicates that the EventedPLEG FG has a critical bug.  IMO.
> 
> /cc @harche @sairameshv

I'm working on an issue that is observed intermittently while enabling the Evented pleg feature gate. This failure may be related. I would take a look. Thanks for the info.

**Comment by pacoxu** [comment]
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kind-alpha-beta-features
- the test passed once on Nov 6th(failed before and after). So this is a flake(with a high rate).

**Comment by pacoxu** [comment]
> I'm working on an issue that is observed intermittently while enabling the Evented pleg feature gate. This failure may be related. I would take a look. Thanks for the info.

The CI behavior is the bug that is described in https://github.com/kubernetes/kubernetes/issues/121003.

Multi containers are created for a pod, and one container failed for `already in use` problem with socket or port.

**Comment by sairameshv** [comment]
> > I'm working on an issue that is observed intermittently while enabling the Evented pleg feature gate. This failure may be related. I would take a look. Thanks for the info.
> 
> The CI behavior is the bug that is described in #121003.
> 
> Multi containers are created for a pod, and one container failed for `already in use` problem with socket or port.

Yes, this is what I've discovered. The generated event has the updated details of the container statuses, but somehow, the pod status is not getting set/updated due to which there is a new duplicate container getting created.

**Comment by pacoxu** [comment]
A local test can reproduce locally with v1.29.0-rc.1.
- When I enable ValidatingAdmissionPolicy=true in apiserver, the kubeadm init will fail if I enable node EventedPLEG.

Both ValidatingAdmissionPolicy and EventedPLEG are beta and by default disabled.

```
apiVersion: "kubeadm.k8s.io/v1beta3"
kind: InitConfiguration
---
apiVersion: "kubeadm.k8s.io/v1beta3"
kind: ClusterConfiguration
imageRepository: m.daocloud.io/registry.k8s.io
kubernetesVersion: v1.29.0-rc.0
dns:
  imageRepository: m.daocloud.io/registry.k8s.io/coredns
networking:
  podSubnet: 192.168.0.0/24
apiServer:
  extraArgs:
    "feature-gates": "AllBeta=false,ValidatingAdmissionPolicy=true"
controllerManager:
  extraArgs:
    "feature-gates": "AllBeta=true"
scheduler:
  extraArgs:
    "feature-gates": "AllBeta=true"
---

apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
failSwapOn: true
featureGates:
  NodeSwap: false
  EventedPLEG: true
  AllBeta: true
```

My local test is using `kubeadm --v=4 init --config kubeadm-config.yaml`.

**Comment by pacoxu** [comment]
I submitted a PR to fix this problem in https://github.com/kubernetes/kubernetes/pull/122124.

- If you want to know detailed kubelet log to know what happened. You may refer to the PR: I added some log in a run in https://github.com/kubernetes/kubernetes/pull/121345.

**Comment by sunnylovestiramisu** [comment]
Is there any update on this?

**Comment by harche** [comment]
https://github.com/kubernetes/kubernetes/pull/122124#issuecomment-1883281827 to partially fix `pull-kubernetes-e2e-kind-beta-features`

**Comment by pacoxu** [comment]
This is fixed by a revert https://github.com/kubernetes/kubernetes/pull/122697.

However, it failed the master-alpha CI and will be tracked in https://github.com/kubernetes/kubernetes/issues/122721

**Comment by aojea** [comment]
> This was fixed by a revert #122697.
> 
> However, it failed the master-alpha CI and will be tracked in #122721

on the bright side, this means progress, as our beta state now is green, we need to fix now our alpha state, but having a beta state that is not working is not something anybody can expect

Great work Paco

**Comment by pacoxu** [comment]
PLEG is so complex🤣 My fix seems only a fix that almost fixes the problem... but still fail in a quite low rate.
