### ISSUE TITLE
[Flaking Test] gce-cos-master-default (containerd socket errors)

### ISSUE THREAD

**Issue by wendy-ha18** [kubernetes/kubernetes#125228]
### Which jobs are flaking?

master-blocking:
- gce-cos-master-default

### Which tests are flaking?

1. `Kubernetes e2e suite.[It] [sig-storage] CSI Mock volume fsgroup policies CSI FSGroupPolicy Update [LinuxOnly] should update fsGroup if update from File to default.`

2. `Kubernetes e2e suite.[It] [sig-network] Networking Granular Checks: Services should update endpoints: http`

### Since when has it been flaking?

This test is only failed **once** recently on 31/05/2024
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1796412325301850112

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd

### Reason for failure (if possible)

**02 test seem failed with the same reason related to containerd socket.**

```
{ failed [FAILED] failed: writing the contents: unable to upgrade connection: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /run/containerd/containerd.sock: connect: no such file or directory": unable to upgrade connection: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /run/containerd/containerd.sock: connect: no such file or directory"
In [It] at: k8s.io/kubernetes/test/e2e/storage/csimock/csi_fsgroup_policy.go:175 @ 05/31/24 05:40:11.726
}
```
Related to behavior of CSI Mock volumes when updating FSGroup policies. Seems like storage issue (?)
```
[FAIL] [sig-storage] CSI Mock volume fsgroup policies CSI FSGroupPolicy Update [LinuxOnly] [It] should update fsGroup if update from File to default [sig-storage]
  k8s.io/kubernetes/test/e2e/storage/csimock/csi_fsgroup_policy.go:175
```
```
2024/05/31 06:04:10 main.go:326: Something went wrong: encountered 1 errors: [error during ./hack/ginkgo-e2e.sh --ginkgo.skip=\[Driver:.gcepd\]|\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8 --report-dir=/logs/artifacts --disable-log-dump=true --cluster-ip-range=10.64.0.0/14: exit status 1]
```
```
subprocess.CalledProcessError: Command '('kubetest', '--dump=/logs/artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--check-leaked-resources', '--extract=ci/fast/latest-fast', '--extract-ci-bucket=k8s-release-dev', '--gcp-master-image=ubuntu', '--gcp-node-image=ubuntu', '--gcp-nodes=4', '--gcp-zone=us-west1-b', '--ginkgo-parallel=30', '--test_args=--ginkgo.skip=\\[Driver:.gcepd\\]|\\[Slow\\]|\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\]|\\[Feature:.+\\] --minStartupPods=8', '--timeout=50m')' returned non-zero exit status 1.
```

### Anything else we need to know?
Check this issue if you want to review the history performance of `Networking Granular Checks: Services should update endpoints: http` test: https://github.com/kubernetes/kubernetes/issues/123760

### Relevant SIG(s)

/sig cloud-provider
/sig storage
@kubernetes/release-team-release-signal

**Comment by aojea** [comment]
Analyzing https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1796412325301850112

The test fails with

>  GetResponseFromContainer: failed to execute "curl -g -q -s 'http://10.64.4.65:9080/dial?request=hostname&protocol=http&host=10.0.79.230&port=80&tries=1'": unable to upgrade connection: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /run/containerd/containerd.sock: connect: no such file or directory", stdout: "", stderr: ""
I0531 05:39:28.731652 10367 utils.go:383] encountered error during dial (did not find expected responses... 

The Pod is running on node 

> I0531 05:39:28.904639 10367 dump.go:53] At 2024-05-31 05:36:51 +0000 UTC - event for test-container-pod: {kubelet bootstrap-e2e-minion-group-79vz} Started: Started container webserver

The containerd logs at that node https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1796412325301850112/artifacts/bootstrap-e2e-minion-group-79vz/containerd.log shows it receives a SIGTERM

> May 31 05:39:25.552612 bootstrap-e2e-minion-group-79vz systemd[1]: containerd.service: Sent signal SIGTERM to main process 8648 (containerd) on client request.

and containerd is restarted

> May 31 05:39:26.010977 bootstrap-e2e-minion-group-79vz containerd[8648]: time="2024-05-31T05:39:25.823748625Z" level=info msg="Stop CRI service"

> May 31 05:39:34.091375 bootstrap-e2e-minion-group-79vz containerd[41887]: time="2024-05-31T05:39:34.090214404Z" level=info msg="containerd successfully booted in 2.142999s"


impacting all the tests that are running at that time.

I would say is the [node-problem-detector](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1796412325301850112/artifacts/bootstrap-e2e-minion-group-79vz/node-problem-detector.log) who restarts containerd, but it should not do that if that is the case

> I0531 05:39:31.630170       1 log_monitor.go:159] New status generated: &{Source:systemd-monitor Events:[{Severity:warn Timestamp:2024-05-31 05:39:31.531417 +0000 UTC Reason:ContainerdStart Message:Starting containerd container runtime...}] Conditions:[]}

/sig node
/cc @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
> is the [node-problem-detector](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1796412325301850112/artifacts/bootstrap-e2e-minion-group-79vz/node-problem-detector.log) who restarts containerd?

NPD only watched for logs. Or you mean some NPD tests would restart it?

**Comment by AnishShah** [comment]
`health-monitor.sh` script restarts containerd if it doesn't respond within 60s - https://github.com/kubernetes/kubernetes/blob/5bf1e95541d90e37f6c6637b5b45d8783e7907aa/cluster/gce/gci/health-monitor.sh#L46C1-L47C1

**Comment by wendy-ha18** [comment]
Hi @AnishShah , @SergeyKanzhelev regarding this, do you think this would be a release blocker? as we're planning for **v1.31.0-alpha.1 release cut TODAY**

**Comment by AnishShah** [comment]
`health-monitor.sh` calls `crictl pods` to health-check containerd. It timed out and restarted containerd. I do not see any reason in containerd logs that it was unhealthy. @SergeyKanzhelev mentioned that `crictl pods` is very memory-hungry command and it might just be a delay to load crictl in memory.

I think it is safe to not consider this test failure as release blocker.

We should modify the `health-monitor.sh` skip to use some other health check command that is not memory-intensive.

**Comment by elmiko** [comment]
we are reviewing this during the sig cloud-provider office hours today and we aren't seeing anything that stands out as an issue with the cloud controller. is there something we are missing?

**Comment by AnishShah** [comment]
Notes from sig-node CI meeting:

- This is not release blocking

**Comment by drewhagen** [comment]
The release cycle for 1.32 starts today. Since this is still open, I will carry it over to the latest milestone. 

I'm curious about opportunities to reduce the flaky tests that we're tracking.
@SergeyKanzhelev  @bart0sh I see you've had some activity to resolve this with a PR that needs review. Is there anything we can do to move this forward? Thanks!

**Comment by bart0sh** [comment]
Last test failure was `failed [FAILED] Failed to register CSIDriver csi-mock-csi-mock-volumes-expansion-7559: error waiting for CSI driver csi-mock-csi-mock-volumes-expansion-7559 registration on node e2e-fake-node-mvjbc: timed out waiting for the condition`. I don't see it mentioned in this issue. It could be related to [this issue](https://github.com/kubernetes/kubernetes/issues/127108), I guess.

**Comment by SergeyKanzhelev** [comment]
@dims can you please help merge https://github.com/kubernetes/kubernetes/pull/126586 to resolve some of flakes?

**Comment by SergeyKanzhelev** [comment]
> Last test failure was `failed [FAILED] Failed to register CSIDriver csi-mock-csi-mock-volumes-expansion-7559: error waiting for CSI driver csi-mock-csi-mock-volumes-expansion-7559 registration on node e2e-fake-node-mvjbc: timed out waiting for the condition`. I don't see it mentioned in this issue. It could be related to [this issue](https://github.com/kubernetes/kubernetes/issues/127108), I guess.

summoning SIG Storage back:

/sig storage

**Comment by dims** [comment]
> @dims can you please help merge #126586 to resolve some of flakes?

Done!

**Comment by drewhagen** [comment]
Hello @dims @SergeyKanzhelev @bart0sh @aojea 

I wanted to check in since this one hasn't been active in a while.

A friendly reminder of what's ahead:
* Code freeze is starting `02:00 UTC Friday November 8th 2024` (about *3 weeks* from now), and while there is still time, we want to ensure that each PR has a chance to be merged on time.

Is this still an issue? If not, can we close this, and if so, do we aim to fix it for the `1.32` release?

Thanks!

cc: @wendy-ha18 for tracking

**Comment by SergeyKanzhelev** [comment]
/sig network

for this test flake:

```
[sig-network] Networking Granular Checks: Services should update endpoints: http
```

**Comment by SergeyKanzhelev** [comment]
/remove-sig node

There are no Node tests flaking in this job any longer

**Comment by wendy-ha18** [comment]
Hello @dims @SergeyKanzhelev @bart0sh @aojea
As I see this issue is still targeting for milestone v1.32 , just a last reminder from my side that the code freeze is starting 02:00 UTC Friday November 8th 2024 (less than 1 week from now).

Please make sure the PR for this issue has both lgtm and approved labels before the code freeze. Thanks!

**Comment by tico88612** [comment]
Hello!
Appreciate all of your efforts with this! Is the plan still to resolve this issue for `v1.32` ?
If so, a gentle reminder that the code freeze has started `02:00 UTC Friday November 8th 2024`. Please make sure any PRs have both `lgtm` and `approved` labels ASAP, and file an [Exception](https://github.com/kubernetes/sig-release/blob/master/releases/EXCEPTIONS.md).
Thanks!

**Comment by mepi262** [comment]
Hello @dims @SergeyKanzhelev @bart0sh @aojea @drewhagen @wendy-ha18 
What do you think about this issue?

**Comment by drewhagen** [comment]
Since this isn't high priority and code freeze has passed, we're going to remove the 1.32 milestone.

/milestone clear

**Comment by wendy-ha18** [comment]
Hi @aojea @SergeyKanzhelev 

The `Kubernetes e2e suite.[It] [sig-network] Networking Granular Checks: Services should update endpoints: http` is recently failling on [master-blocking](https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd) with potentially the same issue.

`{ failed [FAILED] failed dialing endpoint (recovery), received unexpected responses... 
Attempt 0
Command curl -g -q -s 'http://10.64.3.218:9080/dial?request=hostname&protocol=http&host=10.0.189.140&port=80&tries=1'
retrieved map[bootstrap-e2e-minion-group-2sbr:{}]
expected map[netserver-1:{} netserver-2:{} netserver-3:{}]
In [It] at: k8s.io/kubernetes/test/e2e/network/networking.go:338 @ 01/17/25 06:06:11.284
}`

Prow: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1880130462064578560
Triage:
[17/01/2025, 16:50:08](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1880130462064578560)
[15/01/2025, 10:43:06](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1879313319714623488)
[06/01/2025, 02:19:02](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1875924974305284096)

Could you plz help me have a look on it again? Thanks everyone

**Comment by aojea** [comment]
/close

I apologize, I confused the issues, last comment applies to https://github.com/kubernetes/kubernetes/issues/123760 not to this issue, this seems to be solved
