### ISSUE TITLE
Low priority pods running despite high priority pods in pending state

### ISSUE THREAD

**Issue by Yanis-Kouidri** [kubernetes/kubernetes#126479]
### What happened?

When I submit 10 similar pods with high priority, followed by 10 similar pods with low priority, and then 20 seconds later, 10 more low priority pods, the latter low priority pods are scheduled even though some high priority pods are still in a “pending” state. All pods request a significant amount of resources, so my cluster cannot schedule them simultaneously.

### What did you expect to happen?

I expected that all 10 high-priority pods would be scheduled according to the available resources on the cluster first, followed by the 10 low-priority pods, and finally the other 10 low-priority pods. In other words, I want high-priority pods to be scheduled first, and for pods with the same priority, I expect them to be scheduled in a first-in, first-out (FIFO) manner.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a new namespace.
2. Create two priority classes as follows: 
```YAML
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
  namespace: priority-test-zone
value: 1000000
globalDefault: false
preemptionPolicy: Never
---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
  namespace: priority-test-zone
value: 1000
preemptionPolicy: Never
globalDefault: false
```

3. Create 10 pods with high priority: 
```YAML
apiVersion: v1
kind: Pod
metadata:
  name: high-priority-pod-1
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sh", "-c", "sleep 10"]
      resources:
        requests:
          memory: "3Gi"
          cpu: "5"
  priorityClassName: high-priority
  restartPolicy: Never
```

4. Immediately after, create 10 pods with low priority: 
```YAML
apiVersion: v1
kind: Pod
metadata:
  name: low-priority-pod-1
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sh", "-c", "sleep 10"]
      resources:
        requests:
          memory: "3Gi"
          cpu: "5"
  priorityClassName: low-priority
  restartPolicy: Never
```

5. Wait about 20 seconds for some high-priority pods to start running.
6. Create 10 more pods with low priority: 
```YAML
apiVersion: v1
kind: Pod
metadata:
  name: other-low-priority-pod-1
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sh", "-c", "sleep 10"]
      resources:
        requests:
          memory: "3Gi"
          cpu: "5"
  priorityClassName: low-priority
  restartPolicy: Never
```

7. You should see something like this if you run `watch kubectl get pod`:

```console
$ k get po
NAME                        READY   STATUS              RESTARTS   AGE
high-priority-pod-1         0/1     Completed           0          66s
high-priority-pod-10        0/1     Pending             0          66s
high-priority-pod-2         0/1     Completed           0          66s
high-priority-pod-3         0/1     Completed           0          66s
high-priority-pod-4         0/1     Completed           0          66s
high-priority-pod-5         0/1     Completed           0          66s
high-priority-pod-6         1/1     Running             0          66s
high-priority-pod-7         0/1     Pending             0          66s
high-priority-pod-8         0/1     Pending             0          66s
high-priority-pod-9         0/1     Pending             0          66s
low-priority-pod-1          0/1     Pending             0          65s
low-priority-pod-10         0/1     Pending             0          65s
low-priority-pod-2          0/1     Pending             0          65s
low-priority-pod-3          0/1     Pending             0          65s
low-priority-pod-4          0/1     Pending             0          65s
low-priority-pod-5          0/1     Pending             0          65s
low-priority-pod-6          0/1     Pending             0          65s
low-priority-pod-7          0/1     Pending             0          65s
low-priority-pod-8          0/1     Pending             0          65s
low-priority-pod-9          0/1     Pending             0          65s
other-low-priority-pod-1    0/1     Completed           0          42s
other-low-priority-pod-10   0/1     Pending             0          42s
other-low-priority-pod-2    0/1     ContainerCreating   0          42s
other-low-priority-pod-3    0/1     Pending             0          42s
other-low-priority-pod-4    0/1     Pending             0          42s
other-low-priority-pod-5    0/1     Pending             0          42s
other-low-priority-pod-6    0/1     Pending             0          42s
other-low-priority-pod-7    0/1     Pending             0          42s
other-low-priority-pod-8    0/1     Pending             0          42s
other-low-priority-pod-9    0/1     Pending             0          42s
```

### Anything else we need to know?

The defined PriorityClasses are non-preemptive; I do not want the pods to be preempted, but rather to prioritize some over others.
I tried scheduling all pods on the same node, but the result is the same.
I also tested on another cluster running a different version of Kubernetes (1.29), and the problem persists.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:49:13Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15+rke2r1", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T19:54:26Z", GoVersion:"go1.17.13b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
On premises
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

$ uname -a
Linux dev 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Tue Nov 16 14:42:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
When you see a low-priority pod running, are there any of the higher priority Pods still not bound to a node?
If the scheduler has assigned all the high priority Pods to a node, but they have yet to start, the scheduler is free to start assigning the lower-priority Pods to nodes where they might fit.

Let's rule out this explanation, because if that's what's happening, it's not a bug.

**Comment by Yanis-Kouidri** [comment]
> When you see a low-priority pod running, are there any of the higher priority Pods still not bound to a node? If the scheduler has assigned all the high priority Pods to a node, but they have yet to start, the scheduler is free to start assigning the lower-priority Pods to nodes where they might fit.
> 
> Let's rule out this explanation, because if that's what's happening, it's not a bug.

I just test and I can confirm, when a low priority pod is running, some high priority pods are not bound to a node as you can see here :

```console
$ k describe pod high-priority-pod-9
Name:                 high-priority-pod-9
Namespace:            priority
Priority:             1000000
Priority Class Name:  high-priority
Node:                 <none>
Labels:               <none>
Annotations:          kubernetes.io/psp: global-unrestricted-psp
Status:               Pending
IP:
IPs:                  <none>
Containers:
  alpine:
    Image:      alpine
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      sleep 10
    Requests:
      cpu:        8
      memory:     3Gi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4j6xx (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  kube-api-access-4j6xx:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  55s                default-scheduler  0/3 nodes are available: 3 Insufficient cpu.
  Warning  FailedScheduling  37s (x1 over 40s)  default-scheduler  0/3 nodes are available: 3 Insufficient cpu.

```

**Comment by AxeZhan** [comment]
From the events you posted. It looks like the scheduler tried to schedule the high priority pod and failed.

I think this might be the case:

1. You created many high priority pods, due to insufficient resource, some pods failed scheduling and were moved to unschedulable pods pool(they will be rescheduled after some certain time)
2. Some high priority pods completed, and in the same time, scheduler received some low priority pods and try to schedule them and succeed.

Featuregate SchedulerQueueingHints may help with this problem(because we'll try to reschedule the pod immediately when a scheduled pod is deleted). But I'm not sure if "completed" is considered as "deleted"(it should?)

I forgot in which release we merged queueHint for 'noderesources' plugin🤦. Can you try this on a cluster with `SchedulerQueueingHints` enabled in newest release?

**Comment by Yanis-Kouidri** [comment]
> From the events you posted. It looks like the scheduler tried to schedule the high priority pod and failed.
> 
> I think this might be the case:
> 
> 1. You created many high priority pods, due to insufficient resource, some pods failed scheduling and were moved to unschedulable pods pool(they will be rescheduled after some certain time)
> 2. Some high priority pods completed, and in the same time, scheduler received some low priority pods and try to schedule them and succeed.
> 
> Featuregate SchedulerQueueingHints may help with this problem(because we'll try to reschedule the pod immediately when a scheduled pod is deleted). But I'm not sure if "completed" is considered as "deleted"(it should?)
> 
> I forgot in which release we merged queueHint for 'noderesources' plugin🤦. Can you try this on a cluster with `SchedulerQueueingHints` enabled in newest release?

Your analysis makes sense; it explains why sometimes high-priority pods are scheduled in the expected order and sometimes not. There is a backoff mechanism for scheduling pods, so it can’t be seen as a FIFO queue.

`SchedulerQueueingHints` has been implemented since version `1.28`. I don’t have a cluster on this version right now, but I will find a way to test it and let you know what happens with this Feature Gate implemented.

**Comment by AxeZhan** [comment]
1.28 didn't bring https://github.com/kubernetes/kubernetes/pull/119177. I think we need to try at least on 1.30.
This looks like a race problem to me, so it may still can't achieve your goal in 1.30.

> I think I will need to use an external queuing solution like Volcano to address my problem. What are you thinking ?

Unfortunately, I'm not familiar with volcano although our company uses it lol😂.

**Comment by Yanis-Kouidri** [comment]
I conducted tests on Kubernetes version `1.30`, but the issue persists.

Here is the procedure I followed for testing:

Initially, I performed a test without making any modifications to see if the problem occurred. As expected, the issue was present in version `1.30`.

Next, I edited the kube-scheduler manifest file located at `/etc/kubernetes/manifests/kube-scheduler.yaml` to add the following line in the command section:
    `- --feature-gates=SchedulerQueueingHints=true`

The updated section looks like this:

```
spec:
  containers:
  - command:
    - kube-scheduler
    - --feature-gates=SchedulerQueueingHints=true
```

After this modification, the scheduler pod was automatically deleted and recreated.

To verify that the feature gate was correctly set, I ran `kubectl describe po -n kube-system kube-scheduler | grep feature-gates` and confirmed that this feature gate was present.

I then repeated my process of launching high-priority pods, followed by low-priority pods, and after a few seconds, another batch of low-priority pods. Unfortunately, I encountered the same issue with the unexpected scheduling of the second batch of low-priority pods.

Could you please confirm if my process for setting up the feature gate is correct?

If it is, it appears that the `SchedulerQueueingHints` feature gate does not resolve my issue.

<details>
Client Version: v1.30.0  
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3  
Server Version: v1.30.0  


`cat /etc/kubernetes/manifests/kube-scheduler.yaml `
```YAML
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    - --feature-gates=SchedulerQueueingHints=true
    image: registry.k8s.io/kube-scheduler:v1.30.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priority: 2000001000
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
status: {}
```
<details/>

**Comment by AxeZhan** [comment]
> Could you please confirm if my process for setting up the feature gate is correct?

It's correct. I'm afraid we'll need some external solutions.

**Comment by sanposhiho** [comment]
I suppose what @AxeZhan [explained](https://github.com/kubernetes/kubernetes/issues/126479#issuecomment-2262281791) is mostly correct, but, it's not the problem of the accuracy of retrying, and hence won't be solved with QHint feature. It comes from the nature of K8s scheduling.
The scheduler has a concept of backoff internally; when the Pod is rejected at the scheduling cycle, the scheduling for the Pod won't be retried until some time passes. 
And, we do not stop scheduling of low priority Pods even if some high priority Pods are being stopped by the backoff.

So, what is happening is:
1. The high priority Pods are scheduled.
2. Some are scheduled, while others are rejected (because of no enough space in the cluster)
3. The scheduler starts to schedule low priority ones.
4. Some Pods are completed and now the cluster can accommodate more Pods.
5. (4) wakes up the Pods rejected earlier in the queue, but those Pods will have to go through the backoff time before the scheduler retries them.
6. During the backoff time of high priority Pods, low priority Pods get scheduled successfully.

Maybe we should add some note to [our doc](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#effect-of-pod-priority-on-scheduling-order) to explain the scheduling order based on the priority is best-effort basically and sometimes low priority Pods could be scheduled earlier than high priority Pods.

If you need a strict control where the scheduler never starts to schedule low priority Pods until "all" high priority Pods are scheduled, you'd need some custom solution. Maybe, you can write a simple tool that [gates](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/) your low priority Pods until all higher priority Pods are scheduled.

**Comment by sftim** [comment]
Kubernetes is intentionally implemented to allow swapping in a custom scheduler.

**Comment by Yanis-Kouidri** [comment]
Thanks for your answers.
Now I understand how the scheduler works and why I didn't have the expected behavior for priority.
I will search for a custom solution to address my problem.
