### ISSUE TITLE
Pkgs.k8s.io repository for Red Hat based distributions for the latest release 1.31.0 has dependency issue!

### ISSUE THREAD

**Issue by Muthukumar-Subramaniam** [kubernetes/kubernetes#126660]
Hello team k8s,

In a lab environment we wanted to manually test the installation of latest release of kubernetes before pushing it to the automation.
There seems to be a dependency issue in the [pkgs.k8s.io](http://pkgs.k8s.io/) repository for the latest version 1.31.0, nothing provides kubernetes-cni needed by kubelet.
Please find the screen shot as attachment.
Please check and fix the issue as soon as possible.

Cluster information:
Kubernetes version: 1.31.0
Cloud being used: bare-metal
Installation method: RPM based repository [pkgs.k8s.io](http://pkgs.k8s.io/)
Host OS: Red Hat Enterprise Linux release 9.4 (Plow)

-----------------------------------------------

[root@prod-k8s-n1 ~]# cat /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://pkgs.k8s.io/core:/stable:/v1.31/rpm/
enabled=1
gpgcheck=1
gpgkey=https://pkgs.k8s.io/core:/stable:/v1.31/rpm/repodata/repomd.xml.key
[root@prod-k8s-n1 ~]#
[root@prod-k8s-n1 ~]#
[root@prod-k8s-n1 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux release 9.4 (Plow)
[root@prod-k8s-n1 ~]#
[root@prod-k8s-n1 ~]# dnf install kubelet kubeadm kubectl
Updating Subscription Management repositories.
Last metadata expiration check: 0:01:13 ago on Tuesday 13 August 2024 09:39:44 PM.
Error:
Problem: cannot install the best candidate for the job

nothing provides kubernetes-cni >= 1.2.0 needed by kubelet-1.31.0-150500.1.1.x86_64 from kubernetes
(try to add ‘–skip-broken’ to skip uninstallable packages or ‘–nobest’ to use not only best candidate packages)
[root@prod-k8s-n1 ~]#
-----------------------------------------------------------
<img width="710" alt="Screenshot 2024-08-13 221212" src="https://github.com/user-attachments/assets/d3b469a8-c628-4cb9-8111-c4edc35987ae">

Thanks & Regards,
Muthukumar Subramaniam

**Comment by ameukam** [comment]
cc @kubernetes/release-engineering

**Comment by xmudrii** [comment]
Can you try again? It should be fixed.

**Comment by Muthukumar-Subramaniam** [comment]
Hi @xmudrii ,

I just tried, and I could see the issue is fixed now.
Thank you for the quick turn around.

**Comment by yogesit** [comment]
Hello, @Muthukumar-Subramaniam. Could you please share with me the exact script what you have done to fix this issue?
The similar meta data error is occurring issue me too as well... i am looking for support you guys to fix it.

[Unable to Install Kubernetes on Red Hat 8.4 - Repo Not Found (404)](https://discuss.kubernetes.io/t/unable-to-install-kubernetes-on-red-hat-8-4-repo-not-found-404/29325)

Regards,
Yogei

**Comment by Muthukumar-Subramaniam** [comment]
Hi @yogesit , as updated by @xmudrii , you are using outdated legacy yum pacakage repository .
Please check the pointers here, https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

Note: The legacy package repositories (apt.kubernetes.io and yum.kubernetes.io) have been [deprecated and frozen starting from September 13, 2023](https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/). Using the [new package repositories hosted at pkgs.k8s.io](https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/) is strongly recommended and required in order to install Kubernetes versions released after September 13, 2023. The deprecated legacy repositories, and their contents, might be removed at any time in the future and without a further notice period. The new package repositories provide downloads for Kubernetes versions starting with v1.24.0.

Thanks and Regards,
Muthukumar Subramaniam

**Comment by yogesit** [comment]
I have tried the same, but obtaining following error...

[root@illchn-static-203 ~]# sudo setenforce 0
[root@illchn-static-203 ~]# 
[root@illchn-static-203 ~]# sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
[root@illchn-static-203 ~]# 
[root@illchn-static-203 ~]# cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
> [kubernetes]
> name=Kubernetes
> baseurl=https://pkgs.k8s.io/core:/stable:/v1.31/rpm/
> enabled=1
> gpgcheck=1
> gpgkey=https://pkgs.k8s.io/core:/stable:/v1.31/rpm/repodata/repomd.xml.key
> exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
> EOF
[kubernetes]
name=Kubernetes
baseurl=https://pkgs.k8s.io/core:/stable:/v1.31/rpm/
enabled=1
gpgcheck=1
gpgkey=https://pkgs.k8s.io/core:/stable:/v1.31/rpm/repodata/repomd.xml.key
exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
[root@illchn-static-203 ~]# 
[root@illchn-static-203 ~]# 
[root@illchn-static-203 ~]# sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
Updating Subscription Management repositories.

This system is registered with an entitlement server, but is not receiving updates. You can use subscription-manager to assign subscriptions.

Kubernetes                                                                                                                          0.0  B/s |   0  B     01:09    
Errors during downloading metadata for repository 'kubernetes':
  - Curl error (28): Timeout was reached for https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.31/rpm/repodata/repomd.xml [Connection timed out after 30757 milliseconds]
  - Curl error (7): Couldn't connect to server for https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.31/rpm/repodata/repomd.xml [Failed to connect to prod-cdn.packages.k8s.io port 443: Network is unreachable]
Error: Failed to download metadata for repo 'kubernetes': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
[root@illchn-static-203 ~]#

**Comment by yogesit** [comment]
Hello Team - I have tried the following steps... but still facing the same
issue...

***@***.*** ~]# sudo setenforce 0
***@***.*** ~]#
***@***.*** ~]# sudo sed -i
's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
***@***.*** ~]#
***@***.*** ~]# cat <<EOF | sudo tee
/etc/yum.repos.d/kubernetes.repo
> [kubernetes]
> name=Kubernetes
> baseurl=https://pkgs.k8s.io/core:/stable:/v1.31/rpm/
> enabled=1
> gpgcheck=1
> gpgkey=https://pkgs.k8s.io/core:/stable:/v1.31/rpm/repodata/repomd.xml.key
> exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
> EOF
[kubernetes]
name=Kubernetes
baseurl=https://pkgs.k8s.io/core:/stable:/v1.31/rpm/
enabled=1
gpgcheck=1
gpgkey=https://pkgs.k8s.io/core:/stable:/v1.31/rpm/repodata/repomd.xml.key
exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
***@***.*** ~]#
***@***.*** ~]#
***@***.*** ~]# sudo yum install -y kubelet kubeadm kubectl
--disableexcludes=kubernetes
Updating Subscription Management repositories.

This system is registered with an entitlement server, but is not receiving
updates. You can use subscription-manager to assign subscriptions.

Kubernetes
                                                        0.0  B/s |   0  B
   01:09
Errors during downloading metadata for repository 'kubernetes':
  - Curl error (28): Timeout was reached for
https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.31/rpm/repodata/repomd.xml
[Connection timed out after 30757 milliseconds]
  - Curl error (7): Couldn't connect to server for
https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.31/rpm/repodata/repomd.xml
[Failed to connect to prod-cdn.packages.k8s.io port 443: Network is
unreachable]
Error: Failed to download metadata for repo 'kubernetes': Cannot download
repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
***@***.*** ~]#

**Comment by xmudrii** [comment]
@yogesit This appears to be some issue with you environment and the network configuration. Please make sure that access to pkgs.k8s.io and prod-cdn.packages.k8s.io is not blocked on your side. The repos are working and we don't have any other reports at the moment.

**Comment by Muthukumar-Subramaniam** [comment]
@yogesit Its clearly some issue with network connection or firewall is blocking the connection to the repository.
We do regular installation from this official source and we don't have any issues.
