### ISSUE TITLE
Configuring Nodes to Authenticate to a Private Repository

### ISSUE THREAD

**Issue by preillyme** [kubernetes/kubernetes#12835]
```
# docker --version
Docker version 1.6.2-cs5, build 6f88399
```

```
# docker pull dtr.k8s.co/kismatic/oracle-java7:latest
latest: Pulling from dtr.k8s.co/kismatic/oracle-java7

6d370c930acc: Downloading [==========>                                        ] 14.27 MB/68.32 MB
9a63f1e91c4c: Download complete
74364530838d: Download complete
dce38fb57986: Download complete
3c5086cea6ef: Download complete
600f1ea88e8c: Download complete
280e22001ea6: Download complete
9ca2f7e6931b: Downloading [=================================>                 ] 13.79 MB/20.69 MB
f3dae0c260f1: Download complete
1ce61cd2dcad: Downloading [==>                                                ] 15.87 MB/317.4 MB
```

But with:

```
# cat /tmp/private-image-test-1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: private-image-test-1
spec:
  containers:
    - name: uses-private-image
      image: dtr.k8s.co/kismatic/oracle-java7
      command: [ "echo", "SUCCESS" ]
  imagePullPolicy: Always

We see the following

# kubectl describe pods/private-image-test-1 | grep "Failed"
  Mon, 17 Aug 2015 18:29:42 +0000       Mon, 17 Aug 2015 18:30:42 +0000 7       {kubelet 172.31.26.97}  spec.containers{uses-private-image}   failed          Failed to pull image "dtr.k8s.co/kismatic/oracle-java7": image pull failed for dtr.k8s.co/kismatic/oracle-java7, this may be because there are no credentials on this request.  details: (Error: image kismatic/oracle-java7:latest not found)
 ```

Also worth mentioning that:

  ```
# cat /root/.dockercfg
{
        "dtr.k8s.co": {
                "auth": "cGF0***************IB5+",
                "email": "patrick@kismatic.com"
        }
```
exists and works as root directly.

and

```
# ps aux | grep 'kubelet'
root      1077  1.0  0.5 350656 43432 ?        Ssl  Aug13  55:10 /opt/bin/kubelet --address=172.31.17.60 --port=10250 --hostname_override=172.31.17.60 --api_servers=172.31.17.60:8080 --logtostderr=false --log_dir=/var/log/kubernetes
```

**Comment by bgrant0607** [comment]
@preillyme Have you tried imagePullSecrets?
http://kubernetes.io/v1.0/docs/user-guide/production-pods.html#authenticating-with-a-private-image-registry

**Comment by lachie83** [comment]
@bgrant0607 - Yes. I can confirm using imagePullSecrets yields the same error message.

**Comment by preillyme** [comment]
@bgrant0607 — putting the .dockercfg file into a secret resource did the trick it's now working.
```
Tue, 18 Aug 2015 07:39:24 +0000       Tue, 18 Aug 2015 07:39:24 +0000 1       {kubelet 172.31.26.97}  spec.containers{uses-private-image}     started         Started with docker id afd01879bfb4
```
Thanks! This documentation http://kubernetes.io/v1.0/docs/user-guide/images.html#using-a-private-registry should probably be updated as well.

**Comment by preillyme** [comment]
@lachie83 it's working for me with the following:
```
# cat /tmp/image-pull-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockercfg: ewo**********=
type: kubernetes.io/dockercfg
```

and 

```
kubectl create -f /tmp/image-pull-secret.yaml
```

```
# cat /tmp/private-image-test-1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: private-image-test-1
spec:
  containers:
    - name: uses-private-image
      image: dtr.k8s.co/kismatic/oracle-java7
      command: [ "echo", "SUCCESS" ]
  imagePullPolicy: Always
  imagePullSecrets:
    - name: myregistrykey
```

**Comment by lachie83** [comment]
@preillyme Still not working for me. Can you share the format of your .dockercfg. Are you sure you didn't manually pull the image on the node during testing?

Here's something interesting I'm seeing when running a --validate
```
docker run -it --rm --volumes-from data levenson/kubectl --validate create -f /data/cloudops-skd-doc-demo-pod.json
I0818 14:29:19.393067       1 schema.go:126] unknown field: imagePullSecrets
I0818 14:29:19.393236       1 schema.go:129] this may be a false alarm, see https://github.com/GoogleCloudPlatform/kubernetes/issues/6842
pods/cloudops-skd-doc-demo
```

**Comment by preillyme** [comment]
@lachie83 I've confirmed it again. Seems to be working now.

**Comment by lachie83** [comment]
Yes - I was about to get this working. The trick was in the --validate. I had imagePullSecrets under the wrong section of the Pod Spec.

**Comment by preillyme** [comment]
Okay I'm glad it's fixed now @lachie83

**Comment by stephanlindauer** [comment]
however that solution is a per-deployment solution and not per-node or per-cluster. 
i feel like having a setting like that on cluster level would ease the pain of using private registries a lot.

**Comment by discordianfish** [comment]
I'm running kubelet in standalone and need to pull a image from a private registry. Since the kubelet standalone can't use secrets, I followed https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-repository to configure /root/.docker/config.json. Same as OP, I can manually pull images with docker but kubelet still fails to pull the image with `denied: access forbidden`.

Are the docs simply outdated and this way doesn't work anymore?

**Comment by marcofranssen** [comment]
@discordianfish I am experiencing the same issue. All my nodes do contain the /root/.docker/config.json file. I have also tried creating a secret to solve the issue. However this also doesn't work.

When I pull the image from the console everything works fine. So it seems to be really kubernetes related.

**Comment by discordianfish** [comment]
Yes, something is fishy here. I've got it working with manually creating the .docker/config.json, but then somehow it stopped working. Still investigating this.

**Comment by discordianfish** [comment]
It looks like I can reliably fix the issue by restarting kubelet.. But the first time it comes up, even though `/root/.docker/config.json` exists before that, I get the access forbidden errors.

**Comment by discordianfish** [comment]
Ha, okay. I wasn't restarting it, I started it manually for debugging and it works - because I was in a different working directory.
Seems like kubelet is looking in the current working directory for `.docker/config.json`. I've moved my config to `/var/lib/kubelet` and set that as working directory.

So the documentation is slightly wrong. It says: 
```
Docker stores keys for private registries in the $HOME/.dockercfg or $HOME/.docker/config.json file. If you put this in the $HOME of user root on a kubelet, then docker will use it.
```
First of all, I don't think Docker does anything with the file. It's kubelet which reads that file and uses it when talking to the Docker API, correct?
But either way, it's *not* the HOME directory of the kubelet user but the working directory.

**Comment by holygits** [comment]
I struggled with this one, turns out I had to specify the `--docker-server` flag in the secret or it would just fail.
e.g.
```bash
kubectl create secret docker-registry myregistrykey \
  --docker-server=$DOCKER_REGISTRY_SERVER \
  --docker-username=$DOCKER_USER \
  --docker-password=$DOCKER_PASSWORD \
  --docker-email=$DOCKER_EMAIL
```

**Comment by aysark** [comment]
Running into this issue as well.. docs seem dated.  I'm able to successfully pull images when in minikube.

**Comment by renukamanavalan** [comment]
Thank you, discordianfish!

I am running kubelet in standalone mode. This way, I could pass secret w/o requiring k8s control plane.

BTW, does anyone know, how to put secret directly into pod definition/manifest itself.
