### ISSUE TITLE
NUMA-aware memory manager and Topology Manager policy of "restricted" results in TopologyAffinityError when it shouldn't

### ISSUE THREAD

**Issue by cbf123** [kubernetes/kubernetes#128669]
### What happened?

Running K8s 1.29.2, with the kubelet NUMA-aware memory manager policy set to "Static" and the Topology Manager policy set to "restricted".

1. The /var/lib/kubelet/memory_manager_state file shows:

```
[sysadmin@controller-0 pods(keystone_admin)]$ sudo cat /var/lib/kubelet/memory_manager_state
Password:
{"policyName":"Static","machineState":{"0":{"numberOfAssignments":0,"memoryMap":{"hugepages-1Gi":{"total":10737418240,"systemReserved":0,"allocatable":10737418240,"reserved":0,"free":10737418240},"hugepages-2Mi":{"total":0,"systemReserved":0,"allocatable":0,"reserved":0,"free":0},"memory":{"total":99759243264,"systemReserved":10538188800,"allocatable":78483636224,"reserved":0,"free":78483636224}},"cells":[0]},"1":{"numberOfAssignments":0,"memoryMap":{"hugepages-1Gi":{"total":10737418240,"systemReserved":0,"allocatable":10737418240,"reserved":0,"free":10737418240},"hugepages-2Mi":{"total":0,"systemReserved":0,"allocatable":0,"reserved":0,"free":0},"memory":{"total":99283886080,"systemReserved":1101004800,"allocatable":87445463040,"reserved":0,"free":87445463040}},"cells":[1]}},"checksum":2552710201}[sysadmin@controller-0 pods(keystone_admin)]$ 
```

2. Created a pod kube-mgrr-1, then checked pod status and memory_manager_state file content

```
[sysadmin@controller-0 pods(keystone_admin)]$ cat test-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: kube-mgrr-1
  labels:
    app.starlingx.io/component: 'application'
spec:
  containers:
  - image: "gcr.io/kubernetes-e2e-test-images/resource-consumer:1.4"
    imagePullPolicy: IfNotPresent
    name: kube-mgrr-1
    resources:
      limits:
        memory: 256Mi
        cpu: '200m'
      requests:
        memory: 256Mi
        cpu: '200m'
  nodeSelector:
    kubernetes.io/hostname: controller-0

[sysadmin@controller-0 pods(keystone_admin)]$ kubectl get pods
NAME          READY   STATUS    RESTARTS   AGE
kube-mgrr-1   1/1     Running   0          7s

[sysadmin@controller-0 pods(keystone_admin)]$ sudo cat /var/lib/kubelet/memory_manager_state
{"policyName":"Static","machineState":{"0":{"numberOfAssignments":1,"memoryMap":{"hugepages-1Gi":{"total":10737418240,"systemReserved":0,"allocatable":10737418240,"reserved":0,"free":10737418240},"hugepages-2Mi":{"total":0,"systemReserved":0,"allocatable":0,"reserved":0,"free":0},"memory":{"total":99759243264,"systemReserved":10538188800,"allocatable":78483636224,"reserved":268435456,"free":78215200768}},"cells":[0]},"1":{"numberOfAssignments":0,"memoryMap":{"hugepages-1Gi":{"total":10737418240,"systemReserved":0,"allocatable":10737418240,"reserved":0,"free":10737418240},"hugepages-2Mi":{"total":0,"systemReserved":0,"allocatable":0,"reserved":0,"free":0},"memory":{"total":99283886080,"systemReserved":1101004800,"allocatable":87445463040,"reserved":0,"free":87445463040}},"cells":[1]}},"entries":{"84accdfa-8263-4672-9bfe-2ffd93427666":{"kube-mgrr-1":[{"numaAffinity":[0],"type":"memory","size":268435456}]}},"checksum":989528933}[sysadmin@controller-0 pods(keystone_admin)]$ 
```

3.  Created a new pod which exceeds memory of NUMA node 0 and check if the pod is pinned to both NUMA nodes.

```
[sysadmin@controller-0 pods(keystone_admin)]$ cat test-pod_2.yaml
apiVersion: v1
kind: Pod
metadata:
  name: kube-mgrr-2
  labels:
    app.starlingx.io/component: 'application'
spec:
  containers:
  - image: "gcr.io/kubernetes-e2e-test-images/resource-consumer:1.4"
    imagePullPolicy: IfNotPresent
    name: kube-mgrr-2
    resources:
      limits:
        memory: 85Gi
        cpu: '200m'
      requests:
        memory: 85Gi
        cpu: '200m'
  nodeSelector:
    kubernetes.io/hostname: controller-0

[sysadmin@controller-0 pods(keystone_admin)]$ kubectl apply -f test-pod_2.yaml 
pod/kube-mgrr-2 created 

[sysadmin@controller-0 pods(keystone_admin)]$ kubectl get pods NAME          READY   STATUS    RESTARTS   AGE kube-mgrr-1   1/1     Running   0          109s kube-mgrr-2   1/1     Running   0          3s 

[sysadmin@controller-0 pods(keystone_admin)]$ sudo cat /var/lib/kubelet/memory_manager_state {"policyName":"Static","machineState":{"0":{"numberOfAssignments":2,"memoryMap":{"hugepages-1Gi":{"total":10737418240,"systemReserved":0,"allocatable":10737418240,"reserved":0,"free":10737418240},"hugepages-2Mi":{"total":0,"systemReserved":0,"allocatable":0,"reserved":0,"free":0},"memory":{"total":99759243264,"systemReserved":10538188800,"allocatable":78483636224,"reserved":78483636224,"free":0}},"cells":[0,1]},"1":{"numberOfAssignments":1,"memoryMap":{"hugepages-1Gi":{"total":10737418240,"systemReserved":0,"allocatable":10737418240,"reserved":0,"free":10737418240},"hugepages-2Mi":{"total":0,"systemReserved":0,"allocatable":0,"reserved":0,"free":0},"memory":{"total":99283886080,"systemReserved":1101004800,"allocatable":87445463040,"reserved":13052854272,"free":74392608768}},"cells":[0,1]}},"entries":{"84accdfa-8263-4672-9bfe-2ffd93427666":{"kube-mgrr-1":[{"numaAffinity":[0],"type":"memory","size":268435456}]},"8e7262b9-c5ae-4b2e-a0b6-5dba8c4b6d64":{"kube-mgrr-2":[{"numaAffinity":[0,1],"type":"memory","size":91268055040}]}},"checksum":3041831511}
```

4. Delete kube-mgrr-1 pod

```
[sysadmin@controller-0 pods(keystone_admin)]$ kubectl delete -f test-pod.yaml
pod "kube-mgrr-1" deleted
[sysadmin@controller-0 pods(keystone_admin)]$ kubectl get pods
NAME          READY   STATUS    RESTARTS   AGE
kube-mgrr-2   1/1     Running   0          49s
```
 
5. Add kube-mgrr-1 back . Pod status is TopologyAffinityError

```
[sysadmin@controller-0 pods(keystone_admin)]$ kubectl get pods
NAME          READY   STATUS                  RESTARTS   AGE
kube-mgrr-1   0/1     TopologyAffinityError   0          21m
kube-mgrr-2   1/1     Running                 0          22m
[sysadmin@controller-0 pods(keystone_admin)]$
 
[sysadmin@controller-0 pods(keystone_admin)]$ sudo cat /var/lib/kubelet/memory_manager_state
Password:
{"policyName":"Static","machineState":{"0":{"numberOfAssignments":1,"memoryMap":{"hugepages-1Gi":{"total":10737418240,"systemReserved":0,"allocatable":10737418240,"reserved":0,"free":10737418240},"hugepages-2Mi":{"total":0,"systemReserved":0,"allocatable":0,"reserved":0,"free":0},"memory":{"total":99759243264,"systemReserved":10538188800,"allocatable":78483636224,"reserved":78215200768,"free":268435456}},"cells":[0,1]},"1":{"numberOfAssignments":1,"memoryMap":{"hugepages-1Gi":{"total":10737418240,"systemReserved":0,"allocatable":10737418240,"reserved":0,"free":10737418240},"hugepages-2Mi":{"total":0,"systemReserved":0,"allocatable":0,"reserved":0,"free":0},"memory":{"total":99283886080,"systemReserved":1101004800,"allocatable":87445463040,"reserved":13052854272,"free":74392608768}},"cells":[0,1]}},"entries":{"5131157f-ca8a-4824-8fda-a57a4ceab719":{"kube-mgrr-2":[{"numaAffinity":[0,1],"type":"memory","size":91268055040}]}},"checksum":3733538882}
```

Note: if the topology manager policy is set to "best-effort" the request to respawn the Pod succeeds.

### What did you expect to happen?

When re-creating the pod that was killed, it should be able to start up again since there is enough memory available on a single node to satisfy the memory and CPU requests.

### How can we reproduce it (as minimally and precisely as possible)?

Set the memory manager policy to "Static" and topology manager policy to "restricted".   On a two-NUMA-node worker node create a smallish Pod in the Guaranteed QoS class that easily fits on one NUMA node worth of memory.  Create a second Pod in the Guaranteed QoS class with a big enough memory request that it cannot fit on one NUMA node.  Delete the first Pod.  After the memory freed up by the Pod deletion shows as available, attempt to recreate the first Pod.

### Kubernetes version

<details>

```console
sysadmin@controller-0:~$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```

</details>

### Cloud provider

<details>
Wind River Cloud Platform
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
sysadmin@controller-0:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux controller-0 6.6.0-1-rt-amd64 #1 SMP PREEMPT_RT StarlingX Debian 6.6.52-1.stx.95 (2024-10-31) x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ffromani** [comment]
Thanks for the report. We merged a fair bit of bugfixes in the 1.31 and 1.32 cycles. Does it reproduces also against current master?

**Comment by ffromani** [comment]
@Tal-or FYI

**Comment by cbf123** [comment]
I'm unable to test against current master.  I did spin up a VM to test 1.31.2 via minikube.  I had 8GB of allocatable memory on each of two NUMA nodes.  Key kubelet args were:

`-cpu-manager-policy=static --kube-reserved=memory=1Gi --memory-manager-policy=Static --reserved-cpus=0,4 --reserved-memory=0:memory=1Gi;1:memory=1Gi --system-reserved=memory=1Gi --topology-manager-policy=restricted`

I was able to create the first pod with 1cpu and 256Mi of memory, but when I tried to create the second pod with 1cpu and 9Gi of memory it errored out unexpectedly:

```
cfriesen@debian:~$ minikube kubectl -- get pod kube-mgrr-2 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"kube-mgrr-2","namespace":"default"},"spec":{"containers":[{"image":"gcr.io/kubernetes-e2e-test-images/resource-consumer:1.4","imagePullPolicy":"IfNotPresent","name":"kube-mgrr-2","resources":{"limits":{"cpu":1,"memory":"9Gi"}}}]}}
  creationTimestamp: "2024-11-08T19:34:55Z"
  name: kube-mgrr-2
  namespace: default
  resourceVersion: "1028"
  uid: 2e769357-b700-49fa-96dc-2416a0379cb9
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.4
    imagePullPolicy: IfNotPresent
    name: kube-mgrr-2
    resources:
      limits:
        cpu: "1"
        memory: 9Gi
      requests:
        cpu: "1"
        memory: 9Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-27rcb
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-27rcb
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  message: 'Pod was rejected: Allocate failed due to [memorymanager] failed to find
    NUMA nodes to extend the current topology hint, which is unexpected'
  phase: Failed
  reason: UnexpectedAdmissionError
  startTime: "2024-11-08T19:34:55Z"
```


Kubelet logs were:

Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.632981    2326 scope_container.go:75] "TopologyHints" hints={} pod="default/kube-mgrr-2" containerName="kube-mgrr-2"
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.633153    2326 policy_static.go:541] "TopologyHints generated" pod="default/kube-mgrr-2" containerName="kube-mgrr-2" cpuHints=[{"NUMANodeAffinity":1,"Preferred":true},{"NUMANodeAffinity":2,"Preferred":true},{"NUMANodeAffinity":3,"Preferred":false}]
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.633187    2326 scope_container.go:75] "TopologyHints" hints={"cpu":[{"NUMANodeAffinity":1,"Preferred":true},{"NUMANodeAffinity":2,"Preferred":true},{"NUMANodeAffinity":3,"Preferred":false}]} pod="default/kube-mgrr-2" containerName="kube-mgrr-2"
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.633254    2326 scope_container.go:75] "TopologyHints" hints={} pod="default/kube-mgrr-2" containerName="kube-mgrr-2"
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.633276    2326 policy.go:71] "Hint Provider has no preference for NUMA affinity with any resource"
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.633289    2326 policy.go:71] "Hint Provider has no preference for NUMA affinity with any resource"
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.633304    2326 scope_container.go:83] "ContainerTopologyHint" bestHint={"NUMANodeAffinity":1,"Preferred":true}
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.633330    2326 scope_container.go:50] "Best TopologyHint" bestHint={"NUMANodeAffinity":1,"Preferred":true} pod="default/kube-mgrr-2" containerName="kube-mgrr-2"
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.633342    2326 scope_container.go:56] "Topology Affinity" bestHint={"NUMANodeAffinity":1,"Preferred":true} pod="default/kube-mgrr-2" containerName="kube-mgrr-2"
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.633391    2326 policy_static.go:303] "Static policy: Allocate" pod="default/kube-mgrr-2" containerName="kube-mgrr-2"
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.633407    2326 policy_static.go:352] "Topology Affinity" pod="default/kube-mgrr-2" containerName="kube-mgrr-2" affinity={"NUMANodeAffinity":1,"Preferred":true}
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.633421    2326 policy_static.go:392] "AllocateCPUs" numCPUs=1 socket="01"
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.633496    2326 state_mem.go:88] "Updated default CPUSet" cpuSet="0,3-7"
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.635778    2326 policy_static.go:424] "AllocateCPUs" result="2"
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.635830    2326 state_mem.go:80] "Updated desired CPUSet" podUID="2e769357-b700-49fa-96dc-2416a0379cb9" containerName="kube-mgrr-2" cpuSet="2"
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.638325    2326 policy_static.go:106] "Allocate" pod="default/kube-mgrr-2" containerName="kube-mgrr-2"
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.638367    2326 policy_static.go:123] "Got topology affinity" pod="default/kube-mgrr-2" podUID="2e769357-b700-49fa-96dc-2416a0379cb9" containerName="kube-mgrr-2" hint={"NUMANodeAffinity":1,"Preferred":true}
Nov 08 19:34:55 minikube kubelet[2326]: E1108 19:34:55.638418    2326 memory_manager.go:257] "Allocate error" err="[memorymanager] failed to find NUMA nodes to extend the current topology hint"
Nov 08 19:34:55 minikube kubelet[2326]: I1108 19:34:55.638450    2326 kubelet.go:2306] "Pod admission denied" podUID="2e769357-b700-49fa-96dc-2416a0379cb9" pod="default/kube-mgrr-2" reason="UnexpectedAdmissionError" message="Allocate failed due to [memorymanager] failed to find NUMA nodes to extend the current topology hint, which is unexpected"

**Comment by cbf123** [comment]
NOTE: I modified the second pod to request '200m' worth of CPU rather than a whole CPU, and it passed.   This seems like a bug.

**Comment by cbf123** [comment]
I can confirm that the original issue still exists on 1.31.2.   Deleting and re-creating pod 1 results in kubelet logs as follows:

Nov 08 19:52:23 minikube kubelet[2326]: I1108 19:52:23.932365    2326 scope_container.go:75] "TopologyHints" hints={} pod="default/kube-mgrr-1" containerName="kube-mgrr-1"
Nov 08 19:52:23 minikube kubelet[2326]: I1108 19:52:23.932519    2326 policy_static.go:541] "TopologyHints generated" pod="default/kube-mgrr-1" containerName="kube-mgrr-1" cpuHints=[{"NUMANodeAffinity":1,"Preferred":true},{"NUMANodeAffinity":2,"Preferred":true},{"NUMANodeAffinity":3,"Preferred":false}]
Nov 08 19:52:23 minikube kubelet[2326]: I1108 19:52:23.932548    2326 scope_container.go:75] "TopologyHints" hints={"cpu":[{"NUMANodeAffinity":1,"Preferred":true},{"NUMANodeAffinity":2,"Preferred":true},{"NUMANodeAffinity":3,"Preferred":false}]} pod="default/kube-mgrr-1" containerName="kube-mgrr-1"
Nov 08 19:52:23 minikube kubelet[2326]: I1108 19:52:23.932605    2326 memory_manager.go:346] "RemoveStaleState removing state" podUID="8c0ccb88-cd3b-4a5d-acf4-ed8f3fa2a93a" containerName="kube-mgrr-1"
Nov 08 19:52:23 minikube kubelet[2326]: I1108 19:52:23.932624    2326 policy_static.go:249] "RemoveContainer" podUID="8c0ccb88-cd3b-4a5d-acf4-ed8f3fa2a93a" containerName="kube-mgrr-1"
Nov 08 19:52:23 minikube kubelet[2326]: I1108 19:52:23.936531    2326 state_mem.go:75] "Updated machine memory state"
Nov 08 19:52:23 minikube kubelet[2326]: I1108 19:52:23.941236    2326 scope_container.go:75] "TopologyHints" hints={"memory":[{"NUMANodeAffinity":3,"Preferred":false}]} pod="default/kube-mgrr-1" containerName="kube-mgrr-1"
Nov 08 19:52:23 minikube kubelet[2326]: I1108 19:52:23.941287    2326 policy.go:71] "Hint Provider has no preference for NUMA affinity with any resource"
Nov 08 19:52:23 minikube kubelet[2326]: I1108 19:52:23.941305    2326 scope_container.go:83] "ContainerTopologyHint" bestHint={"NUMANodeAffinity":3,"Preferred":false}
Nov 08 19:52:23 minikube kubelet[2326]: I1108 19:52:23.941317    2326 scope_container.go:50] "Best TopologyHint" bestHint={"NUMANodeAffinity":3,"Preferred":false} pod="default/kube-mgrr-1" containerName="kube-mgrr-1"
Nov 08 19:52:23 minikube kubelet[2326]: I1108 19:52:23.941357    2326 kubelet.go:2306] "Pod admission denied" podUID="9dd7dbe0-f3e5-4441-a112-20197f19ecac" pod="default/kube-mgrr-1" reason="TopologyAffinityError" message="Resources cannot be allocated with Topology locality"

**Comment by cbf123** [comment]
I opened a new issue to cover the failure to create the second pod when using an exclusive CPU.

**Comment by ffromani** [comment]
> I opened a new issue to cover the failure to create the second pod when using an exclusive CPU.

sure, thanks. I'd start investigating #128708 first. And correcting myself: the fixes I was hinting to we merged are in the 1.32 cycle.

**Comment by Andyhut2** [comment]
good job to make it great

**Comment by cbf123** [comment]
Based on the discussion at https://github.com/kubernetes/kubernetes/pull/123443 I think the original test setup here is actually invalid, since it has two pods, one of which is single-NUMA-node and one of which is cross-NUMA-node.

It seems like it should be possible in the testcase I describe to initially create the smaller Pod as a multi-NUMA-node Pod even though its resources could be provided by a single NUMA node.  That way we wouldn't artificially prevent the second larger Pod from being scheduled even though there is actually enough memory available for it.

I guess this issue is that we have to decide between preferring NUMA isolation or preferring allowing as many Pods as possible to run on a node even if their NUMA allocations aren't ideal.

**Comment by cbf123** [comment]
This seems to raise the interesting prospect of order-dependent Pod scheduling, where if we schedule a larger cross-NUMA-node Pod first and then a smaller Pod second it might allow both to be scheduled (with the smaller also configured as cross-NUMA-node).

But if the smaller one is scheduled first as a single NUMA-node Pod it would prevent the larger cross-NUMA-node Pod from being scheduled.

**Comment by Tal-or** [comment]
> This seems to raise the interesting prospect of order-dependent Pod scheduling, where if we schedule a larger cross-NUMA-node Pod first and then a smaller Pod second it might allow both to be scheduled (with the smaller also configured as cross-NUMA-node).
> 
> But if the smaller one is scheduled first as a single NUMA-node Pod it would prevent the larger cross-NUMA-node Pod from being scheduled.

Yes I agree. The rational behind it (capture in the Memory Manager's KEP) is that if one node is used for single NUMA-node allocation, somewhere else in the cluster there is a node that could use for a cross-NUMA-node allocations

**Comment by cbf123** [comment]
One problem with that rationale is that it basically means that you can't configure the NUMA-aware memory manager and a Topology Manager policy of "restricted" on a small K8s cluster where there may not be a free worker node available for cross-NUMA-node allocations.   We have quite a few single-K8s-node clusters out at the edge, for example.   So we either need to use "best-effort" Topology Manager policy or else turn off the NUMA-aware memory manager.

It'd be nice if we had a way to tell K8s how much memory a pod is allowed to allocate from each NUMA node, but I don't think Linux gives us that level of control via cgroups and numactl.

**Comment by ffromani** [comment]
I'd be open and very interested in changing the behavior of memory manager, but this warrants a KEP change with the related process

**Comment by Tal-or** [comment]
Please check my [comment](https://github.com/kubernetes/kubernetes/issues/128708#issuecomment-2489591274) on the second issue.

I don't think that KEP changes is enough, because right now it's a kernel limitation.

**Comment by kannon92** [comment]
/remove-kind bug
/kind feature

Based on https://github.com/kubernetes/kubernetes/issues/128669#issuecomment-2503100218

**Comment by cbf123** [comment]
> Please check my [comment](https://github.com/kubernetes/kubernetes/issues/128708#issuecomment-2489591274) on the second issue why mixing of single and multi numa allocation is problematic.
> 
> I don't think that KEP changes is enough, because right now it's a kernel limitation.

I think we could add an option to always create pods as cross-NUMA even if they could in theory fit on a single NUMA node.  This would ensure that the scheduling of which pods can fit on a node is independent of the order that the pods are scheduled.  This would probably not make sense with the "single-numa-node" TopologyManager policy, but should work with all the others.

As it stands, we are order-dependent.  If we schedule a single-NUMA-node pod first then we won't allow a cross-numa pod to be created, but if we schedule a large cross-numa pod first we will create the smaller pod as a cross-numa pod.

**Comment by ffromani** [comment]
this is an interesting point indeed and I can see the value for this. Another option could be (better) integration with eviction manager, pods which need single-NUMA allocation should take precedence over pods spanning over multiple NUMA nodes (or the other way around?).
However a change like this would require socialization to gather the community interest, and a KEP process.
