### ISSUE TITLE
Patching doesn't work with pods with annotation based app armor configuration in Kubernets version 1.32

### ISSUE THREAD

**Issue by rickypeng99** [kubernetes/kubernetes#133416]
### What happened?

Patching doesn't work with pods with annotation based app armor configuration in Kubernets version 1.32

### What did you expect to happen?

I expect the patch to go through

### How can we reproduce it (as minimally and precisely as possible)?

This could be an issue before 1.32, but I only tested in 1.32.

If we have a pod that is still using the annotation based app armor profile, for example
```
 container.apparmor.security.beta.kubernetes.io/game-container: localhost/<profile-name>
```

and we run a simple kubectl patch command
```
kubectl patch pod test-pod \
-p '[{"op": "remove", "path": "/metadata/labels/gameSizeName"}]' \
--type=json
```

The request will fail with message (only showing the relevant part)
```
- 				AppArmorProfile: &core.AppArmorProfile{Type: "Localhost", LocalhostProfile: &"<profile-name>"},
+ 				AppArmorProfile: nil,
  			},
```
as if my patch is trying to remove the apparmor profile.

### Anything else we need to know?

I have tried patching the pod / deployment to onboard with the new apparmor profile. The edit went through but the resource didn't actually get updated with the appArmorProfile

I have raised another issue for this problem: https://github.com/kubernetes/kubectl/issues/1764

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.33.2
Kustomize Version: v5.6.0
Server Version: v1.32.5-eks-5d4a308
```

</details>

### Cloud provider

<details>
EKS
</details>

### OS version

<details>

```console
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac16,7
      Chip: Apple M4 Pro
      Total Number of Cores: 14 (10 performance and 4 efficiency)
      Memory: 48 GB
      System Firmware Version: 11881.121.1
      OS Loader Version: 11881.121.1
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by rickypeng99** [comment]
I suspect that this behavior has something to do the mechanism where we are syncing the deprecated annotation to the `appArmorProfile` field under `securityContext`, probably it's not doing this when we are doing patches?

**Comment by itzPranshul** [comment]
I believe the problem comes from how patching works with the new `securityContext.appArmorProfile` field  introduced in recent Kubernetes versions. What seems to be happening in 1.32 is that,  pod still uses the old annotation form for AppArmor so when we run `kubectl patch` to change something else, Kubernetes rebuilds the Pod spec internally using the new `securityContext.appArmorProfile` field. There is no step to copy the AppArmor value from the old annotation into the new field before calculating the diff, resulting in the Pod's internal version appearing to have no AppArmor profile. The diff logic treats this as a request to remove it.  In short, the backwards-compatibility logic that maps annotations to  `securityContext.appArmorProfile` is missing in the patch conversion flow

**Comment by Goend** [comment]
I can't reproduce it.
```
root@proxy-pass:~# kubectl  get pod test-fake -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/nginx-fake: localhost/cri-containerd.apparmor.d
  creationTimestamp: "2025-08-08T11:52:37Z"
  labels:
    xx: xx
  name: test-fake
  namespace: default
  resourceVersion: "8145"
  uid: 9ca1df6d-8d8f-4d41-8e0b-7dc17c2242b1
spec:
  containers:
  - image: docker.io/library/nginx:latest
    imagePullPolicy: IfNotPresent
    name: nginx-fake
    resources: {}
    securityContext:
      appArmorProfile:
        localhostProfile: cri-containerd.apparmor.d
        type: Localhost
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-cvvvw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: proxy-pass
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-cvvvw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```
patch a existed key
```
root@proxy-pass:~# ./kubectl patch pod test-fake -p '[{"op": "remove", "path": "/metadata/labels"}]' --type=json 
pod/test-fake patched

```
patch a non existed key again
```
root@proxy-pass:~# ./kubectl patch pod test-fake -p '[{"op": "remove", "path": "/metadata/labels"}]' --type=json 
The request is invalid: the server rejected our request due to an error in our request
```

if you remove annotation,you will get
```
root@proxy-pass:~# ./kubectl patch pod test-fake -p '[{"op": "remove", "path": "/metadata/annotations"}]' --type=json 
The Pod "test-fake" is invalid: metadata.annotations[container.apparmor.security.beta.kubernetes.io/nginx-fake]: Forbidden: may not remove or update AppArmor annotations
```


```
root@proxy-pass:~# ./kubectl version
Client Version: v1.33.2
Kustomize Version: v5.6.0
Server Version: v1.32.5

```

the pod which "If we have a pod that is still using the annotation based app armor profile (without the appArmorProfile field under securityContext),"  how to create?

**Comment by rickypeng99** [comment]
> I can't reproduce it.
> ```
> root@proxy-pass:~# kubectl  get pod test-fake -o yaml
> apiVersion: v1
> kind: Pod
> metadata:
>   annotations:
>     container.apparmor.security.beta.kubernetes.io/nginx-fake: localhost/cri-containerd.apparmor.d
>   creationTimestamp: "2025-08-08T11:52:37Z"
>   labels:
>     xx: xx
>   name: test-fake
>   namespace: default
>   resourceVersion: "8145"
>   uid: 9ca1df6d-8d8f-4d41-8e0b-7dc17c2242b1
> spec:
>   containers:
>   - image: docker.io/library/nginx:latest
>     imagePullPolicy: IfNotPresent
>     name: nginx-fake
>     resources: {}
>     securityContext:
>       appArmorProfile:
>         localhostProfile: cri-containerd.apparmor.d
>         type: Localhost
>     terminationMessagePath: /dev/termination-log
>     terminationMessagePolicy: File
>     volumeMounts:
>     - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
>       name: kube-api-access-cvvvw
>       readOnly: true
>   dnsPolicy: ClusterFirst
>   enableServiceLinks: true
>   nodeName: proxy-pass
>   preemptionPolicy: PreemptLowerPriority
>   priority: 0
>   restartPolicy: Always
>   schedulerName: default-scheduler
>   securityContext: {}
>   serviceAccount: default
>   serviceAccountName: default
>   terminationGracePeriodSeconds: 30
>   tolerations:
>   - effect: NoExecute
>     key: node.kubernetes.io/not-ready
>     operator: Exists
>     tolerationSeconds: 300
>   - effect: NoExecute
>     key: node.kubernetes.io/unreachable
>     operator: Exists
>     tolerationSeconds: 300
>   volumes:
>   - name: kube-api-access-cvvvw
>     projected:
>       defaultMode: 420
>       sources:
>       - serviceAccountToken:
>           expirationSeconds: 3607
>           path: token
>       - configMap:
>           items:
>           - key: ca.crt
>             path: ca.crt
>           name: kube-root-ca.crt
>       - downwardAPI:
>           items:
>           - fieldRef:
>               apiVersion: v1
>               fieldPath: metadata.namespace
>             path: namespace
> ```
> patch a existed key
> ```
> root@proxy-pass:~# ./kubectl patch pod test-fake -p '[{"op": "remove", "path": "/metadata/labels"}]' --type=json 
> pod/test-fake patched
> 
> ```
> patch a non existed key again
> ```
> root@proxy-pass:~# ./kubectl patch pod test-fake -p '[{"op": "remove", "path": "/metadata/labels"}]' --type=json 
> The request is invalid: the server rejected our request due to an error in our request
> ```
> 
> if you remove annotation,you will get
> ```
> root@proxy-pass:~# ./kubectl patch pod test-fake -p '[{"op": "remove", "path": "/metadata/annotations"}]' --type=json 
> The Pod "test-fake" is invalid: metadata.annotations[container.apparmor.security.beta.kubernetes.io/nginx-fake]: Forbidden: may not remove or update AppArmor annotations
> ```
> 
> 
> ```
> root@proxy-pass:~# ./kubectl version
> Client Version: v1.33.2
> Kustomize Version: v5.6.0
> Server Version: v1.32.5
> 
> ```
> 
> the pod which "If we have a pod that is still using the annotation based app armor profile (without the appArmorProfile field under securityContext),"  how to create?

My bad I should have made it clearer that to reproduce it, the pod should only have annotation to begin with (no appArmorProfile security context at the time). 

If it helps to reproduce exactly what we have, you can create a replica set deployment with a pod template that only contains the annotation.

Context is that we are upgrading our workloads in a 1.32 cluster where the workloads were still using the same template as what they have in a 1.29 cluster. So they only have the annotation.

**Comment by rickypeng99** [comment]
> I believe the problem comes from how patching works with the new `securityContext.appArmorProfile` field introduced in recent Kubernetes versions. What seems to be happening in 1.32 is that, pod still uses the old annotation form for AppArmor so when we run `kubectl patch` to change something else, Kubernetes rebuilds the Pod spec internally using the new `securityContext.appArmorProfile` field. There is no step to copy the AppArmor value from the old annotation into the new field before calculating the diff, resulting in the Pod's internal version appearing to have no AppArmor profile. The diff logic treats this as a request to remove it. In short, the backwards-compatibility logic that maps annotations to `securityContext.appArmorProfile` is missing in the patch conversion flow

Yes, I agree with that. Especially after looking at https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/strategy.go#L100

**Comment by itzPranshul** [comment]
I think the fix could be as simple as updating `PrepareForUpdate` to call `applyAppArmorVersionSkew(ctx, newPod)`. This would mirror the behaviour in `PrepareForCreate` and ensure that for every patch/update, the Pod is normalised from the old annotation form before the diff is calculated. That should prevent the AppArmor profile from being unintentionally removed.

**Comment by Goend** [comment]
I will try to reproduce this issue and submit a PR to fix it.
I think this fix is good, but we need to reproduce the scenario and ensure the issue is resolved.

> I think the fix could be as simple as updating `PrepareForUpdate` to call `applyAppArmorVersionSkew(ctx, newPod)`. This would mirror the behaviour in `PrepareForCreate` and ensure that for every patch/update, the Pod is normalised from the old annotation form before the diff is calculated. That should prevent the AppArmor profile from being unintentionally removed.

**Comment by Goend** [comment]
Kubernetes old version
```
root@proxy-pass:~# kubectl version
Client Version: v1.29.15
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.15
```
pod yaml
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/nginx-fake: localhost/cri-containerd.apparmor.d
  labels:
    app: test
    xx: xx
  name: test-fake
  namespace: default
spec:
  containers:
  - image: docker.io/library/nginx:latest
    imagePullPolicy: IfNotPresent
    name: nginx-fake
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: proxy-pass
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30


```

get pod with no appArmorProfile security context
```
root@proxy-pass:~# kubectl  apply -f pod 
pod/test-fake created
root@proxy-pass:~# kubectl  get pod
NAME                        READY   STATUS    RESTARTS   AGE
test-fake                   1/1     Running   0          5s
root@proxy-pass:~# kubectl  get pod test-fake -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/nginx-fake: localhost/cri-containerd.apparmor.d
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"container.apparmor.security.beta.kubernetes.io/nginx-fake":"localhost/cri-containerd.apparmor.d"},"labels":{"app":"test","xx":"xx"},"name":"test-fake","namespace":"default"},"spec":{"containers":[{"image":"docker.io/library/nginx:latest","imagePullPolicy":"IfNotPresent","name":"nginx-fake","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"nodeName":"proxy-pass","preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30}}
  creationTimestamp: "2025-08-12T05:40:12Z"
  labels:
    app: test
    xx: xx
  name: test-fake
  namespace: default
  resourceVersion: "9693"
  uid: 5612e477-77eb-4905-9485-4bc5ca8f78b2
spec:
  containers:
  - image: docker.io/library/nginx:latest
    imagePullPolicy: IfNotPresent
    name: nginx-fake
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-89fqs
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: proxy-pass
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
...
```

upgrade kube-apiserver to 1.32,then exec command
```
root@proxy-pass:~# ./kubectl patch pod test-fake  -p '[{"op": "remove", "path": "/metadata/labels/xx"}]' --type=json
pod/test-fake patched
root@proxy-pass:~# ./kubectl  get pod test-fake -o yaml|grep labels -A 2
...
  labels:
    app: test
  name: test-fake

```
version information
```
root@proxy-pass:~# ./kubectl version
Client Version: v1.33.2
Kustomize Version: v5.6.0
Server Version: v1.32.5
```
I still cannot reproduce the issue. We need to identify the root cause or scenario leading to this problem to gather more information.
@rickypeng99

**Comment by rickypeng99** [comment]
> Kubernetes old version
> 
> ```
> root@proxy-pass:~# kubectl version
> Client Version: v1.29.15
> Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
> Server Version: v1.29.15
> ```
> 
> pod yaml
> 
> ```
> apiVersion: v1
> kind: Pod
> metadata:
>   annotations:
>     container.apparmor.security.beta.kubernetes.io/nginx-fake: localhost/cri-containerd.apparmor.d
>   labels:
>     app: test
>     xx: xx
>   name: test-fake
>   namespace: default
> spec:
>   containers:
>   - image: docker.io/library/nginx:latest
>     imagePullPolicy: IfNotPresent
>     name: nginx-fake
>     resources: {}
>     terminationMessagePath: /dev/termination-log
>     terminationMessagePolicy: File
>   dnsPolicy: ClusterFirst
>   enableServiceLinks: true
>   nodeName: proxy-pass
>   preemptionPolicy: PreemptLowerPriority
>   priority: 0
>   restartPolicy: Always
>   schedulerName: default-scheduler
>   securityContext: {}
>   serviceAccount: default
>   serviceAccountName: default
>   terminationGracePeriodSeconds: 30
> ```
> 
> get pod with no appArmorProfile security context
> 
> ```
> root@proxy-pass:~# kubectl  apply -f pod 
> pod/test-fake created
> root@proxy-pass:~# kubectl  get pod
> NAME                        READY   STATUS    RESTARTS   AGE
> test-fake                   1/1     Running   0          5s
> root@proxy-pass:~# kubectl  get pod test-fake -o yaml
> apiVersion: v1
> kind: Pod
> metadata:
>   annotations:
>     container.apparmor.security.beta.kubernetes.io/nginx-fake: localhost/cri-containerd.apparmor.d
>     kubectl.kubernetes.io/last-applied-configuration: |
>       {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"container.apparmor.security.beta.kubernetes.io/nginx-fake":"localhost/cri-containerd.apparmor.d"},"labels":{"app":"test","xx":"xx"},"name":"test-fake","namespace":"default"},"spec":{"containers":[{"image":"docker.io/library/nginx:latest","imagePullPolicy":"IfNotPresent","name":"nginx-fake","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"nodeName":"proxy-pass","preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"default","serviceAccountName":"default","terminationGracePeriodSeconds":30}}
>   creationTimestamp: "2025-08-12T05:40:12Z"
>   labels:
>     app: test
>     xx: xx
>   name: test-fake
>   namespace: default
>   resourceVersion: "9693"
>   uid: 5612e477-77eb-4905-9485-4bc5ca8f78b2
> spec:
>   containers:
>   - image: docker.io/library/nginx:latest
>     imagePullPolicy: IfNotPresent
>     name: nginx-fake
>     resources: {}
>     terminationMessagePath: /dev/termination-log
>     terminationMessagePolicy: File
>     volumeMounts:
>     - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
>       name: kube-api-access-89fqs
>       readOnly: true
>   dnsPolicy: ClusterFirst
>   enableServiceLinks: true
>   nodeName: proxy-pass
>   preemptionPolicy: PreemptLowerPriority
>   priority: 0
>   restartPolicy: Always
>   schedulerName: default-scheduler
>   securityContext: {}
>   serviceAccount: default
>   serviceAccountName: default
>   terminationGracePeriodSeconds: 30
> ...
> ```
> 
> upgrade kube-apiserver to 1.32,then exec command
> 
> ```
> root@proxy-pass:~# ./kubectl patch pod test-fake  -p '[{"op": "remove", "path": "/metadata/labels/xx"}]' --type=json
> pod/test-fake patched
> root@proxy-pass:~# ./kubectl  get pod test-fake -o yaml|grep labels -A 2
> ...
>   labels:
>     app: test
>   name: test-fake
> ```
> 
> version information
> 
> ```
> root@proxy-pass:~# ./kubectl version
> Client Version: v1.33.2
> Kustomize Version: v5.6.0
> Server Version: v1.32.5
> ```
> 
> I still cannot reproduce the issue. We need to identify the root cause or scenario leading to this problem to gather more information. [@rickypeng99](https://github.com/rickypeng99)

Thanks for taking a look. To completely align on everything, my pod was created by a `Deployment`. Not sure if this will bring any difference.

So something like
```
template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/<container>: localhost/<profile_name>
```

I just tried to patch the pod again, but still receiving the same error as above.

**Comment by Goend** [comment]
Are you patching the Pods under the Deployment, or the Deployment configuration itself? Additionally, did you only modify the Pod's labels?

**Comment by rickypeng99** [comment]
I am patching the pod under the deployment. And yes the command that I used was a simple
```
kubectl patch pod <pod_name> -p '[{"op": "remove", "path": "/metadata/labels/<label>"}]' --type=json


<omit other lines>
-                              AppArmorProfile: &core.AppArmorProfile{Type: "Localhost", LocalhostProfile: &"<profile>"},
+                              AppArmorProfile: nil,
```

Directly patching the deployment template is fine
```
kubectl patch deployment <deployment> -p '[{"op": "remove", "path": "/spec/template/metadata/labels/<label>"}]' --type=json
Warning: spec.template.metadata.annotations[container.apparmor.security.beta.kubernetes.io/<container>]: deprecated since v1.30; use the "appArmorProfile" field instead
deployment.apps/<deployment> patched
```
But I can't add the appArmorProfile in using `patch`
```
➜  ~ kubectl patch deployment <deployment> \
  --type strategic \
  -p '{
    "spec": {
      "template": {
        "spec": {
          "containers": [{
            "name": "<container>",
            "securityContext": {
              "appArmorProfile": {
                "type": "Localhost",
                "localhostProfile": "<profile?"
              }
            }
          }]
        }
      }
    }
  }'

deployment.apps/<deployment> patched
```
However if I describe the deployment again, nothing was updated. I raised another issue for this: https://github.com/kubernetes/kubectl/issues/1764

**Comment by Goend** [comment]
Could you fully display the complete YAML of both the Pod you patched and the Deployment configuration? additionally, could you provide a full demonstration of the patching process for a Pod under a Deployment, exactly as I did above? have any custom webhooks or other extension mechanisms been deployed in the cluster?

**Comment by rickypeng99** [comment]
Thanks for the pointers, looks like by deleting an EKS addon that AWS provided (it will bring along a couple webhooks). The issue is then resolved. I will dive deeper into the underlying root cause, but thanks again for helping out.

The main reason why I was thinking of the problem of k8s itself, was due to the fact that I was upgrading our cluster versions.

**Comment by Goend** [comment]
So after the AWS-provided EKS plugin was removed, the patch pod operation could succeed, right?
As for kubernetes/kubectl#1764,  It seems a bit like a controller issue, and it might not be directly related to the CLI itself. I’ll need to look into the code further.

**Comment by rickypeng99** [comment]
Yes, the patch pod operation is working now.
