### ISSUE TITLE
Regression: identical writes to storage interface are not ignored

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#16076]
Historically, a write to etcd that did not change content (existing content == new content on CAS) would not result in a watch event.  At some point between last year and now, that changed, and identical object writes via the etcd storage result in multiple watch events.  This is bad for several reasons - bad controller loops can flood the event logs trying to write the same data, clients are unnecessarily taxed, etc.

Opening this to ensure it gets tracked down - we saw this in openshift/origin#5275.  This could be a 1.1 blocker.

UPDATE: Caused because we started serializing the resource version of the persisted object to the store, which we used to not do.  The version in the store was 1 off from the version we would write (because we return the resource version that someone should watch from), which meant that the objects were different as serialized.

**Comment by smarterclayton** [comment]
Seeing this on etcd 2.1.2 and latest master.

**Comment by yichengq** [comment]
@smarterclayton I think this is not the problem of etcd part.

I have tried to do this in etcd 0.4, which is the first minor version that k8s uses, and it always results in one watch event as etcd 2.1.2 does for `existing content == new content on CAS` request.

**Comment by smarterclayton** [comment]
Ok - then we may have broken this during the refactor of storage.

**Comment by smarterclayton** [comment]
The check

```
if string(data) == origBody {
return nil
}
```

should omit changes.  It's possible we no longer output in a deterministic
order? @wojtek-t would ugorji serialization have resulted in
non-deterministic body output?

**Comment by wojtek-t** [comment]
@smarterclayton - we are still using ugorji only for unmarshaling - marshaling is still done using encoding/json. So this can't be serialization.
Regarding deserialization, I think it is deterministic (i.e. I didn't observe problems), but we may want to double check it.

**Comment by smarterclayton** [comment]
I'll try to add a test in the next few days.  I fixed this very early on in
Kube development (specifically) but the test's for it may have atrophied,
or we have whitespace variation, or something.

**Comment by lavalamp** [comment]
P1 to figure out if it's a regression.

**Comment by smarterclayton** [comment]
This line:
https://github.com/kubernetes/kubernetes/blob/848fed8f4b811d7343d2b012708820817826837e/pkg/storage/etcd/etcd_helper.go#L474

used to defend against the same resource being written multiple times with
no content change.

**Comment by smarterclayton** [comment]
Before, maps had deterministic order from encoding/json.  Is it true that
they still do under ugorji?

**Comment by wojtek-t** [comment]
@smarterclayton 
As I mentioned before, we are still NOT using ugorji for encoding - we just use it for decoding.
So I strongly believer this is not the reason here.

**Comment by lavalamp** [comment]
@smarterclayton Is this still an issue?

**Comment by smarterclayton** [comment]
We suspect we are seeing this in production workloads at this very moment,
still looking for reproduction.  Extremely high etcd change (so that
watches are getting 401'd due to expired index soon after list) in steady
state systems.  We've been trying to get a recreation.  I asked someone
yesterday to try and reproduce but haven't hit it yet.

On Dec 4, 2015, at 7:24 PM, Daniel Smith <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> Is this still an issue?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/16076#issuecomment-162116884>
.

**Comment by smarterclayton** [comment]
Found it:

```
I0102 23:14:56.204700   50786 etcd_helper.go:477] guaranteed update:
old: {"kind":"ImageStream","apiVersion":"v1","metadata":{"name":"mysql","namespace":"default","selfLink":"/oapi/v1/namespaces/default/imagestreams/mysql","uid":"d8d9ae56-b1c5-11e5-b451-7831c1b76042","resourceVersion":"1727","generation":11,"creationTimestamp":"2016-01-03T02:58:20Z","annotations":{"openshift.io/image.dockerRepositoryCheck":"tag \"5.4\" has not been set on repository \"library/mysql\""}},"spec":{"tags":[{"name":"5.4","from":{"kind":"DockerImage","name":"library/mysql:5.4"},"generation":11},{"name":"5.5","from":{"kind":"DockerImage","name":"library/mysql:5.5"},"generation":10},{"name":"5.6","from":{"kind":"DockerImage","name":"library/mysql:5.6"},"generation":9},{"name":"latest","from":{"kind":"DockerImage","name":"library/mysql:latest"},"generation":8}]},"status":{"dockerImageRepository":"","tags":[{"tag":"5.5","items":[{"created":"2016-01-03T04:05:48Z","dockerImageReference":"docker.io/library/mysql@sha256:b2231a45cc9e1855b37f078f1618ddb9462b4d286075e3f6c41f6221495b2759","image":"sha256:b2231a45cc9e1855b37f078f1618ddb9462b4d286075e3f6c41f6221495b2759","generation":11}]},{"tag":"5.6","items":[{"created":"2016-01-03T03:58:06Z","dockerImageReference":"docker.io/library/mysql@sha256:19521c36db34258c6a8ae4f3f2d8f0faf9bb3701be50981ce1c72db03bfa97e4","image":"sha256:19521c36db34258c6a8ae4f3f2d8f0faf9bb3701be50981ce1c72db03bfa97e4","generation":11}]},{"tag":"latest","items":[{"created":"2016-01-03T02:58:25Z","dockerImageReference":"docker.io/library/mysql@sha256:54c7cf6e7dfd6bfcc520b4ed2802d47fed0eccc5329c205b1c503e04ffc454ba","image":"sha256:54c7cf6e7dfd6bfcc520b4ed2802d47fed0eccc5329c205b1c503e04ffc454ba","generation":11}]}]}}

new: {"kind":"ImageStream","apiVersion":"v1","metadata":{"name":"mysql","namespace":"default","selfLink":"/oapi/v1/namespaces/default/imagestreams/mysql","uid":"d8d9ae56-b1c5-11e5-b451-7831c1b76042","resourceVersion":"1728","generation":11,"creationTimestamp":"2016-01-03T02:58:20Z","annotations":{"openshift.io/image.dockerRepositoryCheck":"tag \"5.4\" has not been set on repository \"library/mysql\""}},"spec":{"tags":[{"name":"5.4","from":{"kind":"DockerImage","name":"library/mysql:5.4"},"generation":11},{"name":"5.5","from":{"kind":"DockerImage","name":"library/mysql:5.5"},"generation":10},{"name":"5.6","from":{"kind":"DockerImage","name":"library/mysql:5.6"},"generation":9},{"name":"latest","from":{"kind":"DockerImage","name":"library/mysql:latest"},"generation":8}]},"status":{"dockerImageRepository":"","tags":[{"tag":"5.5","items":[{"created":"2016-01-03T04:05:48Z","dockerImageReference":"docker.io/library/mysql@sha256:b2231a45cc9e1855b37f078f1618ddb9462b4d286075e3f6c41f6221495b2759","image":"sha256:b2231a45cc9e1855b37f078f1618ddb9462b4d286075e3f6c41f6221495b2759","generation":11}]},{"tag":"5.6","items":[{"created":"2016-01-03T03:58:06Z","dockerImageReference":"docker.io/library/mysql@sha256:19521c36db34258c6a8ae4f3f2d8f0faf9bb3701be50981ce1c72db03bfa97e4","image":"sha256:19521c36db34258c6a8ae4f3f2d8f0faf9bb3701be50981ce1c72db03bfa97e4","generation":11}]},{"tag":"latest","items":[{"created":"2016-01-03T02:58:25Z","dockerImageReference":"docker.io/library/mysql@sha256:54c7cf6e7dfd6bfcc520b4ed2802d47fed0eccc5329c205b1c503e04ffc454ba","image":"sha256:54c7cf6e7dfd6bfcc520b4ed2802d47fed0eccc5329c205b1c503e04ffc454ba","generation":11}]}]}}
```

The new resource version we are writing is one value ahead of the existing object.  We used to clear storage version in etcd, looks like we've regressed.

**Comment by smarterclayton** [comment]
Clearing the resource version just prior to encoding the object from etcd_helpers.go is almost certainly the correct behavior.  That will mean that resources that have the resource version set in the storage version will fail a CAS.

**Comment by smarterclayton** [comment]
If we do that guaranteed update needs to get the proper "last good state" and return it (as well as set the resource version back).

**Comment by smarterclayton** [comment]
@kubernetes/rh-cluster-infra

**Comment by smarterclayton** [comment]
@lavalamp as discussed on Thursday

**Comment by smarterclayton** [comment]
We may also be letting selfLink get set down into etcd.  That's also inconsistent (in the event the same resource is exposed via multiple paths, two clients can fight over which object they're updating).

**Comment by lavalamp** [comment]
This seems like a major regression that we need to fix ASAP and add a test. I will fix it myself unless one of @caesarxuchao, @nikhiljindal, or @krousey have time?

**Comment by smarterclayton** [comment]
I may have time this week but I'm not sure.

**Comment by wojtek-t** [comment]
Has this been fixed (sorry I was on paternity leave for last month)?
Do you need any help with this?

**Comment by smarterclayton** [comment]
I have not yet broken free - it's a 1.2 blocker for me though.

On Wed, Feb 3, 2016 at 6:33 AM, Wojciech Tyczynski <notifications@github.com

**Comment by lavalamp** [comment]
I agree we should fix for 1.2 if possible. @wojtek-t if you have cycles, feel free to steal this from me.

**Comment by wojtek-t** [comment]
I will try to look into it tomorrow.

**Comment by lavalamp** [comment]
Thanks a bunch.

**Comment by wojtek-t** [comment]
Looking into it now

**Comment by wojtek-t** [comment]
OK - I'm able to reproduce it with a unit test and I think I understand what is happening there. I will try to create a fix for it.

**Comment by wojtek-t** [comment]
@smarterclayton @lavalamp - PR is out for review

**Comment by bgrant0607** [comment]
cc @madhusudancs
