### ISSUE TITLE
interactive run "Unrecognized input header"

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#16670]
Something is not happy taking extra args.  @ncdc 

```
thockin@freakshow kubernetes master /$ kubectl run date -i --tty --restart=Never --image=busybox --; kubectl delete pod date
Waiting for pod default/date to be running, status is Pending, pod ready: false

/ # 
/ # pod "date" deleted
```

```
thockin@freakshow kubernetes master /$ kubectl run date -i --tty --restart=Never --image=busybox -- /bin/sh; kubectl delete pod date
Waiting for pod default/date to be running, status is Pending, pod ready: false

/ # /bin/date
Mon Nov  2 16:19:56 UTC 2015
/ # pod "date" deleted
```

```
thockin@freakshow kubernetes master /$ kubectl run date -i --tty --restart=Never --image=busybox -- /bin/date; kubectl delete pod date
Waiting for pod default/date to be running, status is Pending, pod ready: false
Error attaching, falling back to logs: error executing remote command: Error executing command in container: container not found ("date")
Error from server: Internal error occurred: Unrecognized input header
pod "date" deleted
```

```
thockin@freakshow kubernetes master /$ kubectl run date -i --tty --restart=Never --image=busybox -- /bin/sh -c /bin/date; kubectl delete pod date
Waiting for pod default/date to be running, status is Pending, pod ready: false
Error attaching, falling back to logs: error executing remote command: Error executing command in container: container not found ("date")
Error from server: Internal error occurred: Unrecognized input header
pod "date" deleted
```

```
thockin@freakshow kubernetes master /$ kubectl run date -i --tty --restart=Never --image=busybox -- -c /bin/date; kubectl delete pod date
Waiting for pod default/date to be running, status is Pending, pod ready: false
Error from server: Internal error occurred: Unrecognized input header
pod "date" deleted
```

**Comment by thockin** [comment]
kubectl exec does not seem to suffer this:

```
thockin@freakshow kubernetes master /$ kubectl run date1 --restart=Never --image=busybox -- sleep 1000;
pod "date1" created

thockin@freakshow kubernetes master /$ kubectl exec -i --tty date1 -- date
Mon Nov  2 16:25:43 UTC 2015

thockin@freakshow kubernetes master /$ kubectl exec -i --tty date1 -- /bin/date
Mon Nov  2 16:25:56 UTC 2015
```

**Comment by ncdc** [comment]
@thockin what is your expectation for `kubectl run ... --; kubectl delete pod date`?

**Comment by thockin** [comment]
`--`  just means "all remaining args are for the container" right.  No
remaining args means the same as if I didn't specify `--` - and that seems
to be what is happening - it runs sh (the ENTRYPOINT for busybox).

**Comment by ncdc** [comment]
@thockin I apologize, I have a lot of stuff going on atm.... Which of the code blocks above is not behaving as you'd expect? The last 3?

**Comment by thockin** [comment]
yeah, all the last 3 say

```
Error attaching, falling back to logs: error executing remote command:
Error executing command in container: container not found ("date")
Error from server: Internal error occurred: Unrecognized input header
```

**Comment by feihujiang** [comment]
#13917 fixed ```kubectl run``` , but it hasn't been merged. #14161 fixed ```kubectl exec```, and it merged.  so why ```kubectl run ``` suffer this but ```kubectl exec``` doesn't.  Because I separated these to two PRs, maybe  @eparis forget to review #13917.  @eparis could you please review #13917. or any other other to review?

**Comment by thockin** [comment]
Thanks!

**Comment by feihujiang** [comment]
@thockin Sorry, I looked into your examples, I found #13917 couldn't fix this.

**Comment by feihujiang** [comment]
I think I know the problem about the following examples:
~~~
thockin@freakshow kubernetes master /$ kubectl run date -i --tty --restart=Never --image=busybox -- /bin/date
~~~
Because the container finishes /bin/date command immediately , then exit, however AttachContainer needs container running not exited and dead . So the error message is "container not found ("date")", because container("date") exited:

**Comment by feihujiang** [comment]
And I tested ```docker run```, the output as follows:
~~~
openstack@controller:~/jiangfeihu/src/k8s.io/kubernetes$ docker run -t -i ubuntu:14.04 /bin/date
Tue Nov  3 11:03:55 UTC 2015
openstack@controller:~/jiangfeihu/src/k8s.io/kubernetes$ 
~~~

**Comment by thockin** [comment]
That makes sense.  I think we need to make this work, even if the container
has exited.

**Comment by feihujiang** [comment]
I looked into the error of "Unrecognized input header". I tested the following example, and found if we set the field```tty:true``` on a container, then used ```kubectl logs``` on that container, the error "Unrecognized input header" occurs whenever the pod is running or completed. And the error is returned from "/home/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/fsouza/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy.go"

I think this is a bug. Maybe the third party's bug.
```
apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  containers:
  - name: count
    image: ubuntu:14.04
    tty: true
    args: [bash, -c, 
           'for ((i = 0; i < 20 ; i++)); do echo "$i: $(date)"; sleep 1; done']
  restartPolicy: Never
```

**Comment by Random-Liu** [comment]
We met similar issue when validate docker 1.10 #19720. I'm not sure whether they are the same issue, just FYI.

For our case, it turns out that the `go-dockerclient` is using `ContentType: plain/text`, while docker only accepts `ContentType: application/json`.

**Comment by cyphar** [comment]
Is there a reason we can't use Docker's [official engine-api](https://github.com/docker/engine-api), which will always comply with Docker's API (they use it for the `docker` client).

**Comment by antoineco** [comment]
(CoreOS 949.0.0 with Kubernetes 1.1.7)
I second @Random-Liu, this issue happens with all containers created by Docker **1.10**.

```
❯ kubectl exec api-l90lm ps aux
error: error executing remote command: Error executing command in container: Unrecognized input header
```
```
❯ kubectl exec -it api-l90lm -- bash -il
Content-Type specified (plain/text) must be 'application/json'
(terminal hangs here)
```

**Comment by Random-Liu** [comment]
@antoineco This will be fixed after bump up go-dockerclient version #20873

**Comment by runseb** [comment]
Same with Ubuntu 14.04, K8s 1.1.4 and Docker 1.10
I cannot exec into a container

```
$ kubectl exec busybox -- nslookup kubernetes.default
error: Error executing remote command: Error executing command in container: Unrecognized input header
```

**Comment by antoineco** [comment]
This is fixed on `master`, it will most likely make it to the 1.1.8 and 1.2 branches (?)

**Comment by OwenChang** [comment]
same as @runesb

**Comment by jumpkick** [comment]
This appears to work again on 1.2.0-alpha8: 

```
kubectl exec busybox -- nslookup kubernetes.default
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      kubernetes.default
Address 1: 10.0.0.1
```

**Comment by runseb** [comment]
yes, confirmed for me as well, it works on 1.2.0-alpha.8 with docker 1.10

**Comment by yvespp** [comment]
`kubectl run` with a short running command still doesn't work for me with 1.2.0 final:

With `--restart=Never` the command ends with `Unrecognized input header`
```
lodur:config yves$ kubectl run busybox -i --tty --image=busybox --rm --restart=Never --command -- nslookup kubernetes.default
Waiting for pod default/busybox-nwobh to be running, status is Pending, pod ready: false
Waiting for pod default/busybox-nwobh to be running, status is Pending, pod ready: false
Waiting for pod default/busybox-nwobh to be running, status is Pending, pod ready: false
Error from server: Unrecognized input header
```
Also the job doesn't get deleted but the pod does.

Without the `--restart=Never` the command hangs:

```
lodur:config yves$ kubectl run busybox -i --tty --image=busybox --rm --command -- nslookup kubernetes.default
Waiting for pod default/busybox-4204947303-78vap to be running, status is Pending, pod ready: false
Waiting for pod default/busybox-4204947303-78vap to be running, status is Pending, pod ready: false
Waiting for pod default/busybox-4204947303-78vap to be running, status is Running, pod ready: false
Waiting for pod default/busybox-4204947303-78vap to be running, status is Running, pod ready: false
Waiting for pod default/busybox-4204947303-78vap to be running, status is Running, pod ready: false
Waiting for pod default/busybox-4204947303-78vap to be running, status is Running, pod ready: false
Waiting for pod default/busybox-4204947303-78vap to be running, status is Running, pod ready: false
Waiting for pod default/busybox-4204947303-78vap to be running, status is Running, pod ready: false
Waiting for pod default/busybox-4204947303-78vap to be running, status is Running, pod ready: false
...
```

I'm using the Docker single node setup with Docker Machine, versions:
```
lodur:config yves$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}

lodur:config yves$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Comment by z00223295** [comment]
there seems kubernetes only support container TTY=false. as in code, it's hard code with RawTerminal.
sopts := StreamOptions{
		OutputStream: stdout,
		ErrorStream:  stderr,
		**RawTerminal:  false,**
}

**Comment by felixbuenemann** [comment]
I'm still seeing this problem with kubernetes / kubectl 1.4.4 and docker 1.11.2.
