### ISSUE TITLE
DaemonSet scheduling pods on SchedulingDisabled nodes

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#16967]
On my GCE cluster the master appears as a `SchedulingDisabled` node. It looks like DaemonSet is trying to schedule something on it and failing with "InsufficientCpu" every few seconds.

Either it should bypass this restriction or it should stop trying. Trying every couple seconds and flooding hte logs is bad.

**Comment by mikedanese** [comment]
cc @davidopp

**Comment by davidopp** [comment]
Which Kubernetes release are you running, or are you running from HEAD?

**Comment by mikedanese** [comment]
This is on HEAD and in 1.1. I thought this was by design.

**Comment by mikedanese** [comment]
Daemon controller bypasses the scheduler by directly writing nodeName and doesn't care whether the node is unschedulable.

**Comment by davidopp** [comment]
Looks like we forgot that Kubelet will reject the Pod if it doesn't meet the predicate checks.

**Comment by davidopp** [comment]
(The ones that are built into Kubelet).

**Comment by mikedanese** [comment]
Yet another reason to fold daemonsetcontroller into nodecontroller.

**Comment by davidopp** [comment]
I don't think that will help -- Kubelet will still do a feasibility check. The Huawei folks offered to implement library with the predicates shared between Kubelet and schedulers; we should use that when scheduling daemons and anything else that writes NodeName directly.

**Comment by paralin** [comment]
@davidopp HEAD, to confirm.

**Comment by davidopp** [comment]
Thanks for reporting the problem.

#17318 should fix the problem of DaemonSet controller trying to schedule onto nodes marked as scheduling disabled.

#12744 will fix the problem that DaemonSet controller assigns pods to nodes without checking that they have sufficient resources.

They're both now noted as graduation requirements in #15310.

**Comment by gg7** [comment]
Is this actually fixed? I'm running 1.5.7 on bare metal and I'm having the same issue:

```bash
root@server:~# kubectl get nodes -o wide | egrep '(NAME|SchedulingDisabled)'
NAME               STATUS                     AGE       EXTERNAL-IP
ldn-013.local      Ready,SchedulingDisabled   81d       <none>

root@server:~# kubectl get pods --all-namespaces -o wide | egrep '(NAME|ldn-013)'
NAMESPACE          NAME                                            READY     STATUS             RESTARTS   AGE       IP             NODE
default            nginx-ingress-lb-spbgx                          1/1       Running            0          3d        10.200.7.4     ldn-013.local
johnny             consumer-repeater-71l4h                         1/2       CrashLoopBackOff   5          5m        10.200.7.5     ldn-013.local
kube-system        fluentd-elasticsearch-g30nv                     1/1       Running            3          45d       10.200.7.6     ldn-013.local
zeus-dev           consumer-repeater-4xsn4                         1/2       CrashLoopBackOff   96         42d       10.200.7.3     ldn-013.local
zeus-prod          consumer-repeater-zmr0v                         1/2       CrashLoopBackOff   99         5d        10.200.7.2     ldn-013.local

root@server:~# kubectl get pods --all-namespaces -o wide | fgrep ldn-013 | awk '{print $1 " " $2}' | while read ns pod; do kubectl delete pod -n "$ns" "$pod"; done
pod "nginx-ingress-lb-spbgx" deleted
pod "consumer-repeater-71l4h" deleted
pod "fluentd-elasticsearch-g30nv" deleted
pod "consumer-repeater-4xsn4" deleted
pod "consumer-repeater-zmr0v" deleted

root@server:~# kubectl get pods --all-namespaces -o wide | egrep '(NAME|ldn-013)'
NAMESPACE          NAME                                            READY     STATUS             RESTARTS   AGE       IP             NODE
default            nginx-ingress-lb-sl1x3                          0/1       Running            0          10s       10.200.7.5     ldn-013.local
johnny             consumer-repeater-7rjqf                         1/2       CrashLoopBackOff   1          13s       10.200.7.2     ldn-013.local
kube-system        fluentd-elasticsearch-2r5jv                     1/1       Running            0          7s        10.200.7.6     ldn-013.local
zeus-dev           consumer-repeater-rx7k3                         1/2       CrashLoopBackOff   1          13s       10.200.7.4     ldn-013.local
zeus-prod          consumer-repeater-1xrsq                         1/2       CrashLoopBackOff   1          13s       10.200.7.3     ldn-013.local
```

**Comment by gg7** [comment]
@mikedanese @davidopp could you please reopen this issue? Or should I create a new ticket?

**Comment by gjcarneiro** [comment]
Yes, we're seeing this issue in Kubernetes v1.6.2, so it's definitely not fixed.

**Comment by mikedanese** [comment]
This is the intended behavior. Use a taint if you don't want a ds to schedule on a node.

**Comment by chrisgahlert** [comment]
Using taints did not really work for me, but in case someone else searches for a solution, here is what I did:
1. Label all Nodes, the DaemonSet is supposed to run on: `kubectl label node mynode node-daemonset.pool=foobar`
2. Make sure the DaemonSet only runs on those nodes by using a label selector: `nodeSelector: {"daemonset.pool": "foobar"}`
3. Before draining the node, remove the label from this node: `kubectl label node mydrainednode node-daemonset.pool-`
4. Wait for the DaemonSet to finish terminating: `while [ ! -z "$(kubectl get pods --field-selector=status.phase=Running --field-selector=spec.nodeName=mydrainednode -o name)" ]; do echo sleeping...; sleep 5; done`

**Comment by lyveng** [comment]
Using taints works. But by default certain tolerations are added for all daemonset pods - [docs](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#taints-and-tolerations). If you add any taint that is other than the default tolerations of a daemonset pod, deleting the pod does not schedule on it again.
