### ISSUE TITLE
Terminating pod status is not refreshed correctly

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#17612]
Using Kubernetes 1.1.2 with Vagrant provider, running two pods:

```
./cluster/kubectl.sh get po
NAME               READY     STATUS    RESTARTS   AGE
mysql-pod          1/1       Running   0          21s
wildfly-rc-l2cto   1/1       Running   0          21s
```

One of the pods was deleted:

```
./cluster/kubectl.sh delete po wildfly-rc-l2cto
pod "wildfly-rc-l2cto" deleted
```

Watching the status of pods are shown as:

```
./cluster/kubectl.sh get -w po
NAME               READY     STATUS        RESTARTS   AGE
mysql-pod          1/1       Running       0          1m
wildfly-rc-2o8vd   1/1       Running       0          13s
wildfly-rc-l2cto   1/1       Terminating   0          1m
NAME               READY     STATUS        RESTARTS   AGE
wildfly-rc-l2cto   0/1       Terminating   0          1m
wildfly-rc-l2cto   0/1       Terminating   0         1m
wildfly-rc-l2cto   0/1       Terminating   0         1m
```

Two issues:
- Refreshed status shows the only for the changed pod and shows it three times
- Even after waiting for 5 minutes, the status does not refresh to Terminated

Just checking the status as `kubectl.sh get po` shows that the pod has been terminated. But its confusing that with `-w` the status never updates to Terminated or something intuitive.

**Comment by ncdc** [comment]
This isn't easy with the watch the watch is implemented in kubectl and how objects the watch receive are printed. The printers only receive the object to print (e.g. a Pod), but the object itself doesn't necessarily have an easy way to reliably determine that it was deleted. The watch code does report that it was a deletion event, but that information is passed along to the printer.

Here is where the watch event is received: https://github.com/kubernetes/kubernetes/blob/a87d927588e5fb391ce71f79e97648ba4452bdc4/pkg/kubectl/cmd/get.go#L180. We could consider evaluating `e.Type` and passing along a `deleted=true` `bool` to the printer, perhaps.

**Comment by ncdc** [comment]
cc @kubernetes/rh-ux

**Comment by jwforres** [comment]
@ncdc we handle this in the openshift web console by adding a deletionTimestamp to our in memory object when we get the DELETE event over the websocket.  we figured at some point we might want to know roughly when that delete happened, and that eventually it would be nice if the object in the event from the API actually included a deletionTimestamp

**Comment by ncdc** [comment]
@jwforres the pod in this case does have a deletionTimestamp. The printer for pods looks at deletionTimestamp and emits Terminating if it's set: https://github.com/kubernetes/kubernetes/blob/62314046825dad08fa3fac2a03c2aadf68702fdc/pkg/kubectl/resource_printer.go#L571.

**Comment by jwforres** [comment]
OK yep I think we only set it if it's not already defined.

**Comment by liggitt** [comment]
does the watch event come back with an UPDATE first (with deletionTimestamp set), then a DELETE (also with deletionTimestamp set), in cases where a graceful delete occurred?

**Comment by ncdc** [comment]
@liggitt I haven't tested today with graceful deletion, but I would assume so.

**Comment by jwforres** [comment]
also FWIW we do this for any object when we get a DELETE event, not just pods.

**Comment by wulonghui** [comment]
I got this issue of  v1.1.2 and v1.1.3
is it fixed at v1.1.4?

**Comment by bgrant0607** [comment]
Note that #11338 is still open.

**Comment by nguyener** [comment]
has this issue been fixed yet?

**Comment by spzala** [comment]
Seems like it's not yet fixed. With the latest minikube, v0.19.1, I could recreate the problem with -w that status doesn't refresh to Terminated:

$ kubectl delete po nginx-deployment-4234284026-8v7vd
pod "nginx-deployment-4234284026-8v7vd" deleted

$kubectl get -w po
NAME                                READY     STATUS        RESTARTS   AGE
nginx-deployment-4234284026-802ct   1/1       Running       0          8s
nginx-deployment-4234284026-8v7vd   0/1       Terminating   0          1m
nginx-deployment-4234284026-d8tx1   1/1       Running       0          1m
nginx-deployment-4234284026-l4mw4   1/1       Running       0          1m
NAME                                READY     STATUS        RESTARTS   AGE
nginx-deployment-4234284026-8v7vd   0/1       Terminating   0          1m
nginx-deployment-4234284026-8v7vd   0/1       Terminating   0         1m

**Comment by liggitt** [comment]
Are you including the argument to get that shows terminated pods? They are filtered by default

**Comment by spzala** [comment]
@liggitt hi, I used "kubectl get -w po" as described in the issue. I suppose this should refresh the output with 'Terminated' from 'Terminating'. The command without -w works fine or even if I run second time with -w that works fine too but the issue is about first time use of -w. Do you want me to try out any particular argument? Thanks!

**Comment by liggitt** [comment]
what does `kubectl get pods -w --show-all` do?

**Comment by spzala** [comment]
@liggitt On a clean env, I could recreate on and off with "kubectl get -w po" and "kubectl get pods -w --show-all" when use after deleting pod or deployment. For example, I could recreate the issue with "kubectl get pods -w --show-all" as you could see in output below:
$ kubectl get -w po
NAME                                READY     STATUS    RESTARTS   AGE
nginx-deployment-4234284026-ktzgw   1/1       Running   0          1m
nginx-deployment-4234284026-nhf16   1/1       Running   0          1m
nginx-deployment-4234284026-pdcf4   1/1       Running   0          8s

$ kubectl delete deployment nginx-deployment
deployment "nginx-deployment" deleted

$ kubectl get pods -w --show-all
NAME                                READY     STATUS        RESTARTS   AGE
nginx-deployment-4234284026-ktzgw   0/1       Terminating   0          2m
nginx-deployment-4234284026-nhf16   0/1       Terminating   0          2m
nginx-deployment-4234284026-pdcf4   0/1       Terminating   0          1m
NAME                                READY     STATUS        RESTARTS   AGE
nginx-deployment-4234284026-ktzgw   0/1       Terminating   0          2m
nginx-deployment-4234284026-ktzgw   0/1       Terminating   0         2m
nginx-deployment-4234284026-nhf16   0/1       Terminating   0         2m
nginx-deployment-4234284026-nhf16   0/1       Terminating   0         2m
nginx-deployment-4234284026-pdcf4   0/1       Terminating   0         1m
nginx-deployment-4234284026-pdcf4   0/1       Terminating   0         1m

**Comment by ncdc** [comment]
I haven't checked the code recently, but unless what I wrote above in https://github.com/kubernetes/kubernetes/issues/17612#issuecomment-161734054 has changed, this has not been resolved yet.

**Comment by liggitt** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/11338
/close
