### ISSUE TITLE
Include local-up-cluster in release

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#18188]
Since the getting-started-locally docs in the binary release reference it, we should either include it as well or modify the docs to say something along the lines of: `hack/` isn't in the binary release, you need to download the source release or clone the repo to get it.

**Comment by drocsid** [comment]
+1

**Comment by bgrant0607** [comment]
We should ensure our local-cluster solution is built and bundled with the rest of our release.
cc @vishh @dlorenc @pwittrock

**Comment by roberthbailey** [comment]
@bgrant0607 @david-mcmahon are we going to have this fixed in the upcoming 1.3 release?

**Comment by david-mcmahon** [comment]
While this issue does involve what's ultimately included in a 'release', it is a product issue related to the subteam and needs resolution from them.

**Comment by dlorenc** [comment]
We can chat more if this turns out to be very important, but I think we'll continue releasing minikube independently through the 1.3 release.

Minikube will rely on the official 1.3 release when it's cut, but we'd like to continue to iterate on the minikube CLI itself out of band for a little longer. We should definitely revisit in the 1.4 timeframe, though.

**Comment by kargakis** [comment]
@kubernetes/sig-release-misc

**Comment by spzala** [comment]
@bprashanth Hi, a gentle touch base, this still an issue? If not, can we please close it? I unfortunately couldn't verify it but a lot has been changed with doc and we are at v1.7 now. Thanks!

**Comment by bgrant0607** [comment]
local-up-cluster is for developers
minikube is for users
closing as obsolete
