### ISSUE TITLE
Job being constanly recreated despite RestartPolicy: Never

### ISSUE THREAD

**Issue by tobad357** [kubernetes/kubernetes#20255]
I have a job with the spec as shown below.
During testing we are forcing a non zero exit code and would expect the job to not be recreated.
However the Job controller keeps on creating new pods again and again while I would expect after reading the docs that it would run it once and if it fails it fails.
Are our assumptions incorrect and if they are is there someway we can run an image on the K8S cluster and get the return value back without it being scheduled to run again on failure?

```
apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: app-deploy
spec:
  selector:
    matchLabels:
      app: app-deploy
  template:
    metadata:
      name: app-deploy
      labels:
        app: app-deploy
    spec:
      containers:
      - name: db-upgrade
        image: XXXX/XXX
      restartPolicy: Never
```

**Comment by soltysh** [comment]
This is by design, see [here](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/jobs.md#handling-pod-and-container-failures). Generally speaking the restart policy is applied to a pod not to a job, as you might understood initially. k8s role is to actually run a pod to successful completion, it cannot judge based on the exit code whether that failure was expected and should re-run or it was not and should stop re-trying. It's user job to do that distinction based on the output from k8s.

**Comment by tobad357** [comment]
Ah ok, thanks then I understand. So while waiting for deployment hooks I could run a pod instead of a job with RestartPolicy Never

Out of interest is it also be design that the JobController creates a never ending stream of Pods which end up in Error state if the Job continues to Error out?
I now took 3-4 min (inc a small timeout) to delete the Job as I had forgotten that it was created and it continued creating new pods for quite a while

**Comment by soltysh** [comment]
1: Yes.

2: The JobController is written in such way it'll try to reach completions.

**Comment by a-robinson** [comment]
Sounds like this is resolved.

Also, StackOverflow is the best place to ask questions like this, since it makes the answers much more findable by people who have similar questions in the future.

**Comment by eghobo** [comment]
@soltysh: the biggest problem with 'try to reach completions' that it create many dead/error pods objects in etcd which significantly slow down all api calls (and of course delete take forever). It looks like use need to implement watchdog for all jobs ):

**Comment by soltysh** [comment]
@eghobo I feel your pain. But in general jobs are just a building block for something else. Eg. ScheduledJobs I'm working on right now :)

**Comment by eghobo** [comment]
@soltysh: I appreciate your effort, but still not convinced that I need to write my own controller just for restart (of course we can use pod instead of job, but it will be nice to have consistent api/behavior  between job and scheduled jobs). Any thoughts about adding restartPolicy at Job level?

**Comment by soltysh** [comment]
No idea, I don't think such ideas where ever discussed, you're free to open an issue and gather opinions around the topic.

**Comment by philipbjorge** [comment]
For any future readers, setting `restartPolicy: OnFailure` will prevent the neverending creation of pods because it will just restart the failing one.

If you want to create new pods on failure with `restartPolicy: Never`, you can limit them by setting `activeDeadlineSeconds` -- Upon reaching the deadline without success, the job will have status with reason: DeadlineExceeded. No more pods will be created, and existing pods will be deleted.

**Comment by innovia** [comment]
one caveat on activeDeadlineSeconds, if your job is depending on capacity controlled by the cluster autoscaler you might be killing the job before a new instance is up and ready

**Comment by soltysh** [comment]
@innovia `.spec.backoffLimit` introduced in https://github.com/kubernetes/kubernetes/pull/48075 and https://github.com/kubernetes/kubernetes/pull/51153 is what you'll be looking for.

**Comment by innovia** [comment]
@soltysh
My use case is a gpu cluster when a user runs a script it creates a job on a gpu instance when theres a node fit failure because that gpu instnace is in a moddle of another job cluster autoscaler kicks in and adds another instance and until that node is up and running on kubernetes theres a chance that the actovedeadline seconds will breach before the pod even ran.

I read the links you provided but its a bit unclear to me how this backoff works

Do you have a link to the docs you've updated?

**Comment by soltysh** [comment]
Quite a bit late, but if anyone else looks for it's https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#pod-backoff-failure-policy

**Comment by remster** [comment]
Trying to parse "Generally speaking the restart policy is applied to a pod not to a job, as you might understood initially. k8s role is to actually run a pod to successful completion, it cannot judge based on the exit code whether that failure was expected and should re-run or it was not and should stop re-trying. It's user job to do that distinction based on the output from k8s." @soltysh 

Does restartPolicy of a job have any meaning whatsoever?
If jobs communicate their failure as an exit code, then how can the scheduler make the conclusion about what has failed?
If jobs do not communicate their result as an exit code then how are they expected to do that instead?

**Comment by thatInfrastructureGuy** [comment]
I was still confused on why `restartPolicy: Never` restarts the job and I wanted to know the difference between `OnFailure` and `Never`.  I found [openshift documentation page](https://docs.openshift.com/container-platform/4.1/nodes/jobs/nodes-nodes-jobs.html#jobs-limits_nodes-nodes-jobs) which helped me understand better. Hopefully this helps someone.

```
The Job specification restart policy only applies to the pods, and not the job controller. However, the job controller is hard-coded to keep retrying Jobs to completion.

As such, restartPolicy: Never or --restart=Never results in the same behavior as restartPolicy: OnFailure or --restart=OnFailure. That is, when a Job fails it is restarted automatically until it succeeds (or is manually discarded). The policy only sets which subsystem performs the restart.

With the Never policy, the job controller performs the restart. With each attempt, the job controller increments the number of failures in the Job status and create new pods. This means that with each failed attempt, the number of pods increases.

With the OnFailure policy, kubelet performs the restart. Each attempt does not increment the number of failures in the Job status. In addition, kubelet will retry failed Jobs starting pods on the same nodes.
```
