### ISSUE TITLE
Examples e2e tests continuously failing

### ISSUE THREAD

**Issue by ixdy** [kubernetes/kubernetes#20999]
5 of our examples e2e tests have been continuously failing on http://ci-test.k8s.io/kubernetes-e2e-gce-examples/:

**[Feature:Example] Liveness liveness pods should be automatically restarted**
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:315 Feb 10 13:17:01.938: Pod liveness-exec was not restarted
```

**[Feature:Example] Downward API should create a pod that prints his name and namespace**
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:354 Expected error: <*errors.errorString | 0xc208535c60>: { s: "Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce-examples/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.61.129 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce-examples/workspace/.kube/config log dapi-test-pod test-container --namespace=e2e-tests-examples-kpyvp] [] Error from server: container \"test-container\" in pod \"dapi-test-pod\" is waiting to start: ContainerCreating\n [] 0xc208521800 exit status 1 true [0xc20843e578 0xc20843e598 0xc20843e5c0] [0xc20843e578 0xc20843e598 0xc20843e5c0] [0xc20843e590 0xc20843e5b0] [0x87bed0 0x87bed0] 0xc20845f020}:\nCommand stdout:\n\nstderr:\nError from server: container \"test-container\" in pod \"dapi-test-pod\" is waiting to start: ContainerCreating\n\nerror:\nexit status 1\n", } Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce-examples/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.61.129 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce-examples/workspace/.kube/config log dapi-test-pod test-container --namespace=e2e-tests-examples-kpyvp] [] Error from server: container "test-container" in pod "dapi-test-pod" is waiting to start: ContainerCreating [] 0xc208521800 exit status 1 true [0xc20843e578 0xc20843e598 0xc20843e5c0] [0xc20843e578 0xc20843e598 0xc20843e5c0] [0xc20843e590 0xc20843e5b0] [0x87bed0 0x87bed0] 0xc20845f020}: Command stdout: stderr: Error from server: container "test-container" in pod "dapi-test-pod" is waiting to start: ContainerCreating error: exit status 1 not to have occurred
```

**[Feature:Example] Secret should create a pod that reads a secret**
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:334 Expected error: <*errors.errorString | 0xc208525070>: { s: "Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce-examples/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.61.129 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce-examples/workspace/.kube/config log secret-test-pod test-container --namespace=e2e-tests-examples-fq99c] [] Error from server: container \"test-container\" in pod \"secret-test-pod\" is waiting to start: ContainerCreating\n [] 0xc208b25b00 exit status 1 true [0xc208a14478 0xc208a14498 0xc208a144b8] [0xc208a14478 0xc208a14498 0xc208a144b8] [0xc208a14490 0xc208a144b0] [0x87bed0 0x87bed0] 0xc20868db00}:\nCommand stdout:\n\nstderr:\nError from server: container \"test-container\" in pod \"secret-test-pod\" is waiting to start: ContainerCreating\n\nerror:\nexit status 1\n", } Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce-examples/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.61.129 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce-examples/workspace/.kube/config log secret-test-pod test-container --namespace=e2e-tests-examples-fq99c] [] Error from server: container "test-container" in pod "secret-test-pod" is waiting to start: ContainerCreating [] 0xc208b25b00 exit status 1 true [0xc208a14478 0xc208a14498 0xc208a144b8] [0xc208a14478 0xc208a14498 0xc208a144b8] [0xc208a14490 0xc208a144b0] [0x87bed0 0x87bed0] 0xc20868db00}: Command stdout: stderr: Error from server: container "test-container" in pod "secret-test-pod" is waiting to start: ContainerCreating error: exit status 1 not to have occurred
```

**[Feature:Example] Cassandra should create and scale cassandra**
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:229 Expected error: <*errors.errorString | 0xc2086ddef0>: { s: "Failed to find \"Listening for thrift clients\", last result: \"/bin/bash: /run.sh: Permission denied\"", } Failed to find "Listening for thrift clients", last result: "/bin/bash: /run.sh: Permission denied" not to have occurred
```

**[Feature:Example] Spark should start spark master, driver and workers**
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:187 Expected error: <*errors.errorString | 0xc20887f4a0>: { s: "Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce-examples/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.61.129 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce-examples/workspace/.kube/config create -f /jenkins-master-data/jobs/kubernetes-e2e-gce-examples/workspace/kubernetes/examples/spark/spark-master-service.json --namespace=e2e-tests-examples-a6dli] [] the path \"/jenkins-master-data/jobs/kubernetes-e2e-gce-examples/workspace/kubernetes/examples/spark/spark-master-service.json\" does not exist\n [] 0xc20888e1a0 exit status 1 true [0xc20803dda8 0xc20803ddd0 0xc20803ddf0] [0xc20803dda8 0xc20803ddd0 0xc20803ddf0] [0xc20803ddc8 0xc20803dde8] [0x87bed0 0x87bed0] 0xc2088869c0}:\nCommand stdout:\n\nstderr:\nthe path \"/jenkins-master-data/jobs/kubernetes-e2e-gce-examples/workspace/kubernetes/examples/spark/spark-master-service.json\" does not exist\n\nerror:\nexit status 1\n", } Error running &{/jenkins-master-data/jobs/kubernetes-e2e-gce-examples/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.61.129 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-e2e-gce-examples/workspace/.kube/config create -f /jenkins-master-data/jobs/kubernetes-e2e-gce-examples/workspace/kubernetes/examples/spark/spark-master-service.json --namespace=e2e-tests-examples-a6dli] [] the path "/jenkins-master-data/jobs/kubernetes-e2e-gce-examples/workspace/kubernetes/examples/spark/spark-master-service.json" does not exist [] 0xc20888e1a0 exit status 1 true [0xc20803dda8 0xc20803ddd0 0xc20803ddf0] [0xc20803dda8 0xc20803ddd0 0xc20803ddf0] [0xc20803ddc8 0xc20803dde8] [0x87bed0 0x87bed0] 0xc2088869c0}: Command stdout: stderr: the path "/jenkins-master-data/jobs/kubernetes-e2e-gce-examples/workspace/kubernetes/examples/spark/spark-master-service.json" does not exist error: exit status 1 not to have occurred
```

Some of these might be easy fixes, but I haven't looked in depth much yet.

@kubernetes/sig-testing @kubernetes/goog-testing @bgrant0607

**Comment by ixdy** [comment]
One more test is pretty flaky, but not failing 100% (last failed in build 7389):
**Pet Store [Feature:Example] should scale to persist a nominal number ( 50 ) of transactions in 1m0s seconds**
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/example_k8petstore.go:167 Expected : 0 to be > : 50
```

**Comment by jayunit100** [comment]
K8petstore: Yeah this is a function of the data generators and the redis store which both might take a second to come online

**Comment by jayunit100** [comment]
Well, more than a second: anyway I can incr the timeout on it . But the test is flakey on anything with a slow internet connection or low cpu/mem.

**Comment by ixdy** [comment]
@jayunit100 I think it might be something else:
```
Feb 10 14:15:22.829: INFO: ... Done starting k8petstore 
Feb 10 14:15:22.829: INFO: Start polling, timeout is 1m0s seconds
Feb 10 14:15:22.829: INFO: Now waiting 30s seconds to see progress (transactions  > 3)
Feb 10 14:15:24.834: INFO: Time: 2016-02-10 14:15:24.834298586 -0800 PST, 0 = total petstore transactions stored into redis.
Feb 10 14:15:26.833: INFO: Time: 2016-02-10 14:15:26.833443856 -0800 PST, 0 = total petstore transactions stored into redis.
Feb 10 14:15:28.833: INFO: Time: 2016-02-10 14:15:28.83379335 -0800 PST, 0 = total petstore transactions stored into redis.
Feb 10 14:15:30.833: INFO: Time: 2016-02-10 14:15:30.833501244 -0800 PST, 0 = total petstore transactions stored into redis.
Feb 10 14:15:32.836: INFO: Time: 2016-02-10 14:15:32.836767414 -0800 PST, 3 = total petstore transactions stored into redis.
Feb 10 14:15:34.834: INFO: Time: 2016-02-10 14:15:34.834214041 -0800 PST, 0 = total petstore transactions stored into redis.
Feb 10 14:15:36.833: INFO: Time: 2016-02-10 14:15:36.833169518 -0800 PST, 0 = total petstore transactions stored into redis.
Feb 10 14:15:38.835: INFO: Time: 2016-02-10 14:15:38.835862574 -0800 PST, 3 = total petstore transactions stored into redis.
Feb 10 14:15:40.834: INFO: Time: 2016-02-10 14:15:40.834804576 -0800 PST, 3 = total petstore transactions stored into redis.
Feb 10 14:15:42.833: INFO: Time: 2016-02-10 14:15:42.833676365 -0800 PST, 0 = total petstore transactions stored into redis.
Feb 10 14:15:44.833: INFO: Time: 2016-02-10 14:15:44.833411311 -0800 PST, 0 = total petstore transactions stored into redis.
Feb 10 14:15:46.835: INFO: Time: 2016-02-10 14:15:46.835750938 -0800 PST, 4 = total petstore transactions stored into redis.
Feb 10 14:15:48.833: INFO: Time: 2016-02-10 14:15:48.833553623 -0800 PST, 0 = total petstore transactions stored into redis.
Feb 10 14:15:50.833: INFO: Time: 2016-02-10 14:15:50.833206135 -0800 PST, 0 = total petstore transactions stored into redis.
Feb 10 14:15:52.833: INFO: Timeout 0xc208a4cf00 reached.  Checking if transactions have occured.
Feb 10 14:15:52.833: INFO: Failed : Error strconv.ParseInt: parsing "Error: 'dial tcp 10.245.0.5:3000: connection refused'\nTrying to reach: 'http://10.245.0.5:3000/llen'": invalid syntax
```

Looks like `readTransactions` is sometimes working, sometimes failing.

**Comment by jayunit100** [comment]
Hmm....Possibly frontend service goes up and down ? 
How often did this test fail? That is interesting.

**Comment by ixdy** [comment]
It's failed 11 times in the last 30 runs. I haven't looked to see if it's always the same error.

**Comment by bgrant0607** [comment]
Celery and Hazelcast look flaky. PetStore fails a large fraction of the time.

**Comment by bgrant0607** [comment]
Cassandra is known to be totally broken: #20746

**Comment by jayunit100** [comment]
Definitely looks infra related.  I can't imagine that 66% passing could be in the code ....  I wonder if the amount of cpu is bound so that this tests data generators simply take up too much juice, and thus container cycling is happening.

**Comment by jayunit100** [comment]
Ok let's consider this a catch-all ticket then.  We can open a separate one for cassandra/k8petstore/celery/.

**Comment by bgrant0607** [comment]
@zmerlynn Would you expect the spark test to be passing currently?

**Comment by nohkwangsun** [comment]
[Feature:Example] Spark should start spark master, driver and workers
Spark examples from latest version uses yaml files while Spark examples of release-1.1 uses json files.
You can see the error message "... spark-master-service.json\" does not exist ..."

**Comment by jayunit100** [comment]
locally I'm seeing that spark workers cant find the sparkMaster, even after updating the yaml files....

**Comment by jayunit100** [comment]
``` Reason: [Association failed with [akka.tcp://sparkMaster@spark-master:7077]] Caused by: [spark-master: unknown[24/1916]
16/02/20 18:24:46 WARN Worker: Failed to connect to master spark-master:7077
akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka.tcp://sparkMaster@spark-master:7077/), Path(/user/Master)]```

**Comment by jayunit100** [comment]
@bgrant0607 @zmerlynn okay, spark is working now in the above PR.  Also updated the DNS stuff and so on.  k8petstore also fixed to be at least more deterministic in failures if they keep occuring.
- [ ] k8petstore
- [ ] spark
- [ ] cassandra
- [ ]  secret
- [ ] downward api
- [ ] liveness

**Comment by jayunit100** [comment]
Ok folks were getting close on this I think...
anyone look into secrets/downward API yet/liveness?

I can dig some this wknd if not..

**Comment by goltermann** [comment]
I'll have a PR for downward in a few min, working now

**Comment by goltermann** [comment]
secret looks like a similar cause, will take that too

**Comment by jayunit100** [comment]
Ok thanks..! 
If liveness remains I'll dig into it.

**Comment by goltermann** [comment]
That's be great if you pick up Liveness.  PR out for the Downward and Secrets fixes.

**Comment by jayunit100** [comment]
we still need to look at `[Feature:Example] Liveness liveness pods should be automatically restarted`.

**Comment by jayunit100** [comment]
http://stackoverflow.com/questions/14460528/redis-periodicly-stops-responding-on-high-load is i think going to effect the redis tests unless the configs are tuned better.  any one have hints on the machine types that examples/ runs on?

**Comment by jayunit100** [comment]
update
- liveness still broken.  not sure why, but the container simply doesnt seem to restart is the core issue.  it does appear initially to start i think.
- I can't reproduce k8petstore flakes.  ran it literally 50 times both on GCE with exact jenkins env vars and with kube-up.sh defaults.

**Comment by jayunit100** [comment]
update 
- liveness fix submitted here #22757 
- since k8petstore flakes arent reproducible even on GCE, maybe we can  assume it has something to do w/ parallel test services colliding... 

- K8petstore passes consistently outside of CI, so maybe its more a parallel test issue then a examples/ failure.
- Spark fixed now: containers were labelled wrong
- Cassandra fixed now: The new maven jar has to be used and labels had to be corrected,before it will actually pass in the e2es.  @brendandburns is volunteered to do that.
- secrets , downward api, fixed (thanks  @goltermann !) 
- liveness is now fixed, and that will probably be merged shortly.

So we've now covered this space, and we can close the issue.

**Comment by spxtr** [comment]
Thanks for taking care of these :)

**Comment by bgrant0607** [comment]
Thanks @jayunit100. 

petstore is still failing continuously, but there are no test results. Leaving this open, but removing from milestone.

**Comment by bgrant0607** [comment]
Found a test result.
```
• Failure [648.408 seconds]
Pet Store [Feature:Example]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/example_k8petstore.go:172
  should scale to persist a nominal number ( 50 ) of transactions in 1m0s seconds [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/example_k8petstore.go:170

  Expected error:
      <*exec.ExitError | 0xc2083b0f88>: {
          ProcessState: {
              pid: 15903,
              status: 256,
              rusage: {
                  Utime: {Sec: 2, Usec: 992000},
                  Stime: {Sec: 0, Usec: 532000},
                  Maxrss: 26860,
                  Ixrss: 0,
                  Idrss: 0,
                  Isrss: 0,
                  Minflt: 166894,
                  Majflt: 4,
                  Nswap: 0,
                  Inblock: 136,
                  Oublock: 112,
                  Msgsnd: 0,
                  Msgrcv: 0,
                  Nsignals: 0,
                  Nvcsw: 18384,
                  Nivcsw: 1756,
              },
          },
      }
      exit status 1
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/example_k8petstore.go:103
```
kubernetes-jenkins/logs/kubernetes-e2e-gce-examples/8210/

**Comment by jayunit100** [comment]
ah this tells me the kubectl path on the test runner isn't found most likely..?
I'll check how the other kubectl tests are running, maybe a convention was updated

**Comment by jayunit100** [comment]
@bgrant0607 ill just add all the k8petstore shell script into the go code for the example , so the shell script implementation dissapears.  i think the value of a shell wrapper is diminished alot now that dns and kubexec are being used ubiquitiously for the examples.

**Comment by bgrant0607** [comment]
All of the application examples are failing all the time now. :-(

Only the contrived feature examples (DNS, downward API, liveness, secrets) are passing.

**Comment by jayunit100** [comment]
likely could be kubectl related?

**Comment by chrislovecnm** [comment]
Is there a way to dynamically build a new image and test that image?  For instance with https://github.com/kubernetes/kubernetes/issues/25583 I have a new container to test.

**Comment by jayunit100** [comment]
The best you can do is push your own image to dockerhub and test that this PR works with your image.

Then we can have them push it based on the fact that we know everything is ready.

**Comment by chrislovecnm** [comment]
@jayunit100 I am wondering if we can work out using the local server repo to push to ... any thoughts on that?

**Comment by jayunit100** [comment]
namespace is mangled, i know how to fix this.  will push a fix to help unbreak this stuff @bgrant0607 standby

**Comment by goltermann** [comment]
These are all working now (https://k8s-testgrid.appspot.com/k8s#gce-examples) can we close?
