### ISSUE TITLE
Consider using fluentd's buffer_queue_full_action setting to avoid dropping logs when the buffer is full

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#22537]
The setting was added late last year and we've just started using a version of fluentd that includes it. It sounds great, in that it causes the input half of fluentd to stop reading input whenever the output buffer is full (when normally the input half would just drop any input it reads during that time). Given that all our input comes from files on disk, this makes a lot of sense.

However, it's a pretty significant change to how the agent works, and the fluentd folks themselves don't seem very hot on the idea, so we should do some due diligence on it first before starting to use it. I tested it a bit this morning and at the very least it didn't cause fluentd to crash or hang when I filled up a buffer, but I didn't validate that it didn't drop anything.

cc @jimmidyson @mr-salty

**Comment by therc** [comment]
I'm seeing this on ~1.2 on AWS, running fluentd-es 1.15:

```
{"log":"2016-03-15 19:33:21 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-15 19:33:22 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"object:1c95350\"\n","stream":"stdout","time":"2016-03-15T19:33:21.350997467Z"}
{"log":"  2016-03-15 19:33:21 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:193:in `perform_request'\n","stream":"stdout","time":"2016-03-15T19:33:21.35103795Z"}
{"log":"  2016-03-15 19:33:21 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'\n","stream":"stdout","time":"2016-03-15T19:33:21.351044846Z"}
{"log":"  2016-03-15 19:33:21 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/client.rb:125:in `perform_request'\n","stream":"stdout","time":"2016-03-15T19:33:21.351049641Z"}
{"log":"  2016-03-15 19:33:21 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/elasticsearch-api-1.0.15/lib/elasticsearch/api/actions/bulk.rb:87:in `bulk'\n","stream":"stdout","time":"2016-03-15T19:33:21.3513538Z"}
{"log":"  2016-03-15 19:33:21 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.3.0/lib/fluent/plugin/out_elasticsearch.rb:195:in `send'\n","stream":"stdout","time":"2016-03-15T19:33:21.351366853Z"}
{"log":"  2016-03-15 19:33:21 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.3.0/lib/fluent/plugin/out_elasticsearch.rb:188:in `write'\n","stream":"stdout","time":"2016-03-15T19:33:21.351371687Z"}
{"log":"  2016-03-15 19:33:21 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/buffer.rb:345:in `write_chunk'\n","stream":"stdout","time":"2016-03-15T19:33:21.351376398Z"}
{"log":"  2016-03-15 19:33:21 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/buffer.rb:324:in `pop'\n","stream":"stdout","time":"2016-03-15T19:33:21.351380727Z"}
{"log":"  2016-03-15 19:33:21 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/output.rb:321:in `try_flush'\n","stream":"stdout","time":"2016-03-15T19:33:21.351386454Z"}
{"log":"  2016-03-15 19:33:21 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/output.rb:140:in `run'\n","stream":"stdout","time":"2016-03-15T19:33:21.351390978Z"}
{"log":"2016-03-15 19:33:22 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-15 19:33:24 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"object:1c95350\"\n","stream":"stdout","time":"2016-03-15T19:33:22.386160595Z"}
{"log":"  2016-03-15 19:33:22 +0000 [warn]: suppressed same stacktrace\n","stream":"stdout","time":"2016-03-15T19:33:22.386211044Z"}
{"log":"2016-03-15 19:33:24 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-15 19:33:28 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"object:1c95350\"\n","stream":"stdout","time":"2016-03-15T19:33:24.455804932Z"}
{"log":"  2016-03-15 19:33:24 +0000 [warn]: suppressed same stacktrace\n","stream":"stdout","time":"2016-03-15T19:33:24.455849879Z"}
{"log":"2016-03-15 19:33:28 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-15 19:33:37 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"object:1c95350\"\n","stream":"stdout","time":"2016-03-15T19:33:28.912100401Z"}
{"log":"  2016-03-15 19:33:28 +0000 [warn]: suppressed same stacktrace\n","stream":"stdout","time":"2016-03-15T19:33:28.912135231Z"}
{"log":"2016-03-15 19:33:37 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-15 19:33:52 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"object:1c95350\"\n","stream":"stdout","time":"2016-03-15T19:33:37.112381699Z"}
{"log":"  2016-03-15 19:33:37 +0000 [warn]: suppressed same stacktrace\n","stream":"stdout","time":"2016-03-15T19:33:37.112412876Z"}
{"log":"2016-03-15 19:33:52 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-15 19:34:22 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"object:1c95350\"\n","stream":"stdout","time":"2016-03-15T19:33:52.20842772Z"}
{"log":"  2016-03-15 19:33:52 +0000 [warn]: suppressed same stacktrace\n","stream":"stdout","time":"2016-03-15T19:33:52.208448065Z"}
{"log":"2016-03-15 19:34:22 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2016-03-15 19:34:52 +0000 error_class=\"Elasticsearch::Transport::Transport::Error\" error=\"Cannot get new connection from pool.\" plugin_id=\"object:1c95350\"\n","stream":"stdout","time":"2016-03-15T19:34:22.204914327Z"}
{"log":"  2016-03-15 19:34:22 +0000 [warn]: suppressed same stacktrace\n","stream":"stdout","time":"2016-03-15T19:34:22.2049351Z"}
{"log":"2016-03-15 19:34:41 +0000 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error=\"queue size exceeds limit\" tag=\"kubernetes.var.log.containers.FOO.log\"\n","stream":"stdout","time":"2016-03-15T19:34:41.662680284Z"}
{"log":"2016-03-15 19:34:41 +0000 [warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error=\"queue size exceeds limit\" tag=\"kubernetes.var.log.containers.FOO.log\"\n","stream":"stdout","time":"2016-03-15T19:34:41.689249386Z"}
[...]
```

The day after, this is still happening, also on another two out of ten nodes.

**Comment by therc** [comment]
After some more investigation, any chance that 0.12.20 or even 0.12.21 could be pushed to all images? The latter has this:

https://github.com/fluent/fluentd/blob/v0.12/ChangeLog
```
* in_tail: Fix input messages loss when receive_lines fail with BufferQueueLimitError
  https://github.com/fluent/fluentd/pull/810
```
As I said, I am still seeing errors with fluentd-elasticsearch, which uses 0.12.19. As far as I can tell, there's no explicit fluentd version anywhere, the Docker file just grabs whatever the APT repo in `https://td-toolbelt.herokuapp.com/sh/install-ubuntu-trusty-td-agent2.sh` points to (notice the second HTTP...). So it's "just" a matter of rebuilding things? I have no privileges to do that.

**Comment by a-robinson** [comment]
I'd be very interested in that new setting.

Last time I tried rebuilding the fluentd-es image (pulling the latest fluentd build, as you observed from the Dockerfile), it would just crash-loop because the kubernetes_metadata_filter plugin didn't like that it couldn't reach the apiserver, and I didn't have time to dig into fixing it.

You should be able to build the image and push it to a different registry path for testing it if you need it done soon, otherwise I should be able to get around to checking out the setting and trying to get fluentd-es updated in a few weeks.

**Comment by jimmidyson** [comment]
I'm looking at that now.

BTW the workaround for the `Cannot get new connection from pool` error is detailed [here](https://discuss.elastic.co/t/elasitcsearch-ruby-raises-cannot-get-new-connection-from-pool-error/36252/10) - set `reload_connections false` in the Elasticsearch plugin config.

**Comment by jimmidyson** [comment]
@a-robinson I've just rebuilt a new version of the Docker image we use for our fluentd Kubernetes logging to ES & all works fine without any changes. Here's the [source repo](https://github.com/fabric8io/docker-fluentd-kubernetes). Happy to take a look at what's happening for you if you can send on logs, Dockerfile, etc (link above doesn't work btw).

**Comment by a-robinson** [comment]
I haven't tried it recently, so I'm happy to trust that it works for you.

And sorry about the link above, I've fixed it now.

**Comment by therc** [comment]
@jimmidyson it looks like your image failed to build somehow?
https://hub.docker.com/r/fabric8/fluentd-kubernetes/builds/bxmti5grn6xwzmvu66nngyx/

**Comment by jimmidyson** [comment]
@therc Thanks - saw that yesterday but can't figure out a way to retrigger the build - Docker hub builds interface seriously needs work. Will re-tag in git & see if that works.

**Comment by jimmidyson** [comment]
Built successfully now - I assume Docker hub has a rubygems cache that was out of date & has caught up now.

**Comment by therc** [comment]
I've been using the very latest fabric8/fluentd-kubernetes image with a bunch of tweaks, including `type elasticsearch_dynamic`. It's better, but I can still get it to fill up buffers. The worst part is that it's very opaque, even after inspecting the logs. It would be nice if fluentd (or anything else doing the same thing) had an HTTP endpoint reporting for each file the timestamp of the last log entry read from disk and the last one forwarded, etc.

Installing netstat on a "healthy" and relatively idle instance, I notice that it doesn't keep connections alive:

```
tcp        0      0 10.68.2.5:49694         10.69.215.79:9200       TIME_WAIT  
tcp        0      0 10.68.2.5:49750         10.69.215.79:9200       TIME_WAIT  
tcp        0      0 10.68.2.5:49774         10.69.215.79:9200       TIME_WAIT  
tcp        0      0 10.68.2.5:49792         10.69.215.79:9200       TIME_WAIT  
[...]
```

In a broken instance (which had stopped logged after ingesting about 900 entries/s for three hours), there are no connections open or even attempted. I have noticed that this can happen more easily if kube-dns has issues. This is even with `reload_connections false` and `resurrect_after 3` (`retry_on_failure` is set to 5 by fluent-plugin-elasticsearch...). I know that `reload_connections` tells it whether to discover nodes, which breaks for people like me who use AWS ES (and that's why it's set to false), but I would expect the old connection to get resurrected or retried when it fails.

**Comment by goltermann** [comment]
Adding P2 priority, removing from v1.3 milestone.  Adjust if that's not right.

**Comment by Crassirostris** [comment]
Closing. Issue is obsolete, we set it already
