### ISSUE TITLE
Can't use service IP from inside the pod that backs the service

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#22717]
To reproduce, create a pod running a simple HTTP server and create a service for it:

web-test.yaml
```
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: web-test
  name: web-test
  namespace: default
spec:
  replicas: 1
  selector:
    app: web-test
  template:
    metadata:
      labels:
        app: web-test
    spec:
      containers:
      - image: python:2.7
        name: web-test
        terminationMessagePath: /dev/termination-log
        args:
        - python
        - -m
        - SimpleHTTPServer
        ports:
        - containerPort: 8000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: web-test
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: web-test
  sessionAffinity: None
  type: ClusterIP
```
```
kubectl create -f web-test.yaml
```

I was able to curl it from another pod:
```
$ kubectl exec -it another-pod -- curl -v web-test:8000
* Rebuilt URL to: web-test:8000/
* Hostname was NOT found in DNS cache
*   Trying 10.3.0.45...
* Connected to web-test (10.3.0.45) port 8000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: web-test:8000
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: SimpleHTTP/0.6 Python/2.7.11
< Date: Tue, 08 Mar 2016 22:43:06 GMT
< Content-type: text/html; charset=UTF-8
< Content-Length: 810
<
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><html>
<title>Directory listing for /</title>
<body>
<h2>Directory listing for /</h2>
<hr>
<ul>
<li><a href=".dockerenv">.dockerenv</a>
<li><a href=".dockerinit">.dockerinit</a>
<li><a href="bin/">bin/</a>
<li><a href="boot/">boot/</a>
<li><a href="dev/">dev/</a>
<li><a href="etc/">etc/</a>
<li><a href="home/">home/</a>
<li><a href="lib/">lib/</a>
<li><a href="lib64/">lib64/</a>
<li><a href="media/">media/</a>
<li><a href="mnt/">mnt/</a>
<li><a href="opt/">opt/</a>
<li><a href="proc/">proc/</a>
<li><a href="root/">root/</a>
<li><a href="run/">run/</a>
<li><a href="sbin/">sbin/</a>
<li><a href="srv/">srv/</a>
<li><a href="sys/">sys/</a>
<li><a href="tmp/">tmp/</a>
<li><a href="usr/">usr/</a>
<li><a href="var/">var/</a>
</ul>
<hr>
</body>
</html>
* Closing connection 0
```

But curling from the web-test pod itself fails:
```
$ kubectl exec -it web-test-ts14s -- curl -v web-test:8000
* Rebuilt URL to: web-test:8000/
* Hostname was NOT found in DNS cache
*   Trying 10.3.0.45...
```

We are using v1.2.0-alpha.8 for the master components and kubelet is on v1.2.0-alpha.6.

EDIT: correcting the versions we are using.

**Comment by guoshimin** [comment]
cc @thomaso-mirodin

**Comment by ArtfulCoder** [comment]
Hairpin mode might not be set on veth, or bridge is not in promiscuous mode.
Can you check ?
You can verify yourself.
`cat /sys/devices/virtual/net/docker0/brif/veth*/hairpin_mode`
It should be '1', not '0'..

you can do the following:
`ip link set docker0 promisc on` and it should solve the issue..

**Comment by ArtfulCoder** [comment]
can you paste the cmd args with which kubelet was started ?

**Comment by guoshimin** [comment]
hairpin mode is already set to 1:
```
core@ip-10-20-9-217 ~ $ cat /sys/devices/virtual/net/docker0/brif/veth*/hairpin_mode
1
1
1
1
1
1
```
kubelet started with
```
/usr/bin/kubelet
--api_servers=https://10.20.0.10
--register-node=true
--allow-privileged=true
--config=/etc/kubernetes/manifests
--cluster_dns=10.3.0.10
--cluster_domain=cluster.local
--cloud-provider=aws
--kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml
--tls-cert-file=/etc/kubernetes/ssl/worker.pem
--tls-private-key-file=/etc/kubernetes/ssl/worker-key.pem
--node-labels={"pool":"default"}
```

I made a mistake in the original issue description. Actually kubelet is running version v1.2.0-alpha.6, but the master components are running v1.2.0-alpha.8.

**Comment by ArtfulCoder** [comment]
can you try `ip link set docker0 promisc on` and see if it fixes it.
If not, can you do 
`sudo iptables-save` and `ip addr show` on the failing node.

**Comment by guoshimin** [comment]
Setting promisc doesn't fix it. Here's `ip addr show`:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 02:c9:7e:7d:9e:59 brd ff:ff:ff:ff:ff:ff
    inet 10.20.9.217/22 brd 10.20.11.255 scope global dynamic eth0
       valid_lft 2345sec preferred_lft 2345sec
    inet6 fe80::c9:7eff:fe7d:9e59/64 scope link
       valid_lft forever preferred_lft forever
3: flannel0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 8973 qdisc noqueue state UNKNOWN group default qlen 500
    link/none
    inet 10.2.41.0/16 scope global flannel0
       valid_lft forever preferred_lft forever
4: docker0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 8973 qdisc noqueue state UP group default
    link/ether 02:42:f8:1a:55:cb brd ff:ff:ff:ff:ff:ff
    inet 10.2.41.1/24 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:f8ff:fe1a:55cb/64 scope link
       valid_lft forever preferred_lft forever
280: vethe0ee54c@if279: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8973 qdisc noqueue master docker0 state UP group default
    link/ether f2:9f:5a:88:8a:48 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::f09f:5aff:fe88:8a48/64 scope link
       valid_lft forever preferred_lft forever
294: vethf8619d4@if293: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8973 qdisc noqueue master docker0 state UP group default
    link/ether 0e:c5:b6:d2:2d:63 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::cc5:b6ff:fed2:2d63/64 scope link
       valid_lft forever preferred_lft forever
298: veth3afddf6@if297: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8973 qdisc noqueue master docker0 state UP group default
    link/ether ea:d1:0b:77:19:aa brd ff:ff:ff:ff:ff:ff
    inet6 fe80::e8d1:bff:fe77:19aa/64 scope link
       valid_lft forever preferred_lft forever
300: veth14b5906@if299: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8973 qdisc noqueue master docker0 state UP group default
    link/ether ca:bb:a0:23:73:e0 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::c8bb:a0ff:fe23:73e0/64 scope link
       valid_lft forever preferred_lft forever
308: vethf9f4e23@if307: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8973 qdisc noqueue master docker0 state UP group default
    link/ether 3e:f8:8f:49:7d:b8 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::3cf8:8fff:fe49:7db8/64 scope link
       valid_lft forever preferred_lft forever
242: vethf1bcf55@if241: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8973 qdisc noqueue master docker0 state UP group default
    link/ether 96:4a:55:cc:e6:c1 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::944a:55ff:fecc:e6c1/64 scope link
       valid_lft forever preferred_lft forever
```

iptables has confidential information in it. Is there some way I can share it with you in private?

**Comment by ArtfulCoder** [comment]
you can email me at abshah@google, though I must say that I don't really own my work email :)

**Comment by ArtfulCoder** [comment]
You are hitting this: #20391

**Comment by ArtfulCoder** [comment]
can you try `ip link set flannel0 promisc on` ? I have never tried this..

**Comment by thomaso-mirodin** [comment]
@ArtfulCoder Setting promisc on flannel0 doesn't appear to change the behavior

```
$ ip addr show flannel0
3: flannel0: <POINTOPOINT,MULTICAST,NOARP,PROMISC,UP,LOWER_UP> mtu 8973 qdisc noqueue state UNKNOWN group default qlen 500
    link/none
    inet 10.2.41.0/16 scope global flannel0
       valid_lft forever preferred_lft forever
```
```
root@web-test-ts14s:/# curl -v web-test:8000
* Rebuilt URL to: web-test:8000/
* Hostname was NOT found in DNS cache
*   Trying 10.3.0.45...
* connect to 10.3.0.45 port 8000 failed: Connection timed out
* Failed to connect to web-test port 8000: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to web-test port 8000: Connection timed out
```

**Comment by AdoHe** [comment]
@thomaso-mirodin can you try `kubectl get service web-test` to get your service cluster ip and then `curl -v <service_cluster_ip>:8000`?

**Comment by thomaso-mirodin** [comment]
Same issue:

```
root@web-test-ts14s:/# curl -v 10.3.0.45:8000
* Rebuilt URL to: 10.3.0.45:8000/
* Hostname was NOT found in DNS cache
*   Trying 10.3.0.45...
* connect to 10.3.0.45 port 8000 failed: Connection timed out
* Failed to connect to 10.3.0.45 port 8000: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to 10.3.0.45 port 8000: Connection timed out
```

**Comment by ArtfulCoder** [comment]
Yes, hairpin mode in a flannel setup seems to not work. 
This is a dup issue of #20391

**Comment by cheyang** [comment]
@thomaso-mirodin 
Can you try?
1. service kubelet stop
2. service kube-proxy stop
3. service docker stop
4. service flanneld stop
5. iptables -t nat -F
6. service kube-proxy start
7. service flanneld start
8. service docker start
9. service kubelet start

The key is to start kube-proxy first then flannel. @ArtfulCoder do you think this work around can be applied? And is there any potential issue?

**Comment by ArtfulCoder** [comment]
If this works, we could consider adding this to flannel logic..

**Comment by guoshimin** [comment]
Actually, after I upgrade kubelet to 1.2.0-beta.0, I can't reproduce the
problem anymore. The POSTROUTING chain now looks like:

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
KUBE-POSTROUTING  all  --  0.0.0.0/0            0.0.0.0/0            /*
kubernetes postrouting rules */
FLANNEL    all  --  10.2.0.0/16          0.0.0.0/0
MASQUERADE  all  -- !10.2.0.0/16          10.2.0.0/16
MASQUERADE  tcp  --  10.2.2.24            10.2.2.24            tcp dpt:443
MASQUERADE  tcp  --  10.2.2.24            10.2.2.24            tcp dpt:80

**Comment by guoshimin** [comment]
Is the problem fixed in 1.2.0-beta.0 or did it happen by chance that
KUBE-POSTROUTING was placed before FLANNEL?

**Comment by ArtfulCoder** [comment]
I suspect its by chance...

**Comment by thockin** [comment]
Dup of #20475
