### ISSUE TITLE
Total priority can overflow

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#24720]
Weight is an int (see [PriorityConfigFactory definition](https://github.com/kubernetes/kubernetes/blob/dae5ac482861382e18b1e7b2943b1b7f333c6a2a/plugin/pkg/scheduler/factory/plugins.go#L53)). Priority can take the range 1-10. Total priority for a node is sum of weight \* priority for each priority function, and the sum is accumulated into an int (see [PrioritizeNodes](https://github.com/kubernetes/kubernetes/blob/dae5ac482861382e18b1e7b2943b1b7f333c6a2a/plugin/pkg/scheduler/generic_scheduler.go#L227)). So obviously the total priority can overflow if someone sets the weight(s) too high.

The weights of all priority functions are compiled in (or specified in config file), so we can check to make sure maximum total priority can't overflow an int (take sum over all priority functions of 10 \* weight of that priority function, and make sure that's smaller than int(MaxUint >> 1) which according to StackOverflow is the way to find out what is max int (math package has max Int32, Int64, etc. but not max Int).

Note that scheduler extender is OK because although the policy runs in a separate process, the weight is specified in scheduler config file (ExtenderConfig struct) and the priority is bounded 1-10 as usual.

**Comment by davidopp** [comment]
We really should also make "score" be an abstract datatype rather than a raw int that is manipulated directly, so we can do things like make sure it is in the range 1-10 (or 0-10 if that's what we want); today the range is inconistent (we say 1-10, but sometimes use 0; probably we should change it to 0-9..).

**Comment by AdoHe** [comment]
I volunteer myself to do this.

**Comment by AdoHe** [comment]
@davidopp I think we can check weight overflow in [getPriorityFunctionConfigs](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/plugins.go#L256) after we get all PriorityConfig. what do you think about this?

**Comment by AdoHe** [comment]
As for "score" I think we can add `type Score int`

**Comment by timothysc** [comment]
Fixed by #24962 - closing.

**Comment by davidopp** [comment]
Tim that PR was closed, not merged. I don't think this is fixed yet.

**Comment by timothysc** [comment]
@davidopp whoops, good catch, just removing milestone then.  

There was a shift that happened yesterday where a bunch of items suddenly came into the 1.6 query.

**Comment by AdoHe** [comment]
@timothysc @davidopp do we still want this fixed? I can re-pick this.

**Comment by davidopp** [comment]
AFAIK it's still broken.

cc/ @kubernetes/sig-scheduling-bugs

**Comment by AdoHe** [comment]
Ok, I will open a PR tomorrow.
