### ISSUE TITLE
Kubernetes hyperkube infinte secrets mounts

### ISSUE THREAD

**Issue by pmoncadaisla** [kubernetes/kubernetes#26864]
Hi,

I'm experiencing a very slow behaviour of my Kubernetes cluster. Evrything starts OK, but passed hours everything starts to be very very slow.

I've noticed that executing "mount" I can see nearly infinite (thousands) mounts like these ones:

![mount](https://cloud.githubusercontent.com/assets/1449482/15808341/dcf9f2a8-2b75-11e6-9ee5-bb5f5b807315.png)

Also, there seems to be a process called "findmnt" running:

![findmnt](https://cloud.githubusercontent.com/assets/1449482/15808343/f1da6ff4-2b75-11e6-8bef-c8def5964e8a.png)

I'm using:

```
Docker: 1.6.2
Hyperkube: 1.2.1
Ubuntu: 14.04
```

![dockerversion](https://cloud.githubusercontent.com/assets/1449482/15808350/1493b348-2b76-11e6-823f-abb8926bbd3c.png)

![kubectlversion](https://cloud.githubusercontent.com/assets/1449482/15808353/1bf885fa-2b76-11e6-96e0-b56fd915d047.png)

![dist](https://cloud.githubusercontent.com/assets/1449482/15808351/18ff5b08-2b76-11e6-8cd7-1799a7c0553a.png)

I've tried to upgrade to:

```
Docker: 1.9.1
Hyperkube: 1.2.3
```
but the result was the same :(

I've also tried to run Kubernetes directly using the kubelet binary, outside Hyperkube, and everything seemed OK, no more infinite mounts, and good speed, but everything was planned to use Hyperkube, and also I really want to know what is going wrong.

**Comment by jason-kane** [comment]
This looks like a dupe of https://github.com/kubernetes/kubernetes/issues/25489

**Comment by dims** [comment]
and of https://github.com/kubernetes/kubernetes/issues/26996

**Comment by pmorie** [comment]
This is a dupe, yes.  Fundamentally the problem is that the mount point isn't propagating back into the mount ns of the container where the hyperkube process is running.

**Comment by jingxu97** [comment]
I think https://github.com/kubernetes/kubernetes/pull/27054 should fix the issue of  infinite (thousands) mounts

**Comment by matchstick** [comment]
Closing. We believe 1.3.4 addresses this. Re-open if we are mistaken.

**Comment by nahadra** [comment]
I have the same (or a similar) issue on 1.4.6 with hyperkube to the point where new mounts are responding with "No space left on device" keeping new Pods from starting.

```
Dec 29 20:56:53 k8s-agentpool1-18640404-0 docker[48641]: Output: mount: mount tmpfs on /var/lib/kubelet/pods/7b7042b0-cde3-11e6-88cf-000d3a21595b/volumes/kubernetes.io~secret/default-token-winew failed: No space left on device
```

The number of mounts was at approx. 90k. I subsequently drained the node, by now (~1 hour) they have reduced to approx. 80k. New mounts are still appearing every couple of seconds though:
```
Dec 29 21:18:10 k8s-agentpool1-18640404-0 docker[48641]: I1229 21:18:10.303224   48724 operation_executor.go:900] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/7b63983f-cde3-11e6-88cf-000d3a21595b-default-token-winew" (spec.Name: "default-token-winew") pod "7b63983f-cde3-11e6-88cf-000d3a21595b" (UID: "7b63983f-cde3-11e6-88cf-000d3a21595b").
Dec 29 21:18:13 k8s-agentpool1-18640404-0 docker[48641]: I1229 21:18:13.209584   48724 operation_executor.go:900] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/7b686b3a-cde3-11e6-88cf-000d3a21595b-default-token-winew" (spec.Name: "default-token-winew") pod "7b686b3a-cde3-11e6-88cf-000d3a21595b" (UID: "7b686b3a-cde3-11e6-88cf-000d3a21595b").
Dec 29 21:18:18 k8s-agentpool1-18640404-0 docker[48641]: I1229 21:18:18.222792   48724 operation_executor.go:900] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/a3ab5140-cdd6-11e6-88ce-000d3a21595b-default-token-winew" (spec.Name: "default-token-winew") pod "a3ab5140-cdd6-11e6-88ce-000d3a21595b" (UID: "a3ab5140-cdd6-11e6-88ce-000d3a21595b").
Dec 29 21:18:45 k8s-agentpool1-18640404-0 docker[48641]: I1229 21:18:45.218138   48724 operation_executor.go:900] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/7b7042b0-cde3-11e6-88cf-000d3a21595b-default-token-winew" (spec.Name: "default-token-winew") pod "7b7042b0-cde3-11e6-88cf-000d3a21595b" (UID: "7b7042b0-cde3-11e6-88cf-000d3a21595b").
Dec 29 21:18:49 k8s-agentpool1-18640404-0 docker[48641]: I1229 21:18:49.227428   48724 operation_executor.go:900] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/7b6db718-cde3-11e6-88cf-000d3a21595b-default-token-winew" (spec.Name: "default-token-winew") pod "7b6db718-cde3-11e6-88cf-000d3a21595b" (UID: "7b6db718-cde3-11e6-88cf-000d3a21595b").`
```

Obviously it's all about the kubernetes.io~secret volumes.
```
:/# mount | sort | uniq | wc
49     294    4594

:/# mount | grep -e "^tmpfs.*kubelet" | wc
  81910  491460 11631220

:/# mount | sort | uniq | grep -e "^tmpfs.*kubelet"
tmpfs on /var/lib/kubelet/pods/7b63983f-cde3-11e6-88cf-000d3a21595b/volumes/kubernetes.io~secret/default-token-winew type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/7b686b3a-cde3-11e6-88cf-000d3a21595b/volumes/kubernetes.io~secret/default-token-winew type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/7b6db718-cde3-11e6-88cf-000d3a21595b/volumes/kubernetes.io~secret/default-token-winew type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/7b7042b0-cde3-11e6-88cf-000d3a21595b/volumes/kubernetes.io~secret/default-token-winew type tmpfs (rw,relatime)
tmpfs on /var/lib/kubelet/pods/a3ab5140-cdd6-11e6-88ce-000d3a21595b/volumes/kubernetes.io~secret/default-token-winew type tmpfs (rw,relatime)
```

The cluster was setup a couple of hours before using an ace-engine-based template on Azure and consisted of one master / one agent. The agent has one azureDisk attached and only one pod (mongod) had been deployed.
