### ISSUE TITLE
APIserver is terminating all watchers from time to time

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#30873]
### Extracted from #30275

In our large tests, it sometimes happens that apiserver is terminating all/most of the watchers.

An example:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-kubemark-500-gce/4686/

- apiserver is always up and is processing a lot of requests all the time (which means it's not a network issue)
- but there are few moments in the test where a significant number of watchers are closed (way quicker then there should be).

In particular in case of the second test there were at least two such moments:
1. ~13:39:41 (time from logs)
```
...
I0809 13:39:41.497914    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.3.39&resourceVersion=17389&timeoutSeconds=536: (33.892785604s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.231.110:57973]
I0809 13:39:41.497916    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.2.14&resourceVersion=16789&timeoutSeconds=536: (34.968920904s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.18.43:38906]
I0809 13:39:41.497919    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.4.15&resourceVersion=17392&timeoutSeconds=366: (33.640344206s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.24.152:60031]
I0809 13:39:41.497928    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.1.58&resourceVersion=16789&timeoutSeconds=507: (34.963146228s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.25.90:35762]
I0809 13:39:41.497945    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.2.67&resourceVersion=16789&timeoutSeconds=513: (35.090430152s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.18.43:46009]
I0809 13:39:41.497948    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.4.39&resourceVersion=16789&timeoutSeconds=564: (34.959931515s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.24.152:38906]
I0809 13:39:41.497950    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.3.24&resourceVersion=17393&timeoutSeconds=564: (33.688039271s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.231.110:38967]
I0809 13:39:41.497953    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.2.62&resourceVersion=16789&timeoutSeconds=513: (34.964669113s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.18.43:56791]
I0809 13:39:41.497959    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.2.48&resourceVersion=17404&timeoutSeconds=536: (33.652193737s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.18.43:55422]
I0809 13:39:41.497959    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.5.20&resourceVersion=17393&timeoutSeconds=564: (33.711206555s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 8.34.213.114:49079]
I0809 13:39:41.497962    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.4.56&resourceVersion=17414&timeoutSeconds=536: (33.620345152s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.24.152:59221]
I0809 13:39:41.497961    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.1.70&resourceVersion=17431&timeoutSeconds=494: (33.592134879s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.25.90:52562]
I0809 13:39:41.497966    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.3.83&resourceVersion=16789&timeoutSeconds=586: (35.101574001s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.231.110:37949]
I0809 13:39:41.497967    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.2.12&resourceVersion=17390&timeoutSeconds=536: (33.8263252s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.18.43:40892]
I0809 13:39:41.497980    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.3.45&resourceVersion=17389&timeoutSeconds=384: (33.877920883s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.231.110:51379]
I0809 13:39:41.497980    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.1.87&resourceVersion=16789&timeoutSeconds=578: (35.27377718s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.25.90:36796]
I0809 13:39:41.497979    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.3.88&resourceVersion=16789&timeoutSeconds=586: (35.013737514s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.231.110:36263]
I0809 13:39:41.498001    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.4.30&resourceVersion=16789&timeoutSeconds=408: (35.178363401s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.24.152:47180]
I0809 13:39:41.497980    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.6.5&resourceVersion=16789&timeoutSeconds=408: (35.202575621s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.210.235:45220]
I0809 13:39:41.497994    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.1.27&resourceVersion=16789&timeoutSeconds=408: (34.974759999s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.25.90:44591]
I0809 13:39:41.497991    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.5.76&resourceVersion=17393&timeoutSeconds=404: (33.627268875s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 8.34.213.114:59383]
I0809 13:39:41.498097    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.6.42&resourceVersion=16789&timeoutSeconds=376: (34.9969969s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.210.235:45849]
I0809 13:39:41.498101    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.2.51&resourceVersion=17390&timeoutSeconds=322: (33.582194456s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.18.43:49728]
I0809 13:39:41.498001    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.5.39&resourceVersion=16789&timeoutSeconds=384: (35.274169258s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 8.34.213.114:49030]
I0809 13:39:41.498004    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.1.72&resourceVersion=16789&timeoutSeconds=513: (35.081200676s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.25.90:40747]
I0809 13:39:41.498115    3183 handlers.go:164] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3D10.180.3.30&resourceVersion=16789&timeoutSeconds=408: (35.057350323s) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/ae40543] 104.198.231.110:34415]
...
```

There were 506 watchers that were stopped at that time.

Exactly the similar thing happened 14:12:06.

The logs that I added confirm that it sometime happens.
As an example in the last 2000-node kubemark run:
http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-kubemark-gce-scale/1336/
It happened twice over the whole test (exluding the beginning of the test which is expected):
```
[This is from the apiserver startup]
W0811 02:50:58.306332    3571 cacher.go:442] Terminating all watchers from cacher *api.Pod
...
W0811 03:29:09.604262    3571 cacher.go:442] Terminating all watchers from cacher *api.Pod
...
W0811 03:29:13.553648    3571 cacher.go:442] Terminating all watchers from cacher *api.Pod
...
```

Looking into the code:
- this is called
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/cacher.go#L240
- but this log is not present in logs:
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/cacher.go#L246

Which means that ListAndWatch was finished without any error after ~40 minutes of running.

Looking deeper into logs, I found those two:
```
W0811 03:29:08.594184    3571 reflector.go:334] pkg/storage/cacher.go:189: watch of *api.Pod ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [944217/944214]) [945216]
...
W0811 03:29:12.553476    3571 reflector.go:334] pkg/storage/cacher.go:189: watch of *api.Pod ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [948812/948772]) [949811]
```

which shows that we simply run out of the history window in etcd.

The questions is why... (maybe Resync() is blocking store for too long? or sth like that?)

@xiang90 @hongchaodeng @kubernetes/sig-scalability

**Comment by wojtek-t** [comment]
The same happened here:
http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-kubemark-gce-scale/1352/console

**Comment by wojtek-t** [comment]
So in the run mentioned above I'm seeing this in the logs:
```
W0818 13:44:21.956410    3550 reflector.go:330] pkg/storage/cacher.go:191: watch of *api.Pod ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2046159/2046048]) [2047158]
...
W0818 13:44:22.956675    3550 cacher.go:439] Terminating all watchers from cacher *api.Pod
```

which suggests that:
- either we weren't able to process events from etcd fast enough
- or etcd weren't able to send them fast enough
- is something else possible?

@hongchaodeng @xiang90 ^^

**Comment by hongchaodeng** [comment]
> http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-kubemark-gce-scale/1352/console

Unable to access the link

**Comment by hongchaodeng** [comment]
In the log, it shows (maximum buffer size is 100):
```
$ cat apiserver.log|grep "objects queued"
I0812 17:50:31.355026    3243 etcd_watcher.go:311] watch: 1 objects queued in channel.
I0812 17:53:04.509500    3243 etcd_watcher.go:311] watch: 2 objects queued in channel.
I0812 17:53:09.859167    3243 etcd_watcher.go:311] watch: 19 objects queued in channel.
I0812 17:53:16.817342    3243 etcd_watcher.go:311] watch: 21 objects queued in channel.
I0812 17:53:17.324558    3243 etcd_watcher.go:311] watch: 33 objects queued in channel.
I0812 17:53:18.017668    3243 etcd_watcher.go:311] watch: 34 objects queued in channel.
I0812 17:53:18.069740    3243 etcd_watcher.go:311] watch: 47 objects queued in channel.
I0812 17:53:18.207544    3243 etcd_watcher.go:311] watch: 85 objects queued in channel.
I0812 17:53:20.082776    3243 etcd_watcher.go:311] watch: 100 objects queued in channel.
```

This is **fast producer, slow consumer** scenario.

I am able to reproduce it with the following simple program (I couldn't reproduce it on e2e test).

```go
func main() {
	cfg := client.Config{
		Endpoints: []string{"http://127.0.0.1:2379"},
	}

	c, err := client.New(cfg)
	if err != nil {
		panic(err)
	}

	kv := client.NewKeysAPI(c)
	w := kv.Watcher("/abc", &client.WatcherOptions{
		Recursive: true,
	})

	resultCh := make(chan string, 10)

	go func() {
		for {
			resp, err := w.Next(context.TODO())
			if err != nil {
				fmt.Println("haha:", err)
				os.Exit(1)
			}
			key := resp.Node.Key
			resultCh <- key
		}
	}()

	go func() {
		for {
			key := <-resultCh
			fmt.Println(key)
			time.Sleep(1 * time.Second)
		}
	}()

	i := 0
	for {
		key := fmt.Sprintf("/abc/%d", i)
		kv.Set(context.TODO(), key, "haha", nil)
		i++
		if i%100 == 0 {
			time.Sleep(100 * time.Millisecond)
		}
	}
}
```

In this case, it will have the same error:
```
haha: 401: The event in requested index is outdated and cleared (the requested history has been cleared [103/30]) [1102]
```

cc @smarterclayton @timothysc

**Comment by hongchaodeng** [comment]
xref: #29888

**Comment by xiang90** [comment]
@wojtek-t 

> either we weren't able to process events from etcd fast enough

This is more likely. etcd does not block on sending. If the consumer is slow and buffer is full, it will simply close the watcher for v2.

**Comment by wojtek-t** [comment]
@hongchaodeng - the logs you pasted can suggest problems, but are not 100% explanation

I looked into logs from 1352 run (pasted above) and there are:
```
I0818 12:10:12.352551    3550 etcd_watcher.go:311] watch: 2 objects queued in channel.
I0818 12:10:52.421008    3550 etcd_watcher.go:311] watch: 4 objects queued in channel.
I0818 12:13:44.844968    3550 etcd_watcher.go:311] watch: 6 objects queued in channel.
I0818 12:15:23.004596    3550 etcd_watcher.go:311] watch: 8 objects queued in channel.
I0818 12:15:23.022320    3550 etcd_watcher.go:311] watch: 9 objects queued in channel.
I0818 12:15:23.029543    3550 etcd_watcher.go:311] watch: 10 objects queued in channel.
I0818 12:16:55.857604    3550 etcd_watcher.go:311] watch: 12 objects queued in channel.
I0818 12:16:55.860587    3550 etcd_watcher.go:311] watch: 14 objects queued in channel.
I0818 12:17:08.899208    3550 etcd_watcher.go:311] watch: 38 objects queued in channel.
I0818 12:17:08.902300    3550 etcd_watcher.go:311] watch: 43 objects queued in channel.
I0818 12:17:43.697028    3550 etcd_watcher.go:311] watch: 47 objects queued in channel.
I0818 12:17:43.705607    3550 etcd_watcher.go:311] watch: 50 objects queued in channel.
I0818 12:18:44.317154    3550 etcd_watcher.go:311] watch: 69 objects queued in channel.
I0818 12:23:59.028772    3550 etcd_watcher.go:311] watch: 100 objects queued in channel.
```

But watchers are terminated much later:
```
W0818 12:09:46.390773    3550 cacher.go:439] Terminating all watchers from cacher *rbac.ClusterRoleBinding
W0818 13:44:22.956675    3550 cacher.go:439] Terminating all watchers from cacher *api.Pod
```

Though sure - it may be related to apiserver too slow - I will try to look into it, but probably not today...

**Comment by wojtek-t** [comment]
I've merged this trivial PR:
https://github.com/kubernetes/kubernetes/pull/30985

I'm not 100% sure it will fully solve the problem, but my feeling is that it may significantly help.

**Comment by hongchaodeng** [comment]
The context of above statement is that we already know the error "401: The event in requested index is outdated and cleared" was the root cause and it caused termination of all watchers. Then it boils down to why we had this error and how did it happen?

The root problem is still that we have **fast producer, slow consumer** and we should threshold on that. At least the storage layer could and should return error and back-pressure it.

**Comment by hongchaodeng** [comment]
@timothysc @wojtek-t 
In etcd3, data are kept in MVCC store and wouldn't be cleared unless we compact them.

**Comment by wojtek-t** [comment]
Actually, it seems that:
- #30985  and
- fixing https://github.com/kubernetes/kubernetes/issues/30975
solved the problem in our tests.

So I'm closing this issue (at least for now).

**Comment by timothysc** [comment]
@wojtek-t looked at the fixes for this and they seem weirdly brittle.  

I think we should aim to fix the http2 blockers in next cycle.

**Comment by wojtek-t** [comment]
>
@wojtek-t looked at the fixes for this and they seem weirdly brittle.

Why? The one that is increasing size of the channel is expected that it will help, because before it required synchronization.
The latter with 429 errors is also expected, if 429 errors is happening suddenly load on apiserver dramatically increases, because we are doing full handshakes, which is overloading apiserver more and more.
It isn't surprising to me.

>
I think we should aim to fix the http2 blockers in next cycle.

That is a separate thing - and yes, we should try to enable it.
