### ISSUE TITLE
GLBC occasionally reverting Deployment defined probe health-check to the default path of '/'

### ISSUE THREAD

**Issue by joonathan** [kubernetes/kubernetes#31222]
We are seeing an issue on GKE (running 1.3.5 both on nodes and master) where GLBC occasionally reverts http-health-checks back to the default value of '/' instead of using the readinessProbe value defined in Deployment.

Initially on Ingress creation the http-health-checks were created correctly.
As we are running on GKE I don't have logs from Master (GLBC).

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:45:16Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:21:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: GKE

**What happened**:

http-health-checks changed from Deolyment defined '/healthz' to the default value of '/'

**What you expected to happen**:

http-health-checks should be controlled by the readinessProbe as per definition and they should not reset to the default value potentially causing service disruption as L7 would mark the backends as being down if there is no route answering on the default '/' path.

**How to reproduce it** (as minimally and precisely as possible):

Have a probe in Deployment configuration:

```
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
            httpHeaders:
              - name: X-Teleport-HealthCheck
                value: http
          initialDelaySeconds: 15
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
            httpHeaders:
              - name: X-Teleport-HealthCheck
                value: http
          initialDelaySeconds: 15
          timeoutSeconds: 3
```

This should produce a http-health-check similar to:

```
> gcloud compute http-health-checks describe k8s-be-31676
checkIntervalSec: 1
creationTimestamp: '2016-06-22T03:50:18.573-07:00'
description: Default kubernetes L7 Loadbalancing health check.
healthyThreshold: 1
host: ''
id: '8294344216172548997'
kind: compute#httpHealthCheck
name: k8s-be-31676
port: 31676
requestPath: /healthz
selfLink: https://www.googleapis.com/compute/v1/projects/teleport-cloud/global/httpHealthChecks/k8s-be-31676
timeoutSec: 1
unhealthyThreshold: 10
```

After some time we saw this switch to `requestPath: /`

**Anything else do we need to know**:

There is also Google Support case with information on this: 10220005

**Comment by gcbirzan** [comment]
We experience the same issue, but we removed the HTTP probes and moved to cmd ones, it still happened.

**Comment by noname85** [comment]
The Ingress controller looks for a compatible readiness probe first, if it finds one, it adopts it as the GCE loadbalancer's HTTP health check. If there's no readiness probe, or the readiness probe requires special HTTP headers, or HTTPS, the Ingress controller points the GCE loadbalancer's HTTP health check at '/' [1]. 

@joonathan I believe that your health check is not working properly  because of the HTTPS headers you set on the Probes.

Notice that when you create the Ingress, there will be a default health check created on "/healthz" for the "default-http-backend" service not to be confused with the health check path you declared on the "readiness probe" that should point to the port of your service.

If the health check path pointing to your service port changed after a while to another path than there is a problem, but I tests here and there is no such problem.

Confirm that you are not mistaken the health check path pointing to the service port, and the default health check that is created with the default "/healthz".

You can check the "default-http-backend" service port running below command:

$ kubectl describe svc default-http-backend --namespace="kube-system"

I also, recommend you to create the deployment with another health check path in order to avoid confusion.

Can you check and confirm if the heaht check path of your service changed ? 

[1] - https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce#user-content-health-checks

**Comment by joonathan** [comment]
We definetley see changes of the path on our backend services and not on the default-http-backend. Initially http-health-check is configured correctly but it will reset and we clearly see LB hitting the default root path instead of the configured one. Fix so far has been to change the path back using gcloud utility, or by removing the service from ingress and after a while adding it back.

**Comment by joonathan** [comment]
I will try to validate the case without the specified httpHeaders property.

**Comment by ptinsley** [comment]
> livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /robots.txt
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1

We are seeing an app with the above liveness probe definition changing to / randomly on deployments.

**Comment by noname85** [comment]
@ptinsley 
- Its changing after deployments? or behaves randomly when deployed ? eg: Once deploys to the proper path other don't

**Comment by ptinsley** [comment]
@noname85 
The deployments file (quoted below) last changed 24 days ago when I first deployed this branch of the app. The areas with {{ are there for Jenkins to sub out to put in the right values based on the branch being built and the id it gave the container it built for each commit.

I've been digging in logs for an hour or so and it's almost impossible to find anything concrete, the audit log for GCP doesn't show when the health check is updated. I have narrowed down (due to load balancer logs) the periods of time where it moved to 502. Going back into the GCE and GKE logs during that period the only API activity I can easily pick out is k8s updating the urlmap for the app in question once a minute. The app was broken for 6 hours (this specific one is non-prod and not monitored) so it's difficult to comb through those logs to find the needle. What API call should I be looking for in the logs that might cause this?

I can say though this isn't tied directly to a deploy, from the LB logs I see the app went to solid 502 responses on the 10th and deploys had been done on the 9th (quite a few hours prior) and on the 12th. So this appears to be an issue with some kind of background sanity check being done vs something during a redeploy.

> ---
  apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    name: "{{APP_NAME}}-app"
  spec:
    revisionHistoryLimit: 5
    template:
      metadata:
        labels:
          app: {{APP_NAME}}
          tier: frontend
      spec:
        containers:
          - name: "{{APP_NAME}}"
            image: "{{CONTAINER_IMAGE}}"
            livenessProbe:
              httpGet:
                path: /robots.txt
                port: 80
                scheme: HTTP
            ports:
            - containerPort: 80
              protocol: TCP
            env:
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: "{{APP_NAME}}"
                  key: "db-url"
            - name: "RAILS_ENV"
              value: "{{RAILS_ENV}}"

**Comment by bprashanth** [comment]
Can you please give me the ingress, service and deployment yaml?

**Comment by ryanschwartz** [comment]
Here you go, @bprashanth - ingress, service, deployment:
```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      ingress.kubernetes.io/backends: '{"k8s-be-31419":"HEALTHY"}'
      ingress.kubernetes.io/forwarding-rule: k8s-fw-default-blm-dev
      ingress.kubernetes.io/target-proxy: k8s-tp-default-blm-dev
      ingress.kubernetes.io/url-map: k8s-um-default-blm-dev
    creationTimestamp: 2016-04-27T21:54:29Z
    generation: 1
    name: blm-dev
    namespace: default
    resourceVersion: "2699685"
    selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/blm-dev
    uid: 9e334d36-0cc2-11e6-ba7e-42010af00040
  spec:
    backend:
      serviceName: blm-dev
      servicePort: 80
  status:
    loadBalancer:
      ingress:
      - ip: XXX.XXX.XXX.XXX
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2016-04-28T17:31:34Z
    labels:
      app: blm-dev
      tier: frontend
    name: blm-dev
    namespace: default
    resourceVersion: "168081"
    selfLink: /api/v1/namespaces/default/services/blm-dev
    uid: 0d7f12ed-0d67-11e6-ba7e-42010af00040
  spec:
    clusterIP: 10.3.244.240
    ports:
    - name: http
      nodePort: 31419
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: blm-dev
      tier: frontend
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "212"
      kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Deployment","apiVersion":"extensions/v1beta1","metadata":{"name":"blm-dev-app","creationTimestamp":null},"spec":{"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"blm-dev","tier":"frontend"}},"spec":{"containers":[{"name":"blm-dev","image":"gcr.io/<project>/blm-dev-app:2016-09-23_17-00-50_528585","ports":[{"containerPort":80,"protocol":"TCP"}],"env":[{"name":"DATABASE_URL","valueFrom":{"secretKeyRef":{"name":"blm-dev","key":"db-url"}}},{"name":"CLOUDSQL_INSTANCES","value":"<project>:us-central1:main-nonprod=tcp:3306"},{"name":"PROXY_SVC_ACCT","valueFrom":{"secretKeyRef":{"name":"blm-dev","key":"sql-svc-acct"}}},{"name":"RAILS_ENV","value":"deployed_dev"}],"resources":{},"livenessProbe":{"httpGet":{"path":"/robots.txt","port":80,"scheme":"HTTP"}}}]}},"strategy":{},"revisionHistoryLimit":5},"status":{}}'
    creationTimestamp: 2016-05-18T20:05:18Z
    generation: 427
    labels:
      app: blm-dev
      tier: frontend
    name: blm-dev-app
    namespace: default
    resourceVersion: "2700831"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/blm-dev-app
    uid: d8003704-1d33-11e6-9302-42010af0019d
  spec:
    replicas: 2
    revisionHistoryLimit: 5
    selector:
      matchLabels:
        app: blm-dev
        tier: frontend
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: blm-dev
          tier: frontend
      spec:
        containers:
        - env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: db-url
                name: blm-dev
          - name: CLOUDSQL_INSTANCES
            value: <project>:us-central1:main-nonprod=tcp:3306
          - name: PROXY_SVC_ACCT
            valueFrom:
              secretKeyRef:
                key: sql-svc-acct
                name: blm-dev
          - name: RAILS_ENV
            value: deployed_dev
          image: gcr.io/<project>/blm-dev-app:2016-09-23_17-00-50_528585
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 80
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: blm-dev
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    observedGeneration: 427
    replicas: 2
    updatedReplicas: 2
kind: List
metadata: {}
```

Also, here is a log entry pulled from Google Cloud Logging for the project that shows the API call that changed the health check in question from `robots.txt` to `/`. There are entries for each time this has happened, all called by the same user/actor.

```
00:17:19.460
compute.httpHealthChecks.update
{"event_timestamp_us":"1474521439460940","event_type":"GCE_API_CALL","request":{"url":"https://www.googleapis.com/compute/v1/projects/<project>/global/httpHealthChecks/k8s-be-31419?alt=json","body":"null"},"ip_address":"","user_agent":"google-api-go-client/0.5,gzip(gfe)","trace_id":"operation-1474521439054-53d11c696a8b1-b048654a-82618511","actor":{"user":"<projectNumber>@cloudservices.gserviceaccount.com"},"resource":{"type":"healthCheck","name":"k8s-be-31419","id":"5373740384437401109","global":true},"version":"1.2","event_subtype":"compute.httpHealthChecks.update","operation":{"type":"operation","name":"operation-1474521439054-53d11c696a8b1-b048654a-82618511","id":"6437662822272784304","global":true}}

{
 metadata: {
  severity: "INFO"    
  projectId: "<project>"    
  serviceName: "compute.googleapis.com"    
  labels: {
   compute.googleapis.com/resource_name: "k8s-be-31419"     
   compute.googleapis.com/resource_type: "healthCheck"     
   compute.googleapis.com/resource_id: "5373740384437401109"     
  }
  timestamp: "2016-09-22T05:17:19.460940Z"    
  projectNumber: "<projectNumber>"    
 }
 insertId: "1do11oufo14sr2"   
 log: "compute.googleapis.com/activity_log"   
 structPayload: {
  event_timestamp_us: "1474521439460940"    
  event_type: "GCE_API_CALL"    
  request: {
   url: "https://www.googleapis.com/compute/v1/projects/<project>/global/httpHealthChecks/k8s-be-31419?alt=json"     
   body: "null"     
  }
  ip_address: ""    
  user_agent: "google-api-go-client/0.5,gzip(gfe)"    
  trace_id: "operation-1474521439054-53d11c696a8b1-b048654a-82618511"    
  actor: {
   user: "<projectNumber>@cloudservices.gserviceaccount.com"     
  }
  resource: {
   type: "healthCheck"     
   name: "k8s-be-31419"     
   id: "5373740384437401109"     
   global: true     
  }
  version: "1.2"    
  event_subtype: "compute.httpHealthChecks.update"    
  operation: {
   type: "operation"     
   name: "operation-1474521439054-53d11c696a8b1-b048654a-82618511"     
   id: "6437662822272784304"     
   global: true     
  }
 }
}
```

**Comment by bprashanth** [comment]
Weird, /robots.txt is a livenss probe and we should only be picking up readiness (https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce#health-checks, https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce/examples/health_checks#limitations). Looking.

**Comment by aronchick** [comment]
Had another customer report this issue today.

**Comment by maltebb** [comment]
That was me @aronchick ;)

**Comment by bprashanth** [comment]
From the previous debug session, you're not allowed to modify the health check. This is usually the case with any Kube controller, if it creates resources on your behalf, doing stuff behind its back will lead to fun and joy. If you set it to the *readiness* probe it will be adopted (see examples in https://github.com/kubernetes/kubernetes/issues/31222#issuecomment-249283356, https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/examples/health_checks/README.md). Otherwise it's the default health check endpoint. If you modify the default to something else the controller will correct it. 

I'm changing this behavior in 1.4.1 to make it so the controller just turns a blind eye after initial creation, till we surface the health check in the resource.

**Comment by joonathan** [comment]
I have not seen any more health-check changes for deployments other than one that still specified httpHeaders for the probe.

```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: X-Teleport-HealthCheck
              value: http
            path: /healthz
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: roaccount-app
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: X-Teleport-HealthCheck
              value: http
            path: /healthz
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
```

Is it expected that this health-check initially gets created correctly to /healthz of the service and later reverts to "/"?

**Comment by bprashanth** [comment]
No, http headers in health checks is currently not supported: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce#health-checks

It should not create /healthz at all, if it is we should fix that. 
Can you give me the ingress/services so I can try to repro?

**Comment by peiwenhu** [comment]
I noticed this as well.
Was previously using plain replication controller and ingress. Then deleted the RC and made a Deployment out of the same RC yaml file.
Then '/' got hit instead of custom livenessprobe 

I don't specify any http header for the probe.

**Comment by bprashanth** [comment]
You can't modify the probe in gce, it'll get reverterd. You also can't use a liveness probe, it needs to be a *readiness* probe. See comments and examples posted above.

**Comment by peiwenhu** [comment]
This is a bulk part of my config, I still see health check set to / when I create completely a new project with it.
Could you help take a look why?
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: websvc-rc
spec:
  replicas: 1
  template:
    metadata:
      name: websvcpod
      labels:
        app: websvcpod
    spec:
      containers:
        - resources:
            limits:
              cpu: 0.1
              memory: 256Mi
          name: websvc-container
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 2            
          ports:
            - containerPort: 8080              
              name: api
```

**Comment by bprashanth** [comment]
Your services needs to also point at 8080, see this example: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/gce/examples/health_checks

**Comment by thockin** [comment]
please reopen if it still exists

**Comment by Legogris** [comment]
This is still hitting us. Use-case: containerized application which listens on HTTP but redirects all non-encrypted HTTP requests to `https://` (using `X-Forwarded-Proto` header).

Deployment with the following probes:
```
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
```

As mentioned above, deploying this on GKE with an Ingress creates a GLBC and an health-check for HTTP on `/`, resulting in 502s.
I can manually change the health-check in the console to be a TCP check instead - which makes things work just as intended - but within less than 5 minutes it becomes overridden and set again to check HTTP on `/` for a 200.

Is there really no easy way around this?
