### ISSUE TITLE
Pod will be created again and again when we have not enough cpu.

### ISSUE THREAD

**Issue by aoxn** [kubernetes/kubernetes#38806]
#### version
```
[root@iZbp14tmy66i2l0ln0vwreZ ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

```
[root@iZbp14tmy66i2l0ln0vwreZ ~]# kubeadm version
kubeadm version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2074+a092d8e0f95f52", GitCommit:"a092d8e0f95f5200f7ae2cba45c75ab42da36537", GitTreeState:"clean", BuildDate:"2016-12-13T17:03:18Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

```
[root@iZbp14tmy66i2l0ln0vwreZ ~]# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64
[root@iZbp14tmy66i2l0ln0vwreZ ~]# docker info
Containers: 16
 Running: 14
 Paused: 0
 Stopped: 2
Images: 16
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-405252-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.742 GB
 Data Space Total: 107.4 GB
 Data Space Available: 29.22 GB
 Metadata Space Used: 3.6 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.703 GiB
Name: iZbp14tmy66i2l0ln0vwreZ
ID: G3CE:GXII:N7FQ:CA27:AIZT:5MRI:GD2M:T4WU:MVAQ:E4VP:SFMX:5R6E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

#### see output

```
[root@iZbp14tmy66i2l0ln0vwreZ ~]# kubectl --namespace=kube-system get po
NAME                                              READY     STATUS              RESTARTS   AGE
dummy-2340867639-qmggs                            1/1       Running             0          55s
etcd-izbp14tmy66i2l0ln0vwrez                      1/1       Running             0          1m
kube-apiserver-izbp14tmy66i2l0ln0vwrez            1/1       Running             0          1m
kube-controller-manager-izbp14tmy66i2l0ln0vwrez   1/1       Running             0          1m
kube-discovery-2798764060-4r96g                   1/1       Running             0          52s
kube-dns-3611717927-038mq                         0/4       OutOfcpu            0          21s
kube-dns-3611717927-14vn6                         0/4       OutOfcpu            0          3s
kube-dns-3611717927-18xhh                         0/4       OutOfcpu            0          27s
kube-dns-3611717927-1th2f                         0/4       OutOfcpu            0          2s
kube-dns-3611717927-21mvg                         0/4       OutOfcpu            0          28s
kube-dns-3611717927-2c1ln                         0/4       OutOfcpu            0          23s
kube-dns-3611717927-2m25g                         0/4       OutOfcpu            0          1s
kube-dns-3611717927-302st                         0/4       OutOfcpu            0          27s
kube-dns-3611717927-34fc2                         0/4       OutOfcpu            0          5s
kube-dns-3611717927-3kl3k                         0/4       OutOfcpu            0          40s
kube-dns-3611717927-3lvzk                         0/4       OutOfcpu            0          7s
kube-dns-3611717927-4cpjq                         0/4       OutOfcpu            0          19s
kube-dns-3611717927-501ms                         0/4       OutOfcpu            0          15s
kube-dns-3611717927-59t74                         0/4       OutOfcpu            0          17s
kube-dns-3611717927-5jcgc                         0/4       OutOfcpu            0          50s
kube-dns-3611717927-5sl2p                         0/4       OutOfcpu            0          5s
kube-dns-3611717927-66l75                         0/4       OutOfcpu            0          29s
kube-dns-3611717927-697wm                         0/4       OutOfcpu            0          32s
kube-dns-3611717927-6xxmd                         0/4       OutOfcpu            0          18s
kube-dns-3611717927-7pw27                         0/4       OutOfcpu            0          25s
kube-dns-3611717927-7xhvx                         0/4       OutOfcpu            0          41s
kube-dns-3611717927-8nvc4                         0/4       OutOfcpu            0          36s
kube-dns-3611717927-8p2t3                         0/4       OutOfcpu            0          26s
kube-dns-3611717927-8wxwv                         0/4       OutOfcpu            0          50s
kube-dns-3611717927-978x6                         0/4       OutOfcpu            0          11s
kube-dns-3611717927-9f71g                         0/4       OutOfcpu            0          34s
kube-dns-3611717927-9mr86                         0/4       OutOfcpu            0          21s
kube-dns-3611717927-9mthz                         0/4       OutOfcpu            0          24s
kube-dns-3611717927-bjwrz                         0/4       OutOfcpu            0          11s
kube-dns-3611717927-bw062                         0/4       OutOfcpu            0          28s
kube-dns-3611717927-c7038                         0/4       OutOfcpu            0          47s
kube-dns-3611717927-cgwdk                         0/4       OutOfcpu            0          44s
kube-dns-3611717927-dkdn9                         0/4       OutOfcpu            0          33s
kube-dns-3611717927-dtg6n                         0/4       OutOfcpu            0          43s
kube-dns-3611717927-dz7dd                         0/4       Pending             0          0s
kube-dns-3611717927-f33bg                         0/4       OutOfcpu            0          7s
kube-dns-3611717927-f753b                         0/4       OutOfcpu            0          44s
kube-dns-3611717927-ff2cs                         0/4       OutOfcpu            0          31s
kube-dns-3611717927-fvbn9                         0/4       OutOfcpu            0          19s
kube-dns-3611717927-j9323                         0/4       OutOfcpu            0          31s
kube-dns-3611717927-j991n                         0/4       OutOfcpu            0          29s
kube-dns-3611717927-jgzbp                         0/4       OutOfcpu            0          13s
kube-dns-3611717927-l2g0t                         0/4       OutOfcpu            0          34s
kube-dns-3611717927-l4t6t                         0/4       OutOfcpu            0          10s
kube-dns-3611717927-lf63x                         0/4       OutOfcpu            0          8s
kube-dns-3611717927-lhj3n                         0/4       OutOfcpu            0          6s
kube-dns-3611717927-lw0rk                         0/4       OutOfcpu            0          25s
kube-dns-3611717927-pbk96                         0/4       OutOfcpu            0          38s
kube-dns-3611717927-pj8d7                         0/4       OutOfcpu            0          42s
kube-dns-3611717927-pmmmt                         0/4       OutOfcpu            0          35s
kube-dns-3611717927-pvxvw                         0/4       OutOfcpu            0          9s
kube-dns-3611717927-pxm54                         0/4       OutOfcpu            0          16s
kube-dns-3611717927-qhq5p                         0/4       OutOfcpu            0          30s
kube-dns-3611717927-rwl3l                         0/4       OutOfcpu            0          12s
kube-dns-3611717927-s1b8g                         0/4       OutOfcpu            0          33s
kube-dns-3611717927-s7wmp                         0/4       OutOfcpu            0          20s
kube-dns-3611717927-s9127                         0/4       OutOfcpu            0          50s
kube-dns-3611717927-sffb4                         0/4       OutOfcpu            0          42s
kube-dns-3611717927-sfsg5                         0/4       OutOfcpu            0          18s
kube-dns-3611717927-sqwfw                         0/4       OutOfcpu            0          10s
kube-dns-3611717927-stk1f                         0/4       OutOfcpu            0          14s
kube-dns-3611717927-t1fdw                         0/4       OutOfcpu            0          45s
kube-dns-3611717927-tcg2r                         0/4       OutOfcpu            0          37s
kube-dns-3611717927-tf7w9                         0/4       OutOfcpu            0          39s
kube-dns-3611717927-tk2zf                         0/4       OutOfcpu            0          22s
kube-dns-3611717927-tkxjl                         0/4       OutOfcpu            0          39s
kube-dns-3611717927-v4c5w                         0/4       OutOfcpu            0          17s
kube-dns-3611717927-vhft0                         0/4       OutOfcpu            0          49s
kube-dns-3611717927-wdgrd                         0/4       OutOfcpu            0          9s
kube-dns-3611717927-x6hqb                         0/4       OutOfcpu            0          36s
kube-dns-3611717927-xgnm3                         0/4       OutOfcpu            0          49s
kube-dns-3611717927-xmh0l                         0/4       OutOfcpu            0          15s
kube-dns-3611717927-xmp5c                         0/4       OutOfcpu            0          4s
kube-dns-3611717927-xrlvb                         0/4       OutOfcpu            0          23s
kube-proxy-q8xf9                                  1/1       Running             0          50s
kubernetes-dashboard-3761021483-6xl56             0/1       ContainerCreating   0          49s
```

**Comment by thockin** [comment]
@boweidu

**Comment by tianyouhui** [comment]
+1 for this problem... what can we do?

**Comment by resouer** [comment]
It seems this is expected?

k8s will not delete user's pod unless it is told to, or under specific resource pressure (cpu is not one of them because it it compressible , see: http://kubernetes.io/docs/admin/out-of-resource/).

**Comment by thockin** [comment]
The fact that it is always DNS makes one wonder if DNS needs more resources
assigned, and under what conditions.

**Comment by tianyouhui** [comment]
I found that when i deleted /etc/cni/net.d/* and reset kubernetes(clean up and reinstall), it becomes ok... there's only one pod @spacexnic

**Comment by dbaumgarten** [comment]
I encountered this problem when trying to install Kubernetes using kubeadm on a set of single-cpu VMs. 
It seems that all the pods started by kubeadm together request slightly more than one full cpu. The kube-dns pod is started last and can't get all the cpu it requests, so it fails to schedule.
As soon as an other node joins the cluster, the dns pod is sheduled to the new node and the create-OutOfCPU-fail-loop stops. 
When changing the flavor of the master VM, so the master has 2 cpus, kube-dns can successfully start on the master and there are no errors.

**Comment by grodrigues3** [comment]
+1.  This is still causing problems.  Fixed by upping the size of VMs in my cluster

**Comment by cmluciano** [comment]
Possibly related https://github.com/kubernetes/kubernetes/issues/42910

**Comment by yvespp** [comment]
Same issue as #42433?

**Comment by mozhata** [comment]
encountered some problem

```
pod/r-project-xiaohou-19-594f4b5f67-4whvp   0/1     OutOfcpu   0          8m53s
pod/r-project-xiaohou-19-594f4b5f67-5f6h6   0/1     OutOfcpu   0          8m52s
pod/r-project-xiaohou-19-594f4b5f67-b6h2p   0/1     OutOfcpu   0          8m51s
pod/r-project-xiaohou-19-594f4b5f67-d852s   0/1     OutOfcpu   0          8m51s
pod/r-project-xiaohou-19-594f4b5f67-dmg6s   0/1     OutOfcpu   0          8m53s
pod/r-project-xiaohou-19-594f4b5f67-gvxtb   0/1     OutOfcpu   0          8m52s
pod/r-project-xiaohou-19-594f4b5f67-pbtwj   1/1     Running    0          8m51s
pod/r-project-xiaohou-19-594f4b5f67-whl9r   0/1     OutOfcpu   0          8m52s
pod/r-project-xiaohou-19-594f4b5f67-zs4n8   0/1     OutOfcpu   0          8m52s
```
I thought pod should keep pending rather than create a new pod 
what should I do to avoid this ?

**Comment by raweber42** [comment]
We are still encountering this on version 1.30.6 😅 

Are there any best practices in regards to getting rid of `OutofCpu pods`?

Right now, I am simply manually deleting those pods effected, but this can't be it...

**Comment by thockin** [comment]
Since this bug is 8 years old and has not been updated in 5 years, can you perhaps post a full description of the problem as you experience it today?

What is the Pod's CPU request?  How much is available in the cluster? Etc.

**Comment by AshinWu** [comment]
> We are still encountering this on version 1.30.6 😅
> 
> Are there any best practices in regards to getting rid of `OutofCpu pods`?
> 
> Right now, I am simply manually deleting those pods effected, but this can't be it...

Will v1.30.6 too? Have you tried the Graceful node shutdown feature: https://kubernetes.io/docs/concepts/cluster-administration/node-shutdown/?
