### ISSUE TITLE
pod-in-a-cluster namespace overwrites `--kubeconfig` namespace

### ISSUE THREAD

**Issue by iameli** [kubernetes/kubernetes#39897]
**Kubernetes version** 1.5.1 server/1.5.2 client

**Environment**:
- **Cloud provider or hardware configuration**: AWS, via CoreOS [kube-aws](https://github.com/coreos/kube-aws)
- **OS** (e.g. from /etc/os-release): CoreOS stable (1235.6.0)
- **Kernel** (e.g. `uname -a`): Linux ip-10-25-20-214.us-west-2.compute.internal 4.7.3-coreos-r2 #1 SMP Sun Jan 8 00:32:25 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux

**What happened**:

I am running `kubectl` within a cluster. The pod in which I'm doing this is in the `wrong-namespace` namespace, for purposes of illustrating this bug. When I run `kubectl get pods` without any command line parameters, it accesses my cluster in my namespace, which seems good.

```
# ./kubectl get pods
NAME                         READY     STATUS    RESTARTS   AGE
eli-test-2-611426134-bbmpd   1/1       Running   0          15m
```

I also have a `kubeconfig` file for accessing a remote cluster, totally unrelated to my normal cluster. This `kubeconfig` file specifies that it should access the `default` namespace.

```
# cat other-kubeconfig
apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: credentials/ca.pem
    server: https://other-cluster-url-redacted
  name: other-cluster
contexts:
- context:
    cluster: other-cluster
    namespace: default
    user: other-cluster-user
  name: other-cluster-context
users:
- name: other-cluster-user
  user:
    client-certificate: credentials/admin.pem
    client-key: credentials/admin-key.pem
current-context: other-cluster-context
```

When I try and connect to that cluster, it uses the `wrong-namespace` namespace, and doesn't see any pods. I have to specify `--namespace default` to see my pods over there.

```
./kubectl --kubeconfig other-kubeconfig get pods
No resources found.
# ./kubectl --kubeconfig other-kubeconfig --namespace default get pods
NAME                                        READY     STATUS    RESTARTS   AGE
[ Long list of pods omitted ]
```

**What you expected to happen**:

I expected it to obey the namespace in the `kubeconfig` file. It doesn't make much sense in this context to use the current pod's namespace -- this environment that I'm in currently has nothing to do with this other cluster I'm connecting to.

I think this is probably unintended behavior -- let me know if it's not and I'm not understanding the use case here.

**Comment by smarterclayton** [comment]
Make have been fixed by https://github.com/kubernetes/kubernetes/pull/39006

**Comment by smarterclayton** [comment]
@fabianofranz

**Comment by nickspat** [comment]
Came across same issue. kubectl commands is not respecting context values when ran from inside kubernetes container in other namespace. What release is this fix going to be available in?

**Comment by fabianofranz** [comment]
Correct, this was fixed by https://github.com/kubernetes/kubernetes/pull/39006 and will be in the 1.6 release. 

[v1.6.0-alpha.3](https://github.com/kubernetes/kubernetes/releases/tag/v1.6.0-alpha.3) should already have it in case you want to give it a try, feel free to reopen if the issue persists.

**Comment by chrisleck** [comment]
Still appears to be broken in 1.6.0.  Should we re-open this issue?
