### ISSUE TITLE
Support high availability clusters

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#473]
Master components need to be replicated for high availability.

**Comment by pires** [comment]
Using ```etcd``` to map existing apiservers seems very fragile indeed. You'd need for some sort of watchdog mechanism to remove entries related to dead/inaccessible servers. And you' rely heavily on the availability of ```etcd``` - which you already do.

Could we think about another solution, like apiservers communicating with each other (p2p, like in a Cassandra or Hazelcast cluster) and have them gossip the state of the cluster between themselves? This would work as well for partitioning/replicating cluster data.

**Comment by smarterclayton** [comment]
We never updated this, but the agreement at the Kube face to face is to nuke operations (no operation in the api server should be long running).  The ip allocator is single writer at this point - it could be converted to a sharded key write / merge operation against etcd with work.  The controllers and scheduler need to elect themselves by waiting on an etcd key in the short term, and in the long term compete for work and shard work on related queues.  The scheduler is the first component that must be made ha if we want to run the scheduler on the cluster (we do) since it would need to schedule it's replacement.  Every control loop is what I'm referring to as controller - we still have a few that are in the master code vs in controller manager.

**Comment by erictune** [comment]
ip allocator could instead be a "finalizer"?

**Comment by erictune** [comment]
finalizers :arrow_right:  #3585

**Comment by smarterclayton** [comment]
Yeah - clients would look at Service.Status.ServiceIP, and would say "service not ready" until it had an IP.

----- Original Message -----

**Comment by bgrant0607** [comment]
Operations have been eliminated.

This is not in our 1.0 roadmap, but if someone is interested in helping, we'd happily guide them.

**Comment by timothysc** [comment]
Are there any known limitations with baby stepping here?  For example load-balancing the api-servers?   

We're finding the api-server to be the bottleneck and can be cpu-bound even on steady state...

**Comment by smarterclayton** [comment]
I have a set of changes for service ip allocation that would allow us to move that to a control loop.  I think we could try everything else there.

Do you guys have profiles yet?  My recent stuff was showing conversion and serialization dominating, but it's not at your workloads.

**Comment by bgrant0607** [comment]
Known issues with replicating apiserver:
* IP allocation -- believed to be the only global state
* Cluster turnup scripts, Salt, kube-push, etc.
* nginx setup so that most/all clients can be oblivious to the number/locations of the apiservers

**Comment by timothysc** [comment]
@smarterclayton - here is the apiserver slog (https://github.com/GoogleCloudPlatform/kubernetes/issues/4521)

**Comment by timothysc** [comment]
@bgrant0607  

- I think the only blocker seems like IP allocation 

- Cluster turnup scripts, Salt, etc.. are deployment 
- re: nginx setup so that most/all clients can be oblivious to the number/locations of the apiservers
-- I was thinking about just using HAProxy as the front end and hide the details as if it were a single api-server.

**Comment by smarterclayton** [comment]
Quick predesign on ip allocation:

Two options:
1. Implement an etcd allocator which does CAS on a single document storing ranges of allocated IPs, on startup check the allocated ranges for unused blocks.
2. Move ip allocator to a controller loop (PortalIPController) in controller-manager, use the indexer function on cache.Store to expose a reverse lookup on portalIP.  Watch for service creations and allocate portalIP.

The latter is more aligned to our current design, and is simpler.  Also, the code it uses can be used to also serve DNS in the future (as per my changes upstream in skydns and in OpenShift to not require writing etcd DNS structures).

**Comment by bgrant0607** [comment]
I vote for (2).

**Comment by timothysc** [comment]
@smarterclayton - is there any issue no. or update on IP alloc?

**Comment by smarterclayton** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/5180

----- Original Message -----

**Comment by timothysc** [comment]
@rrati - perhaps we should breakout apiserver issues and ref back here.

**Comment by smarterclayton** [comment]
IP allocation is not done yet.  I think we need a card and support to move it to a controller or use a shared object to do allocation.

**Comment by bgrant0607** [comment]
Controller, please.

**Comment by smarterclayton** [comment]
I have a pull incoming to switch services to a multi master safe allocation

**Comment by smarterclayton** [comment]
Pull is created as #7704

**Comment by bgrant0607** [comment]
@smarterclayton @timothysc Is there any more progress on this?

**Comment by timothysc** [comment]
@bgrant0607 I'm still waiting on priority resolution for execution on the proposal.  Are there other pressures not on my radar?

**Comment by lavalamp** [comment]
If you access the kubernetes service instead of hard-coding an IP address, it will just work, no need for a load balancer. (some bootstrapping required for kubelet/kube-proxy)

**Comment by smarterclayton** [comment]
I've tested Kube multi master and done a quick pass to verify all known issues have been addressed. The endpoints algo can be improved, but we have TODOs in the code to cover it.  At this point, we need soak testing of multiple fighting masters to look for race conditions - that's something queued but not yet started that Tim's team was looking at.

**Comment by bgrant0607** [comment]
You're just letting multiple controllers and schedulers try to function concurrently?

**Comment by smarterclayton** [comment]
Testing with that to ensure the cluster at least makes forward progress.  I haven't tested the most recent builds but was able to see realistic cluster actions work a few weeks back.

**Comment by bgrant0607** [comment]
One issue that occurred to me while biking in this morning, and which I don't see discussed in docs/proposals/high-availability.md, is what to do about quota enforcement during admission control. @derekwaynecarr

**Comment by derekwaynecarr** [comment]
What is the specific concern?  Admission control uses resource version of quota document to enforce integrity.  In a multi-master setup, we still have a shared etcd, so I don't see an issue that is unique to quota.  Two masters handling concurrent requests is not much different than a single master handling concurrent requests.  We already have some fuZzing and retry logic in the admission controller to improve the experience of a large number of concurrent updates that would result in observed quota changes.

**Comment by jimmycuadra** [comment]
@davidopp You can just click the subscribe button on the right sidebar. No need to comment, as that sends a notification to everyone already subscribed.

**Comment by davidopp** [comment]
@jimmycuadra The /subscribe is so I get added to the Cc line of the email, so I'll notice the thread when it gets updated in the future. I wish there were some way to do this without having to spam everyone, but I'm not aware of one.

**Comment by smarterclayton** [comment]
If you toggle the subscribe button through unsubscribe and back it'll go from generic follow (no email) to specific follow (email), same as responding.

**Comment by davidopp** [comment]
Thanks @smarterclayton ! I had no idea about that feature.

**Comment by davidopp** [comment]
FYI @jdef implemented master election in files
plugin/contrib/mesos/pkg/election/etcd_master.go
plugin/contrib/mesos/pkg/election/master.go
in PR 8882
(I'm still in the process of reviewing it)

**Comment by jdef** [comment]
In the spirit of full disclosure that package was largely copy/pasted from
a prior k8s commit that was later backed out because no components were
ready to use it.

https://github.com/GoogleCloudPlatform/kubernetes/pull/1920/commits

**Comment by vaijab** [comment]
For kubernetes deployed on top of fleet, this approach can be used: https://github.com/vaijab/kube-apiproxy

**Comment by jimmycuadra** [comment]
Any updates on this?

**Comment by timothysc** [comment]
Work is in flight on all pieces atm.

**Comment by timothysc** [comment]
@lavalamp Given the plethora of details and in-flight tickets now, should this one still remain open?

**Comment by lavalamp** [comment]
@timothysc is there another blanket issue? If so, we only need one, otherwise we can leave this open.

**Comment by jimmycuadra** [comment]
Thanks for the update! Which are the issues/PRs I should be tracking to keep up on the details?

**Comment by JavierLorenzoPouso** [comment]
Is there any tutorial for replicate the master?

**Comment by davidopp** [comment]
> Is there any tutorial for replicate the master?

https://github.com/kubernetes/kubernetes/blob/master/docs/admin/high-availability.md
describes how the current HA approach works.

**Comment by justinsb** [comment]
HA works today - let's close this.  Or do we want to get it under e2e testing?

**Comment by davidopp** [comment]
"Works" in a loose sense -- we have a web page that explains how you can bring up an HA master, and there are certainly people doing it, but there's still a lot missing. @fgrzadkowski has taken over this issue. Automation and making it testable are on his plate.

**Comment by fgrzadkowski** [comment]
Actually the web page is not up to date. There are still open question with regard to etcd not being a pet so that we can use managed-instances-groups and equivalents. It's not tested at all.

I think we should keep this issue opened.

**Comment by pires** [comment]
@kubernetes/sig-cluster-lifecycle is looking into integrating HA with `kubeadm` as we speak. Feel free to chime in. /cc @timothysc

**Comment by roberthbailey** [comment]
Re-setting assignees based on who is working on HA in kubeadm for 1.8.

**Comment by timothysc** [comment]
I'm going to move to close this, there are recipes for recipes today and this issue no longer tracks any of the details.  Different repos have assorted parent-child issues tracking the state and there has been docs published to the main site as well.
