### ISSUE TITLE
Kubelet checkpointing or something

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#489]
From a different discussion.

Kubelet currently relies on save state in config files and etcd to retain the actual Pod manifests.  Removal of a pod from a host is signalled by the removal of the config state.  In general this seems OK, except in the case of various failures (such as a restart of Kubelet).  This is supposed to be rare (kubelet tries to catch panics and recover) but I'm not sure we can actually ignore it.  For example, we get great mileage out of the control system changing flags on our agent and bouncing it to control feature rollouts.  We have a hard rule that no matter what happens to the agent we can recover.

So how far do we need to take Kubelet and when?

On one hand, the sooner we do things like saving checkpoints and recovering from them the easier it will be to implement.  On the other hand, we really need to be focusing on what is important to get to a stable API and experience - this is sort of an edge case.

I wanted to file an issue so that we can keep track of it.

It's frequently possible to get away without storing a checksum - for example we embed pod ID into each container's name (as per docker).  This is really just letting Docker do the checkpointing for us.  We now start to have pod-scoped resources that we want to checkpoint some information about.

Specifically, we have GCE persistent disk support in flight - that needs to be mounted once to a host and refcounted.  We also have ideas about volumes that "linger" for some amount of time while being cleaned up (to have data moved).  I am sure there will be more...

Internally we have a formalized checksum subsystem and a clearly-defined state machine for things like pods and volumes.  The state is a checksummed object.  At app startup all of the checksums are restored, so we always know what we intended to be happening.

I'd rather NOT take this on, if we can dodge it.  As a concrete example:

With checkpoints:
- T0: etcd has pods p0, p1, p2
  - pods p0 and p1 both ask for a persistent disk named "foobar"
  - kubelet caches those pod specs and starts them
  - kubelet attaches foobar to the VM
  - kubelet mounts foobar on /kubelet/pd/foobar
  - kubelet creates a private space for p0 at /kubelet/pods/p0
  - kubelet bind mounts /kubelet/pd/foobar onto /kubelet/pods/p0/vol/foobar
  - repeat for p1
  - refcount for PD(foobar) == 2, checkpointed
- T1: etcd has pods p1, p2 -- p0 has been removed
  - kubelet sets p0 to state REMOVING
  - kubelet removes part of p0, but crashes
- T2: kubelet comes back
  - kubelet loads the checkpoint, including p0, which is REMOVING
  - kubelet looks at etcd and finds no p0 -- reconciler says "remove it"
  - kubelet starts removing p0, finding half of it already gone
  - kubelet knows by the checkpoint that PD(foobar) has refcount 2
  - kubelet finishes removing p0, decrements the refcount for foobar

Without checkpoints
- T0: etcd has pods p0, p1, p2
  - pods p0 and p1 both ask for a persistent disk named "foobar"
  - kubelet starts them
  - kubelet attaches foobar to the VM
  - kubelet mounts foobar on /kubelet/pd/foobar
  - kubelet creates a private space for p0 at /kubelet/pods/p0
  - kubelet bind mounts /kubelet/pd/foobar onto /kubelet/pods/p0/vol/foobar
  - repeat for p1
- T1: etcd has pods p1, p2 -- p0 has been removed
  - kubelet removes part of p0, but crashes
- T2: kubelet comes back
  - kubelet looks at docker and finds p0, p1, p2
  - kubelet looks at the filesystem and finds /kubelet/pd/foobar
  - kubelet uses "pd" from that path to look up which "driver" handles this volume
  - kubelet's PD driver now knows that it has a PD named "foobar" mounted, but not the refcount
  - kubelet looks at the filesystem and finds /kubelet/pods/p0/vol/foobar
  - kubelet opens /proc/mounts and figures out that p0's foobar == pd/foobar
  - kubelet tells the PD driver that foobar has a reference
  - repeat for p1
  - kubelet looks at etcd and finds p1, p2, but no p0 -- reconciler says "remove it"
  - kubelet has no memory of p0, but it knows p0 has PD(foobar)
  - kubelet finishes removing p0, decrements the refcount for foobar
  - kubelet looks at /kubelet/pods/p0/vol and finds foobar

The second case actually DOES have checkpoints, it's just that every subsystem has to produce recoverable state on its own.  In this example, the volumes subsystem has to have a mapping from directory names to modules.  It does have the advantage that the checkpoint is intrinsic to the system state - no corrupted checkpoint files or any such thing.  But it's significantly more complex to manage, and I am not convinced that it is possible in EVERY case.

This is long enough now.  Let's let people chew on it.

**Comment by bgrant0607** [comment]
At bare minimum, we're going to need to locally persist resources pulled from apiserver, so that node availability isn't so coupled to apiserver availability and in order to make self-hosting feasible. Probably we need to port to the apiserver package first #2098.

This isn't on our 1.0 roadmap.

**Comment by jdef** [comment]
cherry-picked into https://github.com/mesosphere/kubernetes/pull/55

**Comment by mikedanese** [comment]
cc @pwittrock @vishh

**Comment by philips** [comment]
As part of the [bootkube discussion](https://groups.google.com/d/msg/kubernetes-sig-cluster-lifecycle/p9QFxw-7NKE/jeYJF1hBAwAJ) we have implemented a minimal [checkpoint in userspace](https://github.com/coreos/bootkube/tree/master/cmd/checkpoint#checkpoint) to be scheduled alongside the kubelet.

**Comment by timothysc** [comment]
@roberthbailey @dchen1107 @ncdc @lukemarsden @luxas @aaronlevy - Per conversations this last week, we had hoped to address very basic checkpointing to allow for cluster bootstrapping for self-hosting in the 1.8 cycle so I'm adding names here. 

Our goals are to  try to de-dupe pieces of boot-kube such that they are community managed.

**Comment by roberthbailey** [comment]
@timothysc - we are waiting for our proposal to share with sig-node. Have you made any progress getting it started?

**Comment by timothysc** [comment]
Initial bootstrap checkpointing is done in 1.9 and will be iterated on in 1.10, this does not solve the general purpose case, and I'm unassigning myself now.

**Comment by smekkley** [comment]
Why don't you use pod-checkpointer? @thockin 
https://github.com/kubernetes-incubator/bootkube/tree/master/cmd/checkpoint
This issue should be closed.

**Comment by maikelvl** [comment]
@smekkley Aaron Levy said in his talk:

> Ideally this [checkpointing] is something that we can eventually get into the kubelet itself.

https://www.youtube.com/watch?v=EbNxGK9MwN4&t=2488

@aaronlevy, do you still agree with this? 🙂

**Comment by neolit123** [comment]
there is a checkpoint / restore KEP here:
https://github.com/kubernetes/enhancements/pull/1990

/remove-lifecycle frozen

**Comment by haircommander** [comment]
The checkpoint/restore KEP as it exists now has been updated to relate to pod migration between nodes. I believe it was a decision by sig-node to not checkpoint kubelet state, though I'm having trouble finding documentation for that.

Since the current iteration of the KEP is not relevant to this issue, and because it doesn't seem like sig-node has any intention of working on this, I am closing it. If you would like this feature, please open a new bug and we can re-discuss

/close
