### ISSUE TITLE
hyperkube v1.7.0 gave warning on duplicate proto type registered

### ISSUE THREAD

**Issue by xiangfeiz** [kubernetes/kubernetes#48924]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
# kubectl version
2017-07-14 00:22:33.842797 I | proto: duplicate proto type registered: google.protobuf.Any
2017-07-14 00:22:33.843078 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-07-14 00:22:33.843115 I | proto: duplicate proto type registered: google.protobuf.Timestamp
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-1+e3085e7e4f4022", GitCommit:"e3085e7e4f40227fe2ca0edb80099551058a3a5d", GitTreeState:"clean", BuildDate:"2017-07-14T06:01:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-1+e3085e7e4f4022", GitCommit:"e3085e7e4f40227fe2ca0edb80099551058a3a5d", GitTreeState:"clean", BuildDate:"2017-07-14T06:01:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**What you expected to happen**:
Running kubectl command without those warnings printed out to stderr.

**How to reproduce it (as minimally and precisely as possible)**:
Run any kubectl command.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xiangfeiz** [comment]
@kubernetes/sig-cli-bugs

**Comment by mengqiy** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by xiangfeiz** [comment]
I'm running hyperkube container where kubectl command is linked to hyperkube binary file. The official download of kubectl 1.7.0 does not have this issue.

**Comment by bsherrod** [comment]
Same error occurs in 1.7.2:

```
$ kubectl version
2017-07-26 16:45:22.248030 I | proto: duplicate proto type registered: google.protobuf.Any
2017-07-26 16:45:22.248081 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-07-26 16:45:22.248100 I | proto: duplicate proto type registered: google.protobuf.Timestamp
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ uname -a
Linux i-085512b4c181d19e8 4.4.0-38-generic #57~14.04.1-Ubuntu SMP Tue Sep 6 17:20:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yyw1128** [comment]
Same error 1.7.0, 1.7.2
```
[stack@docker-1 ~]$ kubectl version
2017-07-27 10:27:32.271960 I | proto: duplicate proto type registered: google.protobuf.Any
2017-07-27 10:27:32.272178 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-07-27 10:27:32.272191 I | proto: duplicate proto type registered: google.protobuf.Timestamp
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2+coreos.0", GitCommit:"c6574824e296e68a20d36f00e71fa01a81132b66", GitTreeState:"clean", BuildDate:"2017-07-24T23:28:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2+coreos.0", GitCommit:"c6574824e296e68a20d36f00e71fa01a81132b66", GitTreeState:"clean", BuildDate:"2017-07-24T23:28:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
[stack@docker-1 ~]$
```

```
[stack@docker-1 ~]$ uname -a
Linux docker-1.com 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[stack@docker-1 ~]$
```

**Comment by juliohm1978** [comment]
Just for clarity, can anyone assess the severity of these messages? Should I be worried about any incompatibility issues? Or can I safely ignore them for the moment?

**Comment by bsherrod** [comment]
They appear to be harmless, just annoying.

**Comment by jbunce** [comment]
Also present in 1.7.3:

```
kubectl version
2017-08-16 10:45:45.764757 I | proto: duplicate proto type registered: google.protobuf.Any
2017-08-16 10:45:45.764804 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-08-16 10:45:45.764816 I | proto: duplicate proto type registered: google.protobuf.Timestamp
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3+coreos.0", GitCommit:"42de91f04e456f7625941a6c4aaedaa69708be1b", GitTreeState:"clean", BuildDate:"2017-08-07T19:44:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3+coreos.0", GitCommit:"42de91f04e456f7625941a6c4aaedaa69708be1b", GitTreeState:"clean", BuildDate:"2017-08-07T19:44:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by fedya** [comment]
1.7.4

```
[root@localhost ~]# kubectl version
2017-08-25 14:57:23.352596 I | proto: duplicate proto type registered: google.protobuf.Any
2017-08-25 14:57:23.352790 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-08-25 14:57:23.352970 I | proto: duplicate proto type registered: google.protobuf.Timestamp
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"%{commit}", GitTreeState:"clean", BuildDate:"2017-08-24T14:16:26Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

```

**Comment by tetramin** [comment]
I have some issue on 1.7.2
```
$ kubectl version
2017-08-29 16:53:45.477474 I | proto: duplicate proto type registered: google.protobuf.Any
2017-08-29 16:53:45.477511 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-08-29 16:53:45.477523 I | proto: duplicate proto type registered: google.protobuf.Timestamp
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2+coreos.0", GitCommit:"c6574824e296e68a20d36f00e71fa01a81132b66", GitTreeState:"clean", BuildDate:"2017-07-24T23:28:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2+coreos.0", GitCommit:"c6574824e296e68a20d36f00e71fa01a81132b66", GitTreeState:"clean", BuildDate:"2017-07-24T23:28:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dimthe** [comment]
i have the same issue with kubernetes on openstack . Is it safe to ignore these?


`kubectl get nodes
2017-08-30 09:55:58.612805 I | proto: duplicate proto type registered: google.protobuf.Any
2017-08-30 09:55:58.613600 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-08-30 09:55:58.613728 I | proto: duplicate proto type registered: google.protobuf.Timestamp
NAME                                                    STATUS                     AGE       VERSION
ku-7ongeapfnd-0-yjslsvkiqdzt-kube-master-ti34yoxxwo5k   Ready,SchedulingDisabled   24m       v1.7.4
ku-clzgwpk4r3-0-xzsncputd42o-kube-minion-awcygwm2juj4   Ready                      5m        v1.7.4
ku-clzgwpk4r3-1-tjx6cnbkyafn-kube-minion-xno2dnvvn7n6   Ready                      5m        v1.7.4

**Comment by dimthe** [comment]
i can verify this is fixed if you upgrade to 1.7.4

```
curl -O https://storage.googleapis.com/kubernetes-release/release/v1.7.4/bin/linux/amd64/kubectl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 68.9M  100 68.9M    0     0   925k      0  0:01:16  0:01:16 --:--:-- 1390k
[fedora@ku-7ongeapfnd-0-yjslsvkiqdzt-kube-master-ti34yoxxwo5k ~]$ chmod +x kubectl
[fedora@ku-7ongeapfnd-0-yjslsvkiqdzt-kube-master-ti34yoxxwo5k ~]$ sudo mv kubectl /usr/local/bin/kubectl
[fedora@ku-7ongeapfnd-0-yjslsvkiqdzt-kube-master-ti34yoxxwo5k ~]$ kubectl get nodes
NAME                                                    STATUS                     AGE       VERSION
ku-7ongeapfnd-0-yjslsvkiqdzt-kube-master-ti34yoxxwo5k   Ready,SchedulingDisabled   33m       v1.7.4
ku-clzgwpk4r3-0-xzsncputd42o-kube-minion-awcygwm2juj4   Ready                      15m       v1.7.4
ku-clzgwpk4r3-1-tjx6cnbkyafn-kube-minion-xno2dnvvn7n6   Ready                      15m       v1.7.4
```

**Comment by xiangfeiz** [comment]
@dimthe the messages are only shown with hyperkube version of kubectl. The kubectl command binary never has this issue.

**Comment by juliohm1978** [comment]
@dimthe We've been seeing these messages from hyperkube binaries. Our Kubespray installation uses those. Aside from the annoyance, we never noticed any change in behavior or any other related error messages. We have been ignoring them. Will post an update after we upgrade to 1.7.4 in a near future.

**Comment by chen-anders** [comment]
I just downloaded `hyperkube` off of 1.7.5 for linux-amd64 and this issue persists via `hyperkube kubectl`. Things aren't a problem when one uses the `kubectl` binary.

**Comment by roffe** [comment]
Same phenomen as @chen-anders using image gcr.io/google_containers/hyperkube-amd64:v1.7.5

**Comment by vnalla** [comment]
I am getting the same on CentOS 7 withe coreos/hyperkube:v1.7.4_coreos.0

Linux centos-master 3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
kubectl version
2017-09-19 15:06:17.773495 I | proto: duplicate proto type registered: google.protobuf.Any
2017-09-19 15:06:17.774886 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-09-19 15:06:17.774911 I | proto: duplicate proto type registered: google.protobuf.Timestamp
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4+coreos.0", GitCommit:"4bb697e04f7c356347aee6ffaa91640b428976d5", GitTreeState:"clean", BuildDate:"2017-08-22T08:43:47Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4+coreos.0", GitCommit:"4bb697e04f7c356347aee6ffaa91640b428976d5", GitTreeState:"clean", BuildDate:"2017-08-22T08:43:47Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ameukam** [comment]
I'm getting the same error. 

```
kubectl version
2017-09-20 09:38:32.361200 I | proto: duplicate proto type registered: google.protobuf.Any
2017-09-20 09:38:32.361259 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-09-20 09:38:32.361275 I | proto: duplicate proto type registered: google.protobuf.Timestamp
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+coreos.0", GitCommit:"e14ebed378d5380b9936455584fa454daa67f23b", GitTreeState:"clean", BuildDate:"2017-09-14T21:52:44Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+coreos.0", GitCommit:"e14ebed378d5380b9936455584fa454daa67f23b", GitTreeState:"clean", BuildDate:"2017-09-14T21:52:44Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
VMware virtual Machine version 11

```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
```
uname -a
Linux k8s-master01 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Deployment tool : kubespray

**Comment by juliohm1978** [comment]
Just tested a Kubespray upgrade to k8s **1.8.1** and the warning has gone away. The new hyperkube image no longer displays these messages.
