### ISSUE TITLE
OpenStack Cinder is reporting deprecated API call for PVC create

### ISSUE THREAD

**Issue by xrl** [kubernetes/kubernetes#49414]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

I created a new kube cluster on an openstack (running newton) and I created a statefulset with dynamic volume template. The pod was stuck in pending so I check the pvc:

```
 StorageClass "ssd-sf": Expected HTTP response code [200 204] when accessing [GET https://usw1.viasat.cloud:8776/], but got 300 instead
{"versions": [{"status": "DEPRECATED", "updated": "2016-05-02T20:25:19Z", "links": [{"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}, {"href": "http://usw1.viasat.cloud:8776/v1/", "rel": "self"}], "min_version": "", "version": "", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.volume+json;version=1"}], "id": "v1.0"}, {"status": "SUPPORTED", "updated": "2014-06-28T12:20:21Z", "links": [{"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}, {"href": "http://usw1.viasat.cloud:8776/v2/", "rel": "self"}], "min_version": "", "version": "", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.volume+json;version=1"}], "id": "v2.0"}, {"status": "CURRENT", "updated": "2016-02-08T12:20:21Z", "links": [{"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}, {"href": "http://usw1.viasat.cloud:8776/v3/", "rel": "self"}], "min_version": "3.0", "version": "3.15", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.volume+json;version=1"}], "id": "v3.0"}]}
```

It is stuck like this and will not move forward.

**What you expected to happen**: The volume should have been created and the pod should have been started.

**How to reproduce it (as minimally and precisely as possible)**: Create a PVC:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-storage
  namespace: metrics
  annotations:
    volume.beta.kubernetes.io/storage-class: ssd-hp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
```

then issue the create command:

```
$ k create -f ../kube/heapster/influxdb-pvc.yml
$ km describe pvc influxdb-storage
Name:		influxdb-storage
Namespace:	metrics
StorageClass:	ssd-hp
Status:		Pending
Volume:
Labels:		<none>
Annotations:	volume.beta.kubernetes.io/storage-class=ssd-hp
		volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/cinder
Capacity:
Access Modes:
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  58s		11s		5	persistentvolume-controller			Warning		ProvisioningFailed	Failed to provision volume with StorageClass "ssd-hp": Expected HTTP response code [200 204] when accessing [GET https://usw1.viasat.cloud:8776/], but got 300 instead
{"versions": [{"status": "DEPRECATED", "updated": "2016-05-02T20:25:19Z", "links": [{"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}, {"href": "http://usw1.viasat.cloud:8776/v1/", "rel": "self"}], "min_version": "", "version": "", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.volume+json;version=1"}], "id": "v1.0"}, {"status": "SUPPORTED", "updated": "2014-06-28T12:20:21Z", "links": [{"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}, {"href": "http://usw1.viasat.cloud:8776/v2/", "rel": "self"}], "min_version": "", "version": "", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.volume+json;version=1"}], "id": "v2.0"}, {"status": "CURRENT", "updated": "2016-02-08T12:20:21Z", "links": [{"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}, {"href": "http://usw1.viasat.cloud:8776/v3/", "rel": "self"}], "min_version": "3.0", "version": "3.15", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.volume+json;version=1"}], "id": "v3.0"}]}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.1-coreos.0
- Cloud provider or hardware configuration**: Openstack Newton
- OS (e.g. from /etc/os-release):
```
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.6.0
VERSION_ID=1409.6.0
BUILD_ID=2017-07-06-0128
PRETTY_NAME="Container Linux by CoreOS 1409.6.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`): `Linux deleteme-kube-master-01.openstacklocal 4.11.9-coreos #1 SMP Thu Jul 6 00:54:42 UTC 2017 x86_64 Intel Core Processor (Haswell) GenuineIntel GNU/Linux`
- Install tools: kubespray (today's `master` with modification to run 1.7.1)
- Others:

**Comment by xrl** [comment]
I needed to override the bs-version = v2. The auto feature did not work.

My kubespray-installed openstack cloud config:

```
[Global]
auth-url={{ openstack_auth_url }}
username={{ openstack_username }}
password={{ openstack_password }}
region={{ openstack_region }}
tenant-id={{ openstack_tenant_id }}
{% if openstack_domain_name is defined and openstack_domain_name != "" %}
domain-name={{ openstack_domain_name }}
{% endif %}
[BlockStorage]
bs-version = v2
```

**Comment by dims** [comment]
@xrl yes, i filed a PR to highlight this problem and add some logs with this suggestion, please take a look

https://github.com/kubernetes/kubernetes/pull/49318

**Comment by anguslees** [comment]
This is fixed by https://github.com/kubernetes/kubernetes/pull/47602 - correct?

**Comment by xsgordon** [comment]
@xrl are you able to re-test with https://github.com/kubernetes/kubernetes/pull/47602 applied?

**Comment by xrl** [comment]
@xsgordon unfortunately, no. this cinder instability had me tear down the cluster in openstack. too many issues with openstack so we're switching to AWS for this cluster.

**Comment by dims** [comment]
Thanks @xrl 

/close

**Comment by zioproto** [comment]
I still see the bug with `v1.7.4`

My config looks like:
```
[BlockStorage]
trust-device-path = false
bs-version = v2
```
This is what I see in the Events

```
Events:
  FirstSeen	LastSeen	Count	From		SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----		-------------	--------	------		-------
  1h		1m		48	attachdetach			Warning		FailedMount	AttachVolume.Attach failed for volume "mysql-persistent-storage" : Expected HTTP response code [200 204] when accessing [GET https://api.zhdk.cloud.switch.ch:8776/], but got 300 instead
{"versions": [{"status": "DEPRECATED", "updated": "2016-05-02T20:25:19Z", "links": [{"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}, {"href": "https://api.zhdk.cloud.switch.ch:8776/v1/", "rel": "self"}], "min_version": "", "version": "", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.volume+json;version=1"}], "id": "v1.0"}, {"status": "SUPPORTED", "updated": "2014-06-28T12:20:21Z", "links": [{"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}, {"href": "https://api.zhdk.cloud.switch.ch:8776/v2/", "rel": "self"}], "min_version": "", "version": "", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.volume+json;version=1"}], "id": "v2.0"}, {"status": "CURRENT", "updated": "2016-02-08T12:20:21Z", "links": [{"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}, {"href": "https://api.zhdk.cloud.switch.ch:8776/v3/", "rel": "self"}], "min_version": "3.0", "version": "3.15", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.volume+json;version=1"}], "id": "v3.0"}]}
  1h	1m	43	kubelet, k8s-3		Warning	FailedMount	Unable to mount volumes for pod "mysql_default(3d62f289-8c9d-11e7-b2a8-fa163e4cb433)": timeout expired waiting for volumes to attach/mount for pod "default"/"mysql". list of unattached/unmounted volumes=[mysql-persistent-storage]
  1h	1m	43	kubelet, k8s-3		Warning	FailedSync	Error syncing pod
```

This was working as expected in `v1.6.4`

Should this bug be reopened ?

**Comment by dims** [comment]
Apparently bug still not fixed with #47602, reopening

/reopen

**Comment by dims** [comment]
@rootfs Can you please take a look? (based on your experience in https://github.com/gophercloud/gophercloud/issues/384 )

**Comment by zioproto** [comment]
I apologize. I noticed the container `kube-controller-manager` did not restart and did not pickup the new `[BlockStorage]` config.

I restarted that container manually with Docker commands.

I confirm `bs-version = v2` is a working workaround also for `v1.7.4`
