### ISSUE TITLE
DaemonSet created in namespace kube-system is deleted after ~40s every time.

### ISSUE THREAD

**Issue by macrael** [kubernetes/kubernetes#51376]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I created a DaemonSet on GKE in the namespace kube-system via kubectl create or apply. After 40 seconds, the DaemonSet and all three of its pods are deleted with no visible reason as to why. The closest thing to an error message I could find was 'Need to kill Pod' in the delete event. 

Re-creating the DaemonSet in a different namespace prevented it from being killed.

**What you expected to happen**:
It not to be deleted, or at least, some explanation of what hidden system was deleting my DaemonSet. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a minimal DaemonSet on a GKE cluster in the kube-system namespace. Wait 1 minute. `kubectl get ds -n kube-system`

**Anything else we need to know?**:
I only tried to put it in a different namespace because [this old Stack Overflow answer](https://stackoverflow.com/questions/41825484/gke-stackdriver) said that putting something in the kube-system namespace "might conflict with addon-manager", so that's my only hint as to what's going wrong. 

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T17:03:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-05T16:40:42Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**: GKE

**Comment by macrael** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by resouer** [comment]
Are you able to create Pods in kube-system? Or it is only DaemonSet that failed?

**Comment by macrael** [comment]
I’ll try, but the Deployment I create was creating pods that lived long,
only my DS was being deleted.

**Comment by aolwas** [comment]
HI 

I have the same behavior on gke and k8S 1.8.4. Everything works well in the kube-system namespace except the deamonset object

**Comment by nebril** [comment]
Seems like this was fixed recently.

**Comment by peterkuiper** [comment]
I had the same problem and contacted the excellent GCP Support. After some investigation they found that the following annotation is causing the issue:

```kubernetes.io/cluster-service: "true"```

Removing this from your config should fix the problem. I don't know exactly what this annotation is doing but it is related to the addon manager as described above. This annotation seems to be [deprecated](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/README.md).

HTH

**Comment by shinebayar-g** [comment]
@peterkuiper Thanks a lot, after removing that label my daemonset no longer getting deleted.

**Comment by rschmidtz** [comment]
Still experiencing the same issue.

Removing `kubernetes.io/cluster-service: "true"` didn't help 

GCP Version: **1.12.8-gke.10**

Trying to install  [ELK](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch)

**Comment by noamt** [comment]
I'm experiencing this as well now.
Version: `1.13.7-gke.8`
