### ISSUE TITLE
[upgrade tests] GCE 1.7 upgrade tests aren't coming up

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#52353]
The following upgrade tests aren't coming up and/or timing out.

https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-master
https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-cluster

cc @kubernetes/sig-cluster-lifecycle-test-failures 
cc @kubernetes/test-infra-maintainers 
cc @kubernetes/kubernetes-release-managers 
cc @mbohlool 

Anyone know who owns these test frameworks? They've been failing for quite a while now.

**Comment by krzyzacy** [comment]
Thanks to @krousey spotted this:
```
I0913 00:27:30.914] [It] should be invisible to controllers by default
I0913 00:27:30.915]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/extension/initializers.go:107
I0913 00:27:30.958] Sep 13 00:27:30.957: INFO: Creating pod uninitialized-pod
I0913 00:27:31.061] panic: 
I0913 00:27:31.061] Your test failed.
I0913 00:27:31.062] Ginkgo panics to prevent subsequent assertions from running.
I0913 00:27:31.062] Normally Ginkgo rescues this panic so you shouldn't see it.
I0913 00:27:31.062] 
I0913 00:27:31.062] But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
I0913 00:27:31.063] To circumvent this, you should call
I0913 00:27:31.063] 
I0913 00:27:31.063] 	defer GinkgoRecover()
I0913 00:27:31.063] 
I0913 00:27:31.064] at the top of the goroutine that caused this panic.
I0913 00:27:31.064]  [recovered]
I0913 00:27:31.064] 	panic: 
I0913 00:27:31.064] Your test failed.
I0913 00:27:31.064] Ginkgo panics to prevent subsequent assertions from running.
I0913 00:27:31.065] Normally Ginkgo rescues this panic so you shouldn't see it.
I0913 00:27:31.065] 
I0913 00:27:31.065] But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
I0913 00:27:31.065] To circumvent this, you should call
I0913 00:27:31.065] 
I0913 00:27:31.066] 	defer GinkgoRecover()
I0913 00:27:31.066] 
I0913 00:27:31.066] at the top of the goroutine that caused this panic.
```

cc @smarterclayton as the original author

**Comment by krzyzacy** [comment]
/assign @mehdy 
https://github.com/kubernetes/kubernetes/pull/52438

**Comment by krzyzacy** [comment]
whoops
/assign @mbohlool

**Comment by ericchiang** [comment]
Still seeing issues with https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-cluster-new

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/298

```
W0914 20:43:44.096] 2017/09/14 20:43:44 main.go:270: Something went wrong: failed to prepare test environment: --provider=gce boskos failed to acquire project: Post http://boskos/acquire?type=gce-project&state=free&dest=busy&owner=ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new: dial tcp 10.63.250.132:80: i/o timeout
```

**Comment by krzyzacy** [comment]
that's affected by https://github.com/kubernetes/test-infra/issues/4571 - still looking into that but should be functional after redeployment

**Comment by krousey** [comment]
Just to clarify, the cluster is coming up, and upgrading successfully. A couple of the upgrade tests (jobs and stateful sets) seem to have had some issues. The skew tests (not really upgrade tests) that follow after the upgrade has completed had serious bug and were panicking before they could right any test results. This panic has been fixed. Now the test suite can't obtain a GCP project from boskos (being tracked elsewhere) and we haven't been able to get a good signal after fixing the panic.

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster/1203?log#log (starts 8am today) seems still have the issue.

xref (might be related) https://github.com/kubernetes/kubernetes/issues/52578

**Comment by ericchiang** [comment]
This appears to have been resolved. Upgrade tests ran well throughout the weekend. Thanks @krzyzacy for all the help here.
