### ISSUE TITLE
CertificateManager blocks kubelet start if auto-approval is not enabled

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#53237]
Reported in https://github.com/kubernetes/kubernetes/pull/53231

Scenario (CentOS 7):
- install 1.7.x packages for kubelet on nodes.
- install cluster with kubeadm init stable-1.7
- use kubeadm to upgrade control plane to 1.8.0-rc.1
- on nodes which still run 1.7.x kubelet, install new rpms for 1.8.0.rc.1 where certificate-rotation is enabled.
- systemctl daemon-reload, systemctl restart kubelet.

result: kubelet is in wait loop, waiting for csr to be approved. node is in NotReady state.

The kubelet blocks on startup, despite having a valid kubeconfig file.

It should start up, attempt to rotate in the background, but not block.

**Comment by ericchiang** [comment]
I think this is because of the bootstrap kubeconfig flag. If you only provide the cert rotation flag it should only bootstrap in the background. That's what we where doing for bootkube where we need to start static pods while we're doing our initial cert rotation

**Comment by kad** [comment]
a bit of debug shown that `getCurrentCertificateOrBootstrap()` returns on the last line `return &bootstrapCert, true, nil`. So, kubelet has valid cert, but still wants to rotate it. That in theory should be a valid scenario.
Question is: why it's not automatically approved then ? Even if cert will be in proper place, does that mean that automatic rotation wouldn't work for expired certs ? Or I'm missing something here.

**Comment by liggitt** [comment]
> I think this is because of the bootstrap kubeconfig flag.

no, it's because when a `--kubeconfig` file is provided containing only cert/key data, the cert manager blocks on Start() until a CSR is approved

**Comment by liggitt** [comment]
proposed fix in https://github.com/kubernetes/kubernetes/pull/53238

**Comment by liggitt** [comment]
> Question is: why it's not automatically approved then ? Even if cert will be in proper place, does that mean that automatic rotation wouldn't work for expired certs ? Or I'm missing something here.

@luxas what does `kubeadm` set up for auto-approval of node self certificate requests during an upgrade to 1.8?

**Comment by liggitt** [comment]
@kubernetes/sig-auth-bugs for cert manager hang
@kubernetes/sig-cluster-lifecycle-bugs for kubeadm auto-approval setup issues upgrading to 1.8

**Comment by liggitt** [comment]
looks like kubeadm upgrade instructions indicate approval of CSRs for upgrades nodes is expected:

http://kubernetes-io-vnext-staging.netlify.com/docs/tasks/administer-cluster/kubeadm-upgrade-1-8/

I'd expect that only to be required once certs expired, not automatically required as part of upgrade

**Comment by pipejakob** [comment]
@liggitt Yeah, I [added](https://github.com/kubernetes/kubernetes.github.io/pull/5678) that step to the kubeadm upgrade instructions last-minute today when the problem was discovered and we didn't think we would have a solution in time for 1.8.0. Manually approving the CSRs seems to work fine, but is a less-than-stellar upgrade experience.

**Comment by liggitt** [comment]
lowering priority a notch, since the upgrade procedure is at least documented, and `--rotate-certificates` does not default to true for all installations (specific deployment methods like kubeadm enable it)

**Comment by pipejakob** [comment]
In case it helps, kubeadm 1.8 code for starting the controller manager is [here](https://github.com/kubernetes/kubernetes/blob/release-1.8/cmd/kubeadm/app/phases/controlplane/manifests.go#L207), and the RBAC rules for auto-approval are [here](https://github.com/kubernetes/kubernetes/blob/release-1.8/cmd/kubeadm/app/phases/bootstraptoken/node/tlsbootstrap.go#L69).

**Comment by pipejakob** [comment]
Also, I'm not sure if we have any other docs that need to be updated regarding upgrading kubelet, since this isn't a kubeadm-specific problem.

**Comment by liggitt** [comment]
> this isn't a kubeadm-specific problem

the combination of enabling rotation and not setting up auto-approval is what bit kubeadm here

* `--rotate-certificates` is a deployment-specific choice, and is not true by default. `kubeadm` is the only deployment I see that enables it on upgrade to 1.8
* the auto-approval rules at https://github.com/kubernetes/kubernetes/blob/release-1.8/cmd/kubeadm/app/phases/bootstraptoken/node/tlsbootstrap.go#L69 do not enable nodes to rotate their client certificates, that only sets up auto-approval for the initial TLS bootstrapping token

I agree the kubelet should behave better in this scenario if it already has a valid credential (like https://github.com/kubernetes/kubernetes/pull/53238), but the configured setup by kubeadm doesn't seem correct

**Comment by pipejakob** [comment]
Ah, understood. It wasn't until I was looking at the RBAC rules myself just now that I realized we must have missed that. Definitely needs to get fixed in kubeadm.

**Comment by pipejakob** [comment]
I've created a PR for the documentation fix for kubeadm upgrades: https://github.com/kubernetes/kubernetes.github.io/pull/5683

We still need a kubeadm code fix to add the RBAC rules, hopefully to get into 1.8.1.

**Comment by luxas** [comment]
Yeah, not creating the ClusterRoleBinding between `system:nodes` and `selfnodeclient` was an oversight, but isn't **that** critical in any way. We'll make that change in v1.8.1, and document things meanwhile.
Upgrading your kubelets is a manual process anyway right now, so it's reasonable to add one extra step to create this binding.

@liggitt Is it expected that a kubelet that already has credentials should renew them on restart if `--rotate-certificates` is set?

**Comment by liggitt** [comment]
> @liggitt Is it expected that a kubelet that already has credentials should renew them on restart if --rotate-certificates is set?

No, see https://github.com/kubernetes/kubernetes/pull/53238

**Comment by liggitt** [comment]
Reopening. Blocking on start is still an issue if auto approval is not enabled.

**Comment by liggitt** [comment]
Fix in https://github.com/kubernetes/kubernetes/pull/53238

**Comment by luxas** [comment]
Should this have the v1.8 milestone attached to it?

**Comment by luxas** [comment]
@liggitt is everything here now fixed or are we waiting for https://github.com/kubernetes/kubernetes/pull/53238?

**Comment by luxas** [comment]
ping @liggitt on the status of #53238

**Comment by dims** [comment]
@luxas @liggitt - https://github.com/kubernetes/kubernetes/pull/53238 needs rebase and the https://github.com/kubernetes/kubernetes/pull/53037 mentioned in there is merged. What else needs to be done?

**Comment by luxas** [comment]
I think this issue is now solved @liggitt, right?
