### ISSUE TITLE
[job failure] gci-gke

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#55189]
/priority critical-urgent
/priority failing-test
/area platform/gke
@kubernetes/sig-gcp-test-failures

This job has been failing since 2017-11-02.  It's on the [sig-release-master-blocking dashboard](https://k8s-testgrid.appspot.com/sig-release-master-blocking),
and prevents us from cutting [v1.9.0-alpha.3] (kubernetes/sig-release#27). Is there work ongoing to bring this job back to green?

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke

- last good: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/17906
- first bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/17907
- latest bad as of filing: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/18057/
- suspect changelog: https://github.com/kubernetes/kubernetes/compare/55e216f56...3a15fdbe7

**Comment by spiffxp** [comment]
/status approved-for-milestone
because this is a release-blocking job

**Comment by enisoc** [comment]
It seems the master is getting stuck and we time out waiting for it.

```
W1107 00:08:34.093] 2017/11/07 00:08:34 util.go:155: Running: gcloud container clusters create --quiet --project=gke-up-g1-3-c1-5-up-clu-n --zone=us-central1-f --machine-type=n1-standard-2 --image-type=gci --num-nodes=3 --network=e2e-18057 --cluster-version=1.9.0-alpha.2.266+fdeeed100132cf e2e-18057
W1107 00:08:36.262] Creating cluster e2e-18057...
W1107 00:30:02.919] .....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................done.
W1107 00:30:03.726] ERROR: (gcloud.container.clusters.create) Operation [<Operation
W1107 00:30:03.726]  endTime: u'2017-11-07T00:30:00.716555911Z'
W1107 00:30:03.726]  name: u'operation-1510013316239-37703ad9'
W1107 00:30:03.726]  operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
W1107 00:30:03.727]  selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/216093379844/zones/us-central1-f/operations/operation-1510013316239-37703ad9'
W1107 00:30:03.727]  startTime: u'2017-11-07T00:08:36.239134796Z'
W1107 00:30:03.727]  status: StatusValueValuesEnum(DONE, 3)
W1107 00:30:03.727]  statusMessage: u'Timed out waiting for cluster initialization. Cluster API may not be available.'
W1107 00:30:03.727]  targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/216093379844/zones/us-central1-f/clusters/e2e-18057'
W1107 00:30:03.727]  zone: u'us-central1-f'>] finished with error: Timed out waiting for cluster initialization. Cluster API may not be available.
```

We need someone with access to the GKE master logs to diagnose further. I believe @yliaog is looking into it.

**Comment by yliaog** [comment]
Yes, I think the culprit is  commit 3a15fdbe7 (https://github.com/kubernetes/kubernetes/commit/3a15fdbe7). 
PR is https://github.com/kubernetes/kubernetes/pull/54643

Looking at the diffs, the type of ManifestURLHeader is changed from string to map[string][]string

**Comment by jpbetz** [comment]
Is this a release blocker? We hit this while validating 1.8.3 (https://github.com/kubernetes/kubernetes/issues/55244). Should we proceed with the release and ignore this error or should we hold off?

**Comment by enisoc** [comment]
@jpbetz It looks like @yliaog believes the issue here is something that went into `master` recently, so #55244 is likely a different problem. Sorry if I led you astray by guessing at a connection.

**Comment by jpbetz** [comment]
@enisoc No worries. Following other leads now.

**Comment by yliaog** [comment]
i managed to ssh into one failed cluster master, and got the error msg:
/home/kubernetes/bin/configure.sh: line 244: LOAD_IMAGE_COMMAND: unbound variable

A quick github search revealed https://github.com/kubernetes/kubernetes/pull/54964 is the culprit. It introduced LOAD_IMAGE_COMMAND. Although it added the default in cluster/gce/config-default.sh (LOAD_IMAGE_COMMAND=${KUBE_LOAD_IMAGE_COMMAND:-docker load -i}), however, the default is not properly loaded.

**Comment by Random-Liu** [comment]
Github become pretty slow on my side.

I sent out a PR https://github.com/kubernetes/kubernetes/pull/55331.

As said by @yliaog, GKE is not using `cluster/config-default.sh` and `cluster/config-test.sh` in open source, but we only added the default value in those files.

In https://github.com/kubernetes/kubernetes/pull/55331, we apply a default in `cluster/gce/gci/configure.sh`, which should fix the issue.

**Comment by yliaog** [comment]
lgtm

**Comment by spiffxp** [comment]
/reopen
I'd like to hold this open until I see the results on testgrid

**Comment by spiffxp** [comment]
/reopen
...
😑

**Comment by enisoc** [comment]
It's still failing, but it seems to be a different reason now. @yliaog is continuing to investigate.

**Comment by yliaog** [comment]
sudo journalctl -xe -u kubelet
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]: panic: assignment to entry in nil map
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]: goroutine 1 [running]:
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flag.ColonSeparatedMultimapStringString.Set(0x0, 0x7ffe2dbd0c62, 0x16, 0x7ffe2
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flag/colon_separat
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]: k8s.io/kubernetes/vendor/github.com/spf13/pflag.(*FlagSet).setFlag(0xc420076000, 0xc4204423c0, 0x7ffe2dbd0c62, 0x16, 0x7ffe2dbd0c
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/flag.go:802 +0x63
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]: k8s.io/kubernetes/vendor/github.com/spf13/pflag.(*FlagSet).Parse.func1(0xc4204423c0, 0x7ffe2dbd0c62, 0x16, 0x7ffe2dbd0c4c, 0x2c, 
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/flag.go:960 +0x5c
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]: k8s.io/kubernetes/vendor/github.com/spf13/pflag.(*FlagSet).parseLongArg(0xc420076000, 0x7ffe2dbd0c4c, 0x2c, 0xc420010260, 0x1, 0x
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/flag.go:863 +0x2b7
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]: k8s.io/kubernetes/vendor/github.com/spf13/pflag.(*FlagSet).parseArgs(0xc420076000, 0xc420010260, 0x1, 0x2, 0xc4202a1d00, 0x12, 0x
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/flag.go:940 +0x550
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]: k8s.io/kubernetes/vendor/github.com/spf13/pflag.(*FlagSet).Parse(0xc420076000, 0xc420010150, 0x12, 0x13, 0x564a00, 0xc420076000)
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/flag.go:963 +0xe7
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]: k8s.io/kubernetes/vendor/github.com/spf13/pflag.Parse()
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/flag.go:1015 +0x6f
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flag.InitFlags()
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flag/flags.go:50 +
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]: main.main()
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm kubelet[3376]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:57 +0x8c
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm systemd[1]: kubelet.service: Unit entered failed state.
Nov 10 16:41:51 gke-452295780825-3f11d0ea538a32af43ce-cc87-f398-vm systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Comment by enisoc** [comment]
Probably need to add a default for ManifestURLHeader like this:

https://github.com/kubernetes/kubernetes/blob/4793b714d82ddcdcd5ace8978f01c929fcfc1677/pkg/kubelet/apis/kubeletconfig/v1alpha1/defaults.go#L215-L220

**Comment by yliaog** [comment]
The culprit: https://github.com/kubernetes/kubernetes/pull/54643/files#diff-93eec00d1284a0950a5665a1448c1587L69

ManifestURLHeader was changed to type of map[string][]string, but not initialized.

https://github.com/kubernetes/kubernetes/blob/3a15fdbe7e1ceefa59d7cc41ac6d65998cef1b1a/cmd/kubelet/app/options/options.go#L340
it needs to be initialized like NodeLabels
===========================================================
	c.NodeLabels = make(map[string]string)
	bindableNodeLabels := flag.ConfigurationMap(c.NodeLabels)
	fs.Var(&bindableNodeLabels, "node-labels", "<Warning: Alpha feature> Labels to add when registering the node in the cluster.  Labels must be key=value pairs separated by ','.")

**Comment by mtaufen** [comment]
Surprised this passed the PR builder tests. I'll send a fix.

**Comment by mtaufen** [comment]
@yliaog the way NodeLabels does it is actually bad, could override any defaults unintentionally. I'll allocate it in the defaulter.

**Comment by yliaog** [comment]
Yes, defaulter is better. Thanks.

**Comment by mtaufen** [comment]
https://github.com/kubernetes/kubernetes/pull/55499

**Comment by enisoc** [comment]
The GKE test on #55499 fixes the kubelet panic, but now we are hitting a fourth problem:

```
/home/kubernetes/bin/configure-helper.sh: line 1734: FLUENTD_GCP_MEMORY_LIMIT: unbound variable
```

**Comment by spiffxp** [comment]
>Surprised this passed the PR builder tests. I'll send a fix.

@mtaufen I can't recall the history for why this is the case, but I'm looking at k/k PR's and not seeing any gke jobs.

**Comment by spiffxp** [comment]
In chatting on #sig-testing, it seems like we _do_ have a GKE presubmit job, but it's only setup to be manually triggered, not auto-triggered as a blocking presubmit for all jobs.  I can't recall the history for this, and couldn't dig up anything sifting through kubernetes/test-infra's commit log.  @fejta do you remember anything?

If the GKE jobs are going to be release blocking it'd be _nice_ to have a blocking presubmit for GKE.  OTOH, if they're shouldn't be release blocking, let's get them off the board.  I know this begs the question of what the criteria for release-blocking ought to be, but in the meantime I'm looking to @kubernetes/sig-gcp-test-failures for preference or intent on this.

**Comment by yliaog** [comment]
Found following errors in e2e test:
W1111 06:06:35.956]  zone: u'us-central1-f'>] finished with error: All cluster resources were brought up, but the cluster API is reporting that only 0 nodes out of 3 have registered. Cluster may be unhealthy.

Found the RBAC DENY in API server log
I1111 05:53:29.316972       5 rbac.go:116] RBAC DENY: user "system:node-problem-detector" groups ["system:authenticated"] cannot "patch" resource "nodes/status" named "gke-xxxxx-4th-default-pool-dcab13b3-191f" cluster-wide

I1111 05:53:35.393883       5 rbac.go:116] RBAC DENY: user "system:kube-scheduler" groups ["system:authenticated"] cannot "list" resource "nodes" cluster-wide

looks like caused by the rbac change in https://github.com/kubernetes/kubernetes/pull/53144

**Comment by yliaog** [comment]
Found the following error logs from one node in a failed cluster.

Nov 12 03:32:05 gke-oneoff-e2e-default-pool-d85a29f5-1s1k kubelet[23455]: error: failed to run Kubelet: cannot crea
te certificate signing request: certificatesigningrequests.certificates.k8s.io is forbidden: User "kubelet" cannot 
create certificatesigningrequests.certificates.k8s.io at the cluster scope: Unknown user "kubelet"

**Comment by spiffxp** [comment]
/close
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke 4 green runs in a row, thanks for the help

**Comment by krzyzacy** [comment]
/reopen

https://k8s-testgrid.appspot.com/google-gke#gci-gke
something is busted midnight - from commit range https://github.com/kubernetes/kubernetes/compare/d20b15699...b223955c0 nothing is really suspicious

**Comment by abgworrall** [comment]
There is a theory that it is related to #55950

**Comment by enisoc** [comment]
It seems related to the attempt to disable docker live restore.

From systemctl status kube-master-configuration:

```
Enable docker registry mirror at: https://mirror.gcr.io
Extend the docker.service configuration to remove the network checkpiont
Extend the docker.service configuration to set a higher pids limit
Docker command line is updated. Restart docker to pick it up
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
kube-master-configuration.service: Main process exited, code=exited, status=1/FAILURE
Failed to start Configure kubernetes master.
```

From systemctl status docker:

```
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: live-restore: (from flag: false, from file: false)
```

**Comment by enisoc** [comment]
I suspect https://github.com/kubernetes/kubernetes/pull/55639.

**Comment by yguo0905** [comment]
We are aware of this issue and fixing it.

**Comment by yujuhong** [comment]
Fixed.
