### ISSUE TITLE
eviction_manager relies on nodeReclaimFunc to return the amount of resource they have freed but they don't

### ISSUE THREAD

**Issue by eastlondoner** [kubernetes/kubernetes#56573]
When eviction is triggered by scarcity of inodes the functions to cleanup images (and containers) return 0 instead of the number of inodes freed.

This means that if the inode threshold is ever reached and triggers eviction_manager then a pod will **always** be evicted - even if reclaimNodeLevelResources succeeded in freeing up sufficient resources.

here is where eviction_manager calls nodeReclaimFunc:
https://github.com/kubernetes/kubernetes/blob/2aeace402ac8dc88440eb5c0453b31dd28ca14f2/pkg/kubelet/eviction/eviction_manager.go#L433

here is the deleteImages function which is called and returns 0 if the resource in question is `resourceImageFsInodes` or `resourceNodeFsInodes`:
https://github.com/kubernetes/kubernetes/blob/a65a24a850deb8ec48dc8fa3668f25a67de06637/pkg/kubelet/eviction/helpers.go#L877

n.b. inode exhaustion is very common for docker when using the overlay storage driver. 
Gcloud Kubernetes Engine uses the overlay storage driver so this issue affects all GKE users.

/sig node
/sig resource management

**Comment by eastlondoner** [comment]
@kubernetes/sig-resource-management-bug

**Comment by eastlondoner** [comment]
@kubernetest/sig-node-bug

**Comment by eastlondoner** [comment]
I made a PR with a possible (naive) fix here: https://github.com/kubernetes/kubernetes/pull/56575

**Comment by thkoch2001** [comment]
Hi Andrew,

when we discussed this issue in your support case, you gave me a link to an ancient version of kubernetes:
https://github.com/kubernetes/kubernetes/blob/a65a24a850deb8ec48dc8fa3668f25a67de06637/pkg/kubelet/eviction/helpers.go#L877
However, this bug has been fixed last year:
https://github.com/kubernetes/kubernetes/commit/c9f58c0cd5c8dcaac03cb28e976c7acc253c0606

Can we close this github issue then?

**Comment by eastlondoner** [comment]
@thkoch2001 apologies that the link I gave you caused confusion, I did go back to when the problematic code first appeared because I wanted to look at the commit message at the time.

Despite your best attempts to claim otherwise this bug does exist!

That commit you pointed to doesn't fix the problem. For the inodes case `reportBytesFreed` is set to False. So the return value from the function is `reclaimed := int64(0)` - irrespective of how many resources have been freed.

I think it should be clear that the approach of eviction_manager relying on the node cleanup function to return the size of resources freed is inherently problematic. This PR basically works around that by explicitly checking the resources.

**Comment by eastlondoner** [comment]
If you go back to the PR referenced from my commit you will see that @derekwaynecarr actually says 
> we have no way of knowing the number of inodes reclaimed in response to image gc.

**Comment by dashpole** [comment]
@eastlondoner thanks for pointing this out.  I think your approach in https://github.com/kubernetes/kubernetes/pull/56575 is a good approach.
We should look to address this in 1.10
/kind bug
/priority important-soon

**Comment by eastlondoner** [comment]
Thanks!
