### ISSUE TITLE
controller-manager has stale jobs and can't delete them

### ISSUE THREAD

**Issue by phsiao** [kubernetes/kubernetes#59676]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

We have observed that completed or failed jobs that don't get cleaned up correctly according to its cronjob history limit.  For example, here is one of the log line in controller manager:

```
Event(v1.ObjectReference{Kind:"CronJob", Namespace:"<ns>", Name:"<job>", UID:"aacedebe-a671-11e7-a99f-90b11c577e2e", APIVersion:"batch", ResourceVersion:"441387677", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job <job>
```

repeatedly periodically, but if I look at the job spec it is metadata is

```
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: 2018-02-09T20:00:21Z
  deletionGracePeriodSeconds: 0
  deletionTimestamp: 2018-02-09T21:37:50Z
  finalizers:
  - orphan
  labels:
    controller-uid: dbcb8d9e-0dd3-11e8-9a51-90b11c578803
    job-name: <job>
  name: <job>
  namespace: <ns>
  ownerReferences:
  - apiVersion: batch/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: <job>
    uid: aacedebe-a671-11e7-a99f-90b11c577e2e
  resourceVersion: "441430288"
  selfLink: /apis/batch/v1/namespaces/<ns>/jobs/<job>
  uid: dbcb8d9e-0dd3-11e8-9a51-90b11c578803
```

I can delete the job manually, or I can stop/start controller-manager and it likely will clean it up.

On restart of controller-manager, I would expect to see this:

```
Event(v1.ObjectReference{Kind:"CronJob", Namespace:"<ns>", Name:"<job>", UID:"aacedebe-a671-11e7-a99f-90b11c577e2e", APIVersion:"batch", ResourceVersion:"441387677", FieldPath:""}): type: 'Warning' reason: 'FailedDelete' Deleted job: jobs.batch "<job>" not found
```

**What you expected to happen**:

controller-manager cleans up the job as expected.

**How to reproduce it (as minimally and precisely as possible)**:

Don't know yet, but happens and stays in that state till intervention.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.2
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): CentOS Linux release 7.4.1708 (Core) 
- Kernel (e.g. `uname -a`): 4.14.15-1.el7.elrepo.x86_64
- Install tools: custom
- Others:

**Comment by phsiao** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by deads2k** [comment]
> @kubernetes/sig-api-machinery-misc

apimachinery owns a lot of infrastructure, but the individual workload controllers are @kubernetes/sig-apps-bugs

**Comment by phsiao** [comment]
Happening again but on a cluster running 1.8.6 controller-manager.

controller-manager log showing job deleted successfully repeatedly.

```
I0227 14:31:35.465381      75 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"kube-system", Name:"<job>", UID:"6698a02d-d3bf-11e7-8115-c81f66f22c73", APIVersion:"batch", ResourceVersion:"185249846", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job <job>-1518384900
I0227 14:31:57.215116      75 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"kube-system", Name:"<job>", UID:"6698a02d-d3bf-11e7-8115-c81f66f22c73", APIVersion:"batch", ResourceVersion:"185249846", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job <job>-1518384900
I0227 14:32:18.714885      75 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"kube-system", Name:"<job>", UID:"6698a02d-d3bf-11e7-8115-c81f66f22c73", APIVersion:"batch", ResourceVersion:"185249846", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job <job>-1518384900
I0227 14:32:40.214877      75 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"kube-system", Name:"<job>", UID:"6698a02d-d3bf-11e7-8115-c81f66f22c73", APIVersion:"batch", ResourceVersion:"185249846", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job <job>-1518384900
I0227 14:33:01.714892      75 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"kube-system", Name:"<job>", UID:"6698a02d-d3bf-11e7-8115-c81f66f22c73", APIVersion:"batch", ResourceVersion:"185249846", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job <job>-1518384900
I0227 14:33:23.214967      75 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"kube-system", Name:"<job>", UID:"6698a02d-d3bf-11e7-8115-c81f66f22c73", APIVersion:"batch", ResourceVersion:"185249846", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job <job>-1518384900
I0227 14:33:44.714867      75 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"kube-system", Name:"<job>", UID:"6698a02d-d3bf-11e7-8115-c81f66f22c73", APIVersion:"batch", ResourceVersion:"185249846", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job <job>-1518384900
I0227 14:34:06.214834      75 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"kube-system", Name:"<job>", UID:"6698a02d-d3bf-11e7-8115-c81f66f22c73", APIVersion:"batch", ResourceVersion:"185249846", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job <job>-1518384900
```

metadata of the job:

```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"CronJob","namespace":"kube-system","name":"<job>","uid":"6698a02d-d3bf-11e7-8115-c81f66f22c73","apiVersion":"batch","resourceVersion":"171687344"}}
  creationTimestamp: 2018-02-11T21:35:15Z
  deletionGracePeriodSeconds: 0
  deletionTimestamp: 2018-02-27T14:38:25Z
  finalizers:
  - orphan
  labels:
    controller-uid: 7291f82c-0f73-11e8-9e4a-c81f66f25bdb
    job-name:<job>-1518384900
  name: <job>-1518384900
  namespace: kube-system
  ownerReferences:
  - apiVersion: batch/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: <job>
    uid: 6698a02d-d3bf-11e7-8115-c81f66f22c73
  resourceVersion: "185253564"
  selfLink: /apis/batch/v1/namespaces/kube-system/jobs/<job>-1518384900
  uid: 7291f82c-0f73-11e8-9e4a-c81f66f25bdb
```

Restarted controller-manager shows

```
E0227 14:41:37.323096       7 cronjob_controller.go:401] Error deleting job <job>-1518384900 from kube-system/<job>: jobs.batch "<job>-1518384900" not found
I0227 14:41:37.323233       7 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"kube-system", Name:"<job>", UID:"6698a02d-d3bf-11e7-8115-c81f66f22c73", APIVersion:"batch", ResourceVersion:"185254552", FieldPath:""}): type: 'Warning' reason: 'FailedDelete' Deleted job: jobs.batch "<job>-1518384900" not found
```

**Comment by enisoc** [comment]
The thing that stands out to me is that the Job has the `orphan` finalizer. That seems to be what's holding the Job stuck in a pending-deletion state. I don't know why the `orphan` finalizer is not being processed and removed though. @caesarxuchao Any ideas?

On another note, it seems weird to me that CronJob is deleting its Jobs while orphaning the Pods that the Jobs own. I would think it makes sense to also get rid of any remaining Pods that belonged to the Job.

In the code, this doesn't appear to be an explicit choice. CronJob just uses `nil` for the `*DeleteOptions`, and the default for Job happens to be OrphanDependents for legacy reasons:

https://github.com/kubernetes/kubernetes/blob/0dedd13ad7c546f6acac646742ecf9d52e43ab48/pkg/controller/cronjob/injection.go#L121

@soltysh @janetkuo @erictune Is there any reason you're aware of to keep the Pods around when CronJob deletes a Job?

**Comment by phsiao** [comment]
I am not sure if this is just a stale cache problem.  It looks to me that the controller manager has a stale cache that it thinks the jobs are still there, but on restart they were corrected.  Is there a way for me to verify that if this happens next time?

**Comment by phsiao** [comment]
Worth noting is that we have also upgraded the control plane to 1.9.3 and 1.8.8 since the issue last appeared.  I am not sure if #58547 is a factor or not.

**Comment by soltysh** [comment]
> @soltysh @janetkuo @erictune Is there any reason you're aware of to keep the Pods around when CronJob deletes a Job?

@enisoc here's the story behind it (in short :wink:). Initially (when no server-side deletion was possible) we wrote [manual removal of pods and only then job](https://github.com/kubernetes/kubernetes/blob/0dedd13ad7c546f6acac646742ecf9d52e43ab48/pkg/controller/cronjob/cronjob_controller.go#L359-L409). Now when the server-side deletion was introduced to keep [backwards compatibility](https://github.com/kubernetes/kubernetes/blob/0dedd13ad7c546f6acac646742ecf9d52e43ab48/pkg/registry/batch/job/strategy.go#L48-L49) it set the GC policy to `OrphanDependents`. With the server-side printing being mature at this point in time I think we can entirely remove the old bits and move towards the proper design with both the propagation policy explicitly set in the removal to `DeleteDependents`. 
Not sure if we can change defaults in storage, and something tells me that for backwards compatibility reasons we won't. I'll try to open a PR simplifying the controller code in the following days.

**Comment by enisoc** [comment]
@phsiao wrote:
> It looks to me that the controller manager has a stale cache that it thinks the jobs are still there, but on restart they were corrected. Is there a way for me to verify that if this happens next time?

You can check the real state with `kubectl get job <job-name> -o yaml` since that doesn't use any cache. If that returns an object, then the Job really is stuck pending deletion, and it's not just the controller manager thinking it still exists.

Given what I noted above about the `orphan` finalizer, and the fact that restarting controller-manager tends to result in CronJob saying "FailedDelete: Job not found", I suspect that the garbage collector is failing to process the `orphan` finalizer (perhaps due to a watch issue such as the one you linked).

Since the garbage collector also runs inside controller-manager, restarting it causes the garbage collector to rebuild its cache from the latest state in the API server, process the `orphan` finalizer, and finally delete the Job. Meanwhile, CronJob may be racing to delete the Job as well; if the GC wins the race, that will result in the "FailedDelete: Job not found" error.

@soltysh Thanks for the explanation. I agree that we shouldn't change the default GC policy since Job is v1. Specifying to delete dependents explicitly in CronJob's Delete call sounds good to me.

**Comment by janetkuo** [comment]
> The thing that stands out to me is that the Job has the orphan finalizer. That seems to be what's holding the Job stuck in a pending-deletion state. I don't know why the orphan finalizer is not being processed and removed though. 

@phsiao thanks for reporting this. Not sure if you still have the controller manager logs when the issue happened. Did you see any logs from garbage collector? It might be because the garbage collector was stuck, something we've seen before (e.g. #60037) and are trying to debug. Appreciate if you can give us more information or logs to help us investigate.

**Comment by phsiao** [comment]
@janetkuo sadly, I did not retain the log, but if this happens again I will try to keep all the logs.  What logging level is required to see the garbage collector entries that you are interested?

**Comment by caesarxuchao** [comment]
The default is verbose enough. There are a couple of V(2) in the [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/garbagecollector/garbagecollector.go), and in 60037 people reported not seeing any gc event.

**Comment by andor44** [comment]
I don't have the controller manager logs on hand, but I was tailing them as it was happening to us. There was a steady stream of "job deleted" messages in the controller-manager's logs, but when I `kubectl get jobs | wc -l`'d the number wasn't going down.

**Comment by janetkuo** [comment]
@andor44 do you know which component sent the "job deleted" messages, and which jobs are said to be deleted in the message? Are they all different jobs or the same one?

What jobs do you see from `kubectl get jobs`? Are they the same job that logs said is deleted, or totally different ones?

**Comment by andor44** [comment]
It was the `cronjob-controller`. It reported it deleted jobs that I was able to `kubectl get job foo` after the message. I could also see the `DELETE` requests on the API server, which responded with 200s.

We ended up restarting the controller-manager, which IIRC didn't immediately fix the issue, but CPU usage rose quite sharply shortly after, and it started deleting jobs for real.

**Comment by sebbrandt87** [comment]
We also saw a big amount of jobs not being deleted. As well we restarted the controller-manger and it seems to be related to timestamps assigned to the nodes / by the nodes?

Currently we are using kubernetes version 1.8.7

See log here:
```
E0314 09:32:11.055079      24 actual_state_of_world.go:483] Failed to set statusUpdateNeeded to needed true because nodeName="node-6.foobar.com"  does not exist
E0314 09:32:11.055104      24 actual_state_of_world.go:497] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true because nodeName="node-6.foobar.com"  does not exist
...
I0314 09:32:11.066259      24 controller_utils.go:1048] Caches are synced for certificate controller
I0314 09:32:11.115382      24 controller_utils.go:1048] Caches are synced for TTL controller
I0314 09:32:11.115645      24 controller_utils.go:1048] Caches are synced for certificate controller
I0314 09:32:11.166312      24 controller_utils.go:1048] Caches are synced for namespace controller
I0314 09:32:11.166634      24 controller_utils.go:1048] Caches are synced for HPA controller
I0314 09:32:11.168564      24 controller_utils.go:1048] Caches are synced for service account controller
I0314 09:32:11.196917      24 controller_utils.go:1048] Caches are synced for persistent volume controller
I0314 09:32:11.213218      24 controller_utils.go:1048] Caches are synced for job controller
I0314 09:32:11.213620      24 controller_utils.go:1048] Caches are synced for garbage collector controller
I0314 09:32:11.213631      24 garbagecollector.go:145] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
I0314 09:32:11.214837      24 controller_utils.go:1048] Caches are synced for daemon sets controller
I0314 09:32:11.218892      24 controller_utils.go:1048] Caches are synced for deployment controller
I0314 09:32:11.225636      24 controller_utils.go:1048] Caches are synced for GC controller
I0314 09:32:11.226451      24 controller_utils.go:1048] Caches are synced for replica set controller
I0314 09:32:11.227114      24 controller_utils.go:1048] Caches are synced for endpoint controller
I0314 09:32:11.230224      24 controller_utils.go:1048] Caches are synced for attach detach controller
I0314 09:32:11.234375      24 controller_utils.go:1048] Caches are synced for node controller
I0314 09:32:11.235083      24 node_controller.go:585] Controller observed a new Node: "node-6.foobar.com"
...
W0314 09:32:11.243631      24 node_controller.go:916] Missing timestamp for Node node-6.foobar.com. Assuming now as a timestamp.
...
I0314 09:32:11.252540      24 node_controller.go:832] Controller detected that zone  is now in state Normal.
I0314 09:32:11.252968      24 taint_controller.go:181] Starting NoExecuteTaintManager
I0314 09:32:11.238614      24 controller_utils.go:1048] Caches are synced for disruption controller
I0314 09:32:11.256134      24 disruption.go:296] Sending events to api server.
I0314 09:32:11.327442      24 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"node-6.foobar.com", UID:"c1a6f9d6-0bec-11e8-a800-005056b74ef4", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node node-6.foobar.com event: Registered Node node-6.foobar.com in Controller
...
I0314 09:32:11.331735      24 controller_utils.go:1048] Caches are synced for stateful set controller
I0314 09:32:11.354279      24 controller_utils.go:1048] Caches are synced for RC controller
I0314 09:32:11.358568      24 controller_utils.go:1048] Caches are synced for resource quota controller
I0314 09:32:11.402202      24 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"batz", Name:"batz-import-apple", UID:"157b0196-17bc-11e8-a445-005056b73337", APIVersion:"batch", ResourceVersion:"125609009", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job batz-import-apple-1521018300
I0314 09:32:11.430429      24 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"batz", Name:"batz-import-apple", UID:"157b0196-17bc-11e8-a445-005056b73337", APIVersion:"batch", ResourceVersion:"125609009", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job batz-import-apple-1521018600
I0314 09:32:11.668691      24 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"batz", Name:"batz-import-apple", UID:"157b0196-17bc-11e8-a445-005056b73337", APIVersion:"batch", ResourceVersion:"125609009", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job batz-import-apple-1521018900
I0314 09:32:11.710936      24 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"batz", Name:"batz-import-nuts", UID:"1583aec3-17bc-11e8-a445-005056b73337", APIVersion:"batch", ResourceVersion:"125607606", FieldPath:""}): type: 'Normal' reason: 'SawCompletedJob' Saw completed job: batz-import-nuts-1521019800
```

After the restarted and the successful assuming `now` as timestamp by the controller it works again.

**Comment by andor44** [comment]
I've started setting up API server auditing and I can now see that it seems to be happening continuously.
![jobs](https://user-images.githubusercontent.com/496456/37411219-97b33d96-27a2-11e8-8116-8c295e8c6d78.png)

In this screenshot the controller manager seems to be trying to delete the same job over and over again. Eventually it seems to succeed, but it takes a while. It also seems that it tries twice almost immediately, though this might be an error in my audit log ingestion.

**Comment by janetkuo** [comment]
@andor44 what's the Kubernetes version of your cluster?

**Comment by copland** [comment]
@janetkuo  We are seeing this issue as well and we are running 1.9.3. 

What we see is a correct number of non-orphaned jobs per our CronJob's successfulJobHistoryLimit and a growing number of orphaned Jobs. The deletionTimestamp of the orphaned Jobs is continuously updated and the jobs do not go away (see below). Interestingly, we have a second, larger cluster running the same Kubernetes and CronJob configurations that is NOT seeing the issue.

```
﻿NAME              FINALIZER   DELETE_TIMESTAMP
job1-1521047160    [orphan]    2018-03-14T19:42:39Z
... truncated ...
job1-1521055320    [orphan]    2018-03-14T19:42:45Z
job1-1521055440    <none>      <none>
job1-1521055560    <none>      <none>
job1-1521055680    <none>      <none>
job1-1521055800    <none>      <none>
job1-1521055920    <none>      <none>
job1-1521056040    <none>      <none>
job1-1521056160    <none>      <none>
job1-1521056280    <none>      <none>
job1-1521056400    <none>      <none>
job1-1521056520    <none>      <none>
job2-1521047100    [orphan]    2018-03-14T19:42:45Z
... truncated ...
job2-1521055920    [orphan]    2018-03-14T19:43:00Z
job2-1521055980    <none>      <none>
job2-1521056040    <none>      <none>
job2-1521056100    <none>      <none>
job2-1521056160    <none>      <none>
job2-1521056220    <none>      <none>
job2-1521056280    <none>      <none>
job2-1521056340    <none>      <none>
job2-1521056400    <none>      <none>
job2-1521056520    <none>      <none>
job2-1521056460    <none>      <none>
```

**Comment by enisoc** [comment]
This definitely sounds to me like the GC is failing to process the `orphan` finalizer.

@copland Can you check, for one of the Jobs stuck with the `orphan` finalizer, if it actually has any Pods left? And if so, what state are those Pods in (Running/Succeeded/Failed)? You should be able to do something like:

```sh
kubectl get pods -a -l job-name=...
```

If there are any Pods returned, it would also help if you can show the `metadata` section, in particular the `ownerReferences` (if any):

```sh
kubecl get pod <pod-name> -o yaml
```

**Comment by copland** [comment]
@enisoc There are no pods for any of the stuck Jobs.

**Comment by andor44** [comment]
@janetkuo we see this across clusters running 1.8.3, 1.9.2 and 1.9.3. 

Just like in @copland's case there's no pod, only the job object.

**Comment by copland** [comment]
To follow up on this, I restarted just the controller manager leader a few days ago and haven't seen the issue since.

**Comment by janetkuo** [comment]
This could be that the GC controller gets stuck: #60037

The fix for that (#61201) was merged in 1.10.  The bug was introduced in 1.8 and 1.9 so we're cherrypick the fix into 1.8 and 1.9.

**Comment by soltysh** [comment]
@janetkuo with #61201 merged do you think we can close this one?
@copland || @andor44 are you able to verify if ^ fixes the problem for you?

**Comment by janetkuo** [comment]
I'm going to close this, because the symptom looks like a GC controller issue (#60037). 
Please feel free to reopen this issue if #61201 does not solve the problem.

**Comment by maicohjf** [comment]
Monitor the logs of Pod foobar and
 Extract log lines corresponding to error unable-to-access-website
 Write them to /opt/KULM00201/foobar

$ kubectl logs pod foobar | grep “ unable-to-access-website ” >/opt/KULM00201/foobar

> We also saw a big amount of jobs not being deleted. As well we restarted the controller-manger and it seems to be related to timestamps assigned to the nodes / by the nodes?
> 
> Currently we are using kubernetes version 1.8.7
> 
> See log here:
> 
> ```
> E0314 09:32:11.055079      24 actual_state_of_world.go:483] Failed to set statusUpdateNeeded to needed true because nodeName="node-6.foobar.com"  does not exist
> E0314 09:32:11.055104      24 actual_state_of_world.go:497] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true because nodeName="node-6.foobar.com"  does not exist
> ...
> I0314 09:32:11.066259      24 controller_utils.go:1048] Caches are synced for certificate controller
> I0314 09:32:11.115382      24 controller_utils.go:1048] Caches are synced for TTL controller
> I0314 09:32:11.115645      24 controller_utils.go:1048] Caches are synced for certificate controller
> I0314 09:32:11.166312      24 controller_utils.go:1048] Caches are synced for namespace controller
> I0314 09:32:11.166634      24 controller_utils.go:1048] Caches are synced for HPA controller
> I0314 09:32:11.168564      24 controller_utils.go:1048] Caches are synced for service account controller
> I0314 09:32:11.196917      24 controller_utils.go:1048] Caches are synced for persistent volume controller
> I0314 09:32:11.213218      24 controller_utils.go:1048] Caches are synced for job controller
> I0314 09:32:11.213620      24 controller_utils.go:1048] Caches are synced for garbage collector controller
> I0314 09:32:11.213631      24 garbagecollector.go:145] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
> I0314 09:32:11.214837      24 controller_utils.go:1048] Caches are synced for daemon sets controller
> I0314 09:32:11.218892      24 controller_utils.go:1048] Caches are synced for deployment controller
> I0314 09:32:11.225636      24 controller_utils.go:1048] Caches are synced for GC controller
> I0314 09:32:11.226451      24 controller_utils.go:1048] Caches are synced for replica set controller
> I0314 09:32:11.227114      24 controller_utils.go:1048] Caches are synced for endpoint controller
> I0314 09:32:11.230224      24 controller_utils.go:1048] Caches are synced for attach detach controller
> I0314 09:32:11.234375      24 controller_utils.go:1048] Caches are synced for node controller
> I0314 09:32:11.235083      24 node_controller.go:585] Controller observed a new Node: "node-6.foobar.com"
> ...
> W0314 09:32:11.243631      24 node_controller.go:916] Missing timestamp for Node node-6.foobar.com. Assuming now as a timestamp.
> ...
> I0314 09:32:11.252540      24 node_controller.go:832] Controller detected that zone  is now in state Normal.
> I0314 09:32:11.252968      24 taint_controller.go:181] Starting NoExecuteTaintManager
> I0314 09:32:11.238614      24 controller_utils.go:1048] Caches are synced for disruption controller
> I0314 09:32:11.256134      24 disruption.go:296] Sending events to api server.
> I0314 09:32:11.327442      24 event.go:218] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"node-6.foobar.com", UID:"c1a6f9d6-0bec-11e8-a800-005056b74ef4", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node node-6.foobar.com event: Registered Node node-6.foobar.com in Controller
> ...
> I0314 09:32:11.331735      24 controller_utils.go:1048] Caches are synced for stateful set controller
> I0314 09:32:11.354279      24 controller_utils.go:1048] Caches are synced for RC controller
> I0314 09:32:11.358568      24 controller_utils.go:1048] Caches are synced for resource quota controller
> I0314 09:32:11.402202      24 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"batz", Name:"batz-import-apple", UID:"157b0196-17bc-11e8-a445-005056b73337", APIVersion:"batch", ResourceVersion:"125609009", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job batz-import-apple-1521018300
> I0314 09:32:11.430429      24 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"batz", Name:"batz-import-apple", UID:"157b0196-17bc-11e8-a445-005056b73337", APIVersion:"batch", ResourceVersion:"125609009", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job batz-import-apple-1521018600
> I0314 09:32:11.668691      24 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"batz", Name:"batz-import-apple", UID:"157b0196-17bc-11e8-a445-005056b73337", APIVersion:"batch", ResourceVersion:"125609009", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job batz-import-apple-1521018900
> I0314 09:32:11.710936      24 event.go:218] Event(v1.ObjectReference{Kind:"CronJob", Namespace:"batz", Name:"batz-import-nuts", UID:"1583aec3-17bc-11e8-a445-005056b73337", APIVersion:"batch", ResourceVersion:"125607606", FieldPath:""}): type: 'Normal' reason: 'SawCompletedJob' Saw completed job: batz-import-nuts-1521019800
> ```
> After the restart of the controller-manager and the successful assuming `now` as timestamp it deletes again outdated jobs and is not just logging that it does.
1.
Monitor the logs of Pod foobar and
 Extract log lines corresponding to error unable-to-access-website
 Write them to /opt/KULM00201/foobar

$ kubectl logs pod foobar | grep “ unable-to-access-website ” >/opt/KULM00201/foobar

**Comment by maicohjf** [comment]
> **Is this a BUG REPORT or FEATURE REQUEST?**:
> 
> /kind bug
> 
> **What happened**:
> 
> We have observed that completed or failed jobs that don't get cleaned up correctly according to its cronjob history limit. For example, here is one of the log line in controller manager:
> 
> ```
> Event(v1.ObjectReference{Kind:"CronJob", Namespace:"<ns>", Name:"<job>", UID:"aacedebe-a671-11e7-a99f-90b11c577e2e", APIVersion:"batch", ResourceVersion:"441387677", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted job <job>
> ```
> repeatedly periodically, but if I look at the job spec it is metadata is
> 
> ```
> apiVersion: batch/v1
> kind: Job
> metadata:
>   creationTimestamp: 2018-02-09T20:00:21Z
>   deletionGracePeriodSeconds: 0
>   deletionTimestamp: 2018-02-09T21:37:50Z
>   finalizers:
>   - orphan
>   labels:
>     controller-uid: dbcb8d9e-0dd3-11e8-9a51-90b11c578803
>     job-name: <job>
>   name: <job>
>   namespace: <ns>
>   ownerReferences:
>   - apiVersion: batch/v1beta1
>     blockOwnerDeletion: true
>     controller: true
>     kind: CronJob
>     name: <job>
>     uid: aacedebe-a671-11e7-a99f-90b11c577e2e
>   resourceVersion: "441430288"
>   selfLink: /apis/batch/v1/namespaces/<ns>/jobs/<job>
>   uid: dbcb8d9e-0dd3-11e8-9a51-90b11c578803
> ```
> I can delete the job manually, or I can stop/start controller-manager and it likely will clean it up.
> 
> On restart of controller-manager, I would expect to see this:
> 
> ```
> Event(v1.ObjectReference{Kind:"CronJob", Namespace:"<ns>", Name:"<job>", UID:"aacedebe-a671-11e7-a99f-90b11c577e2e", APIVersion:"batch", ResourceVersion:"441387677", FieldPath:""}): type: 'Warning' reason: 'FailedDelete' Deleted job: jobs.batch "<job>" not found
> ```
> **What you expected to happen**:
> 
> controller-manager cleans up the job as expected.
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> Don't know yet, but happens and stays in that state till intervention.
> 
> **Anything else we need to know?**:
> 
> **Environment**:
> 
> * Kubernetes version (use `kubectl version`): 1.9.2
> * Cloud provider or hardware configuration: bare metal
> * OS (e.g. from /etc/os-release): CentOS Linux release 7.4.1708 (Core)
> * Kernel (e.g. `uname -a`): 4.14.15-1.el7.elrepo.x86_64
> * Install tools: custom
> * Others:

Ensure a single instance of Pod nginx is running on each node of the kubernetes cluster where
nginx also represents the image name which has to be used. Do no override any taints currently
in place.
Use Daemon sets to complete this task and use ds.kusc00201 as Daemonset name.


apiVersion: apps/v1
kind: DaemonSet
metadata:
     name: ds.kusc...
spec:
     selector:
         matchLabels:
         name: nginx
     template:
         metadata:
              labels:
                 name: nginx
         spec:
              containers:
               - name: nginx
                  image: nginx
kubectl create -f   3.yaml

**Comment by maicohjf** [comment]
> > @soltysh @janetkuo @erictune Is there any reason you're aware of to keep the Pods around when CronJob deletes a Job?
> 
> @enisoc here's the story behind it (in short 😉). Initially (when no server-side deletion was possible) we wrote [manual removal of pods and only then job](https://github.com/kubernetes/kubernetes/blob/0dedd13ad7c546f6acac646742ecf9d52e43ab48/pkg/controller/cronjob/cronjob_controller.go#L359-L409). Now when the server-side deletion was introduced to keep [backwards compatibility](https://github.com/kubernetes/kubernetes/blob/0dedd13ad7c546f6acac646742ecf9d52e43ab48/pkg/registryPerform the following tasks

/batch/job/strategy.go#L48-L49) it set the GC policy to `OrphanDependents`. With the server-side printing being mature at this point in time I think we can entirely remove the old bits and move towards the proper design with both the propagation policy explicitly set in the removal to `DeleteDependents`.
> Not sure if we can change defaults in storage, and something tells me that for backwards compatibility reasons we won't. I'll try to open a PR simplifying the controller code in the following days.

 Add an init container to lumpy--koala (Which has been defined in spec file
/opt/kucc00100/pod-spec-KUCC00100.yaml)
 The init container should create an empty file named /workdir/calm.txt
 If /workdir/calm.txt is not detected, the Pod should exit
 Once the spec file has been updated with the init container definition, the Pod should be
created.


yaml 文件：
apiVersion：v1
kind：Pod
Metadate:
      Name: lumpy-koala
Spec
      Volumes
            - name workdir
               Emptydir
      Containers
            - name checker
               Image alpine
              Command .......
              Volumemount
                  - name workdir
                     Mountpath /workdir


Answer:
apiVersion: v1
kind: pod
metadata:
      name: lumpy-koala
spec:
      volumes:
          - name: workdir
             emptyDir: {}
      contianers:
          - name: checker
             image: alpine
             command: ....
             volumeMount:
                 - name: workdir
                    mountPath: /workdir
      initContainers:
         - name: init-lumpy-koala
            image: busybox
            command: ['sh','-c','touch /workdir/calm.txt']
            volumeMounts:
                - name: workdir
                   mountPath: /workdir


kubectl create -f opt/kucc00100/pod-spec-KUCC00100.yaml
