### ISSUE TITLE
Flaky timeouts while waiting for RC pods to be running in density test

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#61189]
Follows from https://github.com/kubernetes/kubernetes/issues/60500#issuecomment-372395317.

We're seeing such flakes in our density test:

```
Error while waiting for replication controller density-latency-pod-54 pods to be running: Timeout while waiting for pods with labels "name=density-latency-pod-54,type=density-latency-pod" to be running
```

E.g:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11568
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11567
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11560
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11553
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11545
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11528
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11507
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11497
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11492

I'm not very sure if this should be a release-blocker - but we need to understand why this is happening.

/sig scalability
/kind bug
/priority important-soon

cc @wojtek-t

**Comment by shyamjvs** [comment]
I'm choosing run https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11568 for further debugging.
So in that run, this happened with `density-latency-pod-53` in particular (note that it's an RC for latency pod):

```
Error while waiting for replication controller density-latency-pod-53 pods to be running: Timeout while waiting for pods with labels "name=density-latency-pod-53,type=density-latency-pod" to be running
```

When I look into the [controller-manager logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11568/artifacts/e2e-big-master/kube-controller-manager.log) for that RC, I find this:

```
I0312 15:03:48.347655       1 replica_set.go:477] Too few replicas for ReplicationController e2e-tests-density-30-1-tnrqx/density-latency-pod-53, need 1, creating 1
I0312 15:03:48.637839       1 event.go:218] Event(v1.ObjectReference{Kind:"ReplicationController", Namespace:"e2e-tests-density-30-1-tnrqx", Name:"density-latency-pod-53", UID:"90da6475-2606-11e8-a154-42010a800002", APIVersion:"v1", ResourceVersion:"69007", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: density-latency-pod-53-x28c5
...
I0312 15:03:50.793242       1 replica_set.go:477] Too few replicas for ReplicationController e2e-tests-density-30-1-tnrqx/density-latency-pod-53, need 1, creating 1
I0312 15:03:51.087032       1 event.go:218] Event(v1.ObjectReference{Kind:"ReplicationController", Namespace:"e2e-tests-density-30-1-tnrqx", Name:"density-latency-pod-53", UID:"90da6475-2606-11e8-a154-42010a800002", APIVersion:"v1", ResourceVersion:"69125", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: density-latency-pod-53-rl69v
...
I0312 15:13:54.342430       1 garbagecollector.go:356] processing item [v1/Pod, namespace: e2e-tests-density-30-1-tnrqx, name: density-latency-pod-53-rl69v, uid: 92e382cc-2606-11e8-a154-42010a800002]
I0312 15:13:54.342430       1 garbagecollector.go:356] processing item [v1/Pod, namespace: e2e-tests-density-30-1-tnrqx, name: density-latency-pod-53-x28c5, uid: 916dbdf1-2606-11e8-a154-42010a800002]
I0312 15:13:54.344375       1 garbagecollector.go:466] delete object [v1/Pod, namespace: e2e-tests-density-30-1-tnrqx, name: density-latency-pod-53-rl69v, uid: 92e382cc-2606-11e8-a154-42010a800002] with propagation policy Background
I0312 15:13:54.348005       1 garbagecollector.go:466] delete object [v1/Pod, namespace: e2e-tests-density-30-1-tnrqx, name: density-latency-pod-53-x28c5, uid: 916dbdf1-2606-11e8-a154-42010a800002] with propagation policy Background
```

So clearly it seems that the rc-controller has created 2 pods ('density-latency-pod-53-x28c5', 'density-latency-pod-53-rl69v') for the RC - though spec.replicas = 1. And later in our test, when we wait for [all pods of that RC to be running](https://github.com/kubernetes/kubernetes/blob/02611149c181f7fd9ab116c40d7ee32fb5934b7c/test/utils/runners.go#L828-L852), there's timeout.

**Comment by shyamjvs** [comment]
There are 2 concerns here:
- we probably shouldn't be waiting in that utility function for "all pods of that RC to be running", but instead for "rc.Replicas many pods to be running"
- even if the RC created an extra pod, why didn't it delete the extra replica later?

**Comment by jberkus** [comment]
/priority critical-urgent

Raisng priority as appropriate, also marking this as in milestone.

**Comment by shyamjvs** [comment]
SGTM

**Comment by wojtek-t** [comment]
@shyamjvs - regarding your concerns, in this comment https://github.com/kubernetes/kubernetes/issues/61189#issuecomment-373134966 mine are actually different (at least one of them)

There are two concerns:
1. why replication controller created two pods (and only then why it didn't remove the second one)
2. Which is even more important, why one of the pods didn't start.

So I looked into those pods, and indeed one of them didn't start. It was scheduled to node:
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11568/artifacts/e2e-big-minion-group-27lb/

And looking into kubelet logs, kubelet successfully received it. but then in kubelet logs I'm seeing this:

```
I0312 15:03:50.459252    1390 kubelet.go:1901] SyncLoop (PLEG): "density-latency-pod-53-x28c5_e2e-tests-density-30-1-tnrqx(916dbdf1-2606-11e8-a154-42010a800002)", event: &pleg.    PodLifecycleEvent{ID:"916dbdf1-2606-11e8-a154-42010a800002", Type:"ContainerStarted", Data:"fe3e0bbcefebc01ad4d34223fd73fa4948d73ab47913a5094cad31bc980c3c4d"}
I0312 15:03:50.459283    1390 kubelet.go:1901] SyncLoop (PLEG): "density-latency-pod-53-x28c5_e2e-tests-density-30-1-tnrqx(916dbdf1-2606-11e8-a154-42010a800002)", event: &pleg.    PodLifecycleEvent{ID:"916dbdf1-2606-11e8-a154-42010a800002", Type:"ContainerStarted", Data:"78ed213a2eee6851bb73f2cf58bec3458b1dc46cf5c4ba689953fe705a12ad5c"}
I0312 15:03:51.351478    1390 kubelet.go:1901] SyncLoop (PLEG): "density-latency-pod-53-x28c5_e2e-tests-density-30-1-tnrqx(916dbdf1-2606-11e8-a154-42010a800002)", event: &pleg.    PodLifecycleEvent{ID:"916dbdf1-2606-11e8-a154-42010a800002", Type:"ContainerDied", Data:"78ed213a2eee6851bb73f2cf58bec3458b1dc46cf5c4ba689953fe705a12ad5c"}
E0312 15:03:51.351931    1390 kubelet_pods.go:1371] Pod attempted illegal phase transition from Failed to Running: &PodStatus{Phase:Running,Conditions:[],Message:,Reason:,HostI    P:,PodIP:10.64.71.81,StartTime:<nil>,ContainerStatuses:[{density-latency-pod-53 {nil nil ContainerStateTerminated{ExitCode:0,Signal:0,Reason:Completed,Message:,StartedAt:2018-0    3-12 15:03:49.457633916 +0000 UTC,FinishedAt:2018-03-12 15:03:50.364256096 +0000 UTC,ContainerID:docker://78ed213a2eee6851bb73f2cf58bec3458b1dc46cf5c4ba689953fe705a12ad5c,}} {n    il nil nil} false 0 k8s.gcr.io/pause-amd64:3.1 docker-pullable://k8s.gcr.io/pause-amd64@sha256:59eec8837a4d942cc19a52b8c09ea75121acc38114a2c68b98983ce9356b8610 docker://78ed213    a2eee6851bb73f2cf58bec3458b1dc46cf5c4ba689953fe705a12ad5c}],QOSClass:Burstable,InitContainerStatuses:[],NominatedNodeName:,}
I0312 15:03:51.352279    1390 kubelet.go:1901] SyncLoop (PLEG): "density-latency-pod-53-x28c5_e2e-tests-density-30-1-tnrqx(916dbdf1-2606-11e8-a154-42010a800002)", event: &pleg.    PodLifecycleEvent{ID:"916dbdf1-2606-11e8-a154-42010a800002", Type:"ContainerDied", Data:"fe3e0bbcefebc01ad4d34223fd73fa4948d73ab47913a5094cad31bc980c3c4d"}
E0312 15:03:51.352513    1390 kubelet_pods.go:1371] Pod attempted illegal phase transition from Failed to Running: &PodStatus{Phase:Running,Conditions:[],Message:,Reason:,HostI    P:,PodIP:10.64.71.81,StartTime:<nil>,ContainerStatuses:[{density-latency-pod-53 {nil nil ContainerStateTerminated{ExitCode:0,Signal:0,Reason:Completed,Message:,StartedAt:2018-0    3-12 15:03:49.457633916 +0000 UTC,FinishedAt:2018-03-12 15:03:50.364256096 +0000 UTC,ContainerID:docker://78ed213a2eee6851bb73f2cf58bec3458b1dc46cf5c4ba689953fe705a12ad5c,}} {n    il nil nil} false 0 k8s.gcr.io/pause-amd64:3.1 docker-pullable://k8s.gcr.io/pause-amd64@sha256:59eec8837a4d942cc19a52b8c09ea75121acc38114a2c68b98983ce9356b8610 docker://78ed213    a2eee6851bb73f2cf58bec3458b1dc46cf5c4ba689953fe705a12ad5c}],QOSClass:Burstable,InitContainerStatuses:[],NominatedNodeName:,}
```

Those lines are what is frightening me:
```
E0312 15:03:51.352513    1390 kubelet_pods.go:1371] Pod attempted illegal phase transition from Failed to Running
```

@yujuhong @kubernetes/sig-node-bugs - is that expected? 

Another thing is why that pod stuck in this state until it was deleted by ReplicationController 10 minutes later.

**Comment by wojtek-t** [comment]
> why replication controller created two pods (and only then why it didn't remove the second one)

@kow3ns @janetkuo @kubernetes/sig-apps-bugs - if any of you can help with debugging that one.
There are a number of link in the first post and each of them seems the same. Because of some reason ReplicationController with 1 replica is creating 2 replicas and such state exists until we trigger deletion of RC.
Example logs are here: https://github.com/kubernetes/kubernetes/issues/61189#issuecomment-373133940

**Comment by enisoc** [comment]
From the ReplicationController side, I believe this is working as intended.

First it creates Pod `density-latency-pod-53-x28c5` which gets scheduled to a node. However, after a few seconds, the Pod is evicted by preemption:

```json
{
  "phase": "Failed",
  "message": "Preempted in order to admit critical pod",
  "reason": "Preempting",
  "startTime":"2018-03-12T15:03:48Z"
}
```

Once a Pod goes to Failed state due to rejection or eviction by the Node, ReplicationController ignores it completely. This means not only that it creates a replacement, but also that it does not delete Failed Pods.

The fix should be that the test should also ignore Failed Pods that happen to match the RC's selector.

**Comment by janetkuo** [comment]
> why replication controller created two pods (and only then why it didn't remove the second one)

It looks like one of the RC's pods Failed? RC never sets its pods to Failed state, because its `restartPolicy` is `Always`. It must be kubelet. 

When kubelet evicts pods, it sets pod state to Failed but doesn't delete evicted pods (#54525). 
@enisoc we've debugged another issue related to this.

RC doesn't take any inactive pods (failed, succeeded, terminating) into account: 
https://github.com/kubernetes/kubernetes/blob/02611149c181f7fd9ab116c40d7ee32fb5934b7c/pkg/controller/replicaset/replica_set.go#L607-L612
From RC's view, there's only 1 active replica so RC didn't try to remove more replicas.

**Comment by janetkuo** [comment]
@enisoc didn't see your comment . It seems we have the same conclusion 😄

**Comment by wojtek-t** [comment]
@janetkuo @enisoc - thanks a lot that's super useful!

So I did a bit more debugging. And what is happening is that in all cases that I've seen is:

1. daemon-set controller is removing fluentd from that node
2. the latency-pod is scheduled on that node
3. daemon-set controller is recreating fluentd on that node
4. kubelet is preempting latency-pod to make place for fluentd (which is critical pod)

So that flow seems reasonable.

My only question now is why daemon-set controller is deleting and recreating fluentd on some node.
What is important is that this operation is not done on all nodes.

As an example, in this run:
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/11664/artifacts/e2e-big-master/

There were 100 nodes, but during the whole run (~40 minutes), controller-manager recreated fluentd pods only on 39 nodes.
@janetkuo @enisoc What is triggering those recreations?

**Comment by shyamjvs** [comment]
@wojtek-t Cool debugging! Btw there's at least 2 other places where I noticed sth similar:
- https://github.com/kubernetes/kubernetes/issues/61190#issue-305275363 (ds-controller recreating fluentds)
- https://github.com/kubernetes/kubernetes/issues/60035#issuecomment-366684544 (kubemark pods getting evicted when fluentd pod recreated on node)

Quite remarkably, I noticed all of them were observed after the fluentd-scaler fix https://github.com/kubernetes/kubernetes/pull/59921

@x13n - after all the fluentd recreations seems likely related to your change? :)

**Comment by x13n** [comment]
fluentd-gcp daemonset is created initially without any resource requests nor limits, but gets them as soon as fluentd-gcp-scaler starts running. This effectively is a race condition - if a pod was created without any resource requests/limits, it will be recreated once they are there. If it is created later, the pod will have resource requests/limits already set correctly. Do we need to get rid of that race condition?

**Comment by shyamjvs** [comment]
> Do we need to get rid of that race condition?

I believe yes - as this is sth which can hurt users (wrt evictions of their already running pods).
One more concern to me is - this shouldn't ideally increase the cluster startup time (because we're waiting for scaler to do the setting).

**Comment by wojtek-t** [comment]
Wait - you're saying it's a race. I'm seeing this recreations 30 minutes after cluster startup. Is that expected?

**Comment by x13n** [comment]
@wojtek-t Nope, it should be a matter of seconds. If it takes 30 minutes, this looks like a bug.
@shyamjvs All addons created at once, so I think there are races anyways. I have some ideas how to change that for fluentd but these ideas fall into two categories: bad and worse :)

**Comment by x13n** [comment]
Actually, could restart after 30 minutes be caused by https://github.com/kubernetes/kubernetes/issues/61190?

**Comment by wojtek-t** [comment]
Possible - we didn't see problems since the PR bumping limits was merged.

**Comment by wojtek-t** [comment]
That said, I don't fully understand why this was supposed to help.
The fix meant that we are no longer sending no-op upgrades of DaemonSet.
But even previously, I would expect an update of DaemonSet to either trigger upgrade of all pods, or not trigger any upgrade.
So I would like to understand what exactly it was happening there even if this is fixed..

**Comment by janetkuo** [comment]
I don't know the details of fluentd-scaler and what it does. If it keeps updating DaemonSet template, could it be that the scaler updated the DaemonSet for multiple times very quickly, and therefore Daemon pods don't get updated at the same rate? It's hard to tell without fully understanding how the DaemonSet is used here.

**Comment by enisoc** [comment]
I dug in on one example of DS deleting and recreating a Pod. This seems to confirm that from the perspective of DS, the template was updated and it is doing a rolling update.

Here is the important part of the diff of the Pod on a given Node when it gets deleted, and the replacement Pod that got created on the same Node later.

```diff
55c53,61
<             "resources" : {},
---
>             "resources" : {
>                "limits" : {
>                   "memory" : "300Mi"
>                },
>                "requests" : {
>                   "cpu" : "100m",
>                   "memory" : "200Mi"
>                }
>             },
116c122,130
<             "resources" : {},
---
>             "resources" : {
>                "limits" : {
>                   "memory" : "300Mi"
>                },
>                "requests" : {
>                   "cpu" : "100m",
>                   "memory" : "200Mi"
>                }
>             },
```

I noticed that between deletion and creation of the replacement, 53 seconds elapsed. If the DS is slow to create Pods in general (due to load? self-throttling? I did notice a lot of RV conflicts on DS trying to update status), this might explain why we observed delete/recreates on only 39 of the 100 Nodes.

Maybe those 39 Nodes are the ones where DS had already managed to create Pods (with empty resources) before the DS template was updated to fill in the resources. The rest got created with resources from the beginning (and thus never needed to be "updated") because they didn't exist yet when the template was updated.

@janetkuo Does this hypothesis seem plausible given how DS rolling update works?

**Comment by wojtek-t** [comment]
@enisoc - thanks a lot for looking!

I think the hypothesis makes perfect sense.

> Maybe those 39 Nodes are the ones where DS had already managed to create Pods

The other hypothesis is that during those ~30 minutes of test, we didn't have enough time to recreate more pods.

But I think that in general we understand the issue.

We should fix the test to make it more robust, but I don't consider this as a release blocker.

**Comment by shyamjvs** [comment]
Thanks for the great debugging! I agree this a non-release-blocker wrt the test-side of the issue (I'll send out a fix for that soon).
The fluentd recreations part of the issue still seems a release-blocker, but IIUC we have https://github.com/kubernetes/kubernetes/issues/61190 for that.

**Comment by wojtek-t** [comment]
> The fluentd recreations part of the issue still seems a release-blocker, but IIUC we have #61190 for that.

I'm not convinced that this is release blocker. But it should be handled there.

In this issue, we should only fix our tests to be more resiliant for such failures. Which is definitely not a release blocker.

**Comment by shyamjvs** [comment]
> I'm not convinced that this is release blocker.

The reason why I believe it should be a release-blocker is https://github.com/kubernetes/kubernetes/issues/61189#issuecomment-373645495. Just my 2 cents - but if 30 mins after the cluster start, if some fluentds are getting restarted (potentially leading to user pod evictions, loss of logs, etc) it may not be ideal.

That said, I agree it's probably not an end-of-the-world problem and don't have too strong opinion :)

**Comment by jdumars** [comment]
@shyamjvs can you please verify this is resolved?

**Comment by shyamjvs** [comment]
My fix was just merged... Need at least a day to reasonably assert the flake is gone.
Either way, note that this is not a blocker anymore as @wojtek-t said in https://github.com/kubernetes/kubernetes/issues/61189#issuecomment-373999656

**Comment by shyamjvs** [comment]
The job has turned green and we're no longer seeing such flakes (at least in the last ~1.5 day).
IMO we can safely assume this is fixed now.
