### ISSUE TITLE
Internal PreStartContainer hook failed: not enough cpus available to satisfy request

### ISSUE THREAD

**Issue by discordianfish** [kubernetes/kubernetes#63018]
/kind bug
**What happened**:
Sometimes when an deployment creates new pods they get scheduled on a node successfully but the containers fail to start with:

```
Warning  Failed                 14m (x8 over 15m)    kubelet, ip-172-20-162-142.ec2.internal  Internal PreStartContainer hook failed: not enough cpus available to satisfy request
```

**What you expected to happen**:
The scheduler shouldn't put pods on nodes without enough resources.

**How to reproduce it (as minimally and precisely as possible)**:
I don't know how it got into this situation. Deleting the pods and have the RS recreate them works around this issue.

**Anything else we need to know?**:
We're using the CPUManager with static policy which might contribute to this problem.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-beta.2", GitCommit:"63dad40a0391b7af32c34fdbf41fa199c3b247ad", GitTreeState:"clean", BuildDate:"2018-03-07T20:42:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): coreos

/sig scheduling

**Comment by ConnorDoyle** [comment]
/sig node
(for CPU manager)

**Comment by discordianfish** [comment]
@ConnorDoyle Hi! :)
No, I don't see these 'still running' messages. This is what I've got in the kubelet log (slightly redacted):
```
kubelet-wrapper[918]: I0424 09:23:38.196136     918 policy_static.go:190] [cpumanager] allocateCpus: (numCPUs: 2)
kubelet-wrapper[918]: E0424 09:23:38.196148     918 policy_static.go:170] [cpumanager] unable to allocate 2 CPUs (container id: fffeb37bb2bc4e0389b3c6b80a4b04100c356010611bc5092ea5bff56af73f1f, error: not enough cpus available to satisfy request)
kubelet-wrapper[918]: E0424 09:23:38.196155     918 cpu_manager.go:173] [cpumanager] AddContainer error: not enough cpus available to satisfy request
kubelet-wrapper[918]: E0424 09:23:38.196176     918 kuberuntime_manager.go:733] container start failed: not enough cpus available to satisfy request: Internal PreStartContainer hook failed
kubelet-wrapper[918]: E0424 09:23:38.196195     918 pod_workers.go:186] Error syncing pod d12ff33d-479b-11e8-8eb4-12cb0c7fcb5e ("xx-868986d669-pnk5g_master(d12ff33d-479b-11e8-8eb4-12cb0c7fcb5e)"), skipping: failed to "StartContainer" for "xx" with not enough cpus available to satisfy request: "Internal PreStartContainer hook failed"
kubelet-wrapper[918]: I0424 09:23:38.317812     918 policy_static.go:180] [cpumanager] static policy: RemoveContainer (container id: db40d1a7bcf5a8582a47dfbb0c046870ae60538034bfa81e9d6a9af90643f97f)
kubelet-wrapper[918]: I0424 09:23:38.317901     918 kuberuntime_manager.go:513] Container {Name:xx .....} is dead, but RestartPolicy says that we should restart it.
kubelet-wrapper[918]: I0424 09:23:38.562794     918 policy_static.go:160] [cpumanager] static policy: AddContainer (pod: xx-868986d669-j5n99, container: xx, container id: ff2f75c5d41fe84be96f797400c3a020812733a723a4fa2842f41d4d05689031)
kubelet-wrapper[918]: I0424 09:23:38.562815     918 policy_static.go:190] [cpumanager] allocateCpus: (numCPUs: 2)
kubelet-wrapper[918]: E0424 09:23:38.562827     918 policy_static.go:170] [cpumanager] unable to allocate 2 CPUs (container id: ff2f75c5d41fe84be96f797400c3a020812733a723a4fa2842f41d4d05689031, error: not enough cpus available to satisfy request)
kubelet-wrapper[918]: E0424 09:23:38.562833     918 cpu_manager.go:173] [cpumanager] AddContainer error: not enough cpus available to satisfy request
kubelet-wrapper[918]: E0424 09:23:38.562856     918 kuberuntime_manager.go:733] container start failed: not enough cpus available to satisfy request: Internal PreStartContainer hook failed
kubelet-wrapper[918]: E0424 09:23:38.562877     918 pod_workers.go:186] Error syncing pod 259983b0-479d-11e8-8eb4-12cb0c7fcb5e ("xx-868986d669-j5n99_master(259983b0-479d-11e8-8eb4-12cb0c7fcb5e)"), skipping: failed to "StartContainer" for "xx" with not enough cpus available to satisfy request: "Internal PreStartContainer hook failed"
```

**Comment by balajismaniam** [comment]
@discordianfish Can you share more information on this? Deployment manifest, platform details, frequency of these errors?

**Comment by discordianfish** [comment]
I've just realize that only one specific node (which is suppose to be the same as all other nodes) seems to be affected on which all pods that require full CPUs (triggering the static allocation) fail. Going to taint and drain the node now and will decomision it ~tomorrow, so let me know if you want me to pull something from the node first.

Unfortunately I don't have long enough log rentention to see what kubelet might have logged before it got into this state.

**Comment by discordianfish** [comment]
My kubelet args:
```
kubelet --kubeconfig=/etc/kubernetes/admin.conf --pod-manifest-path=/etc/kubernetes/manifests --cloud-provider=aws --cloud-config=/etc/kubernetes/cloud-config --network-plugin=cni --pod-cidr=10.244.0.0/16 --cluster-dns=10.96.0.10 --cluster-domain=int.xxxx --register-with-taints= --feature-gates=CPUManager=true --cpu-manager-policy=static --kube-reserved=cpu=100m --system-reserved=cpu=100m --allow-privileged
```

**Comment by balajismaniam** [comment]
@discordianfish We have fixed the completed pods related issue before: https://github.com/kubernetes/kubernetes/pull/52363.

**Comment by ConnorDoyle** [comment]
@discordianfish would you mind digging into the cpu manager state checkpointed to disk? This will confirm or refute for us that we failed to release CPUs from a terminal container.

The state file is located by default in `var/run/kubernetes/cpu_manager_state` and the content is simply utf-8 JSON. We should be able to see some container-to-cpuset mappings in there. If we can verify that some of the mappings are for terminal container IDs then that's where we should focus the search.

My next question would be, were the PreStopContainer and PostStopContainer callbacks invoked, and if so, was there a failed write to the checkpoint file.

Thanks for helping us to debug this remotely!

**Comment by discordianfish** [comment]
Ah damn, looks like the cluster autoscaler terminated that node already so unfortunately can't provide the cpu_manager_state.. Would be nice to have the relevant bits exposed as Prometheus metrics.

I'll update this issue if this happens again.

**Comment by discordianfish** [comment]
@ConnorDoyle "Good" news, problem just re-appeared - this time on two nodes. Here is one:

cpu_manager_state:
```
{"policyName":"static","defaultCpuSet":"0,8","entries":{"16bf35ba58c9de4b74465827d3c0b8697085ae7e56be4439cca8152bbbacf14c":"2,10","1bd374e223d4dc4d3f4622534f652a6029751184271a5b37d0282c6795382509":"6,14","4b7e8104744bc613de080a0d5ce48d2199abe86b74bf8c624ae27f48d103fb4d":"1,9","914ffa330276d67e93275217ab352c2a6337c0e91c603c1e4dbd6b001867733a":"3,11","97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51":"5,13","a8a7b6c1f1fa29493d2373596df55e4c7e0e04a3d48bab45b465ab607b169a4b":"7,15","c5c76b711d8d4177b184a06e2c18683043f09f3792cfa4202955ef37ba66a851":"4,12"}}
```

One of the containers doesn't exist at all and another one is exited:
```
# cat /var/lib/kubelet/cpu_manager_state |jq -r '.entries|keys[]'|while read id; do docker inspect "$id" |jq '.[0].Id + ": " + .[0].State.Status'; done
"16bf35ba58c9de4b74465827d3c0b8697085ae7e56be4439cca8152bbbacf14c: running"
"1bd374e223d4dc4d3f4622534f652a6029751184271a5b37d0282c6795382509: running"
"4b7e8104744bc613de080a0d5ce48d2199abe86b74bf8c624ae27f48d103fb4d: exited"
"914ffa330276d67e93275217ab352c2a6337c0e91c603c1e4dbd6b001867733a: running"
Error: No such image, container or task: 97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51
": "
"a8a7b6c1f1fa29493d2373596df55e4c7e0e04a3d48bab45b465ab607b169a4b: running"
"c5c76b711d8d4177b184a06e2c18683043f09f3792cfa4202955ef37ba66a851: running"
```

Here is the state field from `docker describe` for the exited container:
```
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 137,
            "Error": "",
            "StartedAt": "2018-04-28T05:29:51.596281736Z",
            "FinishedAt": "2018-04-28T05:31:45.017613968Z"
        },
```
                
It has "io.kubernetes.pod.name": "koko-intelligence-74f64b7c59-np2zh", set and according to k8s this pod is still running on that host:

```
    State:          Running
      Started:      Sat, 28 Apr 2018 07:31:45 +0200
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Sat, 28 Apr 2018 07:29:51 +0200
      Finished:     Sat, 28 Apr 2018 07:31:45 +0200
```

I found this in the kubelet log for this container:
```
# journalctl -u kubelet -S '2018-04-28' --until '2018-04-30'|grep 4b7e810
Apr 28 05:29:51 ip-172-20-161-228 kubelet-wrapper[920]: I0428 05:29:51.528388     920 policy_static.go:160] [cpumanager] static policy: AddContainer (pod: koko-intelligence-74f64b7c59-np2zh, container: koko-intelligence, container id: 4b7e8104744bc613de080a0d5ce48d2199abe86b74bf8c624ae27f48d103fb4d)
Apr 28 05:29:51 ip-172-20-161-228 kubelet-wrapper[920]: I0428 05:29:51.528551     920 state_mem.go:79] [cpumanager] updated desired cpuset (container id: 4b7e8104744bc613de080a0d5ce48d2199abe86b74bf8c624ae27f48d103fb4d, cpuset: "1,9")
Apr 28 05:31:14 ip-172-20-161-228 kubelet-wrapper[920]: I0428 05:31:14.892351     920 policy_static.go:180] [cpumanager] static policy: RemoveContainer (container id: 4b7e8104744bc613de080a0d5ce48d2199abe86b74bf8c624ae27f48d103fb4d)
Apr 28 05:31:24 ip-172-20-161-228 kubelet-wrapper[920]: I0428 05:31:24.463759     920 policy_static.go:160] [cpumanager] static policy: AddContainer (pod: koko-intelligence-74f64b7c59-np2zh, container: koko-intelligence, container id: 4b7e8104744bc613de080a0d5ce48d2199abe86b74bf8c624ae27f48d103fb4d)
Apr 28 05:31:24 ip-172-20-161-228 kubelet-wrapper[920]: I0428 05:31:24.463958     920 state_mem.go:79] [cpumanager] updated desired cpuset (container id: 4b7e8104744bc613de080a0d5ce48d2199abe86b74bf8c624ae27f48d103fb4d, cpuset: "1,9")
```

**Comment by discordianfish** [comment]
Oh and it's indeed running, now in container `16bf35ba58c9` which is also properly accounted for in the state file.

Now regarding the non-existent container, I also see it in the kubelet log:
```
Apr 28 17:32:28 ip-172-20-161-228 kubelet-wrapper[920]: I0428 17:32:28.793268     920 policy_static.go:160] [cpumanager] static policy: AddContainer (pod: koko-gateway-track-659d9c47d8-6mljm, container: koko-gateway, container id: 97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51)
Apr 28 17:32:28 ip-172-20-161-228 kubelet-wrapper[920]: E0428 17:32:28.793303     920 policy_static.go:170] [cpumanager] unable to allocate 2 CPUs (container id: 97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51, error: not enough cpus available to satisfy request)
Apr 28 17:32:38 ip-172-20-161-228 kubelet-wrapper[920]: I0428 17:32:38.719238     920 policy_static.go:180] [cpumanager] static policy: RemoveContainer (container id: 97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51)
Apr 28 17:32:46 ip-172-20-161-228 kubelet-wrapper[920]: I0428 17:32:46.801164     920 policy_static.go:180] [cpumanager] static policy: RemoveContainer (container id: 97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51)
Apr 28 17:32:47 ip-172-20-161-228 kubelet-wrapper[920]: I0428 17:32:47.099371     920 policy_static.go:160] [cpumanager] static policy: AddContainer (pod: koko-gateway-track-659d9c47d8-6mljm, container: koko-gateway, container id: 97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51)
Apr 28 17:32:47 ip-172-20-161-228 kubelet-wrapper[920]: I0428 17:32:47.099494     920 state_mem.go:79] [cpumanager] updated desired cpuset (container id: 97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51, cpuset: "5,13")
Apr 28 17:32:47 ip-172-20-161-228 kubelet-wrapper[920]: E0428 17:32:47.101139     920 remote_runtime.go:302] UpdateContainerResources "97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51" from runtime service failed: rpc error: code = Unknown desc = failed to update container "97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51": Error response from daemon: No such container: 97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51
Apr 28 17:32:47 ip-172-20-161-228 kubelet-wrapper[920]: E0428 17:32:47.101168     920 cpu_manager.go:183] [cpumanager] AddContainer error: rpc error: code = Unknown desc = failed to update container "97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51": Error response from daemon: No such container: 97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51
Apr 28 17:32:47 ip-172-20-161-228 kubelet-wrapper[920]: E0428 17:32:47.101176     920 cpu_manager.go:246] [cpumanager] reconcileState: failed to add container (pod: koko-gateway-track-659d9c47d8-6mljm, container: koko-gateway, container id: 97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51, error: rpc error: code = Unknown desc = failed to update container "97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51": Error response from daemon: No such container: 97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51)
Apr 28 17:32:47 ip-172-20-161-228 kubelet-wrapper[920]: E0428 17:32:47.102126     920 remote_runtime.go:302] UpdateContainerResources "97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51" from runtime service failed: rpc error: code = Unknown desc = failed to update container "97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51": Error response from daemon: No such container: 97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51
Apr 28 17:32:47 ip-172-20-161-228 kubelet-wrapper[920]: E0428 17:32:47.102149     920 cpu_manager.go:267] [cpumanager] reconcileState: failed to update container (pod: koko-gateway-track-659d9c47d8-6mljm, container: koko-gateway, container id: 97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51, cpuset: "5,13", error: rpc error: code = Unknown desc = failed to update container "97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51": Error response from daemon: No such container: 97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51)
Apr 28 17:32:47 ip-172-20-161-228 kubelet-wrapper[920]: W0428 17:32:47.815738     920 pod_container_deletor.go:77] Container "97909f764df06271330a64373cbf40018d9fb2a284bd890a45914c083ed52a51" not found in pod's containers
```

Looks like this belongs to koko-gateway-track-659d9c47d8-6mljm, which doesn't exist anymore. But most likely because it just got gracefully removed eventually.

Maybe some race condition preventing it to remove it and leading to these inconsistencies?

**Comment by ConnorDoyle** [comment]
This is awesome info @discordianfish — thanks for updating. I won’t have time to look at this immediately, but perhaps @balajismaniam can help trace it. I suspect some kind of race in reconcileState.

**Comment by balajismaniam** [comment]
Thanks for the info @discordianfish. I will take a look at this.
/assign

**Comment by discordianfish** [comment]
@balajismaniam / @ConnorDoyle Do you have a rough estimate for this? Fully understand if you have other things on your plate but then I'd probably revert the static policy since this becomes a bigger and bigger problem for us (it looks like it got worse over time, now even nodes are affected that were just brought up).

**Comment by discordianfish** [comment]
@balajismaniam / @ConnorDoyle: Is there some way I can help you debug/fix this? Seems unrelated to anything special in our setup from what I can tell. We had to disable this for all our deployments because it was causing severe issues.

**Comment by discordianfish** [comment]
@balajismaniam /  @ConnorDoyle Do you have any update/ETA on this?

**Comment by clkao** [comment]
Note that this is fixed in 1.12, but backports to 1.11 and 1.10 are not merged yet:

- [1.11 #69736](https://github.com/kubernetes/kubernetes/pull/69736)
- [1.10 #69626](https://github.com/kubernetes/kubernetes/pull/69626)

**Comment by clkao** [comment]
This still happens occasionally in 1.12 (with #67430) . #68619 provides cleanup for stalled entries.

**Comment by klueska** [comment]
Out of curiousity, does anyone still seeing this issue utilize `init` containers in their pod Specs? If so, the curlprit is likely addressed by the following: https://github.com/kubernetes/kubernetes/pull/78219

**Comment by whypro** [comment]
The issue is still existing in kubernetes v1.14.4, without init containers to pod spec.
Some way below may reproduce it:
1. make container crash on a node frequently and then delete the pod.
2. create a new pod and schedule to this node.
Is this already fixed on master branch?
