### ISSUE TITLE
[mesos] Report and enforce resource constraints

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#6828]
When we launch pods , we'll want to confirm that memory, disk, cpu and so on constraints are honored.  Frameworks like mesos will translate these parameters.

Blocked by #5671 

@connordoyle @timothysc @jayunit100

xref https://github.com/mesosphere/kubernetes-mesos/issues/447

**Comment by quinton-hoole** [comment]
jayunit, could you add a bit more detail here?  Assigning priority 3 in the mean time.

**Comment by derekwaynecarr** [comment]
I too would like to know the approach. We should validate requires and limits in resource requirements.

**Comment by quinton-hoole** [comment]
@jayunit100 to get his attention, as I mistyped it above ;-)

**Comment by jayunit100** [comment]
kubelets are deployed differently in different environments, so this e2e test confirms that kubelets themselves are able to honor resources....  So, we can

- launch containers which confirm that the maximum resources available correspond to the constraints provided, 
- launch several containers which run a cpu intensive job, and verify that the ones with more CPU allocations finish first, 
and so on.  

The *original* motivation for this JIRA is specifically that we were brainstorming about how we could *confirm* that kube on mesos honors resource restrictions the same way kube does, and to do this, we need a test which enforces resource restrictions...

**Comment by karlkfi** [comment]
/cc @jdef This is a little old.
I think this was resolved by https://github.com/GoogleCloudPlatform/kubernetes/pull/11230
Can you confirm?

**Comment by jdef** [comment]
@karlkfi #11230 does not implement an e2e test that confirms resource accounting is working as advertised, which is the subject of this issue.

**Comment by sttts** [comment]
There is a e2e test already which checks that cpu resources are validated: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scheduler_predicates.go#L236

**Comment by jdef** [comment]
perhaps if we had a mesos e2e test that ran the petstore example we'd meet the test-for-containment goals of this ticket

**Comment by sttts** [comment]
I still don't see what we need in addition to the mentioned test above. How does the petstore help?

What we really would need in addition would be a real OOM triggering test.

**Comment by sttts** [comment]
I still don't see what we need in addition to the mentioned test above. How does the petstore help?

What we really would need in addition would be a real OOM triggering test.

**Comment by jdef** [comment]
We just spent a bunch of time on our scheduler w/ respect to Mesos "roles" support (think static resource reservations per node, per "role"). One point that came up was related to resource limits vs. requested. Right now the scheduler attempts to allocate resources according to max(limits,requested) with no way to accommodate situations when there are "requested" resources available but not "limits" quantities. There's an open Mesos JIRA for allowing the scheduler to request additional resources for tasks over time, and that seems like a good fit for a use case wherein our scheduler could allocate "requested" resources and then, over time, allocation additional resources up to "limits".

Another thought is to blend revocable and normal resources for tasks, such that "requested"  resources come from the normal pool, and the difference (between requested and limits) come from the revocable pool. A fly in the ointment is that the Mesos QOS controller treats the entire container (executor) as revocable in this case and will heartlessly kill the whole thing if revocable resources need to be reclaimed (see http://mesos.apache.org/documentation/latest/oversubscription/).
