### ISSUE TITLE
Failing tests : [sig-storage] Multiple on gke-gci-new-gci-master-upgrade-cluster-parallel

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#68314]
# Failing Jobs
[sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-new-gci-master-upgrade-cluster-parallel)
# Failing Tests
[PersistentVolumes NFS when invoking the Recycle reclaim policy should test that a PV becomes Available and is clean after the PVC is deleted.](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link-bindmounted] One pod requesting one prebound PVC should be able to mount volume and read from pod1](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link-bindmounted] One pod requesting one prebound PVC should be able to mount volume and write from pod1](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link-bindmounted] Set fsGroup for local volume should not set different fsGroups for two pods simultaneously](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link-bindmounted] Set fsGroup for local volume should set fsGroup for one pod](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link-bindmounted] Set fsGroup for local volume should set same fsGroup for two pods simultaneously](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link-bindmounted] Two pods mounting a local volume at the same time should be able to write from pod1 and read from pod2](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link-bindmounted] Two pods mounting a local volume one after the other should be able to write from pod1 and read from pod](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link] One pod requesting one prebound PVC should be able to mount volume and write from pod1](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link] Set fsGroup for local volume should not set different fsGroups for two pods simultaneously](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link] Set fsGroup for local volume should set different fsGroup for second pod if first pod is deleted](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link] Set fsGroup for local volume should set fsGroup for one pod](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link] Set fsGroup for local volume should set same fsGroup for two pods simultaneously](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link] Two pods mounting a local volume at the same time should be able to write from pod1 and read from pod2](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link] Two pods mounting a local volume one after the other should be able to write from pod1 and read from pod2](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link-bindmounted] Set fsGroup for local volume should set different fsGroup for second pod if first pod is deleted](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)
[PersistentVolumes-local [Volume type: dir-link] One pod requesting one prebound PVC should be able to mount volume and read from pod1](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6268)

/kind failing-test
/priority critical-urgent
/sig storage
/milestone v1.12
/cc @tpepper @AishSundar @kubernetes/sig-storage-test-failures 
/assign @msau42

**Comment by NickrenREN** [comment]
I think the cause may be the permission changes in my commit: https://github.com/kubernetes/kubernetes/pull/63011/commits/5bc823f141efde1e086f6696c26a197b78f9cf52, in PR: https://github.com/kubernetes/kubernetes/pull/63011
And there is also a bug for gce ssd @msau42 fixed here: https://github.com/kubernetes/kubernetes/pull/68312
We need to cherry-pick this to 1.11 ? @msau42

**Comment by msau42** [comment]
I think only the symlink creation changes need to be ported to 1.11.  I created a PR #68371 

The NFS recycle test failure fix has been backported to 1.11 and merged in #67954 2 days ago, but the upgrade tests seem to be using a test version that doesn't include the commit.

**Comment by spiffxp** [comment]
The upgrade job in the description uses "ci/k8s-stable1" as its version, which is the latest build off of the release-1.N-1 branch, aka release-1.11, so I am inclined to say yes your fix is included, but it hasn't solved the problem.

Specifically, the most recent failing run upgraded to https://github.com/kubernetes/kubernetes/commit/a4529464e4629c

**Comment by msau42** [comment]
@spiffxp PR #68371 merged 6 hours ago, but latest upgrade test from a few hours after that is not using the HEAD of release-1.11:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/6327

**Comment by msau42** [comment]
@BenTheElder could you see why the ci/k8s-stable1 tag still doesn't have my commit from #68371?

**Comment by BenTheElder** [comment]
sorry, will look into this after current meeting. had some other issues to look into 😬

**Comment by tpepper** [comment]
Given the new documentation at https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/ci-signal/upgrade-job-versions.md it appears ci/k8s-stable1 has commit a4529464e4629c21224b3d52edfe0ea91b072862 at its head as of this moment, which also corresponds specifically to v1.11.3 tag.  There are newer commits on release-1.11 branch.  This is suspicious.  @BenTheElder @spiffxp seems either ci/k8s-stable1 is following release tags, or is not correctly moving forward?

**Comment by BenTheElder** [comment]
I'm investigating finally (sorry about that!) looks like docker is too old in the kubekins image, working on a fix.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/9379

**Comment by AishSundar** [comment]
How long will the new commit take to merge?

**Comment by BenTheElder** [comment]
pull-kubernetes-e2e-gce took unusually long and failed :/

**Comment by BenTheElder** [comment]
~50 more minutes if it behaves this time.. triggered a retest

**Comment by BenTheElder** [comment]
PR merged but, see https://github.com/kubernetes/release/pull/627 and discussion in #sig-release :|

**Comment by msau42** [comment]
I see the these particular tests passing now, although I noticed other upgrade jobs are not using updated tags.

/close
