### ISSUE TITLE
Kubelet inmediatelly eats all node's memory when livenessProbe command outputs infinite stdout

### ISSUE THREAD

**Issue by alanbover** [kubernetes/kubernetes#70890]
**What happened**:
If a pod configures a livenessProbe command that just outputs infinitelly through stdout, kubelet quickly ends up eating all node's memory, possibly ending up with OOM kills and the node going to unhealthy state.

**What you expected to happen**:
Kubelet increases memory to store a certain amount of logs. The rest are just  dropped.

**How to reproduce it (as minimally and precisely as possible)**:
You just need to create the next pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox
    readinessProbe:
      exec:
        command:
        - "yes"
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    livenessProbe:
      exec:
        command:
        - "yes"
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  Reproduced on 1.6, 1.9 and 1.12
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CoreOS 1800.7.0
- Kernel (e.g. `uname -a`): Linux ip-10-24-15-116.eu-west-1.compute.internal 4.14.63-coreos #1 SMP Wed Aug 15 22:26:16 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux
- Install tools: kube-aws (except for 1.12, which was using DCOS)
- Others:

/kind bug

**Comment by haiyanmeng** [comment]
Can anyone reproduce the issue? I have trouble to reproduce it.
The liveness exec command probe ends up using the [ExecSync](https://github.com/kubernetes/kubernetes/blob/739af85d7a63dec41e07913c14c3fe26695804bb/pkg/kubelet/kuberuntime/kuberuntime_container.go#L790) CRI method, which executes the command in the container and returns the output.
The command set in the liveness probe is `yes`, which will keep running and never stop in the container. This should cause the probe to timeout, and retry until the `failureThreshold` is reached. Then the container should be restarted. 
In addition, the CRI grpc client in kubelet sets the maximum message size the client can receive to be `16MB` ([maxMsgSize](https://github.com/kubernetes/kubernetes/blob/b67126e350fdba6d89a0ee64310cac7db14e33d3/pkg/kubelet/remote/remote_runtime.go#L62)). 

Any comments? Thanks!

**Comment by alanbover** [comment]
@haiyanmeng do you mean reproduce it on 1.13 or on last master build? If you let me know the version exactly I think I should be able to test it myself :)

**Comment by haiyanmeng** [comment]
Here is the k8s version:
```
haiyanmeng@haiyanmeng:tmp$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.4", GitCommit:"618716cbb236fb7ca9cabd822b5947e298ad09f7", GitTreeState:"clean", BuildDate:"2019-02-05T19:22:29Z", GoVersion:"go1.10.7b4", Compiler:"gc", Platform:"linux/amd64"}
```


The pod's status changes from `Running` to `Terminating` after several minutes:
```
haiyanmeng@haiyanmeng:tmp$ kubectl get pods
NAME        READY   STATUS        RESTARTS   AGE
myapp-pod   0/1     Terminating   0          8m
```


Here is the detailed info about the node hosting the pod (the node is definitely not healthy, however, it is not obvious to me that it is due to OOM):
```
haiyanmeng@haiyanmeng:tmp$ kubectl describe nodes/gke-helloworld-default-pool-ac7e804f-6mlk
....
Non-terminated Pods:         (4 in total)
  Namespace                  Name                                                    CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                                                    ------------  ----------  ---------------  -------------
  default                    myapp-pod                                               100m (10%)    0 (0%)      0 (0%)           0 (0%)
  kube-system                fluentd-gcp-v3.2.0-kmkrc                                100m (10%)    1 (106%)    200Mi (7%)       500Mi (18%)
  kube-system                kube-proxy-gke-helloworld-default-pool-ac7e804f-6mlk    100m (10%)    0 (0%)      0 (0%)           0 (0%)
  kube-system                metrics-server-v0.2.1-fd596d746-cxvjt                   53m (5%)      148m (15%)  154Mi (5%)       404Mi (15%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource  Requests     Limits
  --------  --------     ------
  cpu       353m (37%)   1148m (122%)
  memory    354Mi (13%)  904Mi (34%)
Events:
  Type    Reason                     Age                From                                                        Message
  ----    ------                     ----               ----                                                        -------
  Normal  Starting                   18m                kubelet, gke-helloworld-default-pool-ac7e804f-6mlk          Starting kubelet.
  Normal  NodeHasSufficientDisk      18m (x2 over 18m)  kubelet, gke-helloworld-default-pool-ac7e804f-6mlk          Node gke-helloworld-default-pool-ac7e804f-6mlk status is now: NodeHasSufficientDisk
  Normal  NodeHasSufficientMemory    18m (x2 over 18m)  kubelet, gke-helloworld-default-pool-ac7e804f-6mlk          Node gke-helloworld-default-pool-ac7e804f-6mlk status is now: NodeHasSufficientMemory
  Normal  NodeHasNoDiskPressure      18m (x2 over 18m)  kubelet, gke-helloworld-default-pool-ac7e804f-6mlk          Node gke-helloworld-default-pool-ac7e804f-6mlk status is now: NodeHasNoDiskPressure
  Normal  NodeHasSufficientPID       18m (x2 over 18m)  kubelet, gke-helloworld-default-pool-ac7e804f-6mlk          Node gke-helloworld-default-pool-ac7e804f-6mlk status is now: NodeHasSufficientPID
  Normal  NodeAllocatableEnforced    18m                kubelet, gke-helloworld-default-pool-ac7e804f-6mlk          Updated Node Allocatable limit across pods
  Normal  NodeReady                  18m                kubelet, gke-helloworld-default-pool-ac7e804f-6mlk          Node gke-helloworld-default-pool-ac7e804f-6mlk status is now: NodeReady
  Normal  Starting                   18m                kube-proxy, gke-helloworld-default-pool-ac7e804f-6mlk       Starting kube-proxy.
  Normal  FrequentKubeletRestart     14m                systemd-monitor, gke-helloworld-default-pool-ac7e804f-6mlk  Node condition FrequentKubeletRestart is now: False, reason: FrequentKubeletRestart
  Normal  CorruptDockerOverlay2      14m                docker-monitor, gke-helloworld-default-pool-ac7e804f-6mlk   Node condition CorruptDockerOverlay2 is now: False, reason: CorruptDockerOverlay2
  Normal  UnregisterNetDevice        14m                kernel-monitor, gke-helloworld-default-pool-ac7e804f-6mlk   Node condition FrequentUnregisterNetDevice is now: False, reason: UnregisterNetDevice
  Normal  FrequentDockerRestart      14m                systemd-monitor, gke-helloworld-default-pool-ac7e804f-6mlk  Node condition FrequentDockerRestart is now: False, reason: FrequentDockerRestart
  Normal  FrequentContainerdRestart  14m                systemd-monitor, gke-helloworld-default-pool-ac7e804f-6mlk  Node condition FrequentContainerdRestart is now: False, reason: FrequentContainerdRestart
```

**Comment by nikopen** [comment]
looks like a long-standing niche bug that is non-release blocking, plus no PR and difficult to reproduce.

clearing the milestone to be fixed at another point (and cherry picked to previous patch releases too)

if there are objections let us know at #sig-release

/milestone clear

**Comment by alanbover** [comment]
tested on 1.14.

After creating the pod on an empty cluster, on the node that the pod is scheduled kubelet exhausts the whole memory of the node, and after not-too-long, the node becomes unresponsive.

```
top - 10:42:11 up  2:08,  2 users,  load average: 11.54, 6.50, 2.89
Tasks: 276 total,   8 running, 268 sleeping,   0 stopped,   0 zombie
%Cpu(s): 73.2 us,  5.3 sy,  0.0 ni, 19.0 id,  0.0 wa,  1.6 hi,  0.5 si,  0.3 st
MiB Mem :  61399.3 total,    406.9 free,  55106.1 used,   5886.3 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  10639.6 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                    
 1327 root      20   0   84.5g  52.2g  85580 S  41.5  87.0  11:08.09 kubelet                                                                                                                                                                    
17878 root      20   0  538304 223844   9804 S   8.3   0.4   2:22.79 ruby2.3     
```

![imagen](https://user-images.githubusercontent.com/892918/57370045-7644e780-718f-11e9-8b44-adc860c2de8c.png)

![imagen](https://user-images.githubusercontent.com/892918/57370072-865cc700-718f-11e9-9d14-57852bc0d9ed.png)

**Comment by haiyanmeng** [comment]
> Are you using Docker or another CRI implementation?

I am using `docker-containerd-shim`.

**Comment by dims** [comment]
Ack thanks @haiyanmeng

**Comment by xmudrii** [comment]
Hello! We have started the code freeze for 1.15. Is this issue still planned for the 1.15 cycle?

**Comment by hoegaarden** [comment]
@xmudrii @dims I don't have any bandwidth to do that for 1.15.

**Comment by liggitt** [comment]
is this resolved by https://github.com/kubernetes/kubernetes/pull/76518?

**Comment by xmudrii** [comment]
Hello! I'm the bug triage lead for the 1.16 release cycle and considering this issue is tagged for 1.16, I'd like to check its status. The code freeze is starting on August 29th EOD PST (about 5 days from now) and once the code freeze starts, only release-blocking changes will be considered to be merged. Is this issue still planned to be fixed for the 1.16 release?

**Comment by tallclair** [comment]
Sorry, I was commenting on the general class of issues like this, not for probes specifically. I just checked and don't see any `io.Copy` calls in the probe path, so I think we can close this.

**Comment by tallclair** [comment]
Sorry, https://github.com/kubernetes/kubernetes/pull/76518 doesn't actually fix this issue. Exec probes are still unbounded.

**Comment by dims** [comment]
@tallclair dang! filed https://github.com/kubernetes/kubernetes/pull/82514

**Comment by liggitt** [comment]
/milestone v1.17

this isn't release-blocking
