### ISSUE TITLE
metrics-server can't pull data from nodes with cri-o related to #69658

### ISSUE THREAD

**Issue by shahaf600** [kubernetes/kubernetes#71712]
/kind bug

/sig node
/area kubelet
/area kubelet-api

**What happened**:
related to this issue #69658 , I work with @aalubin on the same team.
We are trying to migrate from docker to cri-o for container runtime
after fixing the other issue (#69658 ), I found the metrics-server can't get any data from any node with crio although i see in the hpa description the stats. also metrics-server outputs a log with error can't scrape data from all nodes with crio:

manager.go:102] unable to fully scrape metrics from source kubelet_summary:node-1: [unable to get CPU for container
and when i curl it like this: curl node-1:10255/stats/summary i get all the data..

this is the data in hpa description:
$ kubectl describe hpa
Name: ****************
Namespace: algo-prod
Labels: 
Annotations: 
CreationTimestamp: Tue, 28 Aug 2018 11:29:19 +0300
Reference: Deployment/************
Metrics: ( current / target )
resource cpu on pods (as a percentage of request): 0% (36m) / 75%
Min replicas: 1
Max replicas: 32
Deployment pods: 1 current / 2 desired
Conditions:
Type Status Reason Message

AbleToScale True SucceededGetScale the HPA controller was able to get the target's current scale
ScalingActive False FailedGetResourceMetric the HPA was unable to compute the replica count: unable to get metrics for resource cpu: no metrics returned from resource metrics API
ScalingLimited True TooFewReplicas the desired replica count is increasing faster than the maximum scale rate
Events:
Type Reason Age From Message

Warning FailedGetResourceMetric 3m55s (x6688 over 2d8h) horizontal-pod-autoscaler unable to get metrics for resource cpu: no metrics returned from resource metrics API

How to reproduce it (as minimally and precisely as possible):
not sure, here is our kubelet configuration:
xecStart=/usr/bin/kubelet --allow-privileged=true 
--cadvisor-port=4194 
--cgroup-driver=cgroupfs 
--client-ca-file=/etc/pki/kubernetes_certs/ca.pem 
--cluster-dns=10.10.10.2 
--cluster-domain=customdomain.com 
--cni-bin-dir=/opt/cni/bin 
--cni-conf-dir=/etc/cni/net.d 
--container-runtime-endpoint=unix:///var/run/crio/crio.sock 
--container-runtime=remote 
--cpu-manager-policy=none 
--feature-gates=TaintBasedEvictions=true 
--image-gc-high-threshold=70 
--image-gc-low-threshold=50 
--kube-reserved-cgroup=podruntime.slice 
--kube-reserved=cpu=1,memory=3Gi 
--kubeconfig=/etc/kubernetes/kubelet_kubeconfig 
--kubelet-cgroups=/podruntime.slice 
--network-plugin=cni 
--node-labels=configure_bgp_peers=true 
--pod-manifest-path=/etc/kubernetes/manifests 
--register-node=true 
--register-with-taints=new_node=true:NoSchedule 
--runtime-cgroups=/podruntime.slice 
--runtime-request-timeout=10m 
--system-reserved-cgroup=system.slice 
--system-reserved=cpu=1,memory=768Mi 
--tls-cert-file=/etc/pki/kubernetes_certs/k24.customdomain.com_cert.pem 
--tls-private-key-file=/etc/pki/kubernetes_certs/k24.customdomain.com_key.pem

Anything else we need to know?:
We've got the same results with mix of the following configuration:

kubelet 1.10.7 and 1.11.3
cri-o 1.10.5 and 1.11.6
Another issue that we have that I think is the result of this is that crictl stats does not return any information

Environment:

Kubernetes version (use kubectl version): 1.11.3
Cloud provider or hardware configuration: on premise Dell 630/640 servers
OS (e.g. from /etc/os-release): centos 7
Kernel (e.g. uname -a): Linux k24.customdomain.com 4.14.35-1818.2.1.el7uek.x86_64 #2 SMP Mon Aug 27 21:16:31 PDT 2018 x86_64 x86_64 x8 6_64 GNU/Linux
Install tools: puppet automation
Others:

/kind bug

**Comment by jnummelin** [comment]
We seem to be hitting the same issue.

Metrics server logs has these kind of errors:
```
unable to get CPU for container "coredns" in pod kube-system/coredns-5784d68866-b9cz6 on node "10.133.86.156", discarding data: missing cpu usage metric, 
```

Those repeat for each pod on every node.

Also in our case, I can see the stats from kubelet API (secured):
```
$ curl -k -H "Authorization: Bearer <token>" https://localhost:10250/stats/summary
...
"pods": [
   {
    "podRef": {
     "name": "rook-ceph-mon1-9d5c8",
     "namespace": "kontena-storage",
     "uid": "12bc9bf0-15a9-11e9-bf9e-821ab12dbea6"
    },
    "startTime": "2019-01-11T13:59:12Z",
    "containers": [
     {
      "name": "rook-ceph-mon",
      "startTime": "2019-01-11T13:59:13Z",
      "cpu": {
       "time": "2019-01-11T14:54:04Z",
       "usageCoreNanoSeconds": 10468485702
      },
      "memory": {
       "time": "2019-01-11T14:54:04Z",
       "workingSetBytes": 40890368
      },
      "rootfs": {
       "time": null
      },
      "logs": {
       "time": "2019-01-11T14:54:01Z",
       "availableBytes": 30959779840,
       "capacityBytes": 41442029568,
       "usedBytes": 405504,
       "inodesFree": 4953784,
       "inodes": 5160960,
       "inodesUsed": 2
      },
      "userDefinedMetrics": null
     }
    ],
    "cpu": {
     "time": "2019-01-11T14:54:00Z",
     "usageNanoCores": 2309420,
     "usageCoreNanoSeconds": 10626148707
    },
    "memory": {
     "time": "2019-01-11T14:54:00Z",
     "usageBytes": 43126784,
     "workingSetBytes": 36405248,
     "rssBytes": 31973376,
     "pageFaults": 0,
     "majorPageFaults": 0
    },
    "volume": [
     {
      "time": "2019-01-11T14:00:05Z",
      "availableBytes": 1045061632,
      "capacityBytes": 1045073920,
      "usedBytes": 12288,
      "inodesFree": 255136,
      "inodes": 255145,
      "inodesUsed": 9,
      "name": "default-token-scsk2"
     }
    ],
    "ephemeral-storage": {
     "time": "2019-01-11T14:54:01Z",
     "availableBytes": 30959779840,
     "capacityBytes": 41442029568,
     "usedBytes": 405504,
     "inodesFree": 4953784,
     "inodes": 5160960
    }
   },
...
```

Versions:
```
root@jussi-pharos-worker-0:~# kubelet --version
Kubernetes v1.12.4
root@jussi-pharos-worker-0:~# crio -v
crio version 1.12.3
```

**Comment by aalubin** [comment]
@jnummelin We couldn't solve the issue, so we gave up cri-o because of that.
For the time being we returned to docker, with plans to move to containerd in the near future.

**Comment by jakolehm** [comment]
It seems that problem goes away after removing `unix://` prefix from `--container-runtime-endpoint`. This behaviour is fixed in the master branch but is not included in any release that I know.

Tested with kubernetes 1.13.1 & cri-o 1.13.0 on Ubuntu 18.04 & Centos 7.

**Comment by jnummelin** [comment]
(we're working together on this with @jakolehm )

To add some more detail.

This commit would probably fix it: https://github.com/kubernetes/kubernetes/commit/4fe1b6f33f5e85fc2656de0983b512b8b1625bfb

That is only on master and not in any of the release branches AFAIK.

So reverse engineering that commit, we deciphered that the `--container-runtime-endpoint` option for kubelet needs to be without the `unix://` prefix.

It's a bummer since pretty much all CRI-O docs mention it with the prefix, e.g. https://github.com/kubernetes-sigs/cri-o/blob/master/kubernetes.md#preparing-kubelet

IMO that fix should be picked to the releases, just following kube & CRI-O docs will make one stumble on this.

**Comment by shahaf600** [comment]
Well, we moved to containerd implementation (30,000 cores, 7 clusters), as was recommended by k8s community, and because it (cri-o) didn’t work.
But I’m interested to check if it works, so I’ll check it with one node next week and tell here my results.

**Comment by jcrowthe** [comment]
I've run into this issue as well and have confirmed that swapping
```
--container-runtime-endpoint=unix:///var/run/crio/crio.sock
for
--container-runtime-endpoint=/var/run/crio/crio.sock
```
on each kubelet fixes this issue (running Kubernetes v1.13.3 running CRI-o v1.13.0). I do still get some disparate error logs, but so far I haven't received any error when running `kubectl top pod <pod>`.

**Comment by SleepyBrett** [comment]
Stripping the unix:// from the runtime-endpoint did not solve this problem for me.

I still get the same errors about missing cpu usage metrics, When I run top pods I get the following errors in the metrics-server for pods that are on my crio nodes:

```
E0416 16:33:12.016258       1 reststorage.go:144] unable to fetch pod metrics for pod monitoring/veneur-g4v9n: no metrics known for pod
```

**Comment by matthias50** [comment]
> I've run into this issue as well and have confirmed that swapping
> 
> ```
> --container-runtime-endpoint=unix:///var/run/crio/crio.sock
> for
> --container-runtime-endpoint=/var/run/crio/crio.sock
> ```
> 
> on each kubelet fixes this issue (running Kubernetes v1.13.3 running CRI-o v1.13.0). I do still get some disparate error logs on the metrics-server, but so far I haven't received any error when running `kubectl top pod <pod>`.

So this did indeed make the errors go away, but it caused the cAdvisor metrics being reported by kubelet when using crio to be broken See https://github.com/cri-o/cri-o/issues/2926.
