### ISSUE TITLE
kube-apiserver 1.13.x refuses to work when first etcd-server is not available.

### ISSUE THREAD

**Issue by Cytrian** [kubernetes/kubernetes#72102]
**How to reproduce the problem**:
Set up a new demo cluster with kubeadm 1.13.1.
Create default configurationwith `kubeadm config print init-defaults`
Initialize cluster as usual with `kubeadm init`

Change the `--etcd-servers` list in kube-apiserver manifest to `--etcd-servers=https://127.0.0.2:2379,https://127.0.0.1:2379`, so that the first etcd node is unavailable ("connection refused").

The kube-apiserver is then not able to connect to etcd any more.

Last message: `Unable to create storage backend: config (\u0026{ /registry [https://127.0.0.2:2379 https://127.0.0.1:2379] /etc/kubernetes/pki/apiserver-etcd-client.key /etc/kubernetes/pki/apiserver-etcd-client.crt /etc/kubernetes/pki/etcd/ca.crt true 0xc000381dd0 \u003cnil\u003e 5m0s 1m0s}), err (dial tcp 127.0.0.2:2379: connect: connection refused)\n","stream":"stderr","time":"2018-12-17T12:13:19.608822816Z"}`

kube-apiserver does not start.

If I upgrade etcd to version 3.3.10, it reports an error `remote error: tls: bad certificate", ServerName ""`

**Environment**:
- Kubernetes version 1.13.1
- kubeadm in Vagrant box

I also experience this bug in an environment with a real etcd cluster.

/kind bug

**Comment by yue9944882** [comment]
/sig api-machinery

apologies, just had another look and it's indeed an api-machinery issue. 

> // Endpoints defines a set of URLs (schemes, hosts and ports only)
    // that can be used to communicate with a logical etcd cluster. For
    // example, a three-node cluster could be provided like so:
    //
    // 	Endpoints: []string{
    //		"http://node1.example.com:2379",
    //		"http://node2.example.com:2379",
    //		"http://node3.example.com:2379",
    //	}
    //
    // If multiple endpoints are provided, the Client will attempt to
    // use them all in the event that one or more of them are unusable.
    //
    // If Client.Sync is ever called, the Client may cache an alternate
    // set of endpoints to continue operation.

we are passing the server list straight into etcd v3 client which return the error u reported. not sure if it's designed

**Comment by JishanXing** [comment]
This is an etcdv3 client issue. See [.](https://github.com/etcd-io/etcd/issues/9949)

**Comment by timothysc** [comment]
/assign @timothysc @detiber  

So live updating a static pod manifest is typically not recommended, was this triggered via some other operation or were you editing your static manifests?

**Comment by Cytrian** [comment]
No pod manifest involved here. Just a group of etcd and a kube-apiserver. The issue appeared when we rebooted the first etcd node.

**Comment by alexbrand** [comment]
I was able to repro this issue with the repro steps provided by @Cytrian. I also reproduced this issue with a real etcd cluster.

As @JishanXing previously mentioned, the problem is caused by a bug in the etcd v3 client library (or perhaps the grpc library). The vault project is also running into this: https://github.com/hashicorp/vault/issues/4349

The problem seems to be that the etcd library uses the first node’s address as the `ServerName` for TLS. This means that all attempts to connect to any server other than the first will fail with a certificate validation error (i.e. cert has `${nameOfNode2}` in SANs, but the client is expecting `${nameOfNode1}`).

An important thing to highlight is that when the first etcd server goes down, it also takes the Kubernetes API servers down, because they fail to connect to the remaining etcd servers.

With that said, this all depends on what your etcd server certificates look like:
* If you follow the [kubeadm instructions](https://kubernetes.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/) to stand up a 3 node etcd cluster, you get a set of certificates that include the first node’s name and IP in the SANs (because all certs are generated on the first etcd node). Thus, you should not run into this issue.
* If you have used another process to generate certificates for etcd, and the certs do not include the first node’s name and IP in the SANs, you will most likely run into this issue when the first etcd node goes down.

**To reproduce the issue with a real etcd cluster:**
1. Create a 3 node etcd cluster with TLS enabled. Each certificate should only contain the name/IP of the node that will be serving it.
2. Start an API server that points to the etcd cluster.
3. Stop the first etcd node.
4. API server crashes and fails to come back up

**Versions:**
- kubeadm version: v1.13.2
- kubernetes api server version: v1.13.2
- etcd image: k8s.gcr.io/etcd:3.2.24

API server crash log: https://gist.github.com/alexbrand/ba86f506e4278ed2ada4504ab44b525b

I was unable to reproduce this issue with API server v1.12.5 (n.b. this was somewhat of a non-scientific test => tested by updating the image field of the API server static pod produced by kubeadm v1.13.2)

**Comment by timothysc** [comment]
@liggitt ^ FYI.

**Comment by neolit123** [comment]
thank you for the investigation @alexbrand

**Comment by alexbrand** [comment]
No problem! I started looking into the etcd client to see if I could spot the issue, but couldn't quite figure it out.

**Comment by gyuho** [comment]
@timothysc I will look into this.

**Comment by gyuho** [comment]
I think this was the issue more on how gRPC balancer does failover with credentials.

I've shared a workaround to fix this issue in upstream gRPC https://github.com/grpc/grpc-go/pull/2650.

And waiting for their feedback.
/cc @xiang90 @jpbetz

**Comment by niuqg** [comment]
We have 3 master and 3 etcdservers, a workaround is to change the order of etcdservers.
**master0:**
```
--etcd-servers=etcd0,etcd1,etcd2
```
**master1:**
```
--etcd-servers=etcd1,etcd0,etcd2
```
**master2:**
```
--etcd-servers=etcd2,etcd0,etcd1
```

**Comment by bjhaid** [comment]
I just tried using a SAN cert with my etcd nodes having the names of all etcd nodes. The apiserver connects to only the last etcd node in it's `--etcd-servers` list.

We run 3 apiservers per cluster and I can confirm the behavior the apiservers in this particular cluster is consistent that they are picking the last, however if I shutdown the last node the connect to the other 2 without issues, once that comes back up they connect to only the last.

and there are entries like this:

```
Apr 12 15:36:17 kube-etcd02.com etcd[12309]: rejected connection from "192.168.208.25:47582" (error "EOF", ServerName "kube-etcd01.com")
```

in the etcd journal, where `192.168.208.25` is the apiserver IP.

Without the SAN certs the behavior matches what is described by others here.

So the SAN does not make the client distribute load across etcd nodes, it just prevents a total outage if the node the api-server talking to goes down.

**Comment by timothysc** [comment]
@gyuho @xiang90 - what's the state here, this is still an issue.

**Comment by gyuho** [comment]
@jingyih @jpbetz Can we ping gRPC team again? Open to discuss over the conference call.

**Comment by jingyih** [comment]
> @jingyih @jpbetz Can we ping gRPC team again? Open to discuss over the conference call.

@gyuho Will do!

**Comment by gyuho** [comment]
Just discussed with gRPC team and @jingyih. We will rework on this in the next few weeks.

**Comment by aneeshwara** [comment]
hi we are trying to create etcd cluster but we are facing the following error please find below error

**Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 192.168.2.139:2379: getsockopt: connection refused**

please help us to get out of this

thanks in advance

**Comment by marciopribeiro87** [comment]
I'm running kubernetes 1.11.9 and etcd 3.2.24 , running on AWS provisioned by KOPS 1.12.0 and im seeing the same error message : 

Unable to create storage backend: config (&{etcd3 /registry [http://127.0.0.1:4001]    true false 1000 0xc42039fa00 <nil> 5m0s 1m0s}), err (dial tcp 127.0.0.1:4001: connect: connection refused)

**Comment by timothysc** [comment]
@gyuho - any update?

**Comment by gyuho** [comment]
@timothysc I just came back from trip. Will start working on this from this week! And post updates here.

**Comment by gyuho** [comment]
Made some progress here https://github.com/etcd-io/etcd/pull/10911.

**Comment by dims** [comment]
If anyone needs an urgent fix, please use this - https://github.com/moondev/kubernetes/commit/45f6cb2c96705d03b3b77c16a3680b5526e14729#diff-c9fae1df26aedd520ef93a008d255581R136-R148

**Comment by igcherkaev** [comment]
Is Kubernetes 1.13 or 1.14 going to get updated with the fixed grpc lib? Or it's going to 1.15 only?

**Comment by gyuho** [comment]
@igcherkaev We are planning to backport the fix to etcd 3.3 after etcd 3.4 release. Then, kubernetes can pick up the latest etcd 3.3.

**Comment by dims** [comment]
@gyuho Can we please wrap up the backport (to etcd 3.3) within the next week or two? Please see timeline for 1.16 ( https://github.com/kubernetes/sig-release/tree/master/releases/release-1.16#timeline ) We need to have sufficient soak time for this change in k/k.

**Comment by gyuho** [comment]
@dims Sure. The earliest we can do is August 13, 2019.

1. We need gRPC 1.23 to include upstream bug fixes https://github.com/grpc/grpc-go/milestone/21
2. We need a day or two to rewrite 3.3 client balancer

Today, we do etcd 3.4 release code freeze, which means we will start running functional (failure injection) tests + kubemark to test new etcd client changes including https://github.com/etcd-io/etcd/pull/10911.

If anything changes, we will post updates here.

**Comment by dims** [comment]
Thanks a ton @gyuho !

**Comment by DaniDD** [comment]
Hi, is this the same issue:
I have 3 control planes. On every control plane are one etcd-server. The apiserver can only connect to the etcd-server on the same node. With other etcd servers I habe Warnings in the log:
clientconn.go:1251] grpc: addrConn.createTransport failed to connect to {172.22.75.8:2379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake f
ailed: x509: certificate is valid for 172.22.75.8, 127.0.0.1, ::1, 172.22.75.8, not 172.22.75.7". Reconnecting...

**Comment by figo** [comment]
> @dims Sure. The earliest we can do is August 13, 2019.
> 
> 1. We need gRPC 1.23 to include upstream bug fixes https://github.com/grpc/grpc-go/milestone/21
> 2. We need a day or two to rewrite 3.3 client balancer
> 
> Today, we do etcd 3.4 release code freeze, which means we will start running functional (failure injection) tests + kubemark to test new etcd client changes including [etcd-io/etcd#10911](https://github.com/etcd-io/etcd/pull/10911).
> 
> If anything changes, we will post updates here.
@gyuho a quick clarification, is August 13, 2019 the earliest day the fix going to land on 3.3? thx

**Comment by gyuho** [comment]
> August 13, 2019 the earliest day the fix going to land on 3.3

Yes

**Comment by gyuho** [comment]
Update: https://github.com/grpc/grpc-go/releases/tag/v1.23.0 is out. Bumping up gRPC https://github.com/etcd-io/etcd/pull/11029 in etcd master branch, in addition to Go runtime upgrade https://groups.google.com/forum/#!topic/golang-announce/65QixT3tcmg. Once tests look good, we will start working on 3.3 backports.

**Comment by gyuho** [comment]
@dims @jpbetz https://github.com/etcd-io/etcd/releases/tag/v3.3.14-beta.0 has been released with all the fixes. Please try. Once tests look good in the next few days, I will release `v3.3.14`.

**Comment by dims** [comment]
@gyuho i just kicked off a WIP on the k/k CI - https://github.com/kubernetes/kubernetes/pull/81434

**Comment by gyuho** [comment]
Some tests in k8s may break. We need pass `grpc.WithBlock` with the new etcd client. Please take a look at https://github.com/etcd-io/etcd/issues/10980.

**Comment by ylhyh** [comment]
Is there a hotfix for v1.15?

**Comment by dims** [comment]
@ylhyh - see https://github.com/kubernetes/kubernetes/issues/72102#issuecomment-515979520

**Comment by igcherkaev** [comment]
The issue is still there with Kubernetes 1.14.6 and etcd 3.3.15. Any changes to kubernetes libs or code needed to tackle this issue?

**Comment by dims** [comment]
@igcherkaev - see https://github.com/kubernetes/kubernetes/issues/72102#issuecomment-515979520

**Comment by igcherkaev** [comment]
@dims hmm, if there are changes required in k8s source code, why has this issue got closed? I'll try to build a custom image and test, though. Thanks.

**Comment by liggitt** [comment]
this will be resolved in 1.16 in https://github.com/kubernetes/kubernetes/pull/81434

the changes required (upgrading etcd client libraries) were too invasive to backport to patch releases

**Comment by igcherkaev** [comment]
@liggitt that leaves people on 1.13-1.15 without proper H/A? I think this issue deserves to be fixed in the three supported releases of Kubernetes. The hotfix mentioned here looks simple enough to be added, but you are saying the proper fix will require much more. So this is all sorta obscure and confusing to the community, IMO.

Not that I am complaining, don't get me wrong, it's just I think everyone would welcome some clarity on this issue. Maybe document it somewhere and provide some workarounds for the people who are still on v1.13.-1.15? Because right now, bring down the first etcd member and oops, api is not working, cluster is not working.

**Comment by liggitt** [comment]
agree on documenting the issue at the very least, and recommending any possible workarounds

@jpbetz @gyuho, any feedback on ^?

**Comment by gyuho** [comment]
@liggitt @igcherkaev  I will work on the documentation.

**Comment by igcherkaev** [comment]
@dims just built custom 1.14 image from the release-1.14 branch and patched that credentials.go file and it's so much better now when I bring down the first etcd node down. Now I am confused, if the fix is so simple, why does it have to wait until 1.16?

**Comment by gyuho** [comment]
@igcherkaev The fix requires upgrading google.golang.org/grpc from v1.7.5 to v1.23.0, which is quite a big change :0

**Comment by gyuho** [comment]
I am adding "Known issue" section to etcd docs here https://github.com/kubernetes/website/pull/16156.

**Comment by dims** [comment]
@igcherkaev see what @gyuho said :)

**Comment by javendo** [comment]
Some days ago I had opened this issue #81837, but reading this one I think it is related. Can anyone take a look at my issue and see it they are related and if so, close it.

Thanks

**Comment by TheDukeDK** [comment]
I believe I am running into this issue or at least something similar. 

```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                       PORTS               NAMES
ef5a8da82f60        3cab8e1b9802           "etcd --advertise-..."   41 seconds ago      Up 40 seconds                                    k8s_etcd_etcd-nem-docker-master01.inter-olymp.local_kube-system_beb5ba6bc28b987902829f8d53bdef31_1381
3f1cd9728ecc        3cab8e1b9802           "etcd --advertise-..."   2 minutes ago       Exited (0) 40 seconds ago                        k8s_etcd_etcd-nem-docker-master01.inter-olymp.local_kube-system_beb5ba6bc28b987902829f8d53bdef31_1380
9b991bfbf812        ab60b017e34f           "kube-apiserver --..."   5 minutes ago       Exited (255) 4 minutes ago                       k8s_kube-apiserver_kube-apiserver-nem-docker-master01.inter-olymp.local_kube-system_e4ebc726604ae399a1b7beb9adcb6b4d_1056
f66d4ae02fea        5a1527e735da           "kube-scheduler --..."   3 days ago          Up 3 days                                        k8s_kube-scheduler_kube-scheduler-nem-docker-master01.inter-olymp.local_kube-system_dd3b0cd7d636afb2b116453dc6524f26_19
482625481e36        07e068033cf2           "kube-controller-m..."   3 days ago          Up 3 days                                        k8s_kube-controller-manager_kube-controller-manager-nem-docker-master01.inter-olymp.local_kube-system_ee67cb8ee97d2edbb62c52d7615f8b47_18
```

I see the etcd going up and down and the api server. This cluster was created with `kubeadm`. 

The logs from etcd show the following.

```

**Comment by gjcarneiro** [comment]
There are claims here that the bug is solved, but I am seeing evidence of it not being solved in our cluster:

```
I1016 09:59:22.196298       1 client.go:361] parsed scheme: "endpoint"
I1016 09:59:22.196340       1 endpoint.go:66] ccResolverWrapper: sending new addresses to cc: [{https://hex-64d-pm.k2.gambit:2379 0  <nil>} {https://hex-64f-pm.k2.gambit:2379 0  <nil>} {https://hex-8c4-pm.k2.gambit:2379 0  <nil>}]
W1016 09:59:22.212143       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://hex-8c4-pm.k2.gambit:2379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for localhost, hex-8c4-pm.k2.gambit, hex-8c4-pm, not hex-64d-pm.k2.gambit". Reconnecting...
W1016 09:59:22.216358       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://hex-64f-pm.k2.gambit:2379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for hex-64f-pm, hex-64f-pm.k2.gambit, hex-64f-pm.hex10.gambit, not hex-64d-pm.k2.gambit". Reconnecting...
I1016 09:59:22.511696       1 client.go:361] parsed scheme: "endpoint"
I1016 09:59:22.511736       1 endpoint.go:66] ccResolverWrapper: sending new addresses to cc: [{https://hex-64d-pm.k2.gambit:2379 0  <nil>} {https://hex-64f-pm.k2.gambit:2379 0  <nil>} {https://hex-8c4-pm.k2.gambit:2379 0  <nil>}]
W1016 09:59:22.525738       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://hex-8c4-pm.k2.gambit:2379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for localhost, hex-8c4-pm.k2.gambit, hex-8c4-pm, not hex-64d-pm.k2.gambit". Reconnecting...
W1016 09:59:22.530117       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://hex-64f-pm.k2.gambit:2379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for hex-64f-pm, hex-64f-pm.k2.gambit, hex-64f-pm.hex10.gambit, not hex-64d-pm.k2.gambit". Reconnecting...
```

Are we absolutely sure the etcd client fix made it onto the release?

**Comment by seh** [comment]
That bug is not fixed yet. The only fix was for IP address-only connections, not those using DNS names like this. We are waiting on #83968 for what will probably be Kubernetes version 1.16.3.

The workaround I'm using today is to replace my _etcd_ server certificates with ones that use a wildcard SAN for the members in the subdomain, rather than including the given machine's DNS name as a SAN. So far, it works.

**Comment by liggitt** [comment]
It was fixed for IP addresses, but not DNS names (DNS name issue is tracked in https://github.com/kubernetes/kubernetes/issues/83028). Additionally, part of the fix regressed IPv6 address handling (https://github.com/kubernetes/kubernetes/issues/83550). See https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#known-issues.

These two issues have been resolved in master, and https://github.com/kubernetes/kubernetes/pull/83968 is open to pick them to 1.16 (targeting 1.16.3)

**Comment by gjcarneiro** [comment]
Ah... thank you @seh and @liggitt, that explains it.  Cheers!

**Comment by Nuru** [comment]
@seh Would you please explain how to change the SAN on the etcd certificates? 

> 
> The workaround I'm using today is to replace my _etcd_ server certificates with ones that use a wildcard SAN for the members in the subdomain, rather than including the given machine's DNS name as a SAN. So far, it works.

**Comment by seh** [comment]
> Would you please explain how to change the SAN on the etcd certificates?

I generate these certificates myself using [Terraform's _tls_ provider](https://www.terraform.io/docs/providers/tls/index.html), so it's a matter of revising the arguments passed for [the `tls_cert_request` resource's "dns_names" attribute](https://www.terraform.io/docs/providers/tls/r/cert_request.html#dns_names).

**Comment by yacinelazaar** [comment]
Tried with Kubernetes 1.15.3 and with 1.16.2 but its not working with neither.
This is not fixed even for IP addresses:
`W1107 12:48:06.316691       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://172.17.8.202:2379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for 10.0.2.15, 127.0.0.1, ::1, 172.17.8.202, not 172.17.8.201". Reconnecting...
W1107 12:48:06.328186       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://172.17.8.203:2379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for 10.0.2.15, 127.0.0.1, ::1, 172.17.8.203, not 172.17.8.201". Reconnecting...`

**Comment by r0bj** [comment]
I have similar observation as @yacinelazaar :
etcd 3.3.15
kubernetes 1.16.2

kube-apiserver log:
```
W1107 10:57:50.375677       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://10.12.72.135:2379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for 10.12.72.135, not 10.12.70.111". Reconnecting...
```

**Comment by yacinelazaar** [comment]
> I have similar observation as @yacinelazaar with IP addresses:
> etcd 3.3.15
> kubernetes 1.16.2
> 
> kube-apiserver log:
> 
> ```
> W1107 10:57:50.375677       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://10.12.72.135:2379 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for 10.12.72.135, not 10.12.70.111". Reconnecting...
> ```

You should be fine with 1.16.2 and Etcd 3.3.15 now. I managed to get 3 masters running.

**Comment by Davidrjx** [comment]
In my case, apiserver has been repeating warnings about connecting to external etcd cluster with tls,   log snippets as follows
```
...
I0316 09:23:15.568757       1 client.go:354] parsed scheme: ""
I0316 09:23:15.568774       1 client.go:354] scheme "" not registered, fallback to default scheme
I0316 09:23:15.568812       1 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{10.90.9.32:2379 0  <nil>}]
I0316 09:23:15.568868       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{10.90.9.32:2379 <nil>} {10.90.9.41:2379 <nil>} {10.9
0.9.44:2379 <nil>}]
W0316 09:23:15.573002       1 clientconn.go:1251] grpc: addrConn.createTransport failed to connect to {10.90.9.44:2379 0  <nil>}. Err :connection er
ror: desc = "transport: authentication handshake failed: x509: certificate is valid for 10.90.9.44, 127.0.0.1, not 10.90.9.32". Reconnecting...
W0316 09:23:15.581827       1 clientconn.go:1251] grpc: addrConn.createTransport failed to connect to {10.90.9.41:2379 0  <nil>}. Err :connection er
ror: desc = "transport: authentication handshake failed: x509: certificate is valid for 10.90.9.41, 127.0.0.1, not 10.90.9.32". Reconnecting...
I0316 09:23:15.582204       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{10.90.9.32:2379 <nil>}]
W0316 09:23:15.582232       1 asm_amd64.s:1337] Failed to dial 10.90.9.44:2379: context canceled; please retry.
W0316 09:23:15.582242       1 asm_amd64.s:1337] Failed to dial 10.90.9.41:2379: context canceled; please retry.
...
```
My environment:
HA kubernetes 1.15.5 cluster made by kubeadm
Etcd 3.3.10 cluster with three members

but i am not sure whether my issue is releated with grpc.  any answer will be apprecicated

**Comment by terzonstefano** [comment]
BackUp for etcd

ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key snapshot save /tmp/snapshot-pre-boot.db

Restore for etcd

ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --name=master --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key --data-dir /var/lib/etcd-from-backup --initial-cluster=master=https://127.0.0.1:2380 --initial-cluster-token etcd-cluster-1 --initial-advertise-peer-urls=https://127.0.0.1:2380 snapshot restore /tmp/snapshot-pre-boot.db

Modify /etc/kubernetes/manifests/etcd.yaml

Update ETCD POD to use the new data directory and cluster token by modifying the pod definition file at /etc/kubernetes/manifests/etcd.yaml . When this file is updated, the ETCD pod is automatically re-created as thisis a static pod placed under the /etc/kubernetes/manifests directory.

Update --data-dir to use new target location
--data-dir=/var/lib/etcd-from-backup

Update new initial-cluster-token to specify new cluster
--initial-cluster-token=etcd-cluster-1


Update volumes and volume mounts to point to new path

    volumeMounts:
    - mountPath: /var/lib/etcd-from-backup
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /var/lib/etcd-from-backup
      type: DirectoryOrCreate
    name: etcd-data
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs

**Comment by terzonstefano** [comment]
"""" INSTALL KUBERNETES WITH KUBEADM """"

!!! CHECK ALL INSTALLATION PREREQUISITES BEFORE INSTALLING kubernetes ----> https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/  !!!

prerequisites: Check if it is already installed by running these commands on master nodes:

kubectl

kubeadm

prerequisites: check which version of linux you have: --> cat /etc/os-release

prerequisites: Letting iptables see bridged traffic

prerequisites: Check required ports


prerequisites: install docker on all nodes if not already installed  --> https://kubernetes.io/docs/setup/production-environment/container-runtimes/


docker installation:

sudo -i   



# (Install Docker CE)
## Set up the repository:
### Install packages to allow apt to use a repository over HTTPS


apt-get update && apt-get install -y \
  apt-transport-https ca-certificates curl software-properties-common gnupg2



# Add Docker’s official GPG key:

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -


# Add the Docker apt repository:

add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) \
  stable"


# Install Docker CE

apt-get update && apt-get install -y containerd.io=1.2.13-2 docker-ce=5:19.03.11*3-0*ubuntu-$(lsb_release -cs) docker-ce-cli=5:19.03.11*3-0*ubuntu-$(lsb_release -cs)



# Set up the Docker daemon

cat > /etc/docker/daemon.json <<EOF
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
EOF


  
mkdir -p /etc/systemd/system/docker.service.d


# Restart Docker
systemctl daemon-reload
systemctl restart docker


per vedere se docker è attivo:

systemctl status docker.service


############################end pre-requisites##############################################

INSTALL KUBERNETES

Return to the manual --> https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ and install the following components:


kubeadm: the command to bootstrap the cluster.

kubelet: the component that runs on all of the machines in your cluster and does things like starting pods and containers.

kubectl: the command line util to talk to your cluster.


I report below the steps of the manual, do it on each node:

sudo apt-get update && sudo apt-get install -y apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl


systemctl daemon-reload
systemctl restart kubelet


Vedere la versione di kubeadm --> kubeadm version -o short
Vedere la versione di kubelet --> kubelet --version



we won't install "Configure cgroup driver" as you do when you don't have docker installed


Go to the bottom of the link page mentioned above "What's next":

will take you to the following link --> https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/


Give this command only on the master:

do it with normal user

kubeadm init


Once installed, copy the output that appears and create the directories as follows on the master only:

do it with normal user

mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config



generate the token on the master --> "kubeadm token create --print-join-command"  and then copy the output to all workers 


Still on the master, give the following command:

kubectl get nodes  ## you will see that the nodes are not active since the network for the nodes and pods has not been installed


ENABLE THE NETWORK:

user root:

Enable the following file /proc/sys/net/bridge/bridge-nf-call-iptables to "1"  for all CNI PLUGINS !!! by running this command below on all nodes:

sysctl net.bridge.bridge-nf-call-iptables=1 


Install the network on the master with the normal user

kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"


Check again if the nodes are in the running state

watch kubectl get nodes

**Comment by terzonstefano** [comment]
**Installation of the METRICS SERVER on a MASTER without minkube**

1) git clone https://github.com/kubernetes-incubator/metrics-server.git

2) kubectl create -f deploy/1.8+/

3) wait

4) kubectl top nodes  && kubectl top pods

**Comment by terzonstefano** [comment]
**Deploying flannel network manually**

Flannel can be added to any existing Kubernetes cluster though it's simplest to add flannel before any pods using the pod network have been started.

For Kubernetes v1.17+ kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml



#############################################################


**Quickstart for Calico network on Kubernetes**


1) https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/  ## 

2) Initialize the master using the following command --> kubeadm init --pod-network-cidr=192.168.0.0/16

3) Execute the following commands to configure kubectl (also returned by kubeadm init)  
   
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

4) Install the Tigera Calico operator and custom resource definitions

kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml

5) Install Calico by creating the necessary custom resource

kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml

Note: Before creating this manifest, read its contents and make sure its settings are correct for your environment. For example, you may need to change the default IP pool CIDR to match your pod network CIDR


6) Confirm that all of the pods are running with the following command.

watch kubectl get pods -n calico-system

Note: The Tigera operator installs resources in the calico-system namespace. Other install methods may use the kube-system namespace instead


7) Remove the taints on the master so that you can schedule pods on it

kubectl taint nodes --all node-role.kubernetes.io/master-


8) Confirm that you now have a node in your cluster with the following command.

kubectl get nodes -o wide
It should return something like the following.

NAME              STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
<your-hostname>   Ready    master   52m   v1.12.2   10.128.0.28   <none>        Ubuntu 18.04.1 LTS   4.15.0-1023-gcp   docker://18.6.1


**--------------**

**About installing calicoctl**

calicoctl allows you to create, read, update, and delete Calico objects from the command line. Calico objects are stored in one of two datastores, either etcd or Kubernetes. The choice of datastore is determined at the time Calico is installed. Typically for Kubernetes installations the Kubernetes datastore is the default.

You can run calicoctl on any host with network access to the Calico datastore as either a binary or a container. For step-by-step instructions, refer to the section that corresponds to your desired deployment.


Installing calicoctl as a Kubernetes pod
Use the YAML that matches your datastore type to deploy the calicoctl container to your nodes.

etcd

 kubectl apply -f https://docs.projectcalico.org/manifests/calicoctl-etcd.yaml


Kubernetes API datastore

 kubectl apply -f https://docs.projectcalico.org/manifests/calicoctl.yaml
Note: You can also view the YAML in a new tab.

You can then run commands using kubectl as shown below.

kubectl exec -ti -n kube-system calicoctl -- /calicoctl get profiles -o wide
An example response follows.

NAME                 TAGS
kns.default          kns.default
kns.kube-system      kns.kube-system
We recommend setting an alias as follows.

alias calicoctl="kubectl exec -i -n kube-system calicoctl -- /calicoctl"
Note: In order to use the calicoctl alias when reading manifests, redirect the file into stdin, for example:

calicoctl create -f - < my_manifest.yaml

**Comment by goginenigvk** [comment]
we are using kops. can someone help me on this
showing errors when checking systemctl status kubelet
Jan 07 00:42:11 ip-172-50-2-100 kubelet[5299]: E0107 00:42:11.991760    5299 kubelet.go:2268] node "ip-172-50-2-100.ec2.internal" not found
Jan 07 00:42:12 ip-172-50-2-100 kubelet[5299]: E0107 00:42:12.091892    5299 kubelet.go:2268] node "ip-172-50-2-100.ec2.internal" not found
Jan 07 00:42:12 ip-172-50-2-100 kubelet[5299]: W0107 00:42:12.167515    5299 container.go:409] Failed to create summary reader for "/system.slice/docker-healthcheck.service": none 
of the resources are being tracked.
