### ISSUE TITLE
Undocumented buggy EBS volume ID format

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes/kubernetes#73730]
**What happened**:
When defining persistence volume for EBS using static provisioning, there are two EBS volume ID formats that could be put in the pv spec:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: aws://us-east-1/vol-0d9ea1b8a5c318c12
    fsType: ext4
```

The `awsElasticBlockStore.volumeID` could be either be `aws://us-west-1/vol-035c45314fab68972` or `vol-035c45314fab68972`. And the first ID format is undocumented and buggy where:
1. It causes confusion where people could use problematic IDs and the volume still works. The following IDs both work:
   * `aws://us-west-1/vol-0d9ea1b8a5c318c12` <- volume is created in us-east-1, but identified as us-west-1 as part of the volume ID
   * `aws://unknown/vol-0d9ea1b8a5c318c12` <- using random string as region
1. The slash in the volume ID breaks global volume path by creating extra sub directories along the volume path:
   * Using the example spec, the global path of the volume will be `/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/unknown/vol-0d9ea1b8a5c318c12`. There are two more directories (`aws` and `unknown`) created under `mount` directory. And a sane global path should be like `/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-0d9ea1b8a5c318c12` when the second volume ID format is used.

**What you expected to happen**:
This is not causing any functional issue or misbehave. But the result of this behavior could cause confusing user experience and potential security issue when paths are interpreted/created unintentionally. 

This also have an impact on CSI migration on whether should this behavior be migrated to support both volume ID formats. 

Since the format is undocumented use case (correct me if im wrong), I suggest to not support volume ID in the format of `aws://{region}/{volumeID}` to prevent user confusing and unexpected directories in volume global path for static and dynamic provisioning. And CSI migration for EBS will only support `{volumeID}` as the only ID format

**How to reproduce it (as minimally and precisely as possible)**:
Creating the PV using above pv spec. And consume the pv using follow specs:
pvc:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100
```
pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: claim1
```
**Anything else we need to know?**:
The first ID format is also used by dynamic provisioning.

**Environment**:
- Kubernetes version (use `kubectl version`):v1.13
- Cloud provider or hardware configuration:aws
- Install tools:kops
- Others:

/cc @ddebroy @davidz627

**Comment by davidz627** [comment]
/cc @gnufied 

I agree this seems weird. It brings up the very good question in general about removing undocumented functionality. It's hard to assess real impact or danger here, but it does seem safe to say that removing it will only make things simpler and is a strictly positive thing in terms of code health. The question is whether removing this will break people, and whether that is something we're OK with.

/assign @saad-ali @jsafrane

**Comment by gnufied** [comment]
Won't removing this will break existing PVs?

**Comment by davidz627** [comment]
> Won't removing this will break existing PVs?

I think it will. IIUC dynamic provisioning will provision PV's with ID's of this format.

**Comment by leakingtapan** [comment]
@gnufied it will break PVs that use that format (either dynamically created or static created) if we don't have an upgrade process once the format is disallowed. How about we add something like `Path EBS PVs which use the aws://{region}/{volumeId} format with {volumeId} format` along with the release note?

**Comment by gnufied** [comment]
The problem is not just patching of PVs but actual path on the disk I think. I agree that just using `volumeID` should be sufficient and we don't need the whole `aws://us-east2a/vol-xbya` thing, but we will have to kind of support existing volume paths as well while keeping new format in PV.

So, how are we planning to handle this on kubelet?

**Comment by jsafrane** [comment]
It's not possible to edit existing PVs. You must delete whole PV and create a new one. This may have unexpected consequences on running applications, you need to remove its finalizers and so on. And this will break `/var/lib/kubelet/*` paths if you do it with a PV used by running pod.

IMO, we should fix the in-tree code to create PVs with correct volume IDs, however, the code must be able to work also with PVs with old volume ID format for backward compatibility. We need to keep this compatibility basically forever.

**Comment by ddebroy** [comment]
Can this issue be closed?

**Comment by leakingtapan** [comment]
We still need to address the issue since the problematic format still exists
