### ISSUE TITLE
HPA doesn't scale down to minReplicas even though metric is under target

### ISSUE THREAD

**Issue by max-rocket-internet** [kubernetes/kubernetes#78761]
**What happened**:

HPA scales to `Spec.MaxReplicas` even though metric is always under target.

Here's the HPA in YAML:

```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2019-06-06T10:46:13Z","reason":"ReadyForNewScale","message":"recommended
      size matches current size"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2019-06-06T10:46:13Z","reason":"ValidMetricFound","message":"the
      HPA was able to successfully calculate a replica count from cpu resource utilization
      (percentage of request)"},{"type":"ScalingLimited","status":"True","lastTransitionTime":"2019-06-06T10:46:13Z","reason":"TooManyReplicas","message":"the
      desired replica count is more than the maximum replica count"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":0,"currentAverageValue":"9m"}}]'
  creationTimestamp: "2019-06-06T10:45:58Z"
  name: my-app-1
  namespace: default
  resourceVersion: "55041251"
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/my-app-1
  uid: 44fedc1a-8848-11e9-8465-025acf90d81e
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: my-app-1
  targetCPUUtilizationPercentage: 40
status:
  currentCPUUtilizationPercentage: 0
  currentReplicas: 4
  desiredReplicas: 4
```

And here's a description output:

```
$ kubectl describe hpa my-app-1
  Name:                                                  my-app-1
  Namespace:                                             default
  Labels:                                                <none>
  Annotations:                                           <none>
  CreationTimestamp:                                     Thu, 06 Jun 2019 12:45:58 +0200
  Reference:                                             Deployment/my-app-1
  Metrics:                                               ( current / target )
    resource cpu on pods  (as a percentage of request):  0% (9m) / 40%
  Min replicas:                                          2
  Max replicas:                                          4
  Deployment pods:                                       4 current / 4 desired
  Conditions:
    Type            Status  Reason            Message
    ----            ------  ------            -------
    AbleToScale     True    ReadyForNewScale  recommended size matches current size
    ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
    ScalingLimited  True    TooManyReplicas   the desired replica count is more than the maximum replica count
  Events:           <none>
```

**What you expected to happen**:

HPA only scales up when metric is above target and scales down when under until `Spec.MinReplicas` is reached.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure. We have 9 HPAs and only one has this problem. I can't see anything unique about this HPA when comparing to the others. If I delete and recreate the HPA using Helm, same problem. Also if I recreate the HPA using `kubectl autoscale Deployment/my-app-1 --min=2 --max=4 --cpu-percent=40` same problem.

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.12.6-eks-d69f1b`
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`): EKS AMI release `v20190327`
- Kernel (e.g. `uname -a`): `4.14.104-95.84.amzn2.x86_64`
- Network plugin and version (if this is a network-related bug): AWS CNI
- Metrics-server version: `0.3.2`

**Comment by max-rocket-internet** [comment]
@kubernetes/sig-autoscaling-bugs

**Comment by max-rocket-internet** [comment]
If I scale down manually:

```
I0606 12:06:57.269751 1 horizontal.go:592] Successful rescale of my-app-1, old size: 2, new size: 4, reason: cpu resource utilization (percentage of request) above target
```

And these are the resources specified in the deployment:

```yaml
        resources:
          limits:
            cpu: 2048m
            memory: 4Gi
          requests:
            cpu: 2048m
            memory: 4Gi
```

**Comment by tedyu** [comment]
Can you attach log to this issue ?

thanks

**Comment by max-rocket-internet** [comment]
Hi @tedyu 

I am using AWS EKS so the only HPA related log entries I can see are like this and nothing more:

```
I0612 09:51:36.511060 1 horizontal.go:777] Successfully updated status for xxxx
I0612 09:52:04.080816 1 horizontal.go:777] Successfully updated status for yyyy
I0612 09:52:34.415303 1 horizontal.go:777] Successfully updated status for zzzz
```

**Comment by max-rocket-internet** [comment]
@tedyu Is there some other way I can get more debug information?

**Comment by tedyu** [comment]
There are logs at higher verbosity. e.g. (not that this would be logged in your cluster)
```
		klog.V(4).Infof("proposing %v desired replicas (based on %s from %s) for %s", metricDesiredReplicas, metricName, metricTimestamp, reference)
```
See if you can tune up verbosity

**Comment by max-rocket-internet** [comment]
@tedyu thanks for the suggestion but I don't think we have that option on EKS as it's K8S service: https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html

I guess I have to chase it up with AWS support?

**Comment by max-rocket-internet** [comment]
Our deployment strategy could be also relevant:

```yaml
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
```

**Comment by max-rocket-internet** [comment]
Just look at these events and missing `reason`:

```
Events:
  Type     Reason                        Age                    From                       Message
  ----     ------                        ----                   ----                       -------
  Normal   SuccessfulRescale             4m59s                  horizontal-pod-autoscaler  New size: 8; reason: All metrics below target
  Normal   SuccessfulRescale             4m44s                  horizontal-pod-autoscaler  New size: 16; reason:
  Normal   SuccessfulRescale             4m29s                  horizontal-pod-autoscaler  New size: 32; reason:
  Normal   SuccessfulRescale             4m14s                  horizontal-pod-autoscaler  New size: 64; reason:
  Normal   SuccessfulRescale             3m59s                  horizontal-pod-autoscaler  New size: 128; reason:
  Normal   SuccessfulRescale             3m44s                  horizontal-pod-autoscaler  New size: 200; reason:
  Normal   SuccessfulRescale             0s (x2 over 5m14s)     horizontal-pod-autoscaler  New size: 4; reason: All metrics below target
```

**Comment by vdemonchy** [comment]
I'm having the exact same issue as you @max-rocket-internet, also running on EKS with their latest version available to date. This is frustrating :(

**Comment by SocietyCao** [comment]
@vdemonchy  There may be sudden bursts of traffic，some times cause CPUUtilization to 100% , in this case,it won't scale down

**Comment by max-rocket-internet** [comment]
> some times cause CPUUtilization to 100% , in this case,it won't scale down

This is not the case.

**Comment by SocietyCao** [comment]
The pod is all ready?
 https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details

**If there were any missing metrics, we recompute the average more conservatively, assuming those pods were consuming 100% of the desired value in case of a scale down, and 0% in case of a scale up.** 
I can only speculate this is the case

**Comment by cmanzi** [comment]
@max-rocket-internet Try increasing your metrics resolution from the default. I was experienceing similar behavior, I added the flag `--metric-resolution=5s` (the default is 60s), and it seems to be behaving in a much more expected manner now. 

As @SocietyCao said, in my case it appears that the HPA was rapidly scaling up my service, creating a bunch of pods that didn't have any metrics yet, which in turn caused the HPA to assume the pods were under load. Seems like it can create a feedback loop of sorts.

**Comment by wxwang33** [comment]
We are seeing the same behavior. Has this issue been resolved?

**Comment by cmanzi** [comment]
@wxwang33 What is your metrics-server resolution set to? That fixed it for me (on 1.14.6).

**Comment by wxwang33** [comment]
I will check later as I don't have direct access to it. Will update and thanks for the quick response!

**Comment by itninja-hue** [comment]
I am having the same, issue , at first i thought its not scaling down, but as time went by , exactly 6 minutes , hpa scaled down the pods.
After looking at the events log , it showed up that an event was triggered to scale down the pods the moment the cpi load went off , but got executes 6 minutes later. I guess this is a feature or how it is supposed to work , it would be nice if we can get a  gracePeriod option to define if we want to narrow down or reduce the time. 
I am running k8s 1.16 on vagrant (test cluster) 1 master 2 workers

**Comment by mesutcelik** [comment]
@itninja-hue 

Scale Down stabilization is 5 minutes by default and you can change it with that flag.

`--horizontal-pod-autoscaler-downscale-stabilization`

see more details [here](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details).

**Comment by saravanakumarangamuthu** [comment]
> @max-rocket-internet Try increasing your metrics resolution from the default. I was experienceing similar behavior, I added the flag `--metric-resolution=5s` (the default is 60s), and it seems to be behaving in a much more expected manner now.
> 
> As @SocietyCao said, in my case it appears that the HPA was rapidly scaling up my service, creating a bunch of pods that didn't have any metrics yet, which in turn caused the HPA to assume the pods were under load. Seems like it can create a feedback loop of sorts.

@cmanzi  do you recommend to putting this flag --metric-resolution=5s (the default is 60s), on metrics-server? https://stackoverflow.com/questions/53725248/how-to-enable-kubeapi-server-for-hpa-autoscaling-metrics  as recommened on this link?

**Comment by saravanakumarangamuthu** [comment]
> `--horizontal-pod-autoscaler-downscale-stabilization`

@mesutcelik  you mean to put this on HPA configuration?

**Comment by mesutcelik** [comment]
It needs to be in `kube-controller-manager` as mentioned here though I haven't configured it myself.
https://stackoverflow.com/a/56905137/456602

**Comment by roizentner** [comment]
I am experiencing the same issue (v1.14.6).

In my scenario, I had an auto-scale event that brought the replica number to 2.
After load has stopped, the 2 pods were utilizing ~30% CPU (targetCPUUtilizationPercentage=50).

HPA never kicked in and scaled it down, so I started experimenting (waiting several minutes after each step):
1. Increased targetCPUUtilizationPercentage to 85. Nothing changed.
2. Set maxReplicas to 1. Shortly after, deployment was scaled down.
3. Decreased targetCPUUtilizationPercentage back to 50.
4. Set maxReplicas back to 4. Nothing changed.

CPU utilization kept around 30% all along.

To me, this looks like the HPA is malfunctioning. I thought this might have been fixed on a later release, but I see this issue is still open and active so I guess it wasn't.

**Comment by tuckerconnelly** [comment]
This issue might be related to https://github.com/kubernetes/kubernetes/issues/85506, where it seems pending pods will prevent an HPA from scaling down.

**Comment by doubleo46** [comment]
ANy updat eon this?

**Comment by doubleo46** [comment]
Any update on this?

**Comment by EmanekaT** [comment]
It seems this still happens somehow.
```
Name:               external--verification-main
Namespace:          paasta
Labels:             <none>
Annotations:        signalfx.com.custom.metrics:
CreationTimestamp:  Thu, 07 Nov 2019 17:02:21 -0800
Reference:          Deployment/external--verification-main
Metrics:            ( current / target )
  "uwsgi" on pods:  0 / 50
Min replicas:       3
Max replicas:       10
Deployment pods:    6 current / 6 desired
Conditions:
  Type            Status  Reason               Message
  ----            ------  ------               -------
  AbleToScale     True    ScaleDownStabilized  recent recommendations were higher than current one, applying the highest recent recommendation
  ScalingActive   True    ValidMetricFound     the HPA was able to successfully calculate a replica count from pods metric uwsgi
  ScalingLimited  False   DesiredWithinRange   the desired count is within the acceptable range
Events:
  Type     Reason               Age                  From                       Message
  ----     ------               ----                 ----                       -------
  Warning  FailedGetPodsMetric  110m (x219 over 9h)  horizontal-pod-autoscaler  unable to get metric uwsgi: no metrics returned from custom metrics API
  Normal   SuccessfulRescale    60m (x7 over 11h)    horizontal-pod-autoscaler  New size: 7; reason: All metrics below target
  Normal   SuccessfulRescale    15m (x509 over 10h)  horizontal-pod-autoscaler  New size: 5; reason: All metrics below target
  Normal   SuccessfulRescale    11m (x46 over 10h)   horizontal-pod-autoscaler  New size: 4; reason: All metrics below target
  Normal   SuccessfulRescale    56s (x100 over 10h)  horizontal-pod-autoscaler  New size: 6; reason: All metrics below target
```
Based on events, no metrics are missing, and all metrics are below target. Yet it scaled up to 6?

**Comment by meezaan** [comment]
> @itninja-hue
> 
> Scale Down stabilization is 5 minutes by default and you can change it with that flag.
> 
> `--horizontal-pod-autoscaler-downscale-stabilization`
> 
> see more details [here](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details).

My pods downscaled after 5 minutes of the load disappearing from them. I'm running k8s 1.16.1. This is also discussed on https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/. 

If you want to tweak it HPA yaml though, I'm not sure where this will go.

**Comment by sciffer** [comment]
I see the exact same problem with kubernetes 1.15.6(setup via kops).
I have a deployment with with HPA set to min 2 max 5, played with the target and scale up seems to be happening(almost immediately after I created load) - but scale down does not seem to happen or get triggered(even when it shows 0%).
I played with the target value to figure out if I can cause it to scaledown and noticed a flapping line whendescribing the hpa between:
  AbleToScale     True    ScaleDownStabilized  recent recommendations were higher than current one, applying the highest recent recommendation
and:
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
As if the way that autoscaller is fetching the metric/cpu utilization is not reliable/flaky.
On that also noticed that once it scaled up, it complained once in the events:  did not receiv
e metrics for any ready pods
I think it might be related to the fact that it takes time to have metrics for new pods(it did not complain again after the scale-up - or scale out to be more accurate).

**Comment by max-rocket-internet** [comment]
Do the other people who have hit this issue also have other pods that might have a the same labels as the pods from the deployment of the HPA? For example, created from cronjobs/jobs?

**Comment by bastienbc** [comment]
I have this issue with an nginx ingress controller deployed with helm.
At first HPA did not even compute metrics because it also retrieved the resources from the default backend, which had no resource definition. I "repaired" it by putting requests and limits for the default backend (different deployment but overlapping labelSelector), and now HPA is setting replicas to the max for no reason (60%/80% and 3%/90%).

I have been waiting for 20 minutes waiting for a scale down, but nothing is happening.

**Comment by sciffer** [comment]
I might have few labels that are common on the HPA and the pods of that
deployment, why?

**Comment by max-rocket-internet** [comment]
> labels that are common on the HPA and the pods

It's not this. It's labels that are common with the deployment that the HPA is looking at, and pods that are NOT part of that deployment.

**Comment by alexklibisz** [comment]
Seeing similar behavior on 1.15. First the HPA warns that it can't read metrics, then it quickly scales up to the max replicas, then about five minutes later it scales back down to the minimum replicas. All while there is zero load/traffic to the pods.

**Comment by kimxogus** [comment]
Having the same issue on 1.15.9(on aws via kops), I tried all hpa v1, v2beta1 and v2beta2, and both cpu utilization and custom metrics(like requests per second) via prometheus adapter, hpa always scale up and never scales down even metric is much smaller than target value.

**Comment by kimxogus** [comment]
> Do the other people who have hit this issue also have other pods that might have a the same labels as the pods from the deployment of the HPA? For example, created from cronjobs/jobs?

Since I separated all cronjobs from my app's helm chart, hpa started to scale deployment correctly.
This is very weired, because pods from deployment and cronjobs have different `component` label(`web-server` and `cronjob`).

**Comment by deepanverma19** [comment]
Do we have any update for this issue?

**Comment by michcio1234** [comment]
I had a similar issue and in my case the problem was that some scheduled pods were Pending (because the cluster didn't have enough resources). As soon as I added new nodes, Pending pods were started and HPA was able to scale the deployment down.
So it's what @tuckerconnelly wrote in https://github.com/kubernetes/kubernetes/issues/78761#issuecomment-558399867.

**Comment by sciffer** [comment]
I’m still facing that issue, it never scales down even When cpu shows up to
1%.
And no, don’t have other resources in the same namespace with
colliding/same labels/matchers.

**Comment by sarvjeetrajvansh** [comment]
even i am facing the same issue.
it will reach to max pod but will never come down.

i tried autoscaling/v1 autoscaling/v2beta1

K8s version 1.14 .


kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"resize-app","namespace":"default"},"spec":{"maxReplicas":3,"metrics":[{"resource":{"name":"memory","targetAverageUtilization":60},"type":"Resource"}],"minReplicas":2,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"appservice"}}}


behavior is totally unpredictable.

NAME             REFERENCE                     TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
resize-app   Deployment/app       **61%/60%   2         3         2**          286d
resize-apppayment   Deployment/apppayment        **56%/60%   2         3         3**          264d
resize-appmapservice   Deployment/appmapservice     40%/60%   2         3         2          286d

**Comment by o0st** [comment]
I was able to trigger downscaling on stuck hpa via switching`targetAverageUtilization` to `targetAverageValue` in hpa configuration. Kube version: `v1.14.9`.

**Comment by sarvjeetrajvansh** [comment]
> AverageValue
do you know target average value calculates in bit or byte

 kubectl get hpa
NAME           REFERENCE                TARGETS       MINPODS   MAXPODS   REPLICAS   AGE
resize-hello   Deployment/hello-world   **17817600/85**   1         5         5          62s

i was expecting a hpa

**Comment by anton-fedorov** [comment]
Tried using `targetAverageValue` instead of `targetAverageUtilization` - still no successful scale down

**Comment by senosigit** [comment]
install HPA use helm version 2.14, it's work for me. after 5-6 minutes pods scale down

**Comment by davejhahn** [comment]
I'm having the same problems described by others.  Using k8s 16.7 in Azure.  What I see is scale up works fine (with metrics from cpu and memory), and scale down does happen, but it falls short of the minreplicas.  In my case, I have that set as 1, and it falls back down to 2, 4, etc.... and stays there.  kubectl get hpa shows everything well below the thresholds.  This is a test environment only used by me, nothing else is even hitting it.  Stays like this indefinitely (e.g. hours, overnight).

**Comment by artem-zinnatullin** [comment]
Ehh, we've lost some money in off-peak hours because of not scaling down…

But, I think I've found ***a workaround*** in the meantime.

It seems that using `autoscaling/v1` instead of `autoscaling/v2beta2` if you can rely just on CPU usage works correctly:

```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaler
  namespace: my-namespace
  labels:
    app: my-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
  minReplicas: 3
  maxReplicas: 10
  # We're using old API due to
  # - https://github.com/kubernetes/kubernetes/issues/78712
  # - https://github.com/kubernetes/kubernetes/issues/78761
  targetCPUUtilizationPercentage: 20
```

**Comment by davidxjohnson** [comment]
Any HPA that does not rely on Prometheus seems to scale up and down correctly on k8s 1.14. Our issue appeared to be with custom metrics that rely on Prometheus that would not scale back down. The issue was a persistent volume (EBS) (used by Prometheus) was filled up, which prevented proper evaluation of custom metrics. Not saying this will fix your issue, but the default volume size (Prometheus Helm Chart) is inadequate for a production system. You might want to check the logs coming out of Prometheus server to see if this is the case - i.e. unable to store new metrics.

**Comment by davejhahn** [comment]
I am using the metric server that comes along with AKS (at least now, that will change at some point), seeing the issue with that.  In my case the correct metrics are being reported, it's just not responding to it for the scale down.

**Comment by max-rocket-internet** [comment]
There's been a few PRs merged around fixing HPA issues but AFAIK none of those changes are in a released version of k8s yet?

/remove-lifecycle stale

**Comment by copecopecope** [comment]
> > labels that are common on the HPA and the pods
> 
> It's not this. It's labels that are common with the deployment that the HPA is looking at, and pods that are NOT part of that deployment.

I've had this issue for months and this ended up being what fixed it. I had three deployments in the same cluster which had the same pod labels and `.spec.selector` fields. I added a unique label/selector field to each deployment (note: I needed to delete and recreate the deployment since the selector field is immutable). After that the HPA started behaving normally.

**Comment by denyo** [comment]
I had the same issue where the HPA calculated that there should be 2 replicas even though memory threshold was at `40%/70%`.

I am using prometheus operator and noticed that there where duplicate metrics. 
One metric being scraped from `/metrics/cadvisor` and another one from `/metrics/resource/v1alpha1` with identical values.

Following the advice of https://github.com/helm/charts/issues/23131#issuecomment-658115091 disabling the serviceMonitor for resource fixes the duplicate memory metrics:
```
kubelet:
  serviceMonitor:
    resource: false
```

Since then also HPA works as expected.

**Comment by serain** [comment]
I have the same issue but none of the fixes here are working for me. I'm running 1.16 on digitalocean's DOKS managed k8s.

My CPU util target is 80%.

`kubectl describe hpa` constantly reports below target.

HPA always maxes out.

**Comment by scott2449** [comment]
> > > labels that are common on the HPA and the pods
> > 
> > 
> > It's not this. It's labels that are common with the deployment that the HPA is looking at, and pods that are NOT part of that deployment.
> 
> I've had this issue for months and this ended up being what fixed it. I had three deployments in the same cluster which had the same pod labels and `.spec.selector` fields. I added a unique label/selector field to each deployment (note: I needed to delete and recreate the deployment since the selector field is immutable). After that the HPA started behaving normally.

My issue was this. I was trying to track it down for like 6 weeks, read this and many other posts but completely missed the point that it's the selectors of the scaleTargetRef that you need to make sure are only selecting the pods in the deployment. Deployment, ReplicaSets, etc.. will apparently work perfectly fine with selector that is selecting pods from other deployments, but fail hard when you attach an HPA. This is more than a little frustrating... 

In our case a developer had a dozen different deployments all with the same label `app: myapp` (let's say). Then used 
`selector:
    matchLabels:
      app: myapp` 

So even though the deployment only had 4 pods, the HPA was calculating replicas using over 50 pods... You will not see this in describe, or get, or k8s logs... they all report from the deployment numbers BUT the replica count code is using the targets selector to build the collection of metrics 🤦 https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L574 

So is this our "bug", should this be addressed? Or merely better docs... this is really hard to describe.. took me a couple attempts with the dev team that caused it and my own core k8s team before they got it.

**Comment by max-rocket-internet** [comment]
> should this be addressed? Or merely better docs

This is definitely a bug and should be fixed! The HPA `scaleTargetRef` uses deployment by `name` and that should be enough without having to worry about selectors.

**Comment by max-rocket-internet** [comment]
It can be reproduced with this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          requests:
            cpu: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
---  
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-1
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: nginx-1
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
```

**Comment by garimakemwal** [comment]
> 
> My issue was this. I was trying to track it down for like 6 weeks, read this and many other posts but completely missed the point that it's the selectors of the scaleTargetRef that you need to make sure are only selecting the pods in the deployment. Deployment, ReplicaSets, etc.. will apparently work perfectly fine with selector that is selecting pods from other deployments, but fail hard when you attach an HPA. This is more than a little frustrating...

Faced this exact issue as @scott2449 . Ensuring that every deployment being scaled with HPA has its unique set of selectors and labels in the deployment is crucial for HPA to work. Providing the HPA with target deployment name does not seem to be enough. In our case, there were `commonLabels` being passed from base kustomize deployment to all resources. 

The challenge is that `kubectl describe hpa` will only show the pods belonging to the corresponding deployment, when in reality, HPA is calculating the metric for all pods with that overlapping label (even if the pods belong to another deployment). 
Is this behaviour expected, if yes, is there any documentation addressing this?

**Comment by chaolou** [comment]
HPA get and calculate metrics by label selector completely flexibly, but can only control one deployment, It's so confusing！

**Comment by gerardgorrion** [comment]
Hi all , we have same problem in kubernetes 1.15. We try to deploy some app and add the hpa to autoscale. Scaling up is working fine, but the extra pod is destroyed and created a new pod every 5 min:
![Captura](https://user-images.githubusercontent.com/35425181/96422425-4a3ceb00-11f8-11eb-9a5e-0fac4bc2e1e6.PNG)


When try to scale down (stopped the cpu consume), deployment events show request to scale down and a petition to scale up; the hpa show scale up with no reason; and the extra pods created by the autoscale was removed and created a new also every 5 min. Deployment never return to initial desiredpods (if we try to scale to 2, desiredpods show2, if we autoescale to 5, desiredpods show 5...).

We try to deploy hpa v1, v2beta1 and v2beta2 and only use CPU metric with %. Metric server seem work fine, every 30/40 sec the logs show correct node and pods status.

Thanks!

**Comment by es1o** [comment]
I have similar issue with v2beta2. AverageUtilization is below target but it scales to maximum:
```Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  38% (64m) / 90%
Min replicas:                                          5
Max replicas:                                          10
Deployment pods:                                       10 current / 10 desired
Conditions:
  Type            Status  Reason               Message
  ----            ------  ------               -------
  AbleToScale     True    ScaleDownStabilized  recent recommendations were higher than current one, applying the highest recent recommendation
  ScalingActive   True    ValidMetricFound     the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  True    TooManyReplicas      the desired replica count is more than the maximum replica count```

I've created a Grafana dashboard with desired replicas and replicas calculated manually based on algorithm and I have mismatch:
<img width="1327" alt="Screenshot 2020-10-27 at 12 30 26" src="https://user-images.githubusercontent.com/565758/97295898-d201a580-1847-11eb-98b7-208b0c1991e5.png">

I added `--metric-resolution=5s` to my metrics-server configuration but without success.

**Comment by max-rocket-internet** [comment]
Yeah we also have dashboards to detect this issue. Here's an obvious example (grey band shows HPA min/max pods):

![Screenshot 2020-10-27 at 16 16 50](https://user-images.githubusercontent.com/8859277/97322223-de015d80-186f-11eb-935a-eb72819540d2.png)

**Comment by PeteMac88** [comment]
Hey guys, I am not sure if our problem matches the cases described here but as far as I can read they seem connected. I am doing load tests in order to find the correct scaling configuration for us and having some strange scaling behaviors for the hpa on AWS EKS. I am running the same load test for a few minutes and new replicas are scaled up correctly. The problem is that every 5 minutes the hpa seems to delete and create new pods but always keeps the number the same. In my eyes this should not happen at all because the load stays the same. The recreation of pods causes short peaks in response time and i want to get rid of them. Does anyone of you have an idea?

In this chart you see the old and newly created pods

![image](https://user-images.githubusercontent.com/46486024/99684374-af972c80-2a81-11eb-8771-71d886017a09.png)

**Comment by gerardgorrion** [comment]
Do you use fluxcd ir some continuos deployment? 

> Hey guys, I am not sure if our problem matches the cases described here but as far as I can read they seem connected. I am doing load tests in order to find the correct scaling configuration for us and having some strange scaling behaviors for the hpa on AWS EKS. I am running the same load test for a few minutes and new replicas are scaled up correctly. The problem is that every 5 minutes the hpa seems to delete and create new pods but always keeps the number the same. In my eyes this should not happen at all because the load stays the same. The recreation of pods causes short peaks in response time and i want to get rid of them. Does anyone of you have an idea?
> 
> In this chart you see the old and newly created pods
> 
> ![image](https://user-images.githubusercontent.com/46486024/99684374-af972c80-2a81-11eb-8771-71d886017a09.png)

**Comment by PeteMac88** [comment]
> Do you use fluxcd ir some continuos deployment?
> 
> Make sure that spec.replicas of your deployment.yml no exist.
> 
Thanks @gerardgorrion, that was the problem!

**Comment by lungosta** [comment]
if I'm understanding the issue with hpa and deployments properly, deployments within the cluster cannot share selectors and/or labels, in my case I have several deployments with completely different selectors but they all share a label in common which is being used for the pod identity in AKS, which I think it might be causing the issue with the hpa scale down. Removing this common label is not option for me since it's being used to access secrets in key vault.

I've also configured a replica set on each one of my deployments, should I delete this part of deployment or doesn't make sense at all because I need to get rid of the common label first to make HPA work correctly?

**Comment by NicolasAndresCalvo** [comment]
I'm using `EKS 1.17` and faced same issue. I tried everything that I saw in this thread. Finally I make it down, by deleting old replicasets (`kubectl delete $(kubectl get all | grep replicaset.apps | grep "0         0         0" | cut -d' ' -f 1)`), increasing `targetAverageUtilization` from `80` to `90`, and what I think make it work, removing `replicas: 1` from Deployment.yml

**Comment by okossuth** [comment]
What's the status of this? we are seeing the same issue on a k8s 1.18 cluster, apiVersion: autoscaling/v2beta2 and using custom metrics...

**Comment by Cib0rg** [comment]
I can reproduce that on my 1.18clusterwith custom metrics. And for me that reproduces if I recreate hpa with metrics change - if last metric set high pod count then hpa stucks and don't downscale it.

**Comment by acheraime** [comment]
Same issue here. Running k8s 1.19.13 on GKE. Deployment scales up but won't scale down.

**Comment by seocam** [comment]
It seems we've hit that very same wall here. We are running `1.21.5-gke.1302` and it two of our deployments with HPA decided to keep scaling up only. If we force it down they just went up again by themselves. Using Values instead of Utilization did "corrected" the problem but we don't want to manage values ourselves.

We have tried to scale 0 and then scale 1 but the HPA kept scaling up and up until the upper limit.
We tried to erase the replicaset to let HPA create another one. Same problem.
We tried to delete the HPA and redeploy just the HPA. Same problem.

The only actual solution we found was to delete the two problematic deployments (using helm uninstall) and to redeploy them. That was very annoying.

In our case the problem started after a cluster node got replaced.

**Comment by ThomasBarach** [comment]
Hello, I'm running 1.21.5-gke.1302 and removing `spec.Replicas` in my deployment fixed the issue, HPA started to scale down pods.

**Comment by seocam** [comment]
The problem came back after a few days and so far we have no workaround working for us. We had to disable HPA for now.

**Comment by ThomasBarach** [comment]
Hello, I'm running 1.21.5-gke.1302 and it seems some pods are "blocking" HPA. Whenever I delete pods in `Terminated`, `NodeShutdown` or `OutOfcpu` status, it solves the issue and HPA can scale down correctly. 
I've also delete `spec.Replicas` field in my deployments. 
Hope this helps

**Comment by seocam** [comment]
> Hello, I'm running 1.21.5-gke.1302 and it seems some pods are "blocking" HPA. Whenever I delete pods in `Terminated`, `NodeShutdown` or `OutOfcpu` status, it solves the issue and HPA can scale down correctly. I've also delete `spec.Replicas` field in my deployments. Hope this helps

You nailed it. After erasing those pods HPA starts to work properly again. 

I'm not sure if we shouldn't open another issue for this bug.

Kubernetes version (use kubectl version): v1.21.5-gke.1802
Cloud provider or hardware configuration: GCP GKE
OS (e.g: cat /etc/os-release): Container-Optimized OS from Google
Kernel (e.g. uname -a): 5.4.144+
Metrics-server version:  metrics-server-v0.4.4

**Comment by vitobotta** [comment]
> Hello, I'm running 1.21.5-gke.1302 and it seems some pods are "blocking" HPA. Whenever I delete pods in `Terminated`, `NodeShutdown` or `OutOfcpu` status, it solves the issue and HPA can scale down correctly. I've also delete `spec.Replicas` field in my deployments. Hope this helps

Hi, is it still working for you? I'm in GKE and for example ingress nginx hpa doesn't scale down from the max of 10 replicas to 2 when there is little traffic. It just scales up to the max 10 regardless of what I do. I don't have any pods with those status, and I have tried changing the replicas manually and removing the replicas field from the deployment, but hpa always scales up to the max. Any suggestions?

**Comment by ThomasBarach** [comment]
@vitobotta

**Comment by vitobotta** [comment]
> @vitobotta Hello, yes it still works. Did you check other namespaces?

Yes, I have the same problem in another namespace although slightly different and even weirder. I have an app with HPA set to max 10 replicas as well and no traffic yet (we haven't finished the migration) and for some reason HPA likes to keep it at 9 replicas instead of the min of 2. Not even the max 10 lol. Why 9 I wonder :D

**Comment by elrob** [comment]
I'm having another issue and I have searched and been unable to find out why, if it is a bug, or if I am doing something incorrectly?

• HPA scaled down correctly based on my parameters
• And correctly detects a trigger to scale up
• But continues to scale up when it should not

From the events below:
3 -> 2 -> 3 -> 4 -> 5 makes sense 
7 -> 9 -> 12 -> 15 does not make sense - the metric was back at 0 but it continues to scale up and the `reason: All metrics below target` would suggest that it knows it shouldn't be scaling up.


```
Metrics:                                                                                             ( current / target )
  "XXX" (target average value):                                                                      0 / 10
Min replicas:                                                                                        2
Max replicas:                                                                                        16
Behavior:
  Scale Up:
    Stabilization Window: 0 seconds
    Select Policy: Max
    Policies:
      - Type: Percent  Value: 25  Period: 300 seconds
  Scale Down:
    Stabilization Window: 1800 seconds
    Select Policy: Max
    Policies:
      - Type: Percent  Value: 10  Period: 900 seconds
Deployment pods:       16 current / 16 desired
Conditions:
  Type            Status  Reason               Message
  ----            ------  ------               -------
  AbleToScale     True    ScaleDownStabilized  recent recommendations were higher than current one, applying the highest recent recommendation
  ScalingActive   True    ValidMetricFound     the HPA was able to successfully calculate a replica count from external metric XXX
  ScalingLimited  True    TooManyReplicas      the desired replica count is more than the maximum replica count
Events:
  Type    Reason             Age                 From                       Message
  ----    ------             ----                ----                       -------
  Normal  SuccessfulRescale  45m (x26 over 25h)  horizontal-pod-autoscaler  New size: 2; reason: All metrics below target
  Normal  SuccessfulRescale  43m (x5 over 24h)   horizontal-pod-autoscaler  New size: 3; reason: external metric XXX above target
  Normal  SuccessfulRescale  38m (x25 over 25h)  horizontal-pod-autoscaler  New size: 4; reason: external metric XXX above target
  Normal  SuccessfulRescale  33m (x7 over 23h)   horizontal-pod-autoscaler  New size: 5; reason: external metric XXX above target
  Normal  SuccessfulRescale  27m (x10 over 22h)  horizontal-pod-autoscaler  New size: 7; reason: All metrics below target
  Normal  SuccessfulRescale  22m (x8 over 19h)   horizontal-pod-autoscaler  New size: 9; reason: All metrics below target
  Normal  SuccessfulRescale  17m (x12 over 24h)  horizontal-pod-autoscaler  New size: 12; reason: All metrics below target
  Normal  SuccessfulRescale  12m                 horizontal-pod-autoscaler  New size: 15; reason: All metrics below target
  Normal  SuccessfulRescale  7m8s (x9 over 23h)  horizontal-pod-autoscaler  New size: 16; reason: All metrics below target
```

**Comment by chamoda** [comment]
As a temporary workaround I was able to get it scale down by deleting all pods that were not running (pods with state `Terminated`, `NodeShutdown` ect). Make sure only pods with `Running` status are visible when you run `kubectl get pods -A` 

This was a GKE cluster (version: 1.21.5-gke.1302) with preemptible option enabled which cause lot of instances to be in status of `Terminated`  or `NodeShutdown` status.

**Comment by jeroenj** [comment]
For us this issue started appearing as soon as we upgraded to GKE 1.21 about a month ago. After some investigation we noticed that we have Pods in `Terminated` and/or `NodeShutdown` state more often than when we were on GKE 1.20. Having more such pods is probably (most likely?) related to the [Graceful node shutdown](https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown) feature that went into beta in Kubernetes 1.21 (and thus is enabled by default). Though according to the [GKE release notes](https://cloud.google.com/kubernetes-engine/docs/release-notes#May_03_2021) this should have been enabled on preemptible node pools since GKE 1.20.5-gke.500. However, at least on our GKE 1.20.11-gke.1801 clusters we can confirm (as far as that's possible) that it doesn't seem to be enabled there: `kube-proxy` is not started with the `GracefulNodeShutdown` feature gate (while it is the case for GKE 1.21). Now that's not the way to know if the feature node is enabled in the control plane or not, but it's the closest you can get to it (as far as we know).

Anyway, it indeed seems (in our scenario) that because of the increase in `Status=Failed` Pods we're being hit by our HPAs not scaling down properly anymore. Cleaning up the terminated pods makes the HPA scale down again.

**Comment by seocam** [comment]
Same here @jeroenj. The problems for us started just after upgrading from GKE 1.20 to 1.21. 
I wonder if the Google team is aware of this :thinking:

**Comment by oldgiova** [comment]
Same problem here: we have many Completed pods from scheduled cronjobs; just after deleting all those pods, the HPA starts working again.
```
NAME                                                              READY   STATUS      RESTARTS   AGE
 my-app-5c5b8b6ffc-55qcb                                   1/1     Running     0          15m
 my-app-5c5b8b6ffc-8d4gd                                   1/1     Running     0          20m
 my-app-5c5b8b6ffc-gn2xh                                   1/1     Running     0          13m
 my-app-5c5b8b6ffc-jdnnr                                   1/1     Running     0          14m
 my-app-5c5b8b6ffc-xtz6v                                   1/1     Running     0          16m
 my-app-cronjob1-1643765400-r6878                          0/1     Completed   0          32h
 my-app-cronjob1-1643851800-qjrxd                          0/1     Completed   0          8h
 my-app-cronjob2-1643870400-cschw                          0/1     Completed   0          175m
 my-app-cronjob2-1643874000-cshp2                          0/1     Completed   0          115m
 my-app-cronjob3-164376000296bp                            0/1     Completed   0          33h
 my-app-cronjob3-164384640hds26                            0/1     Completed   0          9h
 ```

**Comment by rmoesbergen** [comment]
For those who are seeing this issue on GKE, here's the google bugtracker for the issue:
https://issuetracker.google.com/issues/204415098

**Comment by azeer-esmail** [comment]
Ok, i think i finally know whats going on, it seems that many people are facing this issue, and since down scaling is important for our model i decided to run some tests, turns out **the problem is in [the calculation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details) done by the HorizontalPodAutoscaler controller**: desiredReplicas = ceil[currentReplicas * ( currentMetricValue / desiredMetricValue )]

_Ansatz:_
this equation when scaling down **works when the change in utilization due to load difference is big, usually with cpu** ( e.g. 100m - 500m <=> 20% - 100%), but it **fails when the change in utilization is small, usually with memory** (e.g. 160Mi - 200Mi <=> 80% - 100%)

_Theoretical example:_
lets say we have a situation where we have a deployment with resources.requests.memory is set to 200Mi, and HPA averageUtilization for memory resource is set to 100%(=200Mi).
because of high memory usage pods were scaled up from 1 to 4, after scaling the memory usage dropped down from 200Mi to 160Mi, now we have 4 pods with avg. of 160Mi, HPA is showing: 80% / 100%   since we demanded scale up on 100% usage of requested 200Mi, current usage = 160Mi -> 160/200 = 0.8 or 80%.
now the HPA will run the equation above and see what to do, so: desiredReplicas = ceil[4 * ( 80 / 100 )] = ceil[3.2] = 4
and there are already 4 pods, so it will not act even though the metric is under avg. of targets.
* if you walk through the same example with 5 pods instead of 4 you'll see that at the first iteration the result = 4 too, and it would actually scale down to 4.
* if you do it with CPU parameters the result would be 1 at first calculation, needles to say that idle pods are usually between 5m - 10m, much less than 100m and difference is much larger.

_Empirical example:_
 Setup: we have the namespace "1" (just for ease of typing), in it there are 3 deployments 
1 - rails pod
2 - redis pod
3 - postgresql pod
testing is done on rails pod where it can be scaled up from 1 to 5 pods when memory usage is high.

in rails deployment yml file:
```
...
          resources:
            limits:
              cpu: 500m
              memory: 300Mi
            requests:
              cpu: 90m
              memory: 200Mi
...
```

rails HPA
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: rails-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rails-dep
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
```

Testing:
first we have the setup with the rails dep, without the HPA, as you can see its idle at 4m & 158Mi, which means when we deploy the HPA with averageUtilization: 50 it would start scaling up
<img width="508" alt="Screen Shot 2022-03-22 at 2 24 04" src="https://user-images.githubusercontent.com/52313686/159383952-17bbe466-da2b-4618-8c83-7ec471e3ee47.png">

deploying HPA
<img width="728" alt="Screen Shot 2022-03-22 at 2 31 44" src="https://user-images.githubusercontent.com/52313686/159384583-7bc9a75e-949d-466c-8bc6-aa94590bc453.png">

after few minutes is scales up to 5 pods (memory still above 50% but it reaches the max limit of 5 pods)
<img width="737" alt="Screen Shot 2022-03-22 at 2 33 54" src="https://user-images.githubusercontent.com/52313686/159384761-444c3870-6b46-4309-929b-69f2a611f56c.png">

------------------------------------------------------------------------------------------------------------------------
------------Mathematical reasoning for those who are interested, you can skip and use the equation------------
now lets calculate what is the limit needed for HPA to scale it down and re create the HPA with different limits to test the theory, to do that we need express the desiredMetricValue in terms of the other values by re arranging:
desiredReplicas = ceil[currentReplicas * ( currentMetricValue / desiredMetricValue )]
or: desiredReplicas = ceil[(currentReplicas * currentMetricValue) / desiredMetricValue ]
its possible to replace the RHS with: (currentReplicas * currentMetricValue) / (desiredMetricValue - epsilon)
(drop ceil function and subtract a quantity from denominator) if the following conditions are satisfied:
1) (currentReplicas * currentMetricValue) / (desiredMetricValue - epsilon) = desiredReplicas
   * where desiredReplicas is a positive integer, and epsilon is a positive number or 0
2) [(currentReplicas * currentMetricValue) / (desiredMetricValue - epsilon)]  - [(currentReplicas * currentMetricValue) / desiredMetricValue] = y
   * where 0 =< y < 1

in simple words the replacement of ceil function is to subtract a number (epsilon) from the denominator so that the division yields an integer and the difference between that integer, and result without subtracting epsilon in less than 1.
so now we have: desiredReplicas = (currentReplicas * currentMetricValue) / (desiredMetricValue - epsilon)
rearranging: desiredMetricValue = [(currentReplicas * currentMetricValue) / desiredReplicas] + epsilon
now if we add the constraint that all these variables are positive integers (which they are in practice) then to ensure that RHS is always an integer (because the LHS desiredMetricValue is an integer):
epsilon = ceil[(currentReplicas * currentMetricValue) / desiredReplicas] - (currentReplicas * currentMetricValue) / desiredReplicas
for example assume the quantity: (currentReplicas * currentMetricValue) / desiredReplicas = 4.4, to ensure the RHS is integer epsilon must be: ceil(4.4) - 4.4 = 5 - 4.4 = 0.6, => 4.4 + 0.6 = 5 which is an integer
it actually can also be 1.6, 2.6, 3.6 etc... which can be added to the epsilon equation (+ k) where k is 0, or positive integer.
but for simplicity let just assume it's 0 and omit it.
then substituting for epsilon we get:
### desiredMetricValue = ceil[(currentReplicas * currentMetricValue) / desiredReplicas]
------------------------------------------------------------------------------------------------------------------------
so we use this equation with what we have now to scale down:
<img width="737" alt="Screen Shot 2022-03-22 at 3 08 11" src="https://user-images.githubusercontent.com/52313686/159387487-02dd4838-7c2a-4ec9-ba34-fe1bc793f19c.png">
desiredMetricValue = ceil[(5 * 84) / 4] = 105
this means we need to set HPA averageUtilization to 105 (105%) in order to scale down to 4, i will set it to 104 first, wait and make sure it doesn't scale down and then to 106 and check if it does.
`        averageUtilization: 104`
apply HPA changes:
<img width="737" alt="Screen Shot 2022-03-22 at 3 32 27" src="https://user-images.githubusercontent.com/52313686/159389611-6637d88d-c1e5-41ef-adf9-7d7c10d40ccf.png">
after 6 min still 5 replicas
<img width="737" alt="Screen Shot 2022-03-22 at 3 34 30" src="https://user-images.githubusercontent.com/52313686/159389808-e8ee4b25-3dbd-4a28-a292-d2b8eae8e46f.png">

now change averageUtilization to 106 and apply
`        averageUtilization: 106`
<img width="737" alt="Screen Shot 2022-03-22 at 3 37 34" src="https://user-images.githubusercontent.com/52313686/159390075-a31998e3-1e55-4d1b-b471-fd9f77506d67.png">
and in less than a minute it scaled down to 4!
<img width="737" alt="Screen Shot 2022-03-22 at 3 38 57" src="https://user-images.githubusercontent.com/52313686/159390284-99bc2346-5cca-4d0b-912a-07bb235c1421.png">

one more try to drive the point home, scale from 4 to 3 calc:
ceil[(4 * 84) / 3] = 112
exact limit test:
`        averageUtilization: 111`
<img width="737" alt="Screen Shot 2022-03-22 at 3 50 24" src="https://user-images.githubusercontent.com/52313686/159391252-d355417f-4b82-464d-ab8c-b7e4ae7ebadd.png">
after 6 min still 4 replicas
<img width="737" alt="Screen Shot 2022-03-22 at 3 52 33" src="https://user-images.githubusercontent.com/52313686/159391469-bcb07584-35aa-4646-8350-832bf2410fe7.png">

`        averageUtilization: 112`
<img width="737" alt="Screen Shot 2022-03-22 at 3 55 20" src="https://user-images.githubusercontent.com/52313686/159391749-2d1e53c4-9e82-4f93-9917-f64b1213061a.png">
and after approx. 1 min scaled down to 3 replicas
<img width="737" alt="Screen Shot 2022-03-22 at 3 56 11" src="https://user-images.githubusercontent.com/52313686/159391841-7ca36eae-df56-43c9-8cd0-70266ee6cd90.png">

_conclusion_:
this algorithm is suitable for scaling up even if the change is small as it ceils the calculated quantity, so it scales up on exact limit of upper bound, but when scaling down it also ceils, so the difference has to be big enough in order to get a smaller number of replicas after ceiling.
it's worth mentioning also, if this wasn't the case that a big difference is needed to scale down with current algorithm, the HPA would have a [flapping](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#flapping) 

problem:
utilization overload -> scales up -> utilization drop -> scales down -> utilization overload -> scales up -> ad infinitum
worst case scenario is when scaling down from 2 -> 1 pod, the the desiredMetricValue should be double the currentMetricValue --- desiredMetricValue = 2 * currentMetricValue for it to scale down (50% / 100%)

solution:
i tweaked around with variables to see if there is a work around, and there is but its bound to idle memory utilization and the amount of increase it takes to scale up, like **if its set in a way that it starts with 49% / 100% (less than 50%) at idle then it will scale down** when there is no load, the catch is that the amount of increase it needs to scale up to 2 pods is larger than double, which is not and ideal solution.
an algorithmic solution could be by introducing a new variable **scaleDownThreshold** defined by the user  as follows:
```
// check if currentMetricValue is above desiredMetricValue, if it is scale up as usual
if (currentMetricValue > desiredMetricValue) {
  desiredMetricValue = ceil[(currentReplicas * currentMetricValue) / desiredReplicas]
  ... scale up ...
} else {
  // otherwise check if the difference between them is above or below scale down threshold
  currentDiff = desiredMetricValue - currentMetricValue
  // using floor instead of ceil -- scale down only if difference is larger otherwise do nothing
  if (currentDiff > scaleDownThreshold) {
    desiredMetricValue = floor[(currentReplicas * currentMetricValue) / desiredReplicas]
    ... scale down ...
  }
}
```

### for now its better to stick to CPU metric and make sure currentMetricValue at idle is at most half desiredMetricValue.
### currentMetricValue * 2 =< desiredMetricValue

**Comment by coding-bunny** [comment]
> > This is also an issue for us with the HPA when using 2 metrics. With the memory added to our HPA, we do see that the downscaling works, but at some point the downscaling stops, even through all reported metrics are below the configured threshold for the averageUtilization.
> > ![Screenshot 2022-06-22 at 17 19 19](https://user-images.githubusercontent.com/726661/175071535-dccc6e81-3de9-4a5c-8fa8-2b9f3f9dc511.png)
> > We haven't tried setting the threshold to double the expected size to see if this makes a difference. The HPA does downscale, but only up to a certain point.
> 
> OT - which dashboard is that?

ArgoCD from our private clusters

**Comment by otakuinside** [comment]
Based on my experience, the key factor is that the metric is based on the Requested, not the Limit. Then, the condition to match is the Usage vs Request and the scale criteria.
On the other side, if you have 2 replicas, the required condition to scaleDown to 1 is that both replicas are 49%, so if it scales, the single one replica remaining would allocate 98% (49% on its side + 49% on the Terminated scaledDown pod). If Usage is not under 50% then an scaleDown trigger would cause the only single remaining pod to handle more than 100% of usage, which would immediately cause and scaleUp condition (which would be a riduculous loop :p).
If you have 3 pods instead of 2, the % change from 50% to 66% but the underlying analysis remains.

**Comment by jimethn** [comment]
Seeing this in kubernetes 1.21 when using custom metrics. The metric drops below target and the HPA responds by scaling up.

```
  Type    Reason             Age                   From                       Message
  ----    ------             ----                  ----                       -------
  Normal  SuccessfulRescale  5m52s (x49 over 15h)  horizontal-pod-autoscaler  New size: 4; reason: Service metric cortex_query_scheduler_queue_length above target
  Normal  SuccessfulRescale  2m20s (x34 over 9h)   horizontal-pod-autoscaler  New size: 8; reason: All metrics below target
```

**Comment by ismashal** [comment]
I facing the same issue Scale down not working for me 

NAME                                       READY   STATUS    RESTARTS   AGE
pod/device-service-78668474b5-fwd75        1/1     Running   0          156m
pod/device-service-78668474b5-g9cvg        1/1     Running   0          89m
pod/device-service-78668474b5-hz79v        1/1     Running   0          37m

NAME                                                 REFERENCE                   TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/device-service   Deployment/device-service   33%/40%, 0%/70%   1         3         3          3h46m

**Comment by MarkAndersonTrocme** [comment]
Having the same issues with some HPA in 1.21 using API `autoscaling/v1`. Can anyone confirm if this is working better with `autoscaling/v2`?

**Comment by h0jeZvgoxFepBQ2C** [comment]
/remove-lifecycle rotten

this is still a valid issue

**Comment by h0jeZvgoxFepBQ2C** [comment]
Could someone reopen this issue?

**Comment by coding-bunny** [comment]
Yeah, this issue needs to be reopened as this is a blocker for using memory HPA in Kubernetes.

**Comment by dani-newman** [comment]
Any news?

**Comment by h0jeZvgoxFepBQ2C** [comment]
@liggitt @wojtek-t @pohly @smarterclayton Could anyone of you reopen this issue maybe?

**Comment by nicon89** [comment]
Is there any update on this?

**Comment by WFA-hhsieh** [comment]
@markandersontrocme Still got same issue on Kubernetes 1.24 with `autoscaling/v2`.

**Comment by max-rocket-internet** [comment]
So much has changed in Kubernetes since I opened this issue but I guess some things never change: I have this issue again 😅

**Comment by max-rocket-internet** [comment]
It seems some others also have the same problem. Rather than reopen an old issue with tonnes of comments I've created a new one to start fresh with `autoscaling/v2`: https://github.com/kubernetes/kubernetes/issues/120875
