### ISSUE TITLE
Dangling volume mechanism for CSI does not exist

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#80488]
The dangling volume mechanism we currently use for recovering volumes that are incorrectly attached will not work for CSI.

This mechanism is in use by Cinder and EBS drivers at present - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L338 and solves real issues where a volume may be erroneously attached to the node. 

In past building exact state of the world after controller-manager recovers from a crash was kinda not very precise which results in bugs like this. I am wondering if for CSI we should be able to use `VolumeAttachment` objects to rebuild the state and workaround/fix problems like this.

/sig storage

cc @jsafrane @msau42 @jingxu97 @davidz627

**Comment by davidz627** [comment]
@gnufied can you permalink a line number? I think things have shifted in master and I can't tell what you're referring to

**Comment by gnufied** [comment]
https://github.com/kubernetes/kubernetes/blob/c68eeb230af92ea834eff70ba84c79e1c4c42dd9/pkg/volume/util/operationexecutor/operation_generator.go#L365

**Comment by leakingtapan** [comment]
@gnufied to help me better understand the problem, do you have some step to reproduce this issue using in-tree?

**Comment by gnufied** [comment]
@leakingtapan see linked issue above.

**Comment by andyzhangx** [comment]
@gnufied could you point out where is the fix for Cinder and EBS drivers? is it possible for cloud provider driver to use the same fix? Thanks.

**Comment by gnufied** [comment]
@andyzhangx here is the code for returning `DanglingError` from AWS - https://github.com/kubernetes/kubernetes/blob/f4e39afea082afac7bf6f6936c34e012b7cb3c25/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L2550

Here is Openstack/Cinder implementation - https://github.com/kubernetes/kubernetes/blob/f4e39afea082afac7bf6f6936c34e012b7cb3c25/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L357

You just need to return this error when `AttachDisk` is called on a node and disk is attached to some other node at that point. That will cause volume to be added to ASOW in "uncertain" state and if there is no pod that is using the volume, it will get detached.

**Comment by andyzhangx** [comment]
@gnufied thanks a lot, I will try to do the same fix in azure disk driver.

**Comment by andyzhangx** [comment]
@gnufied any progress to make this feature into CSI driver?

**Comment by stoyanr** [comment]
@gnufied @andyzhangx is there any update on this issue? Is the corresponding feature already available in the CSI controller, or any plans about it?

**Comment by gnufied** [comment]
@stoyanr as far as I know  CSI controllers don't support this mechanism yet. I haven't yet thought about how this is going to look like. It can be implemented using `VolumeAttachment` API type that now exists for tracking volume attachments or can be implemented using `LIST_VOLUME` RPC call that was introduced in CSI.

**Comment by stoyanr** [comment]
@gnufied So, even if CSI drivers return `DanglingError` as mentioned above, this wouldn't work, correct? What could we do to raise the priority of the corresponding CSI controller implementation? We saw this issue rather frequently in the past particularly on Azure with the in-tree controllers, then it was fixed with #81266. We planned to enable CSI drivers by default on Azure with 1.19 but are now a bit afraid to do so due to this issue.

**Comment by rfranzke** [comment]
cc @andyzhangx

**Comment by msau42** [comment]
cc @misterikkit @yuga711 have been investigating some dangling attach problems

**Comment by misterikkit** [comment]
I was reading the CSI spec earlier this week and realized that the underlying concept is already there. We could implement CSI dangling attach purely in kubernetes using external-attacher and VolumeAttachment.status.

Any driver advertising the `LIST_VOLUMES_PUBLISHED_NODES` capability MUST include attached nodes in the `ListVolumesResponse`. [ref](https://github.com/container-storage-interface/spec/blob/baa71a34651e5ee6cb983b39c03097d7aa384278/csi.proto#L846-L856)


The alpha method `ControllerGetVolume` MUST return attached nodes if the driver has the `PUBLISH_UNPUBLISH_VOLUME` capability. [ref](https://github.com/container-storage-interface/spec/blob/baa71a34651e5ee6cb983b39c03097d7aa384278/csi.proto#L897-L904)

This seems like a stricter requirement that, when GA, will make dangling attach more reliable.

**Comment by misterikkit** [comment]
On a different note, @gnufied original comment on this issue is that `VolumeAttachment` may solve this problem. I think that may be true, as long as we add finalizers, etc. in the correct order. The leading cause of dangling attach errors has been when AttachDetachController restarts, losing internal state, or when RPCs to the service provider fail at the client end.

With CSI, the `VolumeAttachment` is like a forced checkpoint saved into etcd, such that we do not lose track of attach/detach requests in progress.

**Comment by msau42** [comment]
@andyzhangx have you been able to root cause why azure hits the dangling attach problem frequently? Is Azure returning success for detach when it's not actually successful?

@misterikkit and @yuga711 found a problem with AD controller where if AD controller restarts after we issue the attach call but before it completes, AND the pod gets deleted in that time, then we will have a dangling attach problem. This should be relatively easy to fix with CSI because we have the VolumeAttachment object as our record of starting an attach operation. But this doesn't solve the problem if the driver is returning successful detach when it's actually not.

**Comment by andyzhangx** [comment]
> AD controller where if AD controller

@msau42 I am not 100% on the root cause, there could be Azure Resource Provider issue, e.g. detach operation is preempted by other operations; or after a few retry on detach disk, it aborted while pod was removed from the node finally. What's  `AD controller`? do you have the issue link? thanks.

**Comment by andyzhangx** [comment]
BTW, I have implemented a simple fix on dangling issue, it triggers detach directly inside Azure Disk CSI driver v0.9.0: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/499,  it's not a perfect solution, while it basically solves the problem.

**Comment by msau42** [comment]
> there could be Azure Resource Provider issue, e.g. detach operation is preempted by other operations; or after a few retry on detach disk, it aborted while pod was removed from the node finally.

In these scenarios, the csi driver shouldn't return success until it's been actually confirmed by the cloud control plane right? Or if we call detach on a disk that's already detached, then the driver should also return success.

> What's AD controller? do you have the issue link?
AD controller = Attach Detach controller. 
@misterikkit @yuga711 do you want to open an issue for the race you found?

For these dangling attach scenarios, it would be good to figure out that actual root cause of how we get into this state and fix that, instead of treating the symptom.

**Comment by yuga711** [comment]
> > @misterikkit @yuga711 do you want to open an issue for the race you found?
Created the [bug](https://github.com/kubernetes/kubernetes/issues/94912).

**Comment by erismaster** [comment]
@gnufied @yuga711 I am going to remove the milestone v1.20 from this issue. Please milestone this issue to v1.21 if the issue will be resolved in the next release. Thanks! 

/milestone clear

**Comment by Jiawei0227** [comment]
@gnufied @yuga711 Do you guys think there are still remaining tasks/design needed for this one?

**Comment by yuga711** [comment]
The patch (https://github.com/kubernetes/kubernetes/pull/96617) would recover dangling attaches due to certain races. 

The additional work that may need here is rely on plugin detection mechanism. That is, the CSI drivers will detect and return error code (Volume published to another node | 9 FAILED_PRECONDITION) as per the CSI spec. The attach() in the ADC will update its ASW accordingly to trigger detach from the undesired node.

**Comment by msau42** [comment]
Does #96617 cover all the dangling attach root causes that we've seen, or are there more scenarios where we can still hit dangling attach issues?

**Comment by yuga711** [comment]
PR https://github.com/kubernetes/kubernetes/pull/96617 would fix race scenarios where ADC was restarted while the attach() or detach() were in-progress. It won't solve cases where there are potential bugs in the plugins. For example: return success or failure incorrectly during detach or attach.

**Comment by msau42** [comment]
I guess the question is if it's a bug in the plugin, could it have been avoided/fixed in the first place?

**Comment by gnufied** [comment]
I do not think https://github.com/kubernetes/kubernetes/pull/96617 addresses all cases. For example - in vsphere intree driver we saw a bug where a VM can become unavailable because of HA issue and when that happens a detach from that VM succeeds with a no-op but even after VM becomes available no detach ever gets performed because ADC assumes volume was detached.

The intree dangling volume handling mechanism handles such cases and recovers correctly from this and retries detach operation.

One may think of that as a corner case but I am not sure. As I mentioned in - https://github.com/kubernetes/kubernetes/pull/96617#issuecomment-728295780 , CSI has explicit error for volumes that are published to different node:

> Volume published to another node | 9 FAILED_PRECONDITION | Indicates that a volume corresponding to the specified volume_id has already been published at another node and does not have MULTI_NODE volume capability. If this error code is returned, the Plugin SHOULD specify the node_id of the node at which the volume is published as part of the gRPC status.message. | Caller SHOULD ensure the specified volume is not published at any other node before retrying with exponential back off. |

We could use this as well to fix dangling volumes I think.

**Comment by Jiawei0227** [comment]
After syncing with @gnufied offline, here is the info I understand:

Our final goal is that we have a correct CSI dangling volume mechanism that can handles the dangling volumes correctly. This dangling volume mechanism already exists in the in-tree plugin for openstack, aws, azuredisk, vsphere. But not gce-pd. The dangling issue will happen by design, so that means the issue still exists in the in-tree for gce at least.

For out-of-tree(CSI) model, there are two aspects:
1. On the CSI driver side: 
 > Volume published to another node | 9 FAILED_PRECONDITION | Indicates that a volume corresponding to the specified volume_id has already been published at another node and does not have MULTI_NODE volume capability. If this error code is returned, the Plugin SHOULD specify the node_id of the node at which the volume is published as part of the gRPC status.message. | Caller SHOULD ensure the specified volume is not published at any other node before retrying with exponential back off. |

According to CSI spec, we have the error code designed for CSI driver to implement. So if the CSI driver when doing ControllerPublishVolume call, find there is a dangling attachment issue for the volume, it should implement the mechanism to return this error.

2. On the Kubernetes side:
For csi-attacher, if we get the dangling attach error from ControllerPublishVolumeResponse, we need to design and implement how we cope with it.

**Comment by Jiawei0227** [comment]
So I think moving forward, we need to think about these three questions:
1. For in-tree gce-pd, do we still want to implement the dangling attach handling?
2. For each CSI driver, they have to make sure they implement the dangling attach error code in ControllerPublishVolume
3. For csi-attacher, we need to design and implement how we handle the dangling attach error returned from the CSI ControllerPublishVolumeResponse

**Comment by yuga711** [comment]
I think the CSI plugin (CSI attacher) can handle the FAILED_PRECONDITION similar to some current intree plugins. That is, on this failure, add the volume to ASW as "uncertain" attachment.

**Comment by msau42** [comment]
The situation where a plugin returns detach was successful when it was not is problematic and may be difficult to solve. I think it's really a bug that needs to be fixed by the csi driver/cloud provider. When Detach returns success, the VolumeAttachment object gets deleted. So we have no object anymore to tell the driver to detach again.

**Comment by yuga711** [comment]
When VA is gone leaving the dangling attach, the fix https://github.com/kubernetes/kubernetes/pull/96617 won't recover. But, if the driver implements FAILED_PRECONDITION error, the subsequent attach will add the dangling attach to ASW which will be detached when this attachment is undesired. So, I think the above issue will be solved.

**Comment by msau42** [comment]
Adding it to ASW will invoke Detach which will immediately succeed because there's no VolumeAttachment object. Anyway, I think we need to come up with a more detailed design on the flow between components and objects.

**Comment by Jiawei0227** [comment]
https://docs.google.com/document/d/1fEpM1s8qEU6pZvDh9NMsLug606NB5b2qP2GPdX3O_F8/edit

CSI Migration design doc by @yuga711

**Comment by andyzhangx** [comment]
any update on this issue? Thanks.
