### ISSUE TITLE
Many links in API documentation broken

### ISSUE THREAD

**Issue by damemi** [kubernetes/kubernetes#81526]
**What happened**:
There are many spots in API comments that are broken (pointing to https://git.k8s.io/community/contributors/devel/api-conventions.md). One example is here: https://github.com/kubernetes/api/blob/master/core/v1/types.go#L3491, a quick search for that URL currently shows [84 results on github](https://github.com/kubernetes/api/search?q=https%3A%2F%2Fgit.k8s.io%2Fcommunity%2Fcontributors%2Fdevel%2Fapi-conventions.md&unscoped_q=https%3A%2F%2Fgit.k8s.io%2Fcommunity%2Fcontributors%2Fdevel%2Fapi-conventions.md) (however this is obviously including generated files too)

These lead to broken user-facing doc links, such as in `oc explain` in OpenShift

**What you expected to happen**:
I'm assuming these are supposed to be updated to https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md

**Comment by damemi** [comment]
/assign @damemi 
I plan to fix as this should be easy enough. I'm just opening this to track it, since I haven't been able to fetch or push to k8s repos all day. If someone else can then feel free to take

**Comment by liggitt** [comment]
Being fixed in https://github.com/kubernetes/kubernetes/pull/74245

**Comment by Sai-Adarsh** [comment]
Stale issue? Still open to contribution?

**Comment by liggitt** [comment]
Yes, https://github.com/kubernetes/kubernetes/pull/74245 seems to have stalled. If you want to start with that PR, fixup the verify failures with a second commit of your own, and open a new PR, that would be great

**Comment by Ojaswy** [comment]
Hello I am new to this and I want to contribute. How can I help with this issue?

**Comment by damemi** [comment]
Hi @Ojaswy, if you look through the linked PRs (or search the codebase for the incorrect URL) you should find places where the url is still wrong. A lot of the locations I originally pointed out have been fixed with 1.16, but I think there may still be more. If you make your changes, open a pull request and link it to this issue.

**Comment by luigizhou** [comment]
Hi, is this still stalled? 
I would like to try and contribute if it's ok

**Comment by hk1997** [comment]
Hi,
I would like to contribute to this. Is it still stalled?

**Comment by liggitt** [comment]
this is still available for someone to pick up. comment here when you start working on a PR. the approach in https://github.com/kubernetes/kubernetes/pull/74245 would be a reasonable starting point (though starting from latest master might be easier)

**Comment by incidrthreat** [comment]
I'd like to assist/contribute to this issue if still an option. But before I do and so I'm tracking this correctly--urls are missing the `sig-architecture` portion and will need it added in?  If so, the referenced search shows all urls fixed.

**Comment by damemi** [comment]
It does look like these URLs were fixed in the latest version of kube. For that reason, I'm going to close this issue, but if anyone finds more of these URLs that are wrong feel free to reopen/reference this issue for tracking.
/close
