### ISSUE TITLE
[Flaky Test] verify-master (ci-kubernetes-verify-master)

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#87807]
**Which jobs are failing**:
`verify-master (ci-kubernetes-verify-master) `

**Since when has it been failing**:
`4th Feb 19:53 PST`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#verify-master

**Reason for failure**:
```console
 I0204 09:12:04.373746    2848 parse.go:432] type checker: /usr/local/go/src/runtime/panic.go:292:34: cannot use (_defer literal) (value of type _defer) as unsafe.ArbitraryType value in argument to unsafe.Sizeof
I0204 09:12:04.373793    2848 parse.go:432] type checker: /usr/local/go/src/runtime/panic.go:292:20: unsafe.Sizeof((_defer literal)) (value of type uintptr) is not constant
I0204 09:12:04.381637    2848 parse.go:432] type checker: /usr/local/go/src/runtime/sema.go:51:45: cannot use (semaRoot literal) (value of type semaRoot) as unsafe.ArbitraryType value in argument to unsafe.Sizeof
I0204 09:12:04.381691    2848 parse.go:432] type checker: /usr/local/go/src/runtime/sema.go:51:8: array length cpu.CacheLinePadSize - unsafe.Sizeof((semaRoot literal)) (value of type uintptr) must be constant
I0204 09:12:04.391416    2848 parse.go:432] type checker: /usr/local/go/src/runtime/time.go:53:44: cannot use (timersBucket literal) (value of type timersBucket) as unsafe.ArbitraryType value in argument to unsafe.Sizeof
I0204 09:12:04.391556    2848 parse.go:432] type checker: /usr/local/go/src/runtime/time.go:53:7: array length cpu.CacheLinePadSize - unsafe.Sizeof((timersBucket literal)) % cpu.CacheLinePadSize (value of type uintptr) must be constant
I0204 09:12:04.391932    2848 parse.go:432] type checker: /usr/local/go/src/runtime/trace.go:159:30: cannot use (traceBufHeader literal) (value of type traceBufHeader) as unsafe.ArbitraryType value in argument to unsafe.Sizeof 
```

**Anything else we need to know**:
/cc @kubernetes/ci-signal 
/cc @kubernetes/release-managers 

/sig testing
/priority critical-urgent
/milestone v1.18

**Comment by liggitt** [comment]
The type checker warnings are a red herring. They exist even in successful runs.

The failed jobs are timing out at 2 hours.

**Comment by liggitt** [comment]
looking at https://testgrid.k8s.io/sig-release-master-blocking#verify-master&graph-metrics=test-duration-minutes&width=5, it looks like this started happening around 1/23, then frequently around 1/28

**Comment by liggitt** [comment]
The graphs on individual tests don't reveal a lot... variance seems to have increased across the board over the last couple weeks... did something dramatic change on the machines where we run these tests?

**Comment by droslean** [comment]
Jon is now green. Closing...
/close

**Comment by alejandrox1** [comment]
/reopen
This seems to be happening somewhat often

**Comment by alejandrox1** [comment]
Possible duplicate of https://github.com/kubernetes/kubernetes/issues/89052
/close

**Comment by alejandrox1** [comment]
/reopen
closed prematurly, https://github.com/kubernetes/kubernetes/issues/89052 s strictly for 1.18
Failures seem very much related but just to make sure gonna keep this one open to track verify failures in master.
/milestone v1.19

**Comment by droslean** [comment]
/retitle [Flaky Test] verify-master (ci-kubernetes-verify-master) 
/remove-kind failing-test
/kind flake

**Comment by hasheddan** [comment]
@alejandrox1 is this still under investigation? Looks pretty green as of late :)

**Comment by hasheddan** [comment]
This has been flaking quite a bit as of late as noted in #90538. @RobertKielty could you investigate the history and root cause here?

**Comment by liggitt** [comment]
https://testgrid.k8s.io/google-unit#verify-master&graph-metrics=test-duration-minutes&width=20 might be helpful in pinning down specific problematic tests

The following tests stand out as taking a really long time for what they do and/or having a high degree of variance
* verify.generated-files-remake  (10-35 minutes)
* verify.generated-kubelet-plugin-registration (3-10 minutes)
* verify.no-vendor-cycles (3-9 minutes)

**Comment by RobertKielty** [comment]
My initial reading is that when the overall job duration spikes, all the tests are spiking pointing to possible resource contention where the job is run. 

Sometimes for duration spike jobs there are missing results for some of the tests so presumably they are timing out and not failing? 

Next step here would be for me to investigate to see if there is an hour-of-day to job duration spike correlation.

**Comment by BenTheElder** [comment]
here `staticcheck` flaked, IIRC this particular check ("unused") is known to be potentially flaky wrt _test imports https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/90400/pull-kubernetes-verify/1255118096859926529

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/issues/89052#issuecomment-599803604

last time this was resolved by raising the size of the build cluster, and/or raising CPU request, though I suspect that wasn't the actual resource being contended

looks like we're back to not knowing what resource is contended

**Comment by spiffxp** [comment]
you can see it happens to verify across branches, so I doubt it's the introduction of anything particularly new to verify
- https://testgrid.k8s.io/google-unit#verify-master&graph-metrics=test-duration-minutes&width=5
- https://testgrid.k8s.io/google-unit#verify-1.18&graph-metrics=test-duration-minutes&width=5
- https://testgrid.k8s.io/google-unit#verify-1.17&graph-metrics=test-duration-minutes&width=5
- https://testgrid.k8s.io/google-unit#verify-1.16&graph-metrics=test-duration-minutes&width=5

**Comment by RobertKielty** [comment]
Thanks @BenTheElder and @spiffxp I'll do some work on this tomorrow.

**Comment by BenTheElder** [comment]
might be worth seeing if staticheck has a mitigation for this in a newer
version or discussing disabling that check

**Comment by hasheddan** [comment]
Looks like we are still seeing timeouts here every 10 or so runs

**Comment by BenTheElder** [comment]
This one _is_ SIG Testing :upside_down_face: 
Staticcheck is being updated and the typechecker tool in-tree is being rewritten. #92253

**Comment by liggitt** [comment]
is there a plan for resolving this? the verify job munges together lots of unrelated verify tasks, some of which seem to take much more time than I would expect

https://testgrid.k8s.io/sig-release-master-blocking#verify-master&width=5&graph-metrics=test-duration-minutes

I think individual issues with owners assigned will be more effective here. I'd suggest:
* sig-node: generated-kubelet-plugin-registration and generated-device-plugin just regenerate proto files for a couple packages, but consistently take twice as long as generated-protobuf which generates proto files for ~40 packages
* sig-cli: cli-conventions takes two minutes, which seems excessive for what it is doing
* code-organization: no-vendor-cycles taking 4 minutes seems excessively long considering verify-vendor rebuilds the whole vendor tree in 2 minutes
* sig-testing: typecheck-dockerless and typecheck take wildly varying amounts of time ... might be a resource constraint issue ... issue for sig-testing to look into the CPU assigned to the job?
* sig-api-machinery/sttts: generated-files-remake takes 10-20 minutes which seems like **way** too long... investigate ways to speed that up or avoid duplicate work?

**Comment by hasheddan** [comment]
@liggitt I will get those issues opened. I feel like they can likely all be bumped to the v1.20 milestone, would you agree?

**Comment by liggitt** [comment]
yes, though it should be made clear that the issues are very impactful to all contributors on a regular bases

**Comment by hasheddan** [comment]
@liggitt understood 👍 I will prioritize investigating this

/milestone v1.20

**Comment by liggitt** [comment]
> sig-node: generated-kubelet-plugin-registration and generated-device-plugin just regenerate proto files for a couple packages, but consistently take twice as long as generated-protobuf which generates proto files for ~40 packages

opened https://github.com/kubernetes/kubernetes/pull/93633

**Comment by spiffxp** [comment]
Does this still warrant `priority/critical-urgent`?
![Screen Shot 2020-11-20 at 5 49 59 PM](https://user-images.githubusercontent.com/49258/99857270-d83e2580-2b58-11eb-8326-bbbb3d58913d.png)

I would suggest closing this out; no activity in 90+ days
