### ISSUE TITLE
Conformance image v1.18.0 fails on arm64

### ISSUE THREAD

**Issue by erikwilson** [kubernetes/kubernetes#89554]
**What happened**:
`gcr.io/google-containers/conformance:v1.18.0` produces an error:
```
standard_init_linux.go:211: exec user process caused "exec format error"
```

**What you expected to happen**:
Conformance tests should be launched. Examining image contents indicates executables are of the correct architecture.

**How to reproduce it (as minimally and precisely as possible)**:
From aarch64 machine:
```
docker run --rm -it --entrypoint bash gcr.io/google-containers/conformance:v1.18.0 -c "echo ok"
```

**Anything else we need to know?**:
Works with v1.17.4:
```
# docker run --rm -it --entrypoint bash gcr.io/google-containers/conformance:v1.17.4 -c "echo ok"
ok
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0+k3s-5fe1f025", GitCommit:"5fe1f02592397c8a199b898113eb3e798905e918", GitTreeState:"clean", BuildDate:"2020-03-26T23:02:16Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0+k3s-5fe1f025", GitCommit:"5fe1f02592397c8a199b898113eb3e798905e918", GitTreeState:"clean", BuildDate:"2020-03-26T23:02:16Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/arm64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
Ubuntu 18.04.3 LTS
```
- Kernel (e.g. `uname -a`):
```
Linux ip-172-31-17-16 4.15.0-1054-aws #56-Ubuntu SMP Thu Nov 7 16:18:50 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by cjellick** [comment]
@liggitt any thoughts on this issue at all? We use this to test K3d and are blocked on releasing anything in the 1.18 line because of it.

**Comment by liggitt** [comment]
I don't have expertise in the image release pipeline, I'd suggest reaching out to @kubernetes/sig-release

**Comment by BenTheElder** [comment]
@johnSchnake @dims

**Comment by lubinsz** [comment]
Hi @erikwilson ，
Did you run this test in an arm64 virtual machine?
If so, I have fixed this issue in cadvisor side.

This issue is caused by google/cadvisor.
Currently, the version of cadvisor in kubernetes is  v0.36.1-0.20200323171535-8af10c683a96.
There is a bug in this version, it get the wrong machine info on Arm64 guest.

I have delivered the PR into cadvisor in 22 days ago. And this patch was merged in 10 days ago.
Please see my pr as reference: https://github.com/google/cadvisor/pull/2456

Currently, I'm waiting for a new tag of cadvisor, so that I can use this new tag in kubernetes and fix this issue in k8s side.
Please see my issue:
https://github.com/google/cadvisor/issues/2500

Thanks.

**Comment by lubinsz** [comment]
Currently we only have one conformance test is alive, this conformance test was run on AWS：
https://k8s-testgrid.appspot.com/conformance-arm#Periodic%20Arm64%20conformance%20test%20on%20AWS

**Comment by erikwilson** [comment]
Thanks for taking a look @lubinsz, just to be sure it is not a VM issue I fired up an a1-metal arm64 aws instance. Please note I am using sonobuoy for running tests rather than kubetest, I tried to find if kubetest is using the conformance image for testing and from a quick check maybe not. The error is not in the conformance test itself, but launching the conformance test image on arm64.

The `docker --version` is `19.03.8, build afacb8b`. Tried again with with 1.18.2 and got the same error:
```
# docker run --rm -it --entrypoint bash gcr.io/google-containers/conformance:v1.18.2 -c "echo ok"
standard_init_linux.go:211: exec user process caused "exec format error"
```
still works ok for the v1.17 branch:
```
# docker run --rm -it --entrypoint bash gcr.io/google-containers/conformance:v1.17.5 -c "echo ok"
ok
```

It looks like the build chain for images has changed:
```
$ manifest-tool inspect gcr.io/google-containers/conformance-arm64:v1.17.5
gcr.io/google-containers/conformance-arm64:v1.17.5: manifest type: application/vnd.docker.distribution.manifest.v2+json
      Digest: sha256:28c552f98f8782822a0011677ec17a441338e31de7423d760eb8bf01035406bb
Architecture: amd64
          OS: linux
    # Layers: 13
      layer 1: digest = sha256:9eaa7f24d84945e440e52b373346bad450201aa9675ef184d1cf0ad67108e47d
      layer 2: digest = sha256:9be8935edc7b9fa048cbd1a00ed6d460a3fd4b0711b4217878a685c784b2a793
      layer 3: digest = sha256:717a23677156d910c393baecfb7ebead10e4b26a15853847ed4098c5abae2264
      layer 4: digest = sha256:401936c1e26bc5d9fe960f983adf2d5880d665c206477b1228b06ed0a23ccf92
      layer 5: digest = sha256:cc18490b88c366b49d3815bc312d360606f8714d8eaf263767abeb987f37c7b8
      layer 6: digest = sha256:9774a123cd8c073b1e0d842ac4a6e910238d76dd37fa34f3ad943564bd378172
      layer 7: digest = sha256:477d861f083c67b74f28713e954b44b37525e47758b83ef0b08641bf0f9cea8a
      layer 8: digest = sha256:7a4b2319f1ba65ea934130d98c590ce457802623ddbe1ccf985058ee16571f90
      layer 9: digest = sha256:1dd30069b67d20b8cdf6a62c846576fb8d957dd8f1f60d76449f954aa893434a
      layer 10: digest = sha256:493d9e4471f4ebdf9b1b25664928bb57bae15a2853e2e5879a10712ba6833cf9
      layer 11: digest = sha256:6b9d67f9bc67ab6843acb7e30dba31ba2f96b24c66b4195f22372b89355e6ce1
      layer 12: digest = sha256:04e062855c3250a44cda808d8df97dbbd6b2e967cd73a2608c89cc08377895c8
      layer 13: digest = sha256:6e61688fe9eeb5506c9db14a492f753da46652c5145d4f9a29b542e2eba49860
```

```
$ manifest-tool inspect gcr.io/google-containers/conformance-arm64:v1.18.2
gcr.io/google-containers/conformance-arm64:v1.18.2: manifest type: application/vnd.docker.distribution.manifest.v2+json
      Digest: sha256:f3182737369625e9a66232eed9851fe4bfe757b7775a5e7d778bcf34f8694699
Architecture: amd64
          OS: linux
    # Layers: 7
      layer 1: digest = sha256:5e35bd43cf7898d036f8515be74d45b2e3abd2a5534fc280de63a9c22dd175bd
      layer 2: digest = sha256:5f8ad54c1ca94ff61cd0ae4a49ee3e2583218460aa112c5e1db2ad470d4fae25
      layer 3: digest = sha256:d6d7389259d48bcef13cadfe180c2446d9d044406d852869d4dc040b4915b44e
      layer 4: digest = sha256:206ef2f1b1a7bdade11d441123a19beb69253de80ae36dc3a835559a85cda798
      layer 5: digest = sha256:330ecaf54ad67f2da66deb9d9abbd267baea8e0cca170580e83031b372bd1143
      layer 6: digest = sha256:e719cefb54f06957b4718738e9e5819fe308c8ca9c727430667b967fe6b11ea6
      layer 7: digest = sha256:a9ab47012e1328866b7fbe731aa6ef0c957927f5ca506a67007017fd134cd7c3
```

So there are now six less layers of the conformance image for the 1.18 branch.

Please also note how the arm64 images show **amd64** as the architecture for both branches. This has been problematic for trying to air-gap arm64 properly and is a systemic issue for many of the projects on gcr (and elsewhere).

**Comment by lubinsz** [comment]
Hi @erikwilson 
I see. I'll check it.
Thanks.

**Comment by dirkmueller** [comment]
/reopen

This issue is still unfixed as of today. here is a reproducer that helps doing the reverse test on a x86_64 machine:

> # uname -m
x86_64
> # podman pull gcr.io/google-containers/conformance-arm64:v1.17.7
> # podman run 66652b9ed7f16a9bc848038ddb00159f3e2d22d8c2bb1ba050913309daf101c9  cat /etc/os-release
standard_init_linux.go:211: exec user process caused "exec format error"

So this is an image where the base os is actually arm64. starting with v1.18.0 and still as of today (v1.18.5-rc.0 and v1.19.0-beta.2) the uploaded -arm64 image is actually an *amd64* image. There must be a typo somewhere. 

testable this way: 

```sh

$ podman pull gcr.io/google-containers/conformance-arm64:v1.19.0-beta.
...
$ man run 073f5eae3b09e0c8a221519af5ace0c11c4de707cd3c77616e0d35c058b87b5f  cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

This is supposed to generate the 'exec file error', but it doesn't, which indicates that it is actually an x86_64 image (amd64).

**Comment by BenTheElder** [comment]
IIRC the fix was reverted due to not working in the release pipeline.
I did say that would hurt @cpanato  @justaugustus :upside_down_face: 
https://github.com/kubernetes/kubernetes/pull/92042

**Comment by tjkirch** [comment]
/remove-lifecycle rotten

This is still blocking conformance testing on arm64, so I hope it can be considered open.

**Comment by chendave** [comment]
Looks like to me this is a very complicated issue which is related with GCB, Moby Buildkit, it's not easy for me to reproduce and some trouble shooting by myself since I am not able to access GCB.

Just wanna know is there any follow up to make this PR merge again? https://github.com/kubernetes/kubernetes/pull/90400, we do have some needs to run the conformance testing on ARM64 @cpanato @BenTheElder .

**Comment by BenTheElder** [comment]
SIG testing does not use this image (we prefer not to run the test runner as a pod given our clusters may be unreliable since we're testing changes and we want to avoid e.g. the pod being evicted => data loss), however this is currently used by the CNCF conformance program (which is CNCF / SIG arch) and sonobuoy (which is a vmware project).

A bunch of our images are shipping with buildkit / buildx currently at HEAD, something like number #90400 could probably be brought back if someone wanted to work on this.

Currently I'm not going to have time myself.

**Comment by dims** [comment]
cc @saschagrunert @jeremyrickard `"Architecture": "amd64"` for arm64 image :(

```
$ skopeo inspect docker://k8s.gcr.io/conformance-arm64:v1.20.1
{
    "Name": "k8s.gcr.io/conformance-arm64",
    "Digest": "sha256:7306ec659843ab1ebc4fedc6d319fe74f94d1a67f13b8eb213ac4ef4162a1c29",
    "RepoTags": [
        "v1.13.0",
        "v1.13.0-alpha.2",
        "v1.13.0-alpha.3",
        "v1.13.0-beta.0",
        "v1.13.0-beta.1",
        "v1.13.0-beta.2",
        "v1.13.0-rc.1",
        "v1.13.0-rc.2",
        "v1.13.1",
        "v1.13.1-beta.0",
        "v1.13.10",
        "v1.13.10-beta.0",
        "v1.13.11",
        "v1.13.11-beta.0",
        "v1.13.12",
        "v1.13.12-beta.0",
        "v1.13.13-beta.0",
        "v1.13.2",
        "v1.13.2-beta.0",
        "v1.13.3",
        "v1.13.3-beta.0",
        "v1.13.4",
        "v1.13.4-beta.0",
        "v1.13.5",
        "v1.13.5-beta.0",
        "v1.13.6",
        "v1.13.6-beta.0",
        "v1.13.7",
        "v1.13.7-beta.0",
        "v1.13.8",
        "v1.13.8-beta.0",
        "v1.13.9",
        "v1.13.9-beta.0",
        "v1.14.0",
        "v1.14.0-alpha.0",
        "v1.14.0-alpha.1",
        "v1.14.0-alpha.2",
        "v1.14.0-alpha.3",
        "v1.14.0-beta.0",
        "v1.14.0-beta.1",
        "v1.14.0-beta.2",
        "v1.14.0-rc.1",
        "v1.14.1",
        "v1.14.1-beta.0",
        "v1.14.10",
        "v1.14.10-beta.0",
        "v1.14.11-beta.0",
        "v1.14.2",
        "v1.14.2-beta.0",
        "v1.14.3",
        "v1.14.3-beta.0",
        "v1.14.4",
        "v1.14.4-beta.0",
        "v1.14.5",
        "v1.14.5-beta.0",
        "v1.14.6",
        "v1.14.6-beta.0",
        "v1.14.7",
        "v1.14.7-beta.0",
        "v1.14.8",
        "v1.14.8-beta.0",
        "v1.14.9",
        "v1.14.9-beta.0",
        "v1.15.0",
        "v1.15.0-alpha.0",
        "v1.15.0-alpha.1",
        "v1.15.0-alpha.2",
        "v1.15.0-alpha.3",
        "v1.15.0-beta.0",
        "v1.15.0-beta.1",
        "v1.15.0-beta.2",
        "v1.15.0-rc.1",
        "v1.15.1",
        "v1.15.1-beta.0",
        "v1.15.10",
        "v1.15.10-beta.0",
        "v1.15.11",
        "v1.15.11-beta.0",
        "v1.15.12",
        "v1.15.12-beta.0",
        "v1.15.13-beta.0",
        "v1.15.2",
        "v1.15.2-beta.0",
        "v1.15.3",
        "v1.15.3-beta.0",
        "v1.15.4",
        "v1.15.4-beta.0",
        "v1.15.5",
        "v1.15.5-beta.0",
        "v1.15.6",
        "v1.15.6-beta.0",
        "v1.15.7",
        "v1.15.7-beta.0",
        "v1.15.8",
        "v1.15.8-beta.0",
        "v1.15.9",
        "v1.15.9-beta.0",
        "v1.16.0",
        "v1.16.0-alpha.0",
        "v1.16.0-alpha.1",
        "v1.16.0-alpha.2",
        "v1.16.0-alpha.3",
        "v1.16.0-beta.0",
        "v1.16.0-beta.1",
        "v1.16.0-beta.2",
        "v1.16.0-rc.1",
        "v1.16.0-rc.2",
        "v1.16.1",
        "v1.16.1-beta.0",
        "v1.16.10",
        "v1.16.10-beta.0",
        "v1.16.11",
        "v1.16.11-rc.0",
        "v1.16.12",
        "v1.16.12-rc.0",
        "v1.16.12-rc.1",
        "v1.16.13",
        "v1.16.13-rc.0",
        "v1.16.14",
        "v1.16.14-rc.0",
        "v1.16.15",
        "v1.16.15-rc.0",
        "v1.16.16-rc.0",
        "v1.16.2",
        "v1.16.2-beta.0",
        "v1.16.3",
        "v1.16.3-beta.0",
        "v1.16.4",
        "v1.16.4-beta.0",
        "v1.16.5",
        "v1.16.5-beta.0",
        "v1.16.6",
        "v1.16.6-beta.0",
        "v1.16.7",
        "v1.16.7-beta.0",
        "v1.16.8",
        "v1.16.8-beta.0",
        "v1.16.9",
        "v1.16.9-beta.0",
        "v1.17.0",
        "v1.17.0-alpha.0",
        "v1.17.0-alpha.1",
        "v1.17.0-alpha.2",
        "v1.17.0-alpha.3",
        "v1.17.0-beta.0",
        "v1.17.0-beta.1",
        "v1.17.0-beta.2",
        "v1.17.0-rc.1",
        "v1.17.0-rc.2",
        "v1.17.1",
        "v1.17.1-beta.0",
        "v1.17.10",
        "v1.17.10-rc.0",
        "v1.17.11",
        "v1.17.11-rc.0",
        "v1.17.12",
        "v1.17.12-rc.0",
        "v1.17.13",
        "v1.17.13-rc.0",
        "v1.17.14",
        "v1.17.14-rc.0",
        "v1.17.15",
        "v1.17.15-rc.0",
        "v1.17.16",
        "v1.17.16-rc.0",
        "v1.17.17-rc.0",
        "v1.17.2",
        "v1.17.2-beta.0",
        "v1.17.3",
        "v1.17.3-beta.0",
        "v1.17.4",
        "v1.17.4-beta.0",
        "v1.17.5",
        "v1.17.5-beta.0",
        "v1.17.6",
        "v1.17.6-beta.0",
        "v1.17.7",
        "v1.17.7-rc.0",
        "v1.17.8",
        "v1.17.8-rc.0",
        "v1.17.8-rc.1",
        "v1.17.9",
        "v1.17.9-rc.0",
        "v1.18.0",
        "v1.18.0-alpha.0",
        "v1.18.0-alpha.1",
        "v1.18.0-alpha.2",
        "v1.18.0-alpha.3",
        "v1.18.0-alpha.5",
        "v1.18.0-beta.0",
        "v1.18.0-beta.1",
        "v1.18.0-beta.2",
        "v1.18.0-rc.1",
        "v1.18.1",
        "v1.18.1-beta.0",
        "v1.18.10",
        "v1.18.10-rc.0",
        "v1.18.11",
        "v1.18.11-rc.0",
        "v1.18.12",
        "v1.18.12-rc.0",
        "v1.18.13",
        "v1.18.13-rc.0",
        "v1.18.14",
        "v1.18.14-rc.0",
        "v1.18.15-rc.0",
        "v1.18.2",
        "v1.18.2-beta.0",
        "v1.18.3",
        "v1.18.3-beta.0",
        "v1.18.4",
        "v1.18.4-rc.0",
        "v1.18.5",
        "v1.18.5-rc.0",
        "v1.18.5-rc.1",
        "v1.18.6",
        "v1.18.6-rc.0",
        "v1.18.7",
        "v1.18.7-rc.0",
        "v1.18.8",
        "v1.18.8-rc.0",
        "v1.18.9",
        "v1.18.9-rc.0",
        "v1.19.0",
        "v1.19.0-alpha.0",
        "v1.19.0-alpha.1",
        "v1.19.0-alpha.2",
        "v1.19.0-alpha.3",
        "v1.19.0-beta.0",
        "v1.19.0-beta.1",
        "v1.19.0-beta.2",
        "v1.19.0-rc.0",
        "v1.19.0-rc.1",
        "v1.19.0-rc.2",
        "v1.19.0-rc.3",
        "v1.19.0-rc.4",
        "v1.19.1",
        "v1.19.1-rc.0",
        "v1.19.2",
        "v1.19.2-rc.0",
        "v1.19.3",
        "v1.19.3-rc.0",
        "v1.19.4",
        "v1.19.4-rc.0",
        "v1.19.5",
        "v1.19.5-rc.0",
        "v1.19.6",
        "v1.19.6-rc.0",
        "v1.19.7-rc.0",
        "v1.20.0",
        "v1.20.0-alpha.0",
        "v1.20.0-alpha.1",
        "v1.20.0-alpha.2",
        "v1.20.0-alpha.3",
        "v1.20.0-beta.0",
        "v1.20.0-beta.1",
        "v1.20.0-beta.2",
        "v1.20.0-rc.0",
        "v1.20.1",
        "v1.20.1-rc.0",
        "v1.20.2-rc.0",
        "v1.21.0-alpha.0"
    ],
    "Created": "2020-12-18T12:21:56.322060348Z",
    "DockerVersion": "19.03.8",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:e50c3c9ef5a201a24959788dcbc7ebf88d95c63e132a4d7396ce541127afd88e",
        "sha256:937e27af3d2fdb0087505e910c740be994c288ca2ff010ddf5d99d9f846959ae",
        "sha256:581c6b2f307c79cf1014598753f9a7b7391a659651f2628127e7d1ff8fc54cf5",
        "sha256:f3f3577d4f4d7aaea048a0995305b73ca6964e34d7e9d03977d7548a4258a3cd",
        "sha256:88de1fef5a6321a226936731ead573a2f398ff3ed57084e65bbe85408a61706a",
        "sha256:de13b91402284e2d8ff91f4d73a84b7f56f933b87ff9edea3d5039058ac20aa5",
        "sha256:589e7197e2c8fe471190456cfa66e3cf3780689f1c203b416c3ce578cbc7bf1b"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "E2E_FOCUS=\\[Conformance\\]",
        "E2E_SKIP=",
        "E2E_PROVIDER=local",
        "E2E_PARALLEL=1",
        "E2E_VERBOSITY=4",
        "RESULTS_DIR=/tmp/results",
        "KUBECONFIG="
    ]
}
1
[5959:5958 - 0:2009] 12:53:05 [dims@bigbox:/dev/pts/2 +1] ~
$ skopeo inspect docker://k8s.gcr.io/conformance:v1.20.1
{
    "Name": "k8s.gcr.io/conformance",
    "Digest": "sha256:9f165f5d6393246eae4ea77cfc99d7f39b7475bd7650c72759d44f1f2cd3bafe",
    "RepoTags": [
        "v1.13.0",
        "v1.13.0-alpha.2",
        "v1.13.0-alpha.3",
        "v1.13.0-beta.0",
        "v1.13.0-beta.1",
        "v1.13.0-beta.2",
        "v1.13.0-rc.1",
        "v1.13.0-rc.2",
        "v1.13.1",
        "v1.13.1-beta.0",
        "v1.13.10",
        "v1.13.10-beta.0",
        "v1.13.11",
        "v1.13.11-beta.0",
        "v1.13.12",
        "v1.13.12-beta.0",
        "v1.13.13-beta.0",
        "v1.13.2",
        "v1.13.2-beta.0",
        "v1.13.3",
        "v1.13.3-beta.0",
        "v1.13.4",
        "v1.13.4-beta.0",
        "v1.13.5",
        "v1.13.5-beta.0",
        "v1.13.6",
        "v1.13.6-beta.0",
        "v1.13.7",
        "v1.13.7-beta.0",
        "v1.13.8",
        "v1.13.8-beta.0",
        "v1.13.9",
        "v1.13.9-beta.0",
        "v1.14.0",
        "v1.14.0-alpha.0",
        "v1.14.0-alpha.1",
        "v1.14.0-alpha.2",
        "v1.14.0-alpha.3",
        "v1.14.0-beta.0",
        "v1.14.0-beta.1",
        "v1.14.0-beta.2",
        "v1.14.0-rc.1",
        "v1.14.1",
        "v1.14.1-beta.0",
        "v1.14.10",
        "v1.14.10-beta.0",
        "v1.14.11-beta.0",
        "v1.14.2",
        "v1.14.2-beta.0",
        "v1.14.3",
        "v1.14.3-beta.0",
        "v1.14.4",
        "v1.14.4-beta.0",
        "v1.14.5",
        "v1.14.5-beta.0",
        "v1.14.6",
        "v1.14.6-beta.0",
        "v1.14.7",
        "v1.14.7-beta.0",
        "v1.14.8",
        "v1.14.8-beta.0",
        "v1.14.9",
        "v1.14.9-beta.0",
        "v1.15.0",
        "v1.15.0-alpha.0",
        "v1.15.0-alpha.1",
        "v1.15.0-alpha.2",
        "v1.15.0-alpha.3",
        "v1.15.0-beta.0",
        "v1.15.0-beta.1",
        "v1.15.0-beta.2",
        "v1.15.0-rc.1",
        "v1.15.1",
        "v1.15.1-beta.0",
        "v1.15.10",
        "v1.15.10-beta.0",
        "v1.15.11",
        "v1.15.11-beta.0",
        "v1.15.12",
        "v1.15.12-beta.0",
        "v1.15.13-beta.0",
        "v1.15.2",
        "v1.15.2-beta.0",
        "v1.15.3",
        "v1.15.3-beta.0",
        "v1.15.4",
        "v1.15.4-beta.0",
        "v1.15.5",
        "v1.15.5-beta.0",
        "v1.15.6",
        "v1.15.6-beta.0",
        "v1.15.7",
        "v1.15.7-beta.0",
        "v1.15.8",
        "v1.15.8-beta.0",
        "v1.15.9",
        "v1.15.9-beta.0",
        "v1.16.0",
        "v1.16.0-alpha.0",
        "v1.16.0-alpha.1",
        "v1.16.0-alpha.2",
        "v1.16.0-alpha.3",
        "v1.16.0-beta.0",
        "v1.16.0-beta.1",
        "v1.16.0-beta.2",
        "v1.16.0-rc.1",
        "v1.16.0-rc.2",
        "v1.16.1",
        "v1.16.1-beta.0",
        "v1.16.10",
        "v1.16.10-beta.0",
        "v1.16.11",
        "v1.16.11-rc.0",
        "v1.16.12",
        "v1.16.12-rc.0",
        "v1.16.12-rc.1",
        "v1.16.13",
        "v1.16.13-rc.0",
        "v1.16.14",
        "v1.16.14-rc.0",
        "v1.16.15",
        "v1.16.15-rc.0",
        "v1.16.16-rc.0",
        "v1.16.2",
        "v1.16.2-beta.0",
        "v1.16.3",
        "v1.16.3-beta.0",
        "v1.16.4",
        "v1.16.4-beta.0",
        "v1.16.5",
        "v1.16.5-beta.0",
        "v1.16.6",
        "v1.16.6-beta.0",
        "v1.16.7",
        "v1.16.7-beta.0",
        "v1.16.8",
        "v1.16.8-beta.0",
        "v1.16.9",
        "v1.16.9-beta.0",
        "v1.17.0",
        "v1.17.0-alpha.0",
        "v1.17.0-alpha.1",
        "v1.17.0-alpha.2",
        "v1.17.0-alpha.3",
        "v1.17.0-beta.0",
        "v1.17.0-beta.1",
        "v1.17.0-beta.2",
        "v1.17.0-rc.1",
        "v1.17.0-rc.2",
        "v1.17.1",
        "v1.17.1-beta.0",
        "v1.17.10",
        "v1.17.10-rc.0",
        "v1.17.11",
        "v1.17.11-rc.0",
        "v1.17.12",
        "v1.17.12-rc.0",
        "v1.17.13",
        "v1.17.13-rc.0",
        "v1.17.14",
        "v1.17.14-rc.0",
        "v1.17.15",
        "v1.17.15-rc.0",
        "v1.17.16",
        "v1.17.16-rc.0",
        "v1.17.17-rc.0",
        "v1.17.2",
        "v1.17.2-beta.0",
        "v1.17.3",
        "v1.17.3-beta.0",
        "v1.17.4",
        "v1.17.4-beta.0",
        "v1.17.5",
        "v1.17.5-beta.0",
        "v1.17.6",
        "v1.17.6-beta.0",
        "v1.17.7",
        "v1.17.7-rc.0",
        "v1.17.8",
        "v1.17.8-rc.0",
        "v1.17.8-rc.1",
        "v1.17.9",
        "v1.17.9-rc.0",
        "v1.18.0",
        "v1.18.0-alpha.0",
        "v1.18.0-alpha.1",
        "v1.18.0-alpha.2",
        "v1.18.0-alpha.3",
        "v1.18.0-alpha.5",
        "v1.18.0-beta.0",
        "v1.18.0-beta.1",
        "v1.18.0-beta.2",
        "v1.18.0-rc.1",
        "v1.18.1",
        "v1.18.1-beta.0",
        "v1.18.10",
        "v1.18.10-rc.0",
        "v1.18.11",
        "v1.18.11-rc.0",
        "v1.18.12",
        "v1.18.12-rc.0",
        "v1.18.13",
        "v1.18.13-rc.0",
        "v1.18.14",
        "v1.18.14-rc.0",
        "v1.18.15-rc.0",
        "v1.18.2",
        "v1.18.2-beta.0",
        "v1.18.3",
        "v1.18.3-beta.0",
        "v1.18.4",
        "v1.18.4-rc.0",
        "v1.18.5",
        "v1.18.5-rc.0",
        "v1.18.5-rc.1",
        "v1.18.6",
        "v1.18.6-rc.0",
        "v1.18.7",
        "v1.18.7-rc.0",
        "v1.18.8",
        "v1.18.8-rc.0",
        "v1.18.9",
        "v1.18.9-rc.0",
        "v1.19.0",
        "v1.19.0-alpha.0",
        "v1.19.0-alpha.1",
        "v1.19.0-alpha.2",
        "v1.19.0-alpha.3",
        "v1.19.0-beta.0",
        "v1.19.0-beta.1",
        "v1.19.0-beta.2",
        "v1.19.0-rc.0",
        "v1.19.0-rc.1",
        "v1.19.0-rc.2",
        "v1.19.0-rc.3",
        "v1.19.0-rc.4",
        "v1.19.1",
        "v1.19.1-rc.0",
        "v1.19.2",
        "v1.19.2-rc.0",
        "v1.19.3",
        "v1.19.3-rc.0",
        "v1.19.4",
        "v1.19.4-rc.0",
        "v1.19.5",
        "v1.19.5-rc.0",
        "v1.19.6",
        "v1.19.6-rc.0",
        "v1.19.7-rc.0",
        "v1.20.0",
        "v1.20.0-alpha.0",
        "v1.20.0-alpha.1",
        "v1.20.0-alpha.2",
        "v1.20.0-alpha.3",
        "v1.20.0-beta.0",
        "v1.20.0-beta.1",
        "v1.20.0-beta.2",
        "v1.20.0-rc.0",
        "v1.20.1",
        "v1.20.1-rc.0",
        "v1.20.2-rc.0",
        "v1.21.0-alpha.0"
    ],
    "Created": "2020-12-18T12:21:19.665427941Z",
    "DockerVersion": "19.03.8",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:e50c3c9ef5a201a24959788dcbc7ebf88d95c63e132a4d7396ce541127afd88e",
        "sha256:2d22313372b52fd1a8d1cb5e0dce7d4b1db0c74102d50163dceedb3d1fd1cbce",
        "sha256:e8f9aaf107a12ddd6066428e3d2004ebf54ef8c7a6289423f6a9b87be5ef2379",
        "sha256:d45934fb31c17f27b8ec59e09f80c092e16bef15aed0578e41001762059a1633",
        "sha256:a3194f674dc2d6b1ae449461b0ce1914fd44f0118828bb09ba512142a0adfb2d",
        "sha256:cf5b8b7c164c31ebe5f4e2a02a24c3e80cebb899cb143c5aac0a089c55867135",
        "sha256:5d34f588c2eae0d3897b098a38fcdf6bb8a3f142501ec4eae8c1a9fadc3537eb"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "E2E_FOCUS=\\[Conformance\\]",
        "E2E_SKIP=",
        "E2E_PROVIDER=local",
        "E2E_PARALLEL=1",
        "E2E_VERBOSITY=4",
        "RESULTS_DIR=/tmp/results",
        "KUBECONFIG="
    ]
}
1
```

**Comment by hasheddan** [comment]
xref https://github.com/kubernetes/sig-release/issues/1337
/assign

**Comment by saschagrunert** [comment]
It looks like that the issue is not in k/release, since we only build/stage the images via `make package-tarballs`. Then we push the images and annotate them to their corresponding architecture. Looking at the staged artifacts, for example for v1.20.1 arm64:
https://console.cloud.google.com/storage/browser/kubernetes-release/stage/v1.20.1-rc.1.15%2B6af63cd8ac4ed6/v1.20.1/release-images/arm64

Then we can see that also kube-proxy seems to have this issue:
```
> podman inspect k8s.gcr.io/conformance-arm64:v1.20.1 | jq .[].Architecture
"amd64"
> podman inspect k8s.gcr.io/kube-apiserver-arm64:v1.20.1 | jq .[].Architecture
"arm64"
> podman inspect k8s.gcr.io/kube-controller-manager-arm64:v1.20.1 | jq .[].Architecture
"arm64"
> podman inspect k8s.gcr.io/kube-proxy-arm64:v1.20.1 | jq .[].Architecture
"amd64"
> podman inspect k8s.gcr.io/kube-scheduler-arm64:v1.20.1 | jq .[].Architecture
"arm64"
```

I assume that the fix is somewhere in the build scripts, where I'm now looking into.

Beside that, all other architectures (arm, ppc64le, ...) are affected by this bug as well (for the same images only).
