### ISSUE TITLE
Installation of kubeadm=1.13.5* and kubectl=1.13.5* apt packages is broken

### ISSUE THREAD

**Issue by shashankv02** [kubernetes/kubernetes#92587]
**What happened**:

When trying to install `kubeadm=1.13.5*` or `kubelet=1.13.5*` on ubuntu, installation fails due to dependency on kubernetes-cni (= 0.7.5). Workaround is to install `kubernetes-cni=0.7.5-00` along with these packages

```
root@kmaster:~# apt-get install kubeadm=1.13.5*
Reading package lists... Done
Building dependency tree
Reading state information... Done
Selected version '1.13.5-00' (kubernetes-xenial:kubernetes-xenial [amd64]) for 'kubeadm'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kubeadm : Depends: kubernetes-cni (= 0.7.5)
E: Unable to correct problems, you have held broken packages.
root@kmaster:~#
```

# Workaround

Install `kubernetes-cni=0.7.5-00`

```
root@kmaster:~# apt-get install kubeadm=1.13.5* kubelet=1.13.5* kubernetes-cni=0.7.5-00
Reading package lists... Done
Building dependency tree
Reading state information... Done
Selected version '1.13.5-00' (kubernetes-xenial:kubernetes-xenial [amd64]) for 'kubeadm'
Selected version '1.13.5-00' (kubernetes-xenial:kubernetes-xenial [amd64]) for 'kubelet'
The following NEW packages will be installed:
  kubeadm kubelet kubernetes-cni
0 upgraded, 3 newly installed, 0 to remove and 73 not upgraded.
Need to get 6,473 kB/32.9 MB of archives.
After this operation, 200 MB of additional disk space will be used.
Get:1 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 kubernetes-cni amd64 0.7.5-00 [6,473 kB]
Fetched 6,473 kB in 2s (3,002 kB/s)
Selecting previously unselected package kubernetes-cni.
(Reading database ... 143652 files and directories currently installed.)
Preparing to unpack .../kubernetes-cni_0.7.5-00_amd64.deb ...
Unpacking kubernetes-cni (0.7.5-00) ...
Selecting previously unselected package kubelet.
Preparing to unpack .../kubelet_1.13.5-00_amd64.deb ...
Unpacking kubelet (1.13.5-00) ...
Selecting previously unselected package kubeadm.
Preparing to unpack .../kubeadm_1.13.5-00_amd64.deb ...
Unpacking kubeadm (1.13.5-00) ...
Setting up kubernetes-cni (0.7.5-00) ...
Setting up kubelet (1.13.5-00) ...
Setting up kubeadm (1.13.5-00) ...
root@kmaster:~#
```

**What you expected to happen**:

`apt-get install kubelet=1.13.5*` and `apt-get install kubeadm=1.13.5*`  should work

**How to reproduce it (as minimally and precisely as possible)**:
Run `apt-get install kubelet=1.13.5*` or `apt-get install kubeadm=1.13.5*` 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig release

**Comment by dims** [comment]
@kubernetes/release-engineering
/sig release
/area release-eng

**Comment by mrbobbytables** [comment]
I believe this has been resolved now. When viewing the kubeadm or kubelet package, kubernetes-cni is now listed as a dependency and will install 
```
root@90519c587982:/# apt-cache show kubeadm=1.13.*
Package: kubeadm
Version: 1.13.12-00
Installed-Size: 35626
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: amd64
Depends: kubelet (>= 1.13.0), kubectl (>= 1.13.0), kubernetes-cni (>= 0.7.5), cri-tools (>= 1.13.0)
Description: Kubernetes Cluster Bootstrapping Tool
 The Kubernetes command line tool for bootstrapping a Kubernetes cluster.
Description-md5: bb3c7836839894793de38af875e01b30
Homepage: https://kubernetes.io
Filename: pool/kubeadm_1.13.12-00_amd64_5791923bba94b850ca898fdfaa75916bdd3b4f5d86a50ea738d96f14230029b9.deb
Priority: optional
SHA256: 5791923bba94b850ca898fdfaa75916bdd3b4f5d86a50ea738d96f14230029b9
Section: misc
Size: 7411804

root@90519c587982:/# apt-get install kubeadm=1.13.12-00
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  conntrack cri-tools ebtables ethtool iproute2 iptables kmod kubectl kubelet kubernetes-cni libatm1 libbsd0 libcap2 libcap2-bin libelf1 libip4tc2 libip6tc2 libkmod2 libmnl0 libnetfilter-conntrack3 libnfnetlink0 libnftnl11 libpam-cap libwrap0 libxtables12 netbase socat
Suggested packages:
  nftables iproute2-doc firewalld
The following NEW packages will be installed:
  conntrack cri-tools ebtables ethtool iproute2 iptables kmod kubeadm kubectl kubelet kubernetes-cni libatm1 libbsd0 libcap2 libcap2-bin libelf1 libip4tc2 libip6tc2 libkmod2 libmnl0 libnetfilter-conntrack3 libnfnetlink0 libnftnl11 libpam-cap libwrap0 libxtables12 netbase socat
0 upgraded, 28 newly installed, 0 to remove and 4 not upgraded.
Need to get 71.8 MB of archives.
After this operation, 302 MB of additional disk space will be used.
```

I'm going to go ahead and close the issue, but if you continue to have problems please reopen it.
Thanks!

/close

**Comment by shashankv02** [comment]
Nope. It's not resolved.


```
root@hb-kube1:/var/local/healthbot#  apt-cache show kubeadm=1.13.*
Package: kubeadm
Version: 1.13.12-00
Installed-Size: 35626
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: amd64
Depends: kubelet (>= 1.13.0), kubectl (>= 1.13.0), kubernetes-cni (>= 0.7.5), cri-tools (>= 1.13.0)
Description: Kubernetes Cluster Bootstrapping Tool
 The Kubernetes command line tool for bootstrapping a Kubernetes cluster.
Description-md5: bb3c7836839894793de38af875e01b30
Homepage: https://kubernetes.io
Filename: pool/kubeadm_1.13.12-00_amd64_5791923bba94b850ca898fdfaa75916bdd3b4f5d86a50ea738d96f14230029b9.deb
Priority: optional
SHA256: 5791923bba94b850ca898fdfaa75916bdd3b4f5d86a50ea738d96f14230029b9
Section: misc
Size: 7411804

root@hb-kube1:/var/local/healthbot# apt-get install kubeadm=1.13.5* kubelet=1.13.5*
Reading package lists... Done
Building dependency tree
Reading state information... Done
Selected version '1.13.5-00' (kubernetes-xenial:kubernetes-xenial [amd64]) for 'kubeadm'
Selected version '1.13.5-00' (kubernetes-xenial:kubernetes-xenial [amd64]) for 'kubelet'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kubeadm : Depends: kubernetes-cni (= 0.7.5)
 kubelet : Depends: kubernetes-cni (= 0.7.5)
E: Unable to correct problems, you have held broken packages.
root@hb-kube1:/var/local/healthbot#
```

/reopen

**Comment by justaugustus** [comment]
/assign @saschagrunert 
/unassign

Sascha -- can you take a look or assign to someone on @kubernetes/release-engineering to investigate?

The following issues are similar classes of issues for apt/yum:
- https://github.com/kubernetes/kubernetes/issues/92698
- https://github.com/kubernetes/kubernetes/issues/92587
- https://github.com/kubernetes/kubernetes/issues/92586
- https://github.com/kubernetes/kubernetes/issues/92463

**Comment by saschagrunert** [comment]
Confirmed, this is still broken. Not completely sure what is the reason…
/help
I think it's the same as for https://github.com/kubernetes/kubernetes/issues/92586

**Comment by jfrederickson** [comment]
Was able to reproduce on a fresh install, It looks like the package metadata for the most recent 1.13 debian package (`1.13.5-00`) has a strict dependency on exactly 0.7.5 of `kubernetes-cni`:

```
root@localhost:/tmp/kubeadm/control# cat control
Package: kubeadm
Version: 1.13.5-00
Architecture: amd64
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Installed-Size: 35597
Depends: kubelet (>= 1.6.0), kubectl (>= 1.6.0), kubernetes-cni (= 0.7.5), cri-tools (>= 1.12.0)
Section: misc
Priority: optional
Homepage: https://kubernetes.io
Description: Kubernetes Cluster Bootstrapping Tool
 The Kubernetes command line tool for bootstrapping a Kubernetes cluster.
```

However, the available `kubernetes-cni` packages all have [debian_revision components](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version):

```
root@localhost:/tmp/kubeadm/control# apt-cache policy kubernetes-cni
kubernetes-cni:
  Installed: (none)
  Candidate: 0.8.7-00
  Version table:
     0.8.7-00 500
        500 https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
     0.8.6-00 500
        500 https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
     0.7.5-00 500
        500 https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
     0.6.0-00 500
        500 https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
     0.5.1-00 500
        500 https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
     0.3.0.1-07a8a2-00 500
        500 https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
```

I suspect the other version constraints match because a package with a debian_revision is sufficient to satisfy a `>=` constraint on that version. This doesn't appear to be the case for a `=` ([exactly equal](https://www.debian.org/doc/debian-policy/ch-relationships.html)) constraint - I think you'd need to specify the exact package revision you want in the package metadata (so `0.7.5-00` in this case).

**Comment by saschagrunert** [comment]
It feels we will not come to a solution for those issues until someone is really working on it. I will close it for now, especially since 1.13.x is EOL since a long time.

/close
