### ISSUE TITLE
When a new node joins the cluster - scheduler doesn't respect CSI volume limit

### ISSUE THREAD

**Issue by yarinm** [kubernetes/kubernetes#95911]
**What happened**:
I'm using the [aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver) for attaching *pre-provisioned* EBS disks to my pods. I've also customized the max attach limit to 1 (for testing purposes) but I intend to use a low value (around 5-8) in production.
The attach limit value is respected by the scheduler and pods usually are pending until volumes are detached.

The issue I'm having is when I'm adding a new node (using cluster-autoscaler or manually) what happens is as soon as the csi-driver node is live on the new node all pending pods are scheduled to the new node *ignoring* the attach limit and exceeding it.

From my testing I got up to 10 pods to schedule which exceed the limit (1)

After some learning about the CSI Driver and actual process I believe the issue is either in the scheduler or the controller. They probably start scheduling pods to the new node before the CSI Driver configuration completed publishing all relevant values to the cluster.

My current workaround is have all my pods have an affinity to `foo` label and 30 seconds after the CSI node pod is up I patch the node with the `foo` label.  That way I neutralized the race condition but obviously this isn't a very good solution

**What you expected to happen**:
We need to make sure the scheduler won't start scheduling pods until it is certain the node doesn't have max attach limit for the relevant CSI volumes.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install the ebs csi driver with the flag `--volume-attach-limit=1`
2. Example pod + pv + pvc attributes:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pod1-pv-new
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pod1-pvc
    namespace: default
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-003ee7a245e6b2cd2 # note that I'm using a pre-provisioned volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - ca-central-1a
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-sc
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod1-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-sc
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
# This is the label I'm adding to new nodes after CSI node pod is up
#          - matchExpressions:
#              - key: yarin-test
#                operator: Exists
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                  - ca-central-1a
  containers:
    - image: ubuntu:latest
      # Just spin & wait forever
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      name: test-container
      volumeMounts:
        - mountPath: /test-ebs
          name: persistent-storage
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: pod1-pvc

```

Storage class:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
```

3. Apply the podX.yaml several times with different volumes
4. Make sure all pods except one is in "Pending" state due to attach limit enforcement
5. Add a new node to the cluster
6. Once the daemonset is joined you can see all the other pending pods are assigned to the new node.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17
- Cloud provider or hardware configuration: eks on AWS
- I'm using the latest csi-provisioner/csi-attacher/node-registrar

**Comment by msau42** [comment]
/assign @bertinatto 
can you help take a look if there's an issue with volume attach limit and multiple pods being scheduled at the same time?
@kubernetes/sig-storage-bugs

**Comment by bertinatto** [comment]
@yarinm: Interesting issue. The scheduler takes the volume limit value from the `CSINode` object, and the limit is populated by the kubelet when the CSI driver is registered in the node [1]. So it seems like your diagnosis is correct, the scheduler is assigning the node to the pod before the `CSINode` object has been created/populated.

The problem is that currently there's no way in the scheduler (that I'm aware of) of _only_ scheduling pods on nodes where the driver is installed. Just a side note, the same issue can happen with fibre channel volumes for example: the scheduler might schedule a pod that contains fibre channel volumes to a node that doesn't have the hardware.

We definitely should fix the scheduler to not schedule pods on nodes where the driver is not installed yet. In the meantime, do you think you could use node affinity? Perhaps use the label `topology.ebs.csi.aws.com/zone` and operator `Exists` [2]?

[1] https://github.com/kubernetes/kubernetes/blob/2360f22/pkg/volume/csi/nodeinfomanager/nodeinfomanager.go#L572
[2] https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/pod-with-node-affinity.yaml

**Comment by yarinm** [comment]
Hey @bertinatto thanks for the quick reply!

The affinity approach was the first thing I've tried, sadly the issue still occurred. I think it's because the node label was updated before the CSINode configuration was loaded in the scheduler.

My current workaround was using node affinity using a custom label I created which is populated 15 seconds AFTER the csi node pod is starting up - that mitigated the race condition completely.

**Comment by msau42** [comment]
The main challenge we had for having the scheduler only schedule pods to nodes with the csi driver installed, is that it would break autoscaling from zero. We would need to add some configuration to the autoscaler to understand every csi driver that is expected to be installed on the nodes. It may work for managed cloud csi drivers, but I'm not sure how non managed csi drivers could be configured.

cc @kubernetes/sig-autoscaling-feature-requests

**Comment by yarinm** [comment]
@msau42 this isn't related to autoscaling at all! The issue occurs even if you add new nodes yourself. It is true that a cluster with autoscaler installed is more likely to encounter this issue (that's how I found it)

**Comment by msau42** [comment]
I mean that adding a check in the scheduler to only schedule pods on nodes with the csi driver installed on them will break autoscaler's simulation and cause autoscaling to not be triggered at all. Maybe a possible solution could be to have different logic between the scheduler and autoscaler, where autoscaler has a custom version of this predicate that doesn't do the csinode check. We would need to work with autoscaler folks to see what the best solution can be.

Agree there's still a problem that immediately when a node is created and is not initialized with the csi driver yet, the scheduler will not wait for the limit to be set.

Is there a reason why you want the volume limit to be so low? Most cloud platforms I'm aware of have higher limits so a burst of pods getting scheduled will not reach the volume limit yet.

**Comment by yarinm** [comment]
I am building a system that is continuously attaching a detaching disks and performing some operations on those disks. From our experience when we were doing that with EC2 instances, having more than 5-8 disks attached caused degrading issues on the VM. It's not set in stone but I'm not optimistic with running more than about 10 disks attached per node for our system.

**Comment by MaciekPytel** [comment]
> The main challenge we had for having the scheduler only schedule pods to nodes with the csi driver installed, is that it would break autoscaling from zero.

It will actually completely break cluster autoscaler, not just scale from 0. CA works by creating in-memory node object and feeding it to embedded scheduler code to see if adding a new node would help pending pod. Currently CA can't create an in-memory CSINode and so if scheduler started enforcing its presence all CA simulations would always fail.

I'd imagine we could probably easily add some global switch to scheduler logic so the presence of CSINode would only be enforced in scheduler, but not in embedded scheduler code in CA. That should solve the issue for non-autoscaled clusters. However, if we do that and there is ever a node where driver fails and CSINode object is not created it may prevent autoscaler from adding any more nodes (since it will keep waiting forever for pending pods to schedule on this node). I'm not sure how likely that scenario would be though? Can we guarantee that eventually any node will have matching CSINode?

**Comment by msau42** [comment]
> add some global switch to scheduler logic so the presence of CSINode would only be enforced in scheduler, but not in embedded scheduler code in CA.

The other downside of this is if the actual volume limit is very low, CA doesn't know about that limit, and pending pods require volumes exceeding the limit, then CA could create new nodes that are actually unschedulable. But that's also an issue today so we're not making it worse.

> Can we guarantee that eventually any node will have matching CSINode?

We recommend that CSI drivers get deployed on all nodes with a DaemonSet, but it's possible that the deployer could add a nodeSelector/nodeAffinity to restrict the driver to a subset of nodes. This scenario already won't work well today as the scheduler treats "no CSINode" as "supports unlimited number of csi volumes". Maybe if someone wants to do this, they need to make sure their pods that use csi have matching nodeSelectors.

**Comment by yarinm** [comment]
Node selector was still not enough as it take a few seconds for the value to register AFTER the label is already set on the nodes

**Comment by gnufied** [comment]
When a new node is added can be add a dummy `CSINode` object to that node with "0" attach limit or something similar (but we might have to modify scheduler to consider 0 limits) and when driver actually starts up it will populate correct limit or if the driver does not support limits then the "0" limit can be removed.

**Comment by yarinm** [comment]
@gnufied this could work.

Any other input about this? this is a real pain - even my workaround sometimes doesn't and i have to mess with the delays

**Comment by vpnachev** [comment]
Just stumbled on this/similar issue where kube-scheduler assigned 39 pods with disks on a node limited to only 26 disks on infrastructure side (m5 AWS machine). 

The cluster was a bit under pressure as quite some new pods with higher priority were created which caused the pods with lower priority to be preempted. Then cluster autoscaler kicked in and added new nodes to the cluster and kube-scheduler assigned the pending pods to the new nodes, but it made the mistake to assign 39 pods with disks to a single machine. I've some suspicious that scheduling happened before the CSINode object to be fully initialized as well as the machine type label was not yet set on the Node, therefore the scheduler decided the node volume limit is 39, ref: https://github.com/kubernetes/kubernetes/blob/c1de2d70269039fe55efb98e737d9a29f9155246/pkg/scheduler/framework/plugins/nodevolumelimits/non_csi.go#L549


If this cannot be properly fixed in the scheduler, what do you think about a controller that can evict the broken pods to give a second chance to the scheduler to assign them to other nodes?

/remove-lifecycle stale

**Comment by msau42** [comment]
I think we should consider Hemant's proposal to create a placeholder CSINode object with 0 value.

**Comment by vivekskrishna** [comment]
Hi,
  Is the startup taint removaletc which ebs/efs csi drviers support, something that could help here?
Eg
Configure node startup taint
There are potential race conditions on node startup (especially when a node is first joining the cluster) where pods/processes that rely on the EBS CSI Driver can act on a node before the EBS CSI Driver is able to startup up and become fully ready. To combat this, the EBS CSI Driver contains a feature to automatically remove a taint from the node on startup. Users can taint their nodes when they join the cluster and/or on startup, to prevent other pods from running and/or being scheduled on the node prior to the EBS CSI Driver becoming ready.

This feature is activated by default, and cluster administrators should use the taint ebs.csi.aws.com/agent-not-ready:NoExecute (any effect will work, but NoExecute is recommended). For example, EKS Managed Node Groups [support automatically tainting nodes](https://docs.aws.amazon.com/eks/latest/userguide/node-taints-managed-node-groups.html).

Source: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md

Sometimes i still see pod getting assigned which has more volumes that what node can support during startup. ebs-csi drver should hopefully introduce a delay before they remove this taint s they seem to be doing it just before registering which may still cause race condition but the logic looks good

**Comment by kerthcet** [comment]
Seems a valid usecase for https://github.com/kubernetes/kubernetes/issues/115716 as providing a general taint-removal logic when run-to-completion.

**Comment by vivekskrishna** [comment]
> Hi, Is the startup taint removaletc which ebs/efs csi drviers support, something that could help here? Eg Configure node startup taint There are potential race conditions on node startup (especially when a node is first joining the cluster) where pods/processes that rely on the EBS CSI Driver can act on a node before the EBS CSI Driver is able to startup up and become fully ready. To combat this, the EBS CSI Driver contains a feature to automatically remove a taint from the node on startup. Users can taint their nodes when they join the cluster and/or on startup, to prevent other pods from running and/or being scheduled on the node prior to the EBS CSI Driver becoming ready.
> 
> This feature is activated by default, and cluster administrators should use the taint ebs.csi.aws.com/agent-not-ready:NoExecute (any effect will work, but NoExecute is recommended). For example, EKS Managed Node Groups [support automatically tainting nodes](https://docs.aws.amazon.com/eks/latest/userguide/node-taints-managed-node-groups.html).
> 
> Source: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md
> 
> Sometimes i still see pod getting assigned which has more volumes that what node can support during startup. ebs-csi drver should hopefully introduce a delay before they remove this taint s they seem to be doing it just before registering which may still cause race condition but the logic looks good



With the fix https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1945 this solves the ebs issue and now the race condition is not seen. we will still have problem if we go with the default value for volume limit as that is shared with network interfaces in ec2 instances(till gen6) but if we use r7 it should be solved as the reported value is exclusively for ebs volumes. In older gen(till 6) we set the maxvolumelimit in ebs as (maximum- 1 root volume- number of network interface for the instance types in that node group).

**Comment by arsiesys** [comment]
Hi,

We are getting a similar issue with GKE CSI.

This PR seems to fix the issue on our tests:
https://github.com/kubernetes/kubernetes/pull/130702

The issue may also occur when a csi pod is restarted.

**Comment by ialidzhikov** [comment]
@gnufied, should we close this issue as fixed by https://github.com/kubernetes/kubernetes/pull/135012? 
A duplicate/similar issue https://github.com/kubernetes/kubernetes/issues/126921 was closed with the merge of https://github.com/kubernetes/kubernetes/pull/135012.
