### ISSUE TITLE
Is it necessary to disable the container health check function  for sanbox like the service container

### ISSUE THREAD

**Issue by heqg** [kubernetes/kubernetes#98497]
**What would you like to be added**:

Is it necessary to disable the container health check function  for sanbox like the service container in [docker_sandbox.go]。 
related to：
https://github.com/kubernetes/kubernetes/issues/25829
https://github.com/kubernetes/kubernetes/pull/50796

**Why is this needed**:
[kubenetes]： As our sanbox container （pause）, it is generally not like the service container in the k8s cluster system. Health check can be set via pod.sec.

[Docker]：For the sake of CIS requirements.，user-defined healthchecks may be added during making container image （HEALTHCHECK --interval=60s --timeout=20s CMD exit 0），but，pause container  not supporting commands such as CMD exit 0, Therefore, the container-layer health check will fail. The result is as follows (unhealthy):

![image](https://user-images.githubusercontent.com/56527988/106074483-e7d47e80-6146-11eb-8ab7-b29c44403550.png)

However, the health check here fails  does not affect the functions of this container as a sandbox.

**So，Is it necessary to disable the container health check function  for sanbox like the service container?**
docker_sandbox.go-->makeSandboxDockerConfig
docker_container.go--> CreateContainer -->  line: Healthcheck: &dockercontainer.HealthConfig{Test: []string{"NONE"},},

**Comment by heqg** [comment]
sig/node

**Comment by yangjunmyfm192085** [comment]
Is this reasonable?
If this change is reasonable, I will deal with it.
/assign @ehashman

**Comment by ehashman** [comment]
/kind support
/remove-kind bug
/unassign

Going through the previous issues, I agree with Derek, it makes sense that we support health checks at a layer above the CRI (via readiness and liveness probes) rather than in the container runtimes themselves. https://github.com/kubernetes/kubernetes/issues/25829#issuecomment-220203223

The errors pasted above should have been fixed in Docker per https://github.com/kubernetes/kubernetes/pull/50796#discussion_r156193365

I don't think we want to do this so I am going to close this issue. But, if you want to bring it up for wider discussion at a SIG Node meeting, feel free to add it as an agenda item and make a case. We are coming up on enhancements freeze in less than two weeks  (Feb. 9) so there's not a lot of time left for this release.

/close

**Comment by yangjunmyfm192085** [comment]
Hi, @ehashman,thank you for reply,
But i have a question.
#50796 ,this  pr does not fix the check of the puase container.
we can fix it by add code in file docker_sandbox.go:
Healthcheck: &dockercontainer.HealthConfig{
Test: []string{"NONE"},
},

**Comment by ehashman** [comment]
@yangjunmyfm192085 feel free to open a PR with bugfix and tag me

**Comment by heqg** [comment]
> @yangjunmyfm192085 feel free to open a PR with bugfix and tag me

@ehashman  @yangjunmyfm192085
thanks。
