### ISSUE TITLE
[Flaky Test] Kubernetes e2e suite: [sig-network] KubeProxy should set TCP CLOSE_WAIT timeout [Privileged]

### ISSUE THREAD

**Issue by sladyn98** [kubernetes/kubernetes#99801]
#### Which jobs are flaking:
ci-kubernetes-kind-ipv6-e2e-parallel #1367504705533513728

#### Which test(s) are flaking:
Kubernetes e2e suite: [sig-network] KubeProxy should set TCP CLOSE_WAIT timeout [Privileged]

#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-blocking#kind-ipv6-master-parallel&sort-by-failures=&exclude-non-failed-tests=

#### Reason for failure:
```
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/kube_proxy.go:53
Mar  4 16:31:32.747: no valid conntrack entry for port 11302 on node fc00:f853:ccd:e793::4: timed out waiting for the condition
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```
#### Anything else we need to know:
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=KubeProxy%20should%20set%20TCP%20CLOSE_WAIT%20timeout%20

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1367504705533513728

/sig network

**Comment by sladyn98** [comment]
Looking at the commit https://github.com/kubernetes/kubernetes/pull/99755 this was the pR that came up. Could be helpful while deflaking

**Comment by aojea** [comment]
I fixed this recently https://github.com/kubernetes/kubernetes/pull/99564
The test is running in another jobs without failures since this fix, is still soon to declare it as flake, the job linked here has a very high rate of failures with other tests failing, will keep an eye on it

**Comment by sladyn98** [comment]
When I gave it a search this fix did not pop up. Strange.

**Comment by aojea** [comment]
The test is very sensitive to environment constrains, so we should check the behaviour of failures in a "long" time period and correlate with other jobs that exercise the test.
Anyway, thanks for flagging it, let's see how it evolves

**Comment by eddiezane** [comment]
I think this is still failing.

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99921/pull-kubernetes-e2e-kind/1370185640280330240

/reopen

**Comment by aojea** [comment]
yep, this time the problem is that the connection never happen

```
tcp      6 113 SYN_SENT src=10.244.1.22 dst=172.18.0.4 sport=50538 dport=11302 [UNREPLIED] src=172.18.0.4 dst=172.18.0.3 sport=11302 dport=50538 mark=0 use=1
```

so, there is no conntrack entry

What I can't understand is why the pod is ready but kubelet reports an error on creation

> 
> Mar 12 01:58:34 kind-worker2 kubelet[244]: E0312 01:58:34.034024     244 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "e2e-net-server_kube-proxy-6818(c5d22108-6f91-4cb7-82b4-632ebc0271bb)" failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
> Mar 12 01:58:34 kind-worker2 kubelet[244]: E0312 01:58:34.034069     244 kuberuntime_manager.go:771] "CreatePodSandbox for pod failed" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded" kube-proxy-6818/e2e-net-server="(MISSING)"
> Mar 12 01:58:34 kind-worker2 kubelet[244]: E0312 01:58:34.034126     244 pod_workers.go:191] Error syncing pod c5d22108-6f91-4cb7-82b4-632ebc0271bb ("e2e-net-server_kube-proxy-6818(c5d22108-6f91-4cb7-82b4-632ebc0271bb)"), skipping: failed to "CreatePodSandbox" for "e2e-net-server_kube-proxy-6818(c5d22108-6f91-4cb7-82b4-632ebc0271bb)" with CreatePodSandboxError: "CreatePodSandbox for pod \"e2e-net-server_kube-proxy-6818(c5d22108-6f91-4cb7-82b4-632ebc0271bb)\" failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
> Mar 12 01:58:34 kind-worker2 kubelet[244]: W0312 01:58:34.748653     244 pod_container_deletor.go:79] Container "2addbefc5115dbc83bea8d05c72f380a42c56ef78806ff526c458842fe7d536e" not found in pod's containers

**Comment by sladyn98** [comment]
I am new to the debugging aspect but does the line above `rpc error: code = DeadlineExceeded desc = context deadline exceeded"` cause the pod to not get reported, problems with communication to the cluster ?

**Comment by aojea** [comment]
> I am new to the debugging aspect but does the line above `rpc error: code = DeadlineExceeded desc = context deadline exceeded"` cause the pod to not get reported, problems with communication to the cluster ?

the kubelet -> containerd communication happens locally in the node, IIRC kubelet sends createPodSandbox with a timeout, I think that this error is because containerd didn't report back on time. 
However, the pod is relaunched later, .... I´m pretty  busy right now, but maybe the key is there, the problem is that the server never receives the packet, but the server pod in the logs says is running ... and this error :thinking:

**Comment by thockin** [comment]
Is there followup to do on this?

**Comment by aojea** [comment]
there are still failures https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=KubeProxy%20should%20set%20TCP%20CLOSE_WAIT%20timeout%20&xjob=kops 

but there are other tests that flake in kind , right now following the conversation here https://github.com/kubernetes/kubernetes/issues/100047#issuecomment-811513297

**Comment by aojea** [comment]
If we remove kops and the ci-kubernetes-e2e-gci-gce-network-proxy-grpc jobs from the query , 
 this test only fails on jobs that have a a high rate of failures, investigated here https://github.com/kubernetes/kubernetes/issues/100047#issuecomment-811513297

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=KubeProxy%20should%20set%20TCP%20CLOSE_WAIT%20timeout%20&xjob=kops%7Cci-kubernetes-e2e-gci-gce-network-proxy-grpc

**Comment by aojea** [comment]
Same as https://github.com/kubernetes/kubernetes/issues/100220#issuecomment-847711421
super sensible test to performance issues, removing the wrong tests the rate is acceptable
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=KubeProxy%20should%20set%20TCP%20CLOSE_WAIT%20timeout%20&xjob=kops%7Cci-kubernetes-e2e-gci-gce-network-proxy-grpc%7Cci-kubernetes-e2e-ubuntu-gce
I'm going to close it based on that
/close
